force-app/main/default/objects/Campaign/fields/CampagneID_Avaya__c.field-meta.xml
<CustomField>
    <fullName>CampagneID_Avaya__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CampagneID Avaya</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Campaign/fields/File_d_attente__c.field-meta.xml
<CustomField>
    <fullName>File_d_attente__c</fullName>
    <inlineHelpText>Equivalent a la compétence sur Avaya</inlineHelpText>
    <label>File d&apos;attente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRM-Groupe-1</fullName>
                <label>PRM Groupe 1</label>
            </value>
            <value>
                <fullName>PRM-Groupe-2</fullName>
                <label>PRM Groupe 2</label>
            </value>
            <value>
                <fullName>PRM-Groupe-3</fullName>
                <label>PRM Groupe 3</label>
            </value>
            <value>
                <fullName>PRM-Groupe-4</fullName>
                <label>PRM Groupe 4</label>
            </value>
            <value>
                <fullName>PRM-Groupe-5</fullName>
                <label>PRM Groupe 5</label>
            </value>
            <value>
                <fullName>PRM-GROUPE-7</fullName>
                <label>PRM GROUPE 7</label>
            </value>
            <value>
                <fullName>PRM-Groupe-6</fullName>
                <label>PRM Groupe 6</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Ids_des_vues_de_liste__c.field-meta.xml
<CustomField>
    <fullName>Ids_des_vues_de_liste__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Ids des vues de liste</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AP10_updateCampaign_Test.cls
/**
* @description       : 
* @author            : Anes BOUZOUINA
* @group             : 
* @last modified on  : 10-19-2022
* @last modified by  : Anes BOUZOUINA
**/
@istest
public with sharing class AP10_updateCampaign_Test {
    
    @isTest static void testUpdateListView() {
        // Create test data
        Campaign testCampaign = new Campaign(CampagneID_Avaya__c = 'Test Queue',File_d_attente__c  = 'PRM-Groupe-1	',name='test Anes');
        insert testCampaign;
        
        List<SObject> testObjectList = new List<SObject>();
        testObjectList.add(new ListView(Id = '00B0Q000002i7jlUAA'));
        testObjectList.add(new ListView(Id = '00B0Q000003i7jlUAA'));
        
        // Call updateListView method
        AP10_updateCampaign.updateListView(testObjectList, 'Test Queue');
        
        // Verify results
        Campaign updatedCampaign = [SELECT Ids_des_vues_de_liste__c FROM Campaign WHERE Id = :testCampaign.Id];
        System.assertEquals('00B0Q000002i7jlUAA,00B0Q000003i7jlUAA', updatedCampaign.Ids_des_vues_de_liste__c);
    }
}