force-app/main/default/objects/Campaign/fields/CampagneID_Avaya__c.field-meta.xml
<CustomField>
    <fullName>CampagneID_Avaya__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CampagneID Avaya</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Campaign/fields/Ids_des_vues_de_liste__c.field-meta.xml
<CustomField>
    <fullName>Ids_des_vues_de_liste__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Ids des vues de liste</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AP10_updateCampaign.cls
/**
 * @description       : 
 * @author            : Anes BOUZOUINA
 * @group             : 
 * @last modified on  : 10-27-2022
 * @last modified by  : Anes BOUZOUINA
**/
public without sharing class AP10_updateCampaign {
    
    @AuraEnabled
    public static void  updateListView(list<sobject> objectlst,string Queue){
        system.debug('objectlst '+objectlst);
         system.debug('Queue '+Queue);
         //Relation 1 to N between campaign and listView_field_ 
         String queryCampaign= 'SELECT id,Ids_des_vues_de_liste__c from campaign where CampagneID_Avaya__c =:Queue limit 1';
         list<Campaign> campaignLst =  Database.query(queryCampaign);
         system.debug('campaignLst '+campaignLst);
         if(campaignLst.size()>0 ){
            System.debug('inside the if');
           // String idListView='';
            // for(sobject sobjectItr : objectlst){
            //     idListView += ','+sobjectItr.Id;
            // }

            System.debug('campaignLst[0].Ids_des_vues_de_liste__c'+campaignLst[0].Ids_des_vues_de_liste__c );
            //if the field is empty so fill with the new list ( avoid a null value with string...)

          
                for(sobject sobjectItr : objectlst){
                    if(campaignLst[0].Ids_des_vues_de_liste__c == null || campaignLst[0].Ids_des_vues_de_liste__c == ''){
                        campaignLst[0].Ids_des_vues_de_liste__c = sobjectItr.Id;
                    }
                    else if(!campaignLst[0].Ids_des_vues_de_liste__c.contains(sobjectItr.Id) ) {
                        campaignLst[0].Ids_des_vues_de_liste__c = campaignLst[0].Ids_des_vues_de_liste__c + ','+sobjectItr.Id ;
                    }

                }
            
           // campaignLst[0].Ids_des_vues_de_liste__c == null ?  : campaignLst[0].Ids_des_vues_de_liste__c += idListView;          
            System.debug('campaignLst[0].Ids_des_vues_de_liste__c'+campaignLst[0].Ids_des_vues_de_liste__c );
            update campaignLst;
         }

    }
}