force-app/main/default/objects/Campaign/fields/CampagneID_Avaya__c.field-meta.xml
<CustomField>
    <fullName>CampagneID_Avaya__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CampagneID Avaya</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Campaign/fields/File_d_attente__c.field-meta.xml
<CustomField>
    <fullName>File_d_attente__c</fullName>
    <inlineHelpText>Equivalent a la compétence sur Avaya</inlineHelpText>
    <label>File d&apos;attente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRM-Groupe-1</fullName>
                <label>PRM Groupe 1</label>
            </value>
            <value>
                <fullName>PRM-Groupe-2</fullName>
                <label>PRM Groupe 2</label>
            </value>
            <value>
                <fullName>PRM-Groupe-3</fullName>
                <label>PRM Groupe 3</label>
            </value>
            <value>
                <fullName>PRM-Groupe-4</fullName>
                <label>PRM Groupe 4</label>
            </value>
            <value>
                <fullName>PRM-Groupe-5</fullName>
                <label>PRM Groupe 5</label>
            </value>
            <value>
                <fullName>PRM-GROUPE-7</fullName>
                <label>PRM GROUPE 7</label>
            </value>
            <value>
                <fullName>PRM-Groupe-6</fullName>
                <label>PRM Groupe 6</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Ids_des_vues_de_liste__c.field-meta.xml
<CustomField>
    <fullName>Ids_des_vues_de_liste__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Ids des vues de liste</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DeleteLVfromCampaign.cls
/**
 * @description       : 
 * @author            : Anes BOUZOUINA
 * @group             : 
 * @last modified on  : 10-20-2022
 * @last modified by  : Anes BOUZOUINA
**/
public with sharing class DeleteLVfromCampaign {
    @auraEnabled
    public static void DeleteLVfromCampaign(list<sobject> objectlst,string Queue) {
        system.debug('objectlst in DeleteLVfromCampaign'+objectlst);
        system.debug('Queue '+Queue);
        //Relation 1 to N between campaign and listView_field_ 
        String queryCampaign= 'SELECT id,Ids_des_vues_de_liste__c,File_d_attente__c from campaign where CampagneID_Avaya__c =:Queue limit 1';
        list<Campaign> campaignLst =  Database.query(queryCampaign);
        system.debug('campaignLst '+campaignLst);
        if(campaignLst.size()>0 ){

            System.debug('campaignLst[0].Ids_des_vues_de_liste__c'+campaignLst[0].Ids_des_vues_de_liste__c );
           //if the field is empty so fill with the new list ( avoid a null value with string...)

         
               for(sobject sobjectItr : objectlst){
                if((campaignLst[0].Ids_des_vues_de_liste__c).contains(sobjectItr.Id)) 
                {
                    // system.Debug('inside the if');
                    // System.debug('campaignLst[0].Ids_des_vues_de_liste__c) '+campaignLst[0].Ids_des_vues_de_liste__c);
                    String str = (campaignLst[0].Ids_des_vues_de_liste__c.remove(string.valueof(sobjectItr.Id))).replace(',,',',');
                    campaignLst[0].Ids_des_vues_de_liste__c= str.removeStart(',');
                    System.debug('str '+str);
                }

               }
           
          // campaignLst[0].Ids_des_vues_de_liste__c == null ?  : campaignLst[0].Ids_des_vues_de_liste__c += idListView;          
           System.debug('campaignLst[0].Ids_des_vues_de_liste__c'+campaignLst[0].Ids_des_vues_de_liste__c );
           update campaignLst[0];
    }
}
}