force-app/main/default/objects/Campaign/fields/CampagneID_Avaya__c.field-meta.xml
<CustomField>
    <fullName>CampagneID_Avaya__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CampagneID Avaya</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Campaign/fields/File_d_attente__c.field-meta.xml
<CustomField>
    <fullName>File_d_attente__c</fullName>
    <inlineHelpText>Equivalent a la compétence sur Avaya</inlineHelpText>
    <label>File d&apos;attente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRM-Groupe-1</fullName>
                <label>PRM Groupe 1</label>
            </value>
            <value>
                <fullName>PRM-Groupe-2</fullName>
                <label>PRM Groupe 2</label>
            </value>
            <value>
                <fullName>PRM-Groupe-3</fullName>
                <label>PRM Groupe 3</label>
            </value>
            <value>
                <fullName>PRM-Groupe-4</fullName>
                <label>PRM Groupe 4</label>
            </value>
            <value>
                <fullName>PRM-Groupe-5</fullName>
                <label>PRM Groupe 5</label>
            </value>
            <value>
                <fullName>PRM-GROUPE-7</fullName>
                <label>PRM GROUPE 7</label>
            </value>
            <value>
                <fullName>PRM-Groupe-6</fullName>
                <label>PRM Groupe 6</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Ids_des_vues_de_liste__c.field-meta.xml
<CustomField>
    <fullName>Ids_des_vues_de_liste__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Ids des vues de liste</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DeleteLVfromCampaign_Test.cls
@isTest
public class DeleteLVfromCampaign_Test {
    @isTest
    static void testDeleteLVfromCampaign() {
               Campaign cam = test_Utils.createCampaign();
        cam.File_d_attente__c='PRM-Groupe-1';
        cam.Ids_des_vues_de_liste__c='00B0Q000002i7jlUAA,00B3X00000D2rF9UAJ';
        cam.CampagneID_Avaya__c='PRM-Groupe-1';
        insert cam ; 
        cam.Ids_des_vues_de_liste__c+=','+cam.Id;
        update cam;
        Campaign campaign = new campaign(CampagneID_Avaya__c='PRM-Groupe-1',Name='Anes Test2');
      //  insert campaign;
        list<Campaign> camLst= new list<Campaign>();
        camLst.add(cam);
        //camLst.add(campaign);
        
        DeleteLVfromCampaign.DeleteLVfromCampaign(camLst,'PRM-Groupe-1');
    }
}