force-app/main/default/objects/Case/fields/Date_Debut__c.field-meta.xml
<CustomField>
    <fullName>Date_Debut__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Debut</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/date_en_cours__c.field-meta.xml
<CustomField>
    <fullName>date_en_cours__c</fullName>
    <description>La date quand le staut passe à &quot;en cours&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Date passage en cours</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_Fin__c.field-meta.xml
<CustomField>
    <fullName>Date_Fin__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Fin</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Motif_de_la_requete__c.field-meta.xml
<CustomField>
    <fullName>Motif_de_la_requete__c</fullName>
    <label>Motif de la requête</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sous_type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A oublié de retirer sa lettre</fullName>
            </value>
            <value>
                <fullName>A oublié de se déclarer</fullName>
            </value>
            <value>
                <fullName>A oublié d&apos;indiquer sa lettre</fullName>
            </value>
            <value>
                <fullName>A utilisé une autre lettre</fullName>
            </value>
            <value>
                <fullName>Abonnement Canal</fullName>
            </value>
            <value>
                <fullName>Abonnement hors foyer ou autre</fullName>
            </value>
            <value>
                <fullName>Abs</fullName>
            </value>
            <value>
                <fullName>Absence d&apos;audience justifiée</fullName>
            </value>
            <value>
                <fullName>Absence non déclarée</fullName>
            </value>
            <value>
                <fullName>Absence prolongée</fullName>
            </value>
            <value>
                <fullName>Absent du domicile - Audimètre débranché</fullName>
            </value>
            <value>
                <fullName>Ajout de coordonnées</fullName>
            </value>
            <value>
                <fullName>Ajout de poste</fullName>
            </value>
            <value>
                <fullName>Ajout de poste annulé</fullName>
            </value>
            <value>
                <fullName>Application non active</fullName>
            </value>
            <value>
                <fullName>Attribution d&apos;une touche à un enfant de moins de 4 ans</fullName>
            </value>
            <value>
                <fullName>Audience inférieure à 10min</fullName>
            </value>
            <value>
                <fullName>Audience sans présence</fullName>
            </value>
            <value>
                <fullName>Audience&gt; à X heures avec changement de chaîne</fullName>
            </value>
            <value>
                <fullName>Audiences atypiques</fullName>
            </value>
            <value>
                <fullName>Audiences constatées</fullName>
            </value>
            <value>
                <fullName>Autres abonnements</fullName>
            </value>
            <value>
                <fullName>Autres désabonnements</fullName>
            </value>
            <value>
                <fullName>Autres modifications</fullName>
            </value>
            <value>
                <fullName>Autres motifs</fullName>
            </value>
            <value>
                <fullName>Autres raisons</fullName>
            </value>
            <value>
                <fullName>Autres renseignements</fullName>
            </value>
            <value>
                <fullName>Autres usages justifié (utilisation de périphériques, VOD...)</fullName>
            </value>
            <value>
                <fullName>Autres usages justifié sans appel (utilisation de périphériques, VOD...)</fullName>
            </value>
            <value>
                <fullName>Autres usages non justifié (mauvaise audience =&gt; Collecte OK)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sous_type__c.field-meta.xml
<CustomField>
    <fullName>Sous_type__c</fullName>
    <label>Sous-type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Absence collecte</fullName>
            </value>
            <value>
                <fullName>Absence mouvement</fullName>
            </value>
            <value>
                <fullName>Adaptateur casque</fullName>
            </value>
            <value>
                <fullName>Anomalie affichage</fullName>
            </value>
            <value>
                <fullName>Anomalie autre</fullName>
            </value>
            <value>
                <fullName>Anomalie batterie</fullName>
            </value>
            <value>
                <fullName>Anomalie carte Sim</fullName>
            </value>
            <value>
                <fullName>Anomalie des données en base panel</fullName>
            </value>
            <value>
                <fullName>Anomalie horloge</fullName>
            </value>
            <value>
                <fullName>Anomalie informations</fullName>
            </value>
            <value>
                <fullName>Anomalie lors du traitement des données d&apos;audience</fullName>
            </value>
            <value>
                <fullName>A quitte la mesure</fullName>
            </value>
            <value>
                <fullName>Audience individuelle &gt;7h</fullName>
            </value>
            <value>
                <fullName>Audience individuelle &gt; 7h</fullName>
                <isActive>false</isActive>
                <label>Audience individuelle &gt; 7h</label>
            </value>
            <value>
                <fullName>Audimètre</fullName>
            </value>
            <value>
                <fullName>Audimètre non connecté</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon batterie faible</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon inactif</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon jamais détecté</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Autre cause technique</fullName>
            </value>
            <value>
                <fullName>Autre déplacement</fullName>
            </value>
            <value>
                <fullName>Autre déplacement hors zone de mesure</fullName>
            </value>
            <value>
                <fullName>Autres usages</fullName>
            </value>
            <value>
                <fullName>Avis</fullName>
            </value>
            <value>
                <fullName>Beacon</fullName>
            </value>
            <value>
                <fullName>Beacon (logement plus grand)</fullName>
            </value>
            <value>
                <fullName>Beacon(s) Réceptionné(s)</fullName>
            </value>
            <value>
                <fullName>Beacon (tv en plus)</fullName>
            </value>
            <value>
                <fullName>Beacon (vehicule supplémentaire)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Demande_Paneliste.recordType-meta.xml
<RecordType>
    <fullName>Demande_Paneliste</fullName>
    <active>true</active>
    <businessProcess>Autres</businessProcess>
    <label>Demande Panéliste</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Demande_Paneliste_AIP.recordType-meta.xml
<RecordType>
    <fullName>Demande_Paneliste_AIP</fullName>
    <active>true</active>
    <businessProcess>Demande Paneliste AIP</businessProcess>
    <label>Demande panéliste AIP</label>
</RecordType>

force-app/main/default/objects/Formulaire__mdt/Formulaire__mdt.object-meta.xml
<CustomObject>
    <label>Formulaire</label>
    <pluralLabel>Formulaires</pluralLabel>
</CustomObject>

force-app/main/default/objects/Formulaire__mdt/fields/Formulaire__c.field-meta.xml
<CustomField>
    <fullName>Formulaire__c</fullName>
    <label>Formulaire</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commander</fullName>
                <default>true</default>
                <label>Commander</label>
            </value>
            <value>
                <fullName>Nous contacter</fullName>
            </value>
            <value>
                <fullName>Planifier un RDV</fullName>
            </value>
            <value>
                <fullName>Absence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Formulaire__mdt/fields/Sous_type_portail__c.field-meta.xml
<CustomField>
    <fullName>Sous_type_portail__c</fullName>
    <label>Sous_type portail</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Formulaire__mdt/fields/Sous_type_SF__c.field-meta.xml
<CustomField>
    <fullName>Sous_type_SF__c</fullName>
    <label>Sous_type_SF</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Formulaire__mdt/fields/Type_portail__c.field-meta.xml
<CustomField>
    <fullName>Type_portail__c</fullName>
    <label>Type portail</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Formulaire__mdt/fields/Type_SF__c.field-meta.xml
<CustomField>
    <fullName>Type_SF__c</fullName>
    <label>Type SF</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Formulaire__mdt/fields/user_type__c.field-meta.xml
<CustomField>
    <fullName>user_type__c</fullName>
    <label>user type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AIP</fullName>
                <default>true</default>
                <label>AIP</label>
            </value>
            <value>
                <fullName>MMAT/PaME</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/recordTypes/AIP.recordType-meta.xml
<RecordType>
    <fullName>AIP</fullName>
    <active>true</active>
    <label>AIP</label>
</RecordType>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AddFileToCase.cls
public with sharing class AddFileToCase {
    @AuraEnabled
    public static Boolean addAttachment(String fileContentVersionId, String typeValue, String sousTypeValue, String descriptionValue, 
                                        String statusValue, String dateDebut ,String dateFin, String pointDebit, String functionName, 
                                        String appointmentTime, String motif) {    
                                            system.debug('fileContentVersionId'+fileContentVersionId);
                                                                      system.debug('fileContentVersionId'+String.isNotBlank(fileContentVersionId));
                  
                                            
                                            Boolean caseCreated = false;
                                            Id contactId = [SELECT Id, ContactId  
                                                            FROM User 
                                                            WHERE Id = :UserInfo.getUserId() ].get(0).ContactId;
                                            
                                            //Case RecordType Id
                                            String demandePenalisteId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Demande_Paneliste').getRecordTypeId();
                                            String demandePenalisteAIPId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Demande_Paneliste_AIP').getRecordTypeId();
                                            String caseRecordId;
                                            String FoyerPanId;
                                            for(Individu_Paneliste__c ind :[SELECT Id, Foyer_paneliste__r.RecordType.DeveloperName, Foyer_paneliste__c 
                                                                            FROM Individu_Paneliste__c 
                                                                            WHERE Composition_du_foyer__c = :contactId]){
                                                                                caseRecordId = ind.Foyer_paneliste__r.RecordType.DeveloperName == 'AIP' ? demandePenalisteAIPId : demandePenalisteId;
                                                                                FoyerPanId = ind.Foyer_paneliste__c;
                                                                            }
                                            System.debug('caseRecordId ' + caseRecordId);
                                            
                                            //recuperer la picklist value en fonction de metadata type on prenant en compte les sous types
                                            List<Formulaire__mdt> frmlList = ContactFormulaire.contactType() ==  'AIP' ?
                                                [SELECT Sous_type_SF__c, Type_SF__c ,formulaire__c
                                                 from Formulaire__mdt 
                                                 where Type_portail__c =: typeValue
                                                 and Sous_Type_portail__c =: sousTypeValue
                                                 and Formulaire__c =: functionName   
                                                 and user_type__c='AIP'
                                                 limit 1]
                                                :
                                     [SELECT Sous_type_SF__c, Type_SF__c,formulaire__c 
                                                 from Formulaire__mdt 
                                                 where Type_portail__c =: typeValue
                                                 and Sous_Type_portail__c =: sousTypeValue
                                                 and Formulaire__c =: functionName   
                                                 and user_type__c!='AIP'
                                                 limit 1];
 											system.debug('anes typeValue '+typeValue+'anes sousTypeValue ' +sousTypeValue+'anes frmlList '+functionName+'anes contactType '+ ContactFormulaire.contactType()  );
                                            
                                            System.debug('frmlList ' +frmlList);
                                            if (frmlList.size()>0){
                                            Case newCase = new Case(
                                                RecordTypeId = caseRecordId,
                                                Type = frmlList[0].Type_SF__c,
                                                Sous_type__c = frmlList[0].Sous_type_SF__c,
                                                Description = descriptionValue,
                                                Origin = 'Web',
                                                Foyer_paneliste__c=FoyerPanId
                                            );
                                            System.debug('newCase ' + newCase);
                                            
                                            if(functionName == 'commander'){
                                                //newCase.Nombre_De_Point_a_Debiter__c =integer.valueof(pointDebit);
                                            }else if(functionName == 'Absence'){
                                                newCase.Date_Debut__c = Date.valueOf(dateDebut);
                                                newCase.Date_Fin__c = Date.valueOf(dateFin);
                                                newCase.Motif_de_la_requete__c = motif;
                                               newCase.Subject = 'Du ' + Date.valueOf(dateDebut).day()+ '-' + Date.valueOf(dateDebut).month()+ '-'+ Date.valueOf(dateDebut).year() + ' Au ' + Date.valueOf(dateFin).day()+ '-'+ Date.valueOf(dateFin).month()+ '-' + Date.valueOf(dateFin).year();
                                            } else if(functionName == 'Planifier un RDV'){
                                                Date startDate =  Date.valueOf(dateDebut); 
                                                newCase.Subject = 'Le '+ Date.valueOf(dateDebut).day()+ '-' + Date.valueOf(dateDebut).month()+ '-'+ Date.valueOf(dateDebut).year() +', '+ appointmentTime ;
                                                List<String> appointmentTimeList = appointmentTime.split('-');
                                                if(appointmentTimeList.size() > 1){    
                                                    List<String> timeList = appointmentTimeList[0].split(':');
                                                    if(timeList.size() == 2){
                                                        System.debug('Integer.valueOf(timeList[1]) ' + Integer.valueOf(timeList[1]));
                                                        System.debug('Integer.valueOf(timeList[0]) ' + Integer.valueOf(timeList[0]));
                                                        newCase.Date_Debut__c = Datetime.newInstanceGmt(Integer.valueOf(startDate.year()), Integer.valueOf(startDate.month()),
                                                                                                        Integer.valueOf(startDate.day()), Integer.valueOf(timeList[0]),
                                                                                                        Integer.valueOf(timeList[1]), 0);
                                                        System.debug('newCase.Date_Debut__c ' + newCase.Date_Debut__c);
                                                    }
                                                    timeList = appointmentTimeList[1].split(':');
                                                    if(timeList.size() == 2){
                                                        System.debug('Integer.valueOf(timeList[1]) ' + Integer.valueOf(timeList[1]));
                                                        System.debug('Integer.valueOf(timeList[0]) ' + Integer.valueOf(timeList[0]));
                                                        newCase.Date_Fin__c = Datetime.newInstanceGmt(Integer.valueOf(startDate.year()), Integer.valueOf(startDate.month()),
                                                                                                      Integer.valueOf(startDate.day()), Integer.valueOf(timeList[0]),
                                                                                                      Integer.valueOf(timeList[1]), 0);
                                                        System.debug('newCase.Date_Fin__c ' + newCase.Date_Fin__c);
                                                    }
                                                }else{
                                                    newCase.date_en_cours__c = startDate;
                                                } 
                                            }     
                                            try {
                                                insert newCase;
                                                if(String.isNotBlank(fileContentVersionId)){
                                                    insertAttachment(fileContentVersionId, Id.valueOf(newCase.Id));
                                                }
                                                caseCreated = true;
                                            } catch(DMLException e) {
                                                System.debug('An unexpected error has occurred Case: ' + e.getMessage());
                                            }
                                            }
                                            return caseCreated;
                                        
                                            }
    
    private static void insertAttachment(String fileContentVersionId, String newCase){
        System.debug('fileContentVersionId ' + fileContentVersionId);
        list<contentVersion> acc = [SELECT contentDocumentid FROM contentVersion WHERE Id=:fileContentVersionId];
        system.debug('acc = '+acc );
        if (acc.size()>0){
        string Versid = [SELECT contentDocumentid 
                         FROM contentVersion
                         WHERE Id=:fileContentVersionId].ContentDocumentid;
        
        ContentDocumentLink DocLink = new ContentDocumentLink(
            ContentDocumentId = Versid,
            LinkedEntityId = newCase,
            ShareType = 'I',
            Visibility = 'AllUsers'
        );
        
        System.debug('DocLink ' + DocLink);
        try {
            insert doclink; 
        } catch(DMLException e) {
            System.debug('An unexpected error has occurred ContentDocumentLink : ' + e.getMessage());
        }
        }
    }
}