force-app/main/default/objects/Case/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Type_de_controle__c</fullName>
    <label>Type de contrôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <label>Présence</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Autres usages</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Connexion</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Participation</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Réception/abonnement</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Non Répondant</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Participation Web</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Foyer vacancier longue durée</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Inconnu</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Foyer vacancier</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Contrôle Beacon</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Installation SetMeter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Controle__c/Controle__c.object-meta.xml
<CustomObject>
    <label>Contrôle</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du contrôle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrôles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Controle__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Requete__c.field-meta.xml
<CustomField>
    <fullName>Requete__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requête</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Type_de_controle__c</fullName>
    <label>Type de contrôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <label>Présence</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Autres usages</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Connexion</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Participation</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Réception/abonnement</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Non Répondant</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Participation Web</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Foyer vacancier longue durée</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Foyer vacancier</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Contrôle Beacon</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Installation SetMeter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/recordTypes/AIP.recordType-meta.xml
<RecordType>
    <fullName>AIP</fullName>
    <active>true</active>
    <label>AIP</label>
</RecordType>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Batch026_ClotureTest.cls
/*
* @author: Mikael Chaaya
* @date: 20/07/2023
* @TestedClass: Batch026_ClotureCaseSansControle
* @Coverage: 94%
*/
@isTest
public class Batch026_ClotureTest {
    @isTest
    public static void testCreationRequete(){
        Id recordTypeIdFoyerPanelisteAIP = Schema.SObjectType.Foyer_Paneliste__c.getRecordTypeInfosByName().get(Label.PAN_recordType_AIP).getRecordTypeId();
        Id recordTypeIdRequeteControleAIP = Schema.SObjectType.Case.getRecordTypeInfosByName().get(Label.CTRL_RecordType_ControleAIP).getRecordTypeId();
        Id recordTypeIdControleAIP =Schema.SObjectType.Controle__c.getRecordTypeInfosByName().get(Label.CTRL_RecordType_ControleAIP).getRecordTypeId();
        //creer des foyers
        List<Account> foyerList = new List<Account>();
        
        Account foyer1 = new Account();
        foyer1.Name = 'Foyer1';
        foyerList.add(foyer1);

        insert foyerList;
        
        List<Referentiel_Panel__c> referentielPanelToInsert = new List<Referentiel_Panel__c>();
        
        Referentiel_Panel__c refPanAIP = new Referentiel_Panel__c();
        refPanAIP.Name = 'AIP';
        refPanAIP.Type_de_panel__c = Label.RFP_TypePanel_AIP;
        referentielPanelToInsert.add(refPanAIP);
        
        insert referentielPanelToInsert;
        
        List<Foyer_paneliste__c> foyerPanelisteList = new List<Foyer_paneliste__c>();
        
        Foyer_paneliste__c foyerPaneliste1 = Test_Utils.createFoyerPaneliste();
        foyerPaneliste1.RecordTypeId = recordTypeIdFoyerPanelisteAIP;
        foyerPaneliste1.Foyer__c = foyer1.Id;
        foyerPaneliste1.Referentiel_Panel__c = refPanAIP.Id;
        foyerPanelisteList.add(foyerPaneliste1);

        insert foyerPanelisteList;
        

        Case testCase1 = Test_Utils.createCase(foyer1.id);
        testCase1.foyer_paneliste__c = foyerPaneliste1.Id;
        testCase1.Status=Label.CAS_Statut_Nouveau;
        testCase1.Type=Label.CAS_Type_NonRepondantSetMeter;
        testCase1.RecordTypeId = recordTypeIdRequeteControleAIP;
        testCase1.Type_de_controle__c=Label.CAS_TypeControle_Non_Repondant;

        insert testCase1;

        Case testCase2 = Test_Utils.createCase(foyer1.id);
        testCase2.foyer_paneliste__c = foyerPaneliste1.Id;
        testCase2.Status=Label.CAS_Statut_Nouveau;
        testCase2.Type=Label.CAS_Type_Non_repondant;
        testCase2.RecordTypeId = recordTypeIdRequeteControleAIP;
        testCase2.Type_de_controle__c=Label.CAS_TypeControle_Non_Repondant;

        insert testCase2;

        List<controle__c> controleToInsert = new List<controle__c>();
        Controle__c ctrl1 = new controle__c();
        ctrl1.RecordTypeId = recordTypeIdControleAIP;
        ctrl1.foyer__c = foyer1.Id;
        ctrl1.Foyer_paneliste__c = foyerPaneliste1.Id;
        ctrl1.Requete__c = testCase1.Id;
        controleToInsert.add(ctrl1);
        
        insert controleToInsert;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(foyer1.id));
        Batch026_ClotureCaseSansControle bccfb = new Batch026_ClotureCaseSansControle();
        Id batchId = Database.executeBatch(bccfb);
        Test.stopTest();
        
        List<Case> testcases = [SELECT id FROM case WHERE Status=:Label.CAS_Statut_Cloture];
         System.assertEquals(1, testcases.size());
    }

}