force-app/main/default/objects/Case/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sous_type__c.field-meta.xml
<CustomField>
    <fullName>Sous_type__c</fullName>
    <label>Sous-type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Absence collecte</fullName>
            </value>
            <value>
                <fullName>Absence mouvement</fullName>
            </value>
            <value>
                <fullName>Adaptateur casque</fullName>
            </value>
            <value>
                <fullName>Anomalie affichage</fullName>
            </value>
            <value>
                <fullName>Anomalie autre</fullName>
            </value>
            <value>
                <fullName>Anomalie batterie</fullName>
            </value>
            <value>
                <fullName>Anomalie carte Sim</fullName>
            </value>
            <value>
                <fullName>Anomalie des données en base panel</fullName>
            </value>
            <value>
                <fullName>Anomalie horloge</fullName>
            </value>
            <value>
                <fullName>Anomalie informations</fullName>
            </value>
            <value>
                <fullName>Anomalie lors du traitement des données d&apos;audience</fullName>
            </value>
            <value>
                <fullName>A quitte la mesure</fullName>
            </value>
            <value>
                <fullName>Audience individuelle &gt;7h</fullName>
            </value>
            <value>
                <fullName>Audience individuelle &gt; 7h</fullName>
                <isActive>false</isActive>
                <label>Audience individuelle &gt; 7h</label>
            </value>
            <value>
                <fullName>Audimètre</fullName>
            </value>
            <value>
                <fullName>Audimètre non connecté</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon batterie faible</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon inactif</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon jamais détecté</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Autre cause technique</fullName>
            </value>
            <value>
                <fullName>Autre déplacement</fullName>
            </value>
            <value>
                <fullName>Autre déplacement hors zone de mesure</fullName>
            </value>
            <value>
                <fullName>Autres usages</fullName>
            </value>
            <value>
                <fullName>Avis</fullName>
            </value>
            <value>
                <fullName>Beacon</fullName>
            </value>
            <value>
                <fullName>Beacon (logement plus grand)</fullName>
            </value>
            <value>
                <fullName>Beacon(s) Réceptionné(s)</fullName>
            </value>
            <value>
                <fullName>Beacon (tv en plus)</fullName>
            </value>
            <value>
                <fullName>Beacon (vehicule supplémentaire)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Membre</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Invité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Non panéliste</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Formulaire__mdt/Formulaire__mdt.object-meta.xml
<CustomObject>
    <label>Formulaire</label>
    <pluralLabel>Formulaires</pluralLabel>
</CustomObject>

force-app/main/default/objects/Formulaire__mdt/fields/Formulaire__c.field-meta.xml
<CustomField>
    <fullName>Formulaire__c</fullName>
    <label>Formulaire</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commander</fullName>
                <default>true</default>
                <label>Commander</label>
            </value>
            <value>
                <fullName>Nous contacter</fullName>
            </value>
            <value>
                <fullName>Planifier un RDV</fullName>
            </value>
            <value>
                <fullName>Absence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Formulaire__mdt/fields/Sous_type_portail__c.field-meta.xml
<CustomField>
    <fullName>Sous_type_portail__c</fullName>
    <label>Sous_type portail</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Formulaire__mdt/fields/Sous_type_SF__c.field-meta.xml
<CustomField>
    <fullName>Sous_type_SF__c</fullName>
    <label>Sous_type_SF</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Formulaire__mdt/fields/Type_portail__c.field-meta.xml
<CustomField>
    <fullName>Type_portail__c</fullName>
    <label>Type portail</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Formulaire__mdt/fields/Type_SF__c.field-meta.xml
<CustomField>
    <fullName>Type_SF__c</fullName>
    <label>Type SF</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Formulaire__mdt/fields/user_type__c.field-meta.xml
<CustomField>
    <fullName>user_type__c</fullName>
    <label>user type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AIP</fullName>
                <default>true</default>
                <label>AIP</label>
            </value>
            <value>
                <fullName>MMAT/PaME</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/recordTypes/AIP.recordType-meta.xml
<RecordType>
    <fullName>AIP</fullName>
    <active>true</active>
    <label>AIP</label>
</RecordType>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invité</fullName>
            </value>
            <value>
                <fullName>Membre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT( Foyer_paneliste__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactFormulaire_Test.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 06-14-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest(seealldata=true)
public class ContactFormulaire_Test {
    
    static void setup(String nameUser) {
        
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        
        Referentiel_Panel__c referentiel = new Referentiel_Panel__c(Type_de_panel__c = 'AIP');
        insert referentiel;
        Foyer_paneliste__c foyer = new Foyer_paneliste__c(Referentiel_Panel__c = referentiel.Id);
        insert foyer;
        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'User',
            Email = 'testuser@test.com',
            type__c='1',
            AccountId = testAccount.Id,
            Birthdate = System.today().addYears(-30)
        );
        insert testContact;
        Individu_Paneliste__c individu = new Individu_Paneliste__c(Composition_du_foyer__c = testContact.Id, Foyer_paneliste__c = foyer.Id);
        insert individu;
        User u = new User(Alias = 'Alia', Email='standarduser@testorg.com',
                          EmailEncodingKey='UTF-8', LastName=nameUser, LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = [SELECT Id FROM Profile WHERE UserType = 'CspLitePortal' limit 1].Id,
                          TimeZoneSidKey='America/Los_Angeles', UserName=nameUser+'@testorg.com',
                          ContactId = testContact.Id);
        insert u;
        
        List<Formulaire__mdt> testFormulaires = [
            SELECT DeveloperName, Label, Sous_type_portail__c, Sous_type_SF__c, Type_portail__c, Type_SF__c,Formulaire__c,user_type__c 
            FROM Formulaire__mdt
            limit 10
        ];
        system.debug('testFormulaires '+testFormulaires);
    }
    // Testing 'onPageInit' method
    @istest
    static void testOnPageInit() {
        setup('user1');
        
        // This is to avoid the MIXED_DML_OPERATION error.
        System.runAs(new User(Id = UserInfo.getUserId())) {
            // You need to provide the current page that the 'onPageInit' method needs to work on.
            // For each different page, you would need a different test method, or you could use a loop to iterate through multiple page names.
            // Assuming 'Commander', 'Absence', 'NousContacter', 'Planifier un RDV' are the possible page names.
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
            ContactFormulaire.onPageInit('Commander');
            ContactFormulaire.onPageInit('Absence');
            ContactFormulaire.onPageInit('NousContacter');
            ContactFormulaire.onPageInit('Planifier un RDV');
            
            
            Test.stopTest();
            
            // Assert statements to validate the behavior
            // For example, you may need to verify if a certain list in the onLoadWrapper object gets populated based on the currentPage and the contactType.
        }
    }
    
    // Add similar test methods for the other methods in your class
    @isTest
    static void testContactCgu() {
        setup('user2');
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        
        ContactFormulaire.InitWhrapper result = ContactFormulaire.ContactCgu();
        // Add assertions based on the expected behavior of the method
        Test.stopTest();
    }
    
      // Add similar test methods for the other methods in your class
    @isTest
    static void testContactCguPopUp() {
        setup('user2');
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        
        ContactFormulaire.InitWhrapper result = ContactFormulaire.ContactCguPopUp();
        // Add assertions based on the expected behavior of the method
        Test.stopTest();
    }
    
    @isTest
    static void testUpdateContactCgu() {
        setup('user3');
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        
        ContactFormulaire.updateContactCgu();
        // Add assertions based on the expected behavior of the method
        Test.stopTest();
    }
    
    @isTest
    static void testContactType() {
        setup('user4');
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        
        String result = ContactFormulaire.contactType();
        // Add assertions based on the expected behavior of the method
        Test.stopTest();
    }
    
    @isTest
    static void testGetSousType() {
        setup('user5');
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        
        List<String> result = ContactFormulaire.getSousType('motif', 'Formulaire');
        // Add assertions based on the expected behavior of the method
        Test.stopTest();
    }
    
    @isTest
    static void testCreateNousContactezCase() {
        setup('user6');
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        
        User u =[SELECT Id, ContactId, UserName
                 FROM User
                 WHERE UserName = 'user6@testorg.com'
                 LIMIT 1];
        
        
        //ContentVersion cv =[SELECT contentDocumentid FROM contentVersion limit 1 ];
        Id networkId = [SELECT Id FROM Network LIMIT 1].Id;
        
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Test Document',
            PathOnClient = 'Test.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true,
            NetworkId = networkId
            
        ); 
        insert contentVersion;       
        System.runAs(u) {
            

            Boolean result = ContactFormulaire.CreateNousContactezCase('Autre', 'Autre','Abs', 'description', Date.today(), Date.today(),contentVersion.Id);
            
        }        // Add assertions based on the expected behavior of the method
        Test.stopTest();
    }
    
    @isTest
    static void testCreateCommandeCase() {
        setup('user7');
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        
        User u =[SELECT Id, ContactId, UserName
                 FROM User
                 WHERE UserName = 'user7@testorg.com'
                 LIMIT 1];
        System.runAs(u) {
            Boolean result = ContactFormulaire.createCommandeCase('Autre', 'Autre','', 'description', Date.today(), Date.today(),null);
            
        }
        // Add assertions based on the expected behavior of the method
        Test.stopTest();
    }
    
    @isTest
    static void testCreateRendezVousCase() {
        setup('user8');
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        
        User u =[SELECT Id, ContactId, UserName
                 FROM User
                 WHERE UserName = 'user8@testorg.com'
                 LIMIT 1];
        System.runAs(u) {
            Boolean result = ContactFormulaire.createRendezVousCase('Autre', 'Autre', 'description',STRING.valueof(Date.today()),STRING.valueof(Date.today()));
            
        }
        Test.stopTest();
    }
    
    @isTest
    static void testCreateAbsenceCase() {
        setup('user8');
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        
        User u =[SELECT Id, ContactId, UserName
                 FROM User
                 WHERE UserName = 'user8@testorg.com'
                 LIMIT 1];
        System.runAs(u) {
            Boolean result = ContactFormulaire.CreateAbsenceCase('Autre', 'Autre', 'motif', 'description', STRING.valueof(Date.today()), STRING.valueof(Date.today()),null);
            
        }
        Test.stopTest();
    }
    
    @isTest
    static void testTypeValues() {
        setup('user01');
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        List<ContactFormulaire.wrapperType> result = ContactFormulaire.typeValues();
        // Add assertions based on the expected behavior of the method
        Test.stopTest();
    }
    
    @isTest
    static void testStatusValues() {
        setup('user02');
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        
        List<ContactFormulaire.wrapperType> result = ContactFormulaire.statusValues();
        // Add assertions based on the expected behavior of the method
        Test.stopTest();
    }
    
    @isTest
    static void testGetFieldDependencies() {
        setup('user03');
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        Map<String, List<String>> result = ContactFormulaire.getFieldDependencies('Case', 'Type', 'Sous_type__c');
        // Add assertions based on the expected behavior of the method
        Test.stopTest();
    }
    
    @isTest
    static void testgetPicklistValues() {
        setup('user003');
        contact cn=[select id,type__c from contact limit 1];
        Schema.DescribeFieldResult fieldResult = contact.type__c.getDescribe();
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        List<Object> result = ContactFormulaire.getPicklistValues(contact.type__c);
        Test.stopTest();
    }
    
    
    private class HttpCalloutMockImpl implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest request) {
            // Create a fake HTTP response
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{'+
                             '    "defaultValue": {'+
                             '        "label": "Default Entry",'+
                             '        "value": "default_value"'+
                             '    },'+
                             '    "values": ['+
                             '        {'+
                             '            "label": "First Value",'+
                             '            "value": "first_value"'+
                             '        },'+
                             '        {'+
                             '            "label": "Second Value",'+
                             '            "value": "second_value"'+
                             '        },'+
                             '        {'+
                             '            "label": "Third Value",'+
                             '            "value": "third_value"'+
                             '        }'+
                             '    ]'+
                             '}');
            response.setStatusCode(200);
            return response;
        }
    }
    
}