force-app/main/default/objects/Case/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Membre</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Invité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Non panéliste</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Formulaire__mdt/Formulaire__mdt.object-meta.xml
<CustomObject>
    <label>Formulaire</label>
    <pluralLabel>Formulaires</pluralLabel>
</CustomObject>

force-app/main/default/objects/Formulaire__mdt/fields/Formulaire__c.field-meta.xml
<CustomField>
    <fullName>Formulaire__c</fullName>
    <label>Formulaire</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commander</fullName>
                <default>true</default>
                <label>Commander</label>
            </value>
            <value>
                <fullName>Nous contacter</fullName>
            </value>
            <value>
                <fullName>Planifier un RDV</fullName>
            </value>
            <value>
                <fullName>Absence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Formulaire__mdt/fields/Sous_type_portail__c.field-meta.xml
<CustomField>
    <fullName>Sous_type_portail__c</fullName>
    <label>Sous_type portail</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Formulaire__mdt/fields/Sous_type_SF__c.field-meta.xml
<CustomField>
    <fullName>Sous_type_SF__c</fullName>
    <label>Sous_type_SF</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Formulaire__mdt/fields/Type_portail__c.field-meta.xml
<CustomField>
    <fullName>Type_portail__c</fullName>
    <label>Type portail</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Formulaire__mdt/fields/Type_SF__c.field-meta.xml
<CustomField>
    <fullName>Type_SF__c</fullName>
    <label>Type SF</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Formulaire__mdt/fields/user_type__c.field-meta.xml
<CustomField>
    <fullName>user_type__c</fullName>
    <label>user type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AIP</fullName>
                <default>true</default>
                <label>AIP</label>
            </value>
            <value>
                <fullName>MMAT/PaME</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/recordTypes/AIP.recordType-meta.xml
<RecordType>
    <fullName>AIP</fullName>
    <active>true</active>
    <label>AIP</label>
</RecordType>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invité</fullName>
            </value>
            <value>
                <fullName>Membre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT( Foyer_paneliste__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_flows__c.field-meta.xml
<CustomField>
    <fullName>Bypass_flows__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass flows</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_process_builders__c.field-meta.xml
<CustomField>
    <fullName>Bypass_process_builders__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass process builders</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_RDD__c.field-meta.xml
<CustomField>
    <fullName>Bypass_RDD__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass RDD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_validation_rules__c.field-meta.xml
<CustomField>
    <fullName>Bypass_validation_rules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass validation rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Solde_de_point__c.field-meta.xml
<CustomField>
    <fullName>Solde_de_point__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Solde de point</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AddFileToCase_Test.cls
@isTest(seeAllData=true)
public class AddFileToCase_Test {
    
    @isTest
    static void testAddAttachment() {

        Id userrole = [Select Id, DeveloperName From UserRole Where DeveloperName = 'MM' Limit 1].Id;

        User adminUser = [Select Id, UserRoleId From User Where Profile.Name='System Administrator'And IsActive=true Limit 1];
        adminUser.Bypass_flows__c=true;
        adminUser.Bypass_RDD__c=true;
        adminUser.Bypass_validation_rules__c=true;
        adminUser.IsActive = true;
        adminUser.UserRoleId = userrole;
        update adminUser;

        System.runAs(adminUser){
            Account testAccount = new Account(Name = 'Test Account');
            insert testAccount;

            Contact testContact = new Contact(LastName = 'Test', Firstname = 'kjnijb', AccountId = testAccount.Id, Birthdate = Date.newInstance(2000, 1, 1), Type__c = '1');
            insert testContact;


            Profile p = [SELECT Id FROM Profile WHERE UserType = 'CspLitePortal' AND Name = 'Customer Community User' LIMIT 1];

            Referentiel_Panel__c referentiel = new Referentiel_Panel__c(Type_de_panel__c = 'AIP');
            insert referentiel;

            Foyer_paneliste__c testFoyer = new Foyer_paneliste__c(Name = 'Test Foyer', Referentiel_Panel__c = referentiel.Id);
            insert testFoyer;

            Individu_Paneliste__c testIndividu = new Individu_Paneliste__c(Name = 'Test Individu', Foyer_paneliste__c = testFoyer.Id, Composition_du_foyer__c = testContact.Id);
            insert testIndividu;
            

            ////
            Account testAccount2 = new Account(Name = 'Test Account 2');
            insert testAccount2;
    
            Contact testContact2 = new Contact(LastName = 'Test', AccountId = testAccount2.Id, Type__c = '1', Birthdate = Date.newInstance(2000, 3, 1));
            insert testContact2;
    
            User testUser = new User(
                Alias = 'tel',
                Email = 'tslam@testorg.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'Bz test2',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                ProfileId = p.Id,
                TimeZoneSidKey = 'America/Los_Angeles',
                UserName = 'lamiaauniquetestclass@testorg.com',
                ContactId = testContact2.Id,
                Solde_de_point__c = '200',
                Bypass_flows__c = true,
                Bypass_RDD__c = true,
                Bypass_process_builders__c = true
            );
            testUser.IsActive = true;
            insert testUser;
    
            // UserLicense ul = [SELECT Id FROM UserLicense WHERE Name = 'Customer Community' LIMIT 1];
    		//List<ContentVersion> cdi = [SELECT ContentDocumentId from ContentVersion LIMIT 1];
            
            ContentVersion testContentVersion = new ContentVersion();
            testContentVersion.Title = 'Test File';
            testContentVersion.PathOnClient = 'testfile.txt';
            testContentVersion.VersionData = Blob.valueOf('Test file content');
            
            //testContentVersion.ContentDocumentId =cdi.get(0).id;
            insert testContentVersion;
            
            //list<ContentVersion> acc = [SELECT contentDocumentid FROM ContentVersion WHERE Id=testContentVersion.id];
            
            Case testCase = new Case();
            insert testCase;
    
             List<Formulaire__mdt> fmdtList = ContactFormulaire.contactType() == 'AIP' ? 
                                     [SELECT Sous_type_SF__c, Type_SF__c FROM Formulaire__mdt WHERE Type_portail__c = 'Autre' AND Sous_Type_portail__c = 'Autre' AND Formulaire__c ='Absence' AND user_type__c = 'AIP' LIMIT 1] :
                                     [SELECT Sous_type_SF__c, Type_SF__c FROM Formulaire__mdt WHERE Type_portail__c = 'Autre' AND Sous_Type_portail__c = 'Autre' AND Formulaire__c ='Absence' AND user_type__c = 'AIP' limit 1];
    
            Test.startTest();
            System.runAs(testUser) {
                test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
                Boolean result = AddFileToCase.addAttachment(
                    '0013X00003Qh9jIQAR',
                    'Autre',
                    'Autre',
                    'motif',
                    'description',
                    String.valueOf(Date.today()),
                    String.valueOf(Date.today()),
                    '',
                    'Absence',
                    '',
                    ''
                );
                
                //AddFileToCase.insertAttachment(testContentVersion.id,testCase.id);
    
                System.assertEquals(false, result);
                
                
                
                
            }
            Test.stopTest();
        }
    }
    
    //deuxiemeM
    
     @isTest
    static void testAddAttachmentAutre() {

        Id userrole = [Select Id, DeveloperName From UserRole Where DeveloperName = 'MM' Limit 1].Id;

        User adminUser = [Select Id, UserRoleId From User Where Profile.Name='System Administrator'And IsActive=true Limit 1];
        adminUser.Bypass_flows__c=true;
        adminUser.Bypass_RDD__c=true;
        adminUser.Bypass_validation_rules__c=true;
        adminUser.IsActive = true;
        adminUser.UserRoleId = userrole;
        update adminUser;

        System.runAs(adminUser){
            Account testAccount = new Account(Name = 'Test Account');
            insert testAccount;

            Contact testContact = new Contact(LastName = 'Test', Firstname = 'kjnijb', AccountId = testAccount.Id, Birthdate = Date.newInstance(2000, 1, 1), Type__c = '1');
            insert testContact;


            Profile p = [SELECT Id FROM Profile WHERE UserType = 'CspLitePortal' AND Name = 'Customer Community User' LIMIT 1];

            Referentiel_Panel__c referentiel = new Referentiel_Panel__c(Type_de_panel__c = 'AIP');
            insert referentiel;

            Foyer_paneliste__c testFoyer = new Foyer_paneliste__c(Name = 'Test Foyer', Referentiel_Panel__c = referentiel.Id);
            insert testFoyer;

            Individu_Paneliste__c testIndividu = new Individu_Paneliste__c(Name = 'Test Individu', Foyer_paneliste__c = testFoyer.Id, Composition_du_foyer__c = testContact.Id);
            insert testIndividu;
            


  
            User testUser = new User(
                Alias = 'tel',
                Email = 'tslam@testorg.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'Bz test2',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                ProfileId = p.Id,
                TimeZoneSidKey = 'America/Los_Angeles',
                UserName = 'lamiaauniquetestclass@testorg.com',
                ContactId = testContact.Id,
                Solde_de_point__c = '200',
                Bypass_flows__c = true,
                Bypass_RDD__c = true,
                Bypass_process_builders__c = true
            );
            testUser.IsActive = true;
            insert testUser;
    
            // UserLicense ul = [SELECT Id FROM UserLicense WHERE Name = 'Customer Community' LIMIT 1];
    
            ContentVersion testContentVersion = new ContentVersion();
            testContentVersion.Title = 'Test2 File';
            testContentVersion.PathOnClient = 'testfile.txt';
            testContentVersion.VersionData = Blob.valueOf('Test file content');
            insert testContentVersion;
    
             Formulaire__mdt fmdt = ContactFormulaire.contactType() == 'AIP' ? 
                                     [SELECT Sous_type_SF__c, Type_SF__c FROM Formulaire__mdt WHERE Type_portail__c = 'Autre' AND Sous_Type_portail__c = 'Autre' AND Formulaire__c = 'Planifier un RDV' AND user_type__c = 'AIP' LIMIT 1] :
                                     [SELECT Sous_type_SF__c, Type_SF__c FROM Formulaire__mdt WHERE Type_portail__c = 'Autre' AND Sous_Type_portail__c = 'Autre' AND Formulaire__c = 'Planifier un RDV' AND user_type__c = 'AIP' LIMIT 1];
    
            Test.startTest();
            System.runAs(testUser) {
                test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
                Boolean result = AddFileToCase.addAttachment(
                    '0013X00003Qh9jIQAR',
                    'Autre',
                    'Autre',
                    'motif',
                    'description',
                    String.valueOf(Date.today()),
                    String.valueOf(Date.today()),
                    '',
                    'Planifier un RDV',
                    '15:00-17:00',
                     ''
                );
    
                
            }
            Test.stopTest();
        }
    }
    //findeuxiemeM
   
    
    private class HttpCalloutMockImpl implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest request) {
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{'+
                             '    "defaultValue": {'+
                             '        "label": "Default Entry",'+
                             '        "value": "default_value"'+
                             '    },'+
                             '    "values": ['+
                             '        {'+
                             '            "label": "First Value",'+
                             '            "value": "first_value"'+
                             '        },'+
                             '        {'+
                             '            "label": "Second Value",'+
                             '            "value": "second_value"'+
                             '        },'+
                             '        {'+
                             '            "label": "Third Value",'+
                             '            "value": "third_value"'+
                             '        }'+
                             '    ]'+
                             '}');
            response.setStatusCode(200);
            return response;
        }
    }
}