force-app/main/default/objects/Case/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sous_type__c.field-meta.xml
<CustomField>
    <fullName>Sous_type__c</fullName>
    <label>Sous-type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Absence collecte</fullName>
            </value>
            <value>
                <fullName>Absence mouvement</fullName>
            </value>
            <value>
                <fullName>Adaptateur casque</fullName>
            </value>
            <value>
                <fullName>Anomalie affichage</fullName>
            </value>
            <value>
                <fullName>Anomalie autre</fullName>
            </value>
            <value>
                <fullName>Anomalie batterie</fullName>
            </value>
            <value>
                <fullName>Anomalie carte Sim</fullName>
            </value>
            <value>
                <fullName>Anomalie des données en base panel</fullName>
            </value>
            <value>
                <fullName>Anomalie horloge</fullName>
            </value>
            <value>
                <fullName>Anomalie informations</fullName>
            </value>
            <value>
                <fullName>Anomalie lors du traitement des données d&apos;audience</fullName>
            </value>
            <value>
                <fullName>A quitte la mesure</fullName>
            </value>
            <value>
                <fullName>Audience individuelle &gt;7h</fullName>
            </value>
            <value>
                <fullName>Audience individuelle &gt; 7h</fullName>
                <isActive>false</isActive>
                <label>Audience individuelle &gt; 7h</label>
            </value>
            <value>
                <fullName>Audimètre</fullName>
            </value>
            <value>
                <fullName>Audimètre non connecté</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon batterie faible</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon inactif</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon jamais détecté</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Autre cause technique</fullName>
            </value>
            <value>
                <fullName>Autre déplacement</fullName>
            </value>
            <value>
                <fullName>Autre déplacement hors zone de mesure</fullName>
            </value>
            <value>
                <fullName>Autres usages</fullName>
            </value>
            <value>
                <fullName>Avis</fullName>
            </value>
            <value>
                <fullName>Beacon</fullName>
            </value>
            <value>
                <fullName>Beacon (logement plus grand)</fullName>
            </value>
            <value>
                <fullName>Beacon(s) Réceptionné(s)</fullName>
            </value>
            <value>
                <fullName>Beacon (tv en plus)</fullName>
            </value>
            <value>
                <fullName>Beacon (vehicule supplémentaire)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Nom_pilote__c.field-meta.xml
<CustomField>
    <fullName>Nom_pilote__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Nom pilote</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Nombre_de_set_meters__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_set_meters__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nombre de set meters</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/recordTypes/AIP.recordType-meta.xml
<RecordType>
    <fullName>AIP</fullName>
    <active>true</active>
    <label>AIP</label>
</RecordType>

force-app/main/default/classes/AP01_FoyerPaneliste.cls
/*
* @author: Khaled Hammoudeh
* @date: 18/06/2021
* @ Description classe qui cré une requête à la création d'un enregistrement Panel Mediamat / Pame ou AIP
* @TestClass: AP01_Panel_Test
* @Coverage: 92%
* History
* Date of modification :05/07/2021   Author :Ayoub GHAMMAZ    
Description of modification: Modification de la méthode NouvelleReqAIP pour créer une requête qui contient une commande et les produits commandés

* <Date of modification>   <Author>    <Description of modification>
*/
public class AP01_FoyerPaneliste {
    
    //Create new case for "Installation nouveau foyer" 
    public static void NouvelleReq(List<Foyer_paneliste__c> ListNewPanelisteMMPame)
    {
        system.debug('$$$NouvelleReq');
        
        Id recordTypeIdRequeteDemandePaneliste =Schema.SObjectType.Case.getRecordTypeInfosByName().get(label.CAS_Recordtype_DemandePaneliste).getRecordTypeId();
        List<Case> listCaseToInsert = new List<Case>();
        Database.DMLOptions dmo = new Database.DMLOptions();
        dmo.AssignmentRuleHeader.useDefaultRule = true;
        for(Foyer_paneliste__c pan : ListNewPanelisteMMPame)
        {
            Case caseDemandePanel = createRequete(Label.CASE_Description_InstallationNouveauFoyer, recordTypeIdRequeteDemandePaneliste, 
                                                  Label.CAS_Origine_NouveauFoyer, pan.id,pan.Foyer__c, Label.CAS_Type,
                                                  Label.CAS_Sous_type_Installation_Nouveau_Foyer, dmo);
            listCaseToInsert.add(caseDemandePanel); 
            system.debug('ggg' +caseDemandePanel);
        }
        
        if(listCaseToInsert!=null && listCaseToInsert.size()>0)
        {
            try{ 
                system.debug('ttt');
                database.insert(listCaseToInsert);
            }Catch(exception ex){
                system.debug('Insert Case Nouveau Foyer Exception Error:'+ex.getmessage());
            }
        }
    }
    
    //Create new case Pack initial for panel AIP
    public static void NouvelleReqAIP(List<Foyer_paneliste__c> ListNewPanelisteAIP)
    {
        system.debug('$$$NouvelleReqAIP');

        Id recordTypeIdRequeteDemandePanelisteAIP =Schema.SObjectType.Case.getRecordTypeInfosByName().get(label.CAS_Recordtype_DemandePanelisteAIP).getRecordTypeId();
        List<Case> listCaseToInsert = new List<Case>();  
        Database.DMLOptions dmo = new Database.DMLOptions();
        dmo.AssignmentRuleHeader.useDefaultRule = true;
        
        
        for(Foyer_paneliste__c pan : ListNewPanelisteAIP) {
            System.debug('$$$ AP01_FOyerpaneliste Création requête');
            
            String sousType;
            if(pan.Nombre_de_set_meters__c > 0 && pan.Nom_pilote__c == Label.PAN_Nom_Pilote_ROAv3){
                System.debug('***ROA setmeter');
                sousType = Label.CAS_Sous_type_PackInitial_ROAv3_Setmeter;
            }
            else if(pan.Nom_pilote__c == Label.PAN_Nom_Pilote_ROAv3){
                System.debug('***ROA');
                sousType = Label.CAS_Sous_type_PackInitial_ROAv3;
            }
            else if (pan.Nombre_de_set_meters__c > 0) {
                System.debug('***setmeter');
				sousType = Label.CAS_Sous_type_PackInitial_SetMeter;                
            }
            else {
                System.debug('***pager');
                sousType = Label.CAS_Sous_type_PackInitial;
            }
            
            Case caseDemandePanelAIP = createRequete(Null, recordTypeIdRequeteDemandePanelisteAIP, Label.CAS_Origine_NouveauFoyer,
                                                     pan.id,pan.Foyer__c, Label.CAS_Type_Recrute, sousType, dmo);
            listCaseToInsert.add(caseDemandePanelAIP); 
            System.debug('*** caseDemandePanelAIP' + caseDemandePanelAIP);
        }
        System.debug('*** listCaseToInsert' + listCaseToInsert);
        
        if(listCaseToInsert!=null && listCaseToInsert.size()>0) {
            try{ 
                database.insert(listCaseToInsert);
                System.debug('***Insertion réussi');
            } Catch(exception ex) {
                system.debug('Insert Case Pack Initial/Welcome call Exception Error:'+ex.getmessage());
            }
        }
        System.debug('*** listCaseToInsert' + listCaseToInsert);
        
    }
    
    
    //Method to create requête
    // String membreDuFoyerId,
    public static case createRequete(String descriptionRequete, String recTypeId, String origineRequete, String panelId, String foyerId,
                                     String typeRequete, String sousTypeRequete, Database.DMLOptions dmo)
    {
        Case cs = new Case();
        cs.description = descriptionRequete;
        cs.RecordTypeId = recTypeId;
        cs.Origin = origineRequete;
        cs.AccountId=foyerId;
        cs.Foyer_paneliste__c = panelId ;
        //cs.ContactId = membreDuFoyerId;
        cs.Type = typeRequete;
        cs.Sous_type__c = sousTypeRequete;
        cs.setOptions(dmo);
        
        return cs;
    }
}