force-app/main/default/objects/Case/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sous_type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Sous_type_de_controle__c</fullName>
    <label>Sous type de contrôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>13</fullName>
                <label>Anomalie des données en base panel</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Anomalie lors du traitement des données d&apos;audience</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Audience individuelle &gt; 9h</label>
            </value>
            <value>
                <fullName>Audimètre non connecté</fullName>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Individu sans activité Web cohérente</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>Individus sans audience depuis 28 jours ou plus</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Foyers sans audience depuis 6 jours ou plus</label>
            </value>
            <value>
                <fullName>Foyer avec audience sans abo</fullName>
            </value>
            <value>
                <fullName>Foyer avec abo C+ sans audience</fullName>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Foyer sans activité routeur</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Foyer sans activité Web cohérente</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Non envoyé au Médiamat</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Rejeté Médiamat</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>TV On &gt; 12h</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Autres usages</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Audience incohérente</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Autre CauseTechnique</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Foyer vacancier longue durée</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Foyers non connectés</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Participation Audience Individuelle 6h-9h</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Perte abonnement</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Absence mouvement</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Absence collecte</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Pager OFF</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Pager éteint trop longtemps</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Autres</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>Tous beacons inactifs</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Tous beacons &lt;20%</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>Au moins 1 beacon inactif</label>
            </value>
            <value>
                <fullName>38</fullName>
                <label>Indice de qualité faible</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Type_de_controle__c</fullName>
    <label>Type de contrôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <label>Présence</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Autres usages</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Connexion</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Participation</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Réception/abonnement</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Non Répondant</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Participation Web</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Foyer vacancier longue durée</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Inconnu</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Foyer vacancier</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Contrôle Beacon</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Installation SetMeter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Controle.recordType-meta.xml
<RecordType>
    <fullName>Controle</fullName>
    <active>true</active>
    <businessProcess>Contrôle</businessProcess>
    <label>Contrôle</label>
</RecordType>

force-app/main/default/objects/Controle__c/Controle__c.object-meta.xml
<CustomObject>
    <label>Contrôle</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du contrôle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrôles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Controle__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Requete__c.field-meta.xml
<CustomField>
    <fullName>Requete__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requête</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Type_de_controle__c</fullName>
    <label>Type de contrôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <label>Présence</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Autres usages</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Connexion</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Participation</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Réception/abonnement</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Non Répondant</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Participation Web</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Foyer vacancier longue durée</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Foyer vacancier</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Contrôle Beacon</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Installation SetMeter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Etiquette__c/Etiquette__c.object-meta.xml
<CustomObject>
    <label>Étiquette</label>
    <nameField>
        <displayFormat>ETQ - {000000}</displayFormat>
        <label>Numéro de l&apos;étiquette</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Étiquettes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Etiquette__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Etiquettes</relationshipLabel>
    <relationshipName>Etiquettes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Etiquette__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La foyer panéliste sélectionné n&apos;appartient pas au foyer choisi</errorMessage>
        <filterItems>
            <field>Foyer_paneliste__c.Foyer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Foyer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Étiquettes</relationshipLabel>
    <relationshipName>Etiquettes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/recordTypes/AIP.recordType-meta.xml
<RecordType>
    <fullName>AIP</fullName>
    <active>true</active>
    <label>AIP</label>
</RecordType>

force-app/main/default/classes/Batch013_CreationRequeteAIPNonRep.cls
/*
* @date: 02/11/2021
* @ Description : Creation des requêtes Controle AIP de type non répondant à partir de controle précodé arrivé à terme.
* @version 1.00   
* @Auteur Claire VEHRLE
* @TestClass: Batch013_CreationRequeteAIPNonRep_Test
* @Coverage: --%
History
* <Date of modification> 		<Author> 			<Description of modification>
*/
global class Batch013_CreationRequeteAIPNonRep implements Database.Batchable<sObject>, Database.AllowsCallouts {
    
    global List<Controle__c> start(Database.BatchableContext bc) {
        
        Id recordTypeIdControleAIPControle = Schema.SObjectType.Controle__c.getRecordTypeInfosByName().get(label.CTRL_RecordType_ControleAIP).getRecordTypeId();
        List<Controle__c> controleList = [SELECT Id, Foyer__r.Id, requete__c, Foyer_paneliste__c, Type_de_controle__c, sous_type_de_controle__c FROM Controle__c WHERE Statut__c = :Label.CTRL_Statut_Precode AND Requete__c = null
                        AND RecordType.Id = :recordTypeIdControleAIPControle ];
        
        return controleList;
    }
    
    global void execute(Database.BatchableContext bc, List<Controle__c> scope) {
        
        Id recordTypeIdControleAIPRequte = Schema.SObjectType.Case.getRecordTypeInfosByName().get(label.CAS_Recordtype_ControleAIP).getRecordTypeId();
        List<Case> caseToInsert = new List<Case>();
        List<controle__c> controleToUpdate = new List<controle__c>();
        Date today = Date.today();
        List<Id> foyerId = new List<Id>();
        for (Controle__c controle: scope) {
            System.debug('@@@controle: ' + controle);
            foyerId.add(controle.Foyer__r.Id);
        }
        
        List<Etiquette__c> etiquetteList = [SELECT Id, Date_de_fin__c, Foyer__r.Id, Foyer_Paneliste__r.Id FROM Etiquette__c WHERE Foyer__r.Id IN :foyerId];
        
       
        
        for (Controle__c controle: scope) {
            for (Etiquette__c etiquette :etiquetteList) {
                System.debug('@@@etiquette: ' + etiquette);
                if(etiquette.Date_de_fin__c <= today && controle.foyer__c == etiquette.Foyer__c) {
                    System.debug('@@@Création requête');
                    Case requete = new Case();
                    requete.AccountId = controle.Foyer__r.Id;
                    requete.Foyer_paneliste__c = controle.Foyer_paneliste__c;
                    requete.RecordTypeId = recordTypeIdControleAIPRequte;
                    requete.Process_Post_Etiquette_Motif__c = true;
                    requete.Type_de_controle__c = controle.Type_de_controle__c;
                    requete.Sous_type_de_controle__c = controle.Sous_type_de_controle__c;
                    requete.type = Label.CAS_Type_Non_repondant;
                    caseToInsert.add(requete);
                    System.debug('@@@requete: ' + requete);
                }
            }
        }
        
        System.debug('@@@caseToInsert: ' + caseToInsert);
        try{
            insert caseToInsert;
        } catch(Exception e) {
            System.debug('@@@Erreur durant l\'insertion des requêtes : ' + e.getMessage() + '\n');
        }
        
        for (Controle__c controle: scope) {
            for (Case requete: caseToInsert) {
                if(controle.foyer__r.Id == requete.AccountId) {
                    controle.requete__c = requete.Id;
                }
            }
            controleToUpdate.add(controle);
        }
        
        try{
            database.update(controleToUpdate, false);
        } catch(Exception e) {
            System.debug('@@@Erreur durant la mise à jour des contrôles : ' + e.getMessage() + '\n');
        }
    }
    
    global void finish(Database.BatchableContext bc) {
        
    }

}