force-app/main/default/objects/Case/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sous_type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Sous_type_de_controle__c</fullName>
    <label>Sous type de contrôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>13</fullName>
                <label>Anomalie des données en base panel</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Anomalie lors du traitement des données d&apos;audience</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Audience individuelle &gt; 9h</label>
            </value>
            <value>
                <fullName>Audimètre non connecté</fullName>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Individu sans activité Web cohérente</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>Individus sans audience depuis 28 jours ou plus</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Foyers sans audience depuis 6 jours ou plus</label>
            </value>
            <value>
                <fullName>Foyer avec audience sans abo</fullName>
            </value>
            <value>
                <fullName>Foyer avec abo C+ sans audience</fullName>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Foyer sans activité routeur</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Foyer sans activité Web cohérente</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Non envoyé au Médiamat</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Rejeté Médiamat</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>TV On &gt; 12h</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Autres usages</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Audience incohérente</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Autre CauseTechnique</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Foyer vacancier longue durée</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Foyers non connectés</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Participation Audience Individuelle 6h-9h</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Perte abonnement</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Absence mouvement</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Absence collecte</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Pager OFF</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Pager éteint trop longtemps</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Autres</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>Tous beacons inactifs</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Tous beacons &lt;20%</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>Au moins 1 beacon inactif</label>
            </value>
            <value>
                <fullName>38</fullName>
                <label>Indice de qualité faible</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Type_de_controle__c</fullName>
    <label>Type de contrôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <label>Présence</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Autres usages</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Connexion</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Participation</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Réception/abonnement</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Non Répondant</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Participation Web</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Foyer vacancier longue durée</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Inconnu</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Foyer vacancier</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Contrôle Beacon</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Installation SetMeter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Controle.recordType-meta.xml
<RecordType>
    <fullName>Controle</fullName>
    <active>true</active>
    <businessProcess>Contrôle</businessProcess>
    <label>Contrôle</label>
</RecordType>

force-app/main/default/objects/Controle__c/Controle__c.object-meta.xml
<CustomObject>
    <label>Contrôle</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du contrôle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrôles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Controle__c/fields/Date_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Date_de_controle__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de contrôle</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Numero__c.field-meta.xml
<CustomField>
    <fullName>Numero__c</fullName>
    <displayFormat>CTRL - {0000}</displayFormat>
    <label>Numéro</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Sous_type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Sous_type_de_controle__c</fullName>
    <label>Sous type de contrôle</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_de_controle__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>13</fullName>
                <label>Anomalie des données en base panel</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Anomalie lors du traitement des données d&apos;audience</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Audience individuelle &gt; 9h</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Individu sans activité Web cohérente</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>Individus sans audience depuis 28 jours ou plus</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Foyers sans audience depuis 6 jours ou plus</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Foyer avec audience sans abo</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Foyer avec abo C+ sans audience</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Foyer sans activité routeur</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Foyer sans activité Web cohérente</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Non envoyé au Médiamat</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Rejeté Médiamat</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>TV On &gt; 12h</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Autres usages</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Autre cause technique</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Foyer vacancier longue durée</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Audimètre non connecté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Audience individuelle &gt;7h</label>
            </value>
            <value>
                <fullName>-1</fullName>
                <label>Inconnu</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Foyers sans audience depuis 4 jours</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Foyers sans audience depuis plus de 4 jours</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Individus sans audience depuis 4 jours</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Individus sans audience depuis plus de 4 jours</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Statut audim. sans date</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Foyers sans audience depuis plus de 90 jours</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Foyers sans audience depuis plus de 180 jours</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Absence mouvement</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Absence collecte</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Pager OFF</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Pager éteint trop longtemps</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Type_de_controle__c</fullName>
    <label>Type de contrôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <label>Présence</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Autres usages</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Connexion</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Participation</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Réception/abonnement</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Non Répondant</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Participation Web</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Foyer vacancier longue durée</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Foyer vacancier</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Contrôle Beacon</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Installation SetMeter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer Panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Commandes</relationshipLabel>
    <relationshipName>Commandes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ControleController.cls
/*
* @author: Astou NDIAYE
* @date: 18/10/2020
* @ Description display controle List of today
* @TestClass: ControleControlle_Test
* @Coverage: 100 %
* History
* <Date of modification>   <Author>    <Description of modification>
*/
public with sharing class ControleController {
 	@AuraEnabled
       
   //the below method is to get all controles
     public static list<Controle__c> getRelatedList(Id recordId)
    {        
        Case c =[ SELECT Id, CreatedDate, Foyer_paneliste__c FROM Case where id=:recordId limit 1 ];
        //system.debug('result case' +c);
       
       Date d =  Date.ValueOf(c.CreatedDate.Format('YYYY-MM-dd'));
     
      	system.debug('date d'+d);
        
      List<Controle__c> controleList = [Select Id, Name, Numero__c,Date_de_controle__c, Type_de_controle__c, Sous_type_de_controle__c  from Controle__c 
                                          where Foyer_paneliste__c =:c.Foyer_paneliste__c ORDER BY Numero__c ASC ];
        
        List<Controle__c> controlesdujour = new List<Controle__c>();
        
        for(Controle__c ct : controleList){
 			system.debug('ttt'+controleList);
            if (ct.Date_de_controle__c!=null){
            	if(Date.ValueOf(ct.Date_de_controle__c.Format('yyyy-MM-dd'))==d)
            		{               
               system.debug('ctrl j date'+ ct.Date_de_controle__c.Format('yyyy-MM-dd')+ct.id);
                system.debug('ctl id'+ct.id);
               controlesdujour.add(ct);
            		}
            }           
        }
       return controlesdujour;
    }
    
    
    //This method is used to handle the Edit/Delete Operation from Related List
    @AuraEnabled
    public static string deleteControle(string controleId){
 
    Controle__c clist=  [Select id from  Controle__c where id=:controleId];
    	
            Delete clist;
            return 'DONE';
    }  
}