force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Identifiant_foyer_pame__c.field-meta.xml
<CustomField>
    <fullName>Identifiant_foyer_pame__c</fullName>
    <label>Identifiant foyer PAME/Google</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/ID_Google__c.field-meta.xml
<CustomField>
    <fullName>ID_Google__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ID Google</label>
    <length>233</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer Panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Commandes</relationshipLabel>
    <relationshipName>Commandes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AP10_FoyerPaneliste.cls
/*
* @author: Bastien Pinard
* @date: 
* @ Description 
* @TestClass: 
* @Coverage: 
* History
* Date of modification :
* <Date of modification>   <Author>    <Description of modification>
*/
public class AP10_FoyerPaneliste {
    public static void newIdIndividuPaneliste(List<Foyer_paneliste__c> ListUpdatedPaneliste){
        Set<Id> IdFoyerPan = new Set<Id>();
        List<Individu_Paneliste__c> IndiPanToUpdate = new List<Individu_Paneliste__c>();
        List<String> indPanSendToGoogle = new List<String>();
        
        Id recordTypeIdFoyerPanPaME =Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_mediamatpame).getRecordTypeId();
        for(Foyer_paneliste__c foyerPan : ListUpdatedPaneliste){
            if(foyerPan.RecordTypeId == recordTypeIdFoyerPanPaME){
                IdFoyerPan.add(foyerPan.Id);
            }            
        }
        
        List<Individu_Paneliste__c> listIndPan = [
            SELECT Id, Foyer_paneliste__c, Foyer_paneliste__r.Identifiant_foyer_pame__c
            FROM Individu_Paneliste__c
            WHERE Foyer_paneliste__c 
            IN :IdFoyerPan 
            ORDER BY Foyer_paneliste__c, CreatedDate
        ];
        
        String prevFoyerPan = '';
                    Integer IndiPanCounter = 1;

        for(Individu_Paneliste__c i : listIndPan){
            String currentFoyerPan = i.Foyer_paneliste__c;
            system.debug('$$$AP10_FoyerPaneliste i : ' + i);

            if (currentFoyerPan != prevFoyerPan && prevFoyerPan != ''){
                IndiPanCounter = 1;
                i.ID_Google__c =   String.valueOf(i.Foyer_paneliste__r.Identifiant_foyer_pame__c)+10+IndiPanCounter;
                prevFoyerPan = i.Foyer_paneliste__c;
                IndiPanCounter = IndiPanCounter + 1;
            } else if (currentFoyerPan == prevFoyerPan){
                i.ID_Google__c = String.valueOf(i.Foyer_paneliste__r.Identifiant_foyer_pame__c)+10+IndiPanCounter;
                prevFoyerPan = i.Foyer_paneliste__c;
                IndiPanCounter = IndiPanCounter + 1;
            }
            
            if(prevFoyerPan == ''){
                i.ID_Google__c = String.valueOf(i.Foyer_paneliste__r.Identifiant_foyer_pame__c)+10+IndiPanCounter;
                prevFoyerPan = i.Foyer_paneliste__c;
                IndiPanCounter = IndiPanCounter + 1;
            }
            IndiPanToUpdate.add(i);
            indPanSendToGoogle.add(i.Id);
        }
        
        update IndiPanToUpdate;
        if(indPanSendToGoogle != null && indPanSendToGoogle.size() >0) {
            AP01_IndividuPaneliste.provisioningGoogleFlow(indPanSendToGoogle);
        }
        
    }
}