force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Appel_OK_KO__c.field-meta.xml
<CustomField>
    <fullName>Appel_OK_KO__c</fullName>
    <label>Appel OK / KO</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>KO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Date_du_dernier_appel__c.field-meta.xml
<CustomField>
    <fullName>Date_du_dernier_appel__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date du dernier appel</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer_Paneliste_ExtId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>Foyer_Paneliste_ExtId_SIPanel__c</fullName>
    <description>&quot;(UID) c&apos;est l&apos;id unique generé par SIPANEL du foyer panéliste 
Ce champ sert a faire l&apos;Upsert du foyer panéliste&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Foyer_Paneliste_ExtId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Appel_OK_KO__c.field-meta.xml
<CustomField>
    <fullName>Appel_OK_KO__c</fullName>
    <label>Appel OK/KO</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>KO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Browser__c.field-meta.xml
<CustomField>
    <fullName>Browser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Browser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Date_d_entree_de_l_individu__c.field-meta.xml
<CustomField>
    <fullName>Date_d_entree_de_l_individu__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;entrée de l&apos;individu</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Date_de_chute_de_l_individu__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute_de_l_individu__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute de l&apos;individu</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Date_du_dernier_appel__c.field-meta.xml
<CustomField>
    <fullName>Date_du_dernier_appel__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date du dernier appel</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/ID_Google__c.field-meta.xml
<CustomField>
    <fullName>ID_Google__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ID Google</label>
    <length>233</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Lettre__c.field-meta.xml
<CustomField>
    <fullName>Lettre__c</fullName>
    <label>Lettre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Lien_meter__c.field-meta.xml
<CustomField>
    <fullName>Lien_meter__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Lien meter</label>
    <length>233</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mobile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Routeur__c.field-meta.xml
<CustomField>
    <fullName>Routeur__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Routeur</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Signature_convention_individuelle_Meter__c.field-meta.xml
<CustomField>
    <fullName>Signature_convention_individuelle_Meter__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Signature convention individuelle Meter</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/TV__c.field-meta.xml
<CustomField>
    <fullName>TV__c</fullName>
    <defaultValue>true</defaultValue>
    <label>TV</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invité</fullName>
            </value>
            <value>
                <fullName>Membre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP03_IndividuPaneliste.cls
/** 
* @author: Marleine Abi Khalil
* @date: 23/03/2022 
* @description: Appeler mulesoft API pour envoyer les individus panélistes d'un individu à la création de l'un de ses individus panélistes
* @Test: Class AP03_IndividuPaneliste_Test
* @Coverage : 96%
* History
* <Date of modification>   		<Author>   		 <Description of modification>
* 04/04/2022                Téoman Sertçelik    Ajout de l'after insert  dans le cas ou le foyer est panélisete Mediamat et/ou PaME
* 21/04/2022                Téoman Sertçelik    Modification de l'endpoint + méthode future
* 20/05/2022				Ayoub GHAMMAZ		Modification du endpoint
*/

public class AP03_IndividuPaneliste {
    
    public static void indPanAEnvoyerAMulesoftInsert(List<Individu_Paneliste__c> listIndividuPaneliste){
        
        List<String> listIndividuPanIds = new List<String>();
        
        for(Individu_Paneliste__c indPan: listIndividuPaneliste) {
            listIndividuPanIds.add(indPan.Id);
        }
        
        if(listIndividuPanIds.size()>0 && !System.isBatch() && !System.isFuture()){
            envoyerAMulesoftInsert(listIndividuPanIds);
        }
    }
    
    public static void indPanAEnvoyerAMulesoftUpdate(List<Individu_Paneliste__c> listIndividuPaneliste, Map<Id,Individu_Paneliste__c> mapOldIndPan){
        
        Set<String> setExtIds = new Set<String>();
        List<Schema.FieldSetMember> fields = Schema.SObjectType.Individu_Paneliste__c.fieldSets.Champs_envoyes_a_Mulesoft.getFields();
        List<Id> indPanId = new List<Id>();
        for(Individu_Paneliste__c indPan: listIndividuPaneliste) {
            indPanId.add(indPan.Id);
        }
        //Ajouter les champs de l'ensemble de champ
        List<Individu_Paneliste__c> listIndPan = [SELECT Id, Date_d_anonymisation__c, Composition_du_foyer__c, 	Date_d_entree_de_l_individu__c,
                                                  Date_de_chute_de_l_individu__c, Browser__c, TV__c, Routeur__c, Mobile__c, Lien_meter__c,
                                                  Signature_convention_individuelle_Meter__c, Type__c, Lettre__c, Date_du_dernier_appel__c,
                                                  Appel_OK_KO__c, Id_google__c
                                                  FROM Individu_Paneliste__c
                                                  WHERE Id in : indPanId];
        for(Individu_Paneliste__c indPan : listIndPan){
            for(Schema.FieldSetMember indPanField : fields) {
                //Vérifier si l'un des champs à envoyer à Mulesoft a été mis à jour
                System.debug('***indPan: ' + indPan);
                System.debug('***indPanField.getFieldPath(): ' + indPanField.getFieldPath());
                System.debug('***mapOldIndPan.get(indPan.Id).get(indPanField.getFieldPath()): ' + mapOldIndPan.get(indPan.Id).get(indPanField.getFieldPath()));
                if(indPan.get(indPanField.getFieldPath()) != mapOldIndPan.get(indPan.Id).get(indPanField.getFieldPath()) && indPan.Date_d_anonymisation__c ==null) {
                    System.debug('***indPanField: ' + indPan.get(indPanField.getFieldPath()));
                    setExtIds.add(indPan.Id); // to be modified accordingly
                }
            }
        }
        System.debug('***setExtIds: '  + setExtIds);
        if(setExtIds.size() > 0 && setExtIds!= null){
            	envoyerAMulesoftUpdate(setExtIds);

        }
    }
    
    //Téoman : modification endpoint + query
    @future (callout=true)
    public static void envoyerAMulesoftInsert(List<String> listIndividuIds){
        
        List<Individu_paneliste__c> listIndividuToUpdate = [SELECT Id, Foyer_paneliste__r.Foyer_Paneliste_ExtId_SIPanel__c,
                                                            Composition_du_foyer__c
                                                            FROM Individu_Paneliste__c
                                                            WHERE Id in : listIndividuIds];
        String method = 'POST';
        String endpoint;
        Http http = new Http();
        
        for(Individu_paneliste__c ind : listIndividuToUpdate) {
            //modification AYoub GHMMAZ du 20/05/2022 : debut
            ///members/{uuid}?flow=sf-to-sipanel
            endpoint =  'callout:Mulesoft_experience_API/' +'api/'+ Label.Mulesoft_Xapp_MM_Sync_Sipanel+'/v1/'+ label.Mulesoft_expAPI_indivduPanPath + '/' 
                + ind.Composition_du_foyer__c
                + '?flow=' + label.Mulesoft_flow_parameter_sf_to_sipanel 
                + '&uid=' + ind.Foyer_paneliste__r.Foyer_Paneliste_ExtId_SIPanel__c;
            //fin
            HttpRequest req = new HttpRequest();
            req.setHeader('x-client-id', label.Mulesoft_expAPI_clientId);
            req.setHeader('x-client-secret', label.Mulesoft_expAPI_clientSecret);
            req.setHeader('Accept', 'application/json');
            req.setHeader('Content-Type', 'application/json');
            req.setEndpoint(endpoint);
            req.setMethod(method);
            
            JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
            gen.writeStringField('description', 'test');
            gen.writeEndObject();
            req.setBody(gen.getAsString());
            HTTPResponse res = http.send(req);
            System.debug(res.getBody());
        }
    }
    
    @future (callout=true)
    public static void envoyerAMulesoftUpdate(Set<String> listIndividuIds){
        
        List<Individu_paneliste__c> listIndividuToUpdate = [SELECT Id, Composition_du_foyer__c
                                                            FROM Individu_Paneliste__c
                                                            WHERE Id in : listIndividuIds];
        String method = 'PUT';
        String endpoint;
        Http http = new Http();
        
        for(Individu_paneliste__c ind : listIndividuToUpdate) {
            endpoint =  'callout:Mulesoft_experience_API/' +'api/'+Label.Mulesoft_Xapp_MM_Sync_Sipanel+'/v1/'+ label.Mulesoft_expAPI_indivduPanPath + '/' 
                + ind.Composition_du_foyer__c
                + '?flow=' + label.Mulesoft_flow_parameter_sf_to_sipanel;
            //fin
            HttpRequest req = new HttpRequest();
            req.setHeader('x-client-id', label.Mulesoft_expAPI_clientId);
            req.setHeader('x-client-secret', label.Mulesoft_expAPI_clientSecret);
            req.setHeader('Accept', 'application/json');
            req.setHeader('Content-Type', 'application/json');
            req.setEndpoint(endpoint);
            req.setMethod(method);
            
            JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
            gen.writeStringField('description', 'test');
            gen.writeEndObject();
            req.setBody(gen.getAsString());
            HTTPResponse res = http.send(req);
            System.debug(res.getBody());
        }
    }
    
        public static void envoyerAMulesoftUpdateBatch(Set<String> listIndividuIds){
        
        List<Individu_paneliste__c> listIndividuToUpdate = [SELECT Id, Composition_du_foyer__c
                                                            FROM Individu_Paneliste__c
                                                            WHERE Id in : listIndividuIds];
        
        
        for(Individu_paneliste__c ind : listIndividuToUpdate) {
            String endpoint =  'callout:Mulesoft_experience_API/' +'api/'+Label.Mulesoft_Xapp_MM_Sync_Sipanel+'/v1/'+ label.Mulesoft_expAPI_indivduPanPath + '/' 
                + ind.Composition_du_foyer__c
                + '?flow=' + label.Mulesoft_flow_parameter_sf_to_sipanel;
            //fin
            String method = 'PUT';
            Http http = new Http();
            HttpRequest req = new HttpRequest();
            req.setHeader('x-client-id', label.Mulesoft_expAPI_clientId);
            req.setHeader('x-client-secret', label.Mulesoft_expAPI_clientSecret);
            req.setHeader('Accept', 'application/json');
            req.setHeader('Content-Type', 'application/json');
            req.setEndpoint(endpoint);
            req.setMethod(method);
            
            JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
            gen.writeStringField('description', 'test');
            gen.writeEndObject();
            req.setBody(gen.getAsString());
            HTTPResponse res = http.send(req);
            System.debug(res.getBody());
        }
    }
}