force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Nombre_de_beacons__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_beacons__c</fullName>
    <label>Nombre de beacons</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Nombre_de_pagers__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_pagers__c</fullName>
    <defaultValue>IF( $RecordType.Name =&apos;AIP&apos;, 1,0 )</defaultValue>
    <label>Nombre de pagers</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Nombre_de_set_meters__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_set_meters__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nombre de set meters</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer Panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Commandes</relationshipLabel>
    <relationshipName>Commandes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Remplacement_materiel__c.field-meta.xml
<CustomField>
    <fullName>Remplacement_materiel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Remplacement matériel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_de_produit__c.field-meta.xml
<CustomField>
    <fullName>Type_de_produit__c</fullName>
    <label>Type de produit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beacon</fullName>
            </value>
            <value>
                <fullName>Routeur Google</fullName>
            </value>
            <value>
                <fullName>Pager</fullName>
            </value>
            <value>
                <fullName>Setmeter</fullName>
            </value>
            <value>
                <fullName>TVM3</fullName>
            </value>
            <value>
                <fullName>Accessoire</fullName>
            </value>
            <value>
                <fullName>Périphérique</fullName>
            </value>
            <value>
                <fullName>Consommable</fullName>
            </value>
            <value>
                <fullName>Composant</fullName>
            </value>
            <value>
                <fullName>Pack Pager</fullName>
            </value>
            <value>
                <fullName>Pack SetMeter</fullName>
            </value>
            <value>
                <fullName>DMD NON COM</fullName>
            </value>
            <value>
                <fullName>DMD COM</fullName>
            </value>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>Streaming Meter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AP01_ProduitCommande.cls
/*
* @date: 24/03/2023
* @ Description : Crée les produits commandés pour une commande créée
* @version 1.00   
* @Auteur Bastien Pinard
* @TestClass: 
* @Coverage: 
History
* <Date of modification> <Author> 	<Description of modification>
*/
public class AP01_ProduitCommande {
    @InvocableMethod
    public static void creerCommandePackRemplacementMateriel(List<String> listOrder) {
        
        List<PricebookEntry> products = [SELECT id, Product2Id,Product2.Name, UnitPrice, Product2.Family, Product2.Type_de_produit__c
                                         FROM pricebookentry WHERE  IsActive=true AND Product2.Remplacement_materiel__c = TRUE];
        Set<Id> SetCommandeToInsert = new Set<Id>();

        for(String o : listOrder){
            SetCommandeToInsert.add(o);
        }
        
        List<OrderItem> produitsCommandes = new List<OrderItem>();
        List<order> orderList = [
            SELECT  id, Foyer_paneliste__r.id, Foyer_paneliste__r.Nombre_de_set_meters__c , Foyer_paneliste__r.Nombre_de_beacons__c, Foyer_paneliste__r.Referentiel_Panel__r.Name,
            Foyer_paneliste__r.Nombre_de_pagers__c, Type
            FROM order WHERE id IN :SetCommandeToInsert
            AND Type = :Label.Ord_Type_PackRemplacementMateriel
        ];
        
        //if a retirer pour le dev sur les autres packs
        if(orderList!=null && orderList.size()>0){
            for(Order ordr : orderList){
                for(PricebookEntry pbe :products ){
                    if (ordr.Foyer_paneliste__r.Referentiel_Panel__r.Name == pbe.Product2.Family) {
                        OrderItem orderItem = new OrderItem();
                        if(ordr.Foyer_paneliste__r.Nombre_de_beacons__c !=null && ordr.Foyer_paneliste__r.Nombre_de_beacons__c !=0 && pbe.Product2.Type_de_produit__c==Label.Pro_type_Beacon) {
                            orderItem = new OrderItem(OrderId = ordr.id, Product2Id = pbe.id, Quantity = ordr.Foyer_paneliste__r.Nombre_de_beacons__c , UnitPrice = pbe.UnitPrice);
                        }
                        else if (ordr.Foyer_paneliste__r.Nombre_de_set_meters__c != null && ordr.Foyer_paneliste__r.Nombre_de_set_meters__c != 0 &&
                                 pbe.Product2.Type_de_produit__c == Label.Pro_type_SetMeter) {
                                     orderItem = new OrderItem(OrderId = ordr.id, Product2Id = pbe.id, Quantity = ordr.Foyer_paneliste__r.Nombre_de_set_meters__c , UnitPrice = pbe.UnitPrice);     
                                 }
                        else if(ordr.Foyer_paneliste__r.Nombre_de_set_meters__c != null && ordr.Foyer_paneliste__r.Nombre_de_set_meters__c != 0 &&
                                pbe.Product2.name.contains('hargeur') || pbe.Product2.name.contains('USB')) {
                                    orderItem = new OrderItem(OrderId = ordr.id, Product2Id = pbe.id, Quantity = ordr.Foyer_paneliste__r.Nombre_de_set_meters__c + 1 , UnitPrice = pbe.UnitPrice);
                                }
                        else if(
                            pbe.Product2.name=='cordon cou' && 
                            (
                                (ordr.Foyer_paneliste__r.Nombre_de_set_meters__c != null && 
                                 ordr.Foyer_paneliste__r.Nombre_de_set_meters__c != 0) ||
                                (ordr.Foyer_paneliste__r.Nombre_de_pagers__c != null && 
                                 ordr.Foyer_paneliste__r.Nombre_de_pagers__c != 0)
                            )
                        ){
                            Decimal nbrCordon = 0;
                            if(ordr.Foyer_paneliste__r.Nombre_de_set_meters__c != null && ordr.Foyer_paneliste__r.Nombre_de_set_meters__c != 0){
                                nbrCordon += ordr.Foyer_paneliste__r.Nombre_de_set_meters__c;
                            }
                            
                            if(ordr.Foyer_paneliste__r.Nombre_de_pagers__c != null && ordr.Foyer_paneliste__r.Nombre_de_pagers__c != 0){
                                nbrCordon += ordr.Foyer_paneliste__r.Nombre_de_pagers__c;
                            }
                            orderItem = new OrderItem(OrderId = ordr.id, Product2Id = pbe.id, Quantity = nbrCordon, UnitPrice = pbe.UnitPrice);
                        }
                        else {
                            System.debug('$$$Else');
                            orderItem = new OrderItem(OrderId = ordr.id, Product2Id = pbe.id, Quantity = 1 , UnitPrice = pbe.UnitPrice);
                        }
                        
                        System.debug('$$$OrderItem: ' + OrderItem);
                        produitsCommandes.add(OrderItem);
                    }
                }            
            }
        }
        
        system.debug('$$$produitsCommandes ' + produitsCommandes);
        if(produitsCommandes!=null && produitsCommandes.size()>0){
            try{ 
                database.insert(produitsCommandes);
            }Catch(exception ex){
                system.debug('Insert commande Pack Initial Exception Error:'+ex.getmessage());
            }
        }
    }
}