force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Identifiant_foyer_pame__c.field-meta.xml
<CustomField>
    <fullName>Identifiant_foyer_pame__c</fullName>
    <label>Identifiant foyer PAME/Google</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/ID_Google__c.field-meta.xml
<CustomField>
    <fullName>ID_Google__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ID Google</label>
    <length>233</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AP08_IndividuPaneliste.cls
public class AP08_IndividuPaneliste {
    public static void newIndividuPaneliste(List<Individu_Paneliste__c> ListNewIndPan){
        Set<Id> foyerPanSet = new Set<Id>();
        for(Individu_Paneliste__c ind : ListNewIndPan){
            foyerPanSet.add(ind.Foyer_paneliste__c);
        }
        System.debug('$$$AP08_IndividuPaneliste newIndividuPaneliste foyerPanSet : ' + foyerPanSet);
        
        List<AggregateResult> listCountFoyerPan = new List<AggregateResult>();
        If(foyerPanSet.size() > 0 && foyerPanSet!=null){
            listCountFoyerPan = [
                SELECT MAX(ID_Google__c),  Foyer_paneliste__r.Id 
                FROM Individu_Paneliste__c 
                WHERE Foyer_paneliste__c  
                IN :foyerPanSet
                GROUP BY Foyer_paneliste__r.Id
            ];
        }
        
        Map<Id, Foyer_paneliste__c> listFoyerPan = new Map<Id, Foyer_paneliste__c>([
            SELECT id, Identifiant_foyer_pame__c
            FROM Foyer_paneliste__c 
            WHERE id 
            IN :foyerPanSet
        ]);
        
        Map<Id, Integer> mapIndPan = new Map<Id, Integer>();
        
        for(AggregateResult i : listCountFoyerPan){
            System.debug('$$$AP08_IndividuPaneliste newIndividuPaneliste i : ' + i);
            mapIndPan.put(i.id, Integer.valueOf(i.get('expr0')));
        }
        
        if(listCountFoyerPan.size() == 0){
            for(Individu_Paneliste__c ind : ListNewIndPan){
                if(ind.Foyer_paneliste__c == listFoyerPan.get(ind.Foyer_paneliste__c).Id && mapIndPan.get(ind.Foyer_paneliste__c) == null){
                    ind.ID_Google__c =  listFoyerPan.get(ind.Foyer_paneliste__c).Identifiant_foyer_pame__c + '101';
                }
            }
        } else if (listCountFoyerPan.size() > 0 && listCountFoyerPan!=null){
            
            System.debug('$$$AP08_IndividuPaneliste newIndividuPaneliste listCountFoyerPan : ' + listCountFoyerPan);
            
            
            
            System.debug('$$$AP08_IndividuPaneliste newIndividuPaneliste listFoyerPan : ' + listFoyerPan);
            
            
            System.debug('$$$AP08_IndividuPaneliste newIndividuPaneliste mapIndPan : ' + mapIndPan);
            
            for(Individu_Paneliste__c ind : ListNewIndPan){
                if(ind.Foyer_paneliste__c == listFoyerPan.get(ind.Foyer_paneliste__c).Id && mapIndPan.get(ind.Foyer_paneliste__c) != null){
                    Integer numberNewInd = mapIndPan.get(ind.Foyer_paneliste__c) + 1;
                    System.debug('$$$AP08_IndividuPaneliste newIndividuPaneliste numberNewInd : ' + numberNewInd);
                    ind.ID_Google__c = String.valueOf(numberNewInd);
                    System.debug('$$$AP08_IndividuPaneliste newIndividuPaneliste ind.ID_Google__c : ' + ind.ID_Google__c);
                }
            }
        }
        
    }
}