force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer_Paneliste_ExtId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>Foyer_Paneliste_ExtId_SIPanel__c</fullName>
    <description>&quot;(UID) c&apos;est l&apos;id unique generé par SIPANEL du foyer panéliste 
Ce champ sert a faire l&apos;Upsert du foyer panéliste&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Foyer_Paneliste_ExtId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT( Foyer_paneliste__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AP01_IndividuPaneliste.cls
/*
* @author: Jérôme HE
* @date: 25/02/2022
* @ Description 
* @TestClass: AP01_IndividuPaneliste_Test
* @Coverage: 94 %
* History
* <Date of modification>   		<Author>   		 <Description of modification>
* 20/05/2022					Hatime AIT ISHAQ	Modification du endpoint
*/ 
public class AP01_IndividuPaneliste {

    
    @future (callout=true)
    // Imad comment Set instead of List
     public static void provisioningGoogleFlow(list<String> listIndPanToUpdate)
     //  public static void provisioningGoogleFlow(Set<Id> listIndPanToUpdate)

    {
        
        List<Individu_Paneliste__c> indPanList = [Select Foyer_paneliste__r.Foyer_Paneliste_ExtId_SIPanel__c, composition_du_foyer__c
                                                  from Individu_Paneliste__c where id in : listIndPanToUpdate AND Foyer_paneliste__r.Referentiel_panel__r.type_de_panel__c = :Label.RFP_TypePanel_PaME];
        system.debug('Imad Msg' + indPanList);
        for(Individu_paneliste__c indPan : indPanList){
            //modification Hatime AIT ISHAQ du 20/05/2022 : debut
            //members/{uuid}?flow=sf-to-google&uid
            
           String endPoint = 'callout:Mulesoft_experience_API/'+'api/'+label.Mulesoft_Xapp_MM_Sync_Google+'/v1/'+ label.Mulesoft_expAPI_indivduPanPath + '/' 
                + indPan.composition_du_foyer__c +'?flow=' + label.Mulesoft_flow_parameter_sf_to_google
                + '&uid=' + indPan.Foyer_paneliste__r.Foyer_Paneliste_ExtId_SIPanel__c;
            
          /*  String serviceName= 'x-mm-sync-google-prep';
              String endPoint = 'callout:Mulesoft_experience_API/'+'api/'+serviceName+'/v1/'+ label.Mulesoft_expAPI_indivduPanPath + '/' 
                + indPan.composition_du_foyer__c +'?flow=' + label.Mulesoft_flow_parameter_sf_to_google
                + '&uid=' + indPan.Foyer_paneliste__r.Foyer_Paneliste_ExtId_SIPanel__c;
            */
            string method = 'POST';
            //fin
            HttpRequest req = creatHttpRequest(method, endpoint);
            
            Http http = new Http();
            HTTPResponse resp = http.send(req);
            
            //If the response contains an error, cast it into a map
            Map<String, Object> mapResponse = new Map<String, Object>();
            Map<String, Object> mapError = new Map<String, Object>();
            system.debug('Imad Body msg: '+ resp.getBody());  
            system.debug('Imad Status Msg: '+ resp.getStatus()); 
            if(resp.getStatus() != 'OK') {
                mapResponse = (Map<String, Object>) JSON.deserializeUntyped(resp.getBody());
                mapError = (Map<String, Object>) mapResponse.get('error');
            }
          
            //Build the response that will be sent back to the flow
            List<CalloutResponse> listReturnValue = new List<CalloutResponse>();
            CalloutResponse returnValue = new CalloutResponse();
            returnValue.responseStatus = resp.getStatus();
            returnValue.responseStatusCode = resp.getStatusCode();
            returnValue.responseErrorReference = ( (resp.getStatus() != 'OK') && (mapError.containsKey('errorReference')) ) ? (String) mapError.get('errorReference') : 'undefined';
            returnValue.responseErrorDescription = ( (resp.getStatus() != 'OK') && (mapError.containsKey('errorDescription')) ) ? (String) mapError.get('errorDescription') : 'undefined';
            system.debug(returnValue);
            listReturnValue.add(returnValue);
            
        }             
    }
    
    public static HttpRequest creatHttpRequest(string method, string endpoint)
    {
        HttpRequest reqToReturn = new HttpRequest();
        reqToReturn.setHeader('x-client-id', label.Mulesoft_expAPI_clientId);
        reqToReturn.setHeader('x-client-secret', label.Mulesoft_expAPI_clientSecret);
        reqToReturn.setHeader('Accept', 'application/json');
        reqToReturn.setHeader('Content-Type', 'application/json');
        reqToReturn.setEndpoint(endpoint);
        reqToReturn.setMethod(method);
        if(method=='PUT' || method=='POST'){
            JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
            gen.writeStringField('description', 'test');
            gen.writeEndObject();
            reqToReturn.setBody(gen.getAsString());
        }
        
        return reqToReturn;
    }
    
    //Wrapper used to return the HTTP response to the visual flow
    public class CalloutResponse {
        @InvocableVariable
        public String responseStatus;
        
        @InvocableVariable
        public Integer responseStatusCode;
        
        @InvocableVariable
        public String responseErrorReference;
        
        @InvocableVariable
        public String responseErrorDescription;
    }
}