force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Sous_type_d_intervention__c.field-meta.xml
<CustomField>
    <fullName>Sous_type_d_intervention__c</fullName>
    <label>Sous-type d&apos;intervention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Nouveau foyer</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Ajout Equipement</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Suppression d&apos;un poste</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Définitive</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Déménagement</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Réinstallation</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Mutation Audimètre</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Vérification des éléments</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Contrôle audience</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Recensement</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Passage Improviste</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>Visite de courtoisie</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Changement</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Contrôle de connexion</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Contrôle de l&apos;installation</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Modification Abonnement</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>Streaming Meter</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>Contrôle Streaming Meter</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>Réinstallation Streaming Meter</label>
            </value>
            <value>
                <fullName>36</fullName>
                <label>Installation Streaming Meter</label>
            </value>
            <value>
                <fullName>37</fullName>
                <label>Mapping devices</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Auto désinstallation</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Configuration Meters (si boite mail ok)</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Configuration routeur (connexion des equipements au routeur Mediametrie )</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>Configuration routeur (connexion des equipements au routeur Mediametrie ) 2 et +</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Configuration Routeur (Pame)</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Contrôle qualité</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Paramétrage Meters 2 à 4</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Paramétrage Meters 5 à 8</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Pb Sonde Tv (Déclaration)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Le foyer sélectionné n&apos;est pas celui du foyer panéliste</errorMessage>
        <filterItems>
            <field>Foyer_paneliste__c.Foyer__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Interventions</relationshipLabel>
    <relationshipName>Interventions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Sous_type_d_intervention__c.field-meta.xml
<CustomField>
    <fullName>Sous_type_d_intervention__c</fullName>
    <description>OBSOLETE A NE PLUS UTILISER</description>
    <label>Sous-type d&apos;intervention</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_de_l_intervention__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Nouveau foyer</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Ajout Equipement</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Suppression d&apos;un poste</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Définitive</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Déménagement</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Réinstallation</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Mutation Audimètre</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Vérification des éléments</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Contrôle audience</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Recensement</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Passage Improviste</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>Visite de courtoisie</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Changement</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Contrôle de connexion</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Contrôle de l&apos;installation</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Vérification de l&apos;initialisation</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>14</fullName>
                <isActive>false</isActive>
                <label>14</label>
            </value>
            <value>
                <fullName>24</fullName>
                <isActive>false</isActive>
                <label>24</label>
            </value>
            <value>
                <fullName>25</fullName>
                <isActive>false</isActive>
                <label>25</label>
            </value>
            <value>
                <fullName>26</fullName>
                <isActive>false</isActive>
                <label>26</label>
            </value>
            <value>
                <fullName>27</fullName>
                <isActive>false</isActive>
                <label>27</label>
            </value>
            <value>
                <fullName>28</fullName>
                <isActive>false</isActive>
                <label>28</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>30</fullName>
                <isActive>false</isActive>
                <label>30</label>
            </value>
            <value>
                <fullName>31</fullName>
                <isActive>false</isActive>
                <label>31</label>
            </value>
            <value>
                <fullName>32</fullName>
                <isActive>false</isActive>
                <label>32</label>
            </value>
            <value>
                <fullName>Mediamat et PaME</fullName>
                <isActive>false</isActive>
                <label>Mediamat et PaME</label>
            </value>
            <value>
                <fullName>Médiamat</fullName>
                <isActive>false</isActive>
                <label>Médiamat</label>
            </value>
            <value>
                <fullName>PaME</fullName>
                <isActive>false</isActive>
                <label>PaME</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Foyer_Paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_Paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer Panéliste</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Le foyer panéliste n&apos;est pas un des foyers panéliste du foyer</errorMessage>
        <filterItems>
            <field>Foyer_paneliste__c.Foyer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Foyer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Actions</relationshipLabel>
    <relationshipName>Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Sous_type_d_intervention__c.field-meta.xml
<CustomField>
    <fullName>Sous_type_d_intervention__c</fullName>
    <label>Actions</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>21</fullName>
                <label>Ajout de poste</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Auto désinstallation</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Changement (TV, barre de son etc …)</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Configuration Meters  (si boite mail ok)</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Configuration routeur  (connexion des equipements au routeur Mediametrie )</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>Configuration routeur (connexion des equipements au routeur Mediametrie ) 2 et +</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Configuration Routeur (Pame)</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Contrôle audience</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Contrôle de connexion</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Contrôle de l&apos;installation</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Contrôle qualité</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Déménagement</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Désinstallation Définitive</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Mise à jour des èquipements</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Modification Abonnement</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Mutation audimétre</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Nouveau foyer</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Paramétrage Meters  2 à 4</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Paramétrage Meters  5 à 8</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Passage improviste</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Pb Sonde Tv (Déclaration)</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Réinstallation</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Routeur ne s&apos;allume plus</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Suppression d&apos;un poste</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Vérification de l&apos;initialisation</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Vérification des éléments</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>Visite de courtoisie</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchRDD15_Action.cls
/*
* @author: Claire VEHRLE
* @date: 02/03/2023
* @ Description Batch pour la RDD de l'objet Action. Remplissage Foyer
* @TestClass: BatchRDD10_RDVService_Test
* @Coverage: 91 %
* History
* <Date of modification>   		<Author>   		 <Description of modification>
*/
public class BatchRDD15_Action  implements Database.Batchable<sObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        
        
        return Database.getQueryLocator([SELECT Id, WorkOrder.Foyer_Paneliste__c, Foyer_Paneliste__c, Sous_type_d_intervention__c, Actions__c 
                                         FROM WorkOrderLineItem WHERE Foyer_Paneliste__c = null]);
        
    }
    
    public void execute(Database.BatchableContext bc, List<WorkOrderLineItem> scope) {
        System.debug('$$$scope: ' + scope);
        for(WorkOrderLineItem action: scope) {
            System.debug('$$$action.WorkOrder.Foyer_Paneliste__c: ' + action.WorkOrder.Foyer_Paneliste__c);
            action.actions__c = action.Sous_type_d_intervention__c;
            if (action.WorkOrder.Foyer_Paneliste__c != null ) {
                System.debug('$$$ foyer Paneliste non null');
                action.Foyer_Paneliste__c = action.WorkOrder.Foyer_Paneliste__c;
            }
            else {
                action.Foyer_Paneliste__c = null;
            }
        }
        if(scope.size() > 0 && scope != null) {
            System.debug('$$$Update scope');
            //Update scope;
            try{ 
                database.update(scope, false);
                System.debug('Nscope' + scope);
            }Catch(exception ex){
                system.debug('Update Action Exception Error:' + ex.getmessage());
            }
        }
    }
    
    public void finish(Database.BatchableContext bc) {
        
    }
    
}