force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer_equipe__c.field-meta.xml
<CustomField>
    <fullName>Foyer_equipe__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Foyer équipé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Identifiant_foyer_pame__c.field-meta.xml
<CustomField>
    <fullName>Identifiant_foyer_pame__c</fullName>
    <label>Identifiant foyer PAME/Google</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Lettre_operateur__c.field-meta.xml
<CustomField>
    <fullName>Lettre_operateur__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Lettre opérateur</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Numero_foyer__c.field-meta.xml
<CustomField>
    <fullName>Numero_foyer__c</fullName>
    <label>Numéro foyer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Batch_RDDIdentifiantPaME.cls
/*
* @date: 24/04/2023
* @ Description : RDD Post MES des identifiants PaME 
* @Auteur : Claire VEHRLE
* @TestClass: Batch_RDDIdentifiantPaME_Test
* @Coverage: -- %
History
* <Date of modification> 		<Author> 	<Description of modification>
* 
*/
public class Batch_RDDIdentifiantPaME implements Database.Batchable<sObject>, Database.Stateful {

    public List<Foyer_Paneliste__c> start(Database.BatchableContext bc) {
        
        List<Foyer_Paneliste__c> FoyerPanPaMEList = new List<Foyer_Paneliste__c>();
        
        FoyerPanPaMEList = [SELECT Id, name, identifiant_foyer_PaME__c, Numero_foyer__c, Lettre_operateur__c 
                            FROM Foyer_Paneliste__c 
                            WHERE Numero_foyer__c != null AND Lettre_operateur__c != null
                            ANd Referentiel_Panel__r.Type_de_panel__c = :Label.RFP_TypePanel_PaME
                            AND Foyer_equipe__c = true];
        
        return FoyerPanPaMEList;
    }
    
    public void execute(Database.BatchableContext bc, List<Foyer_Paneliste__c> scope) {
        System.debug('$$$scope: ' + scope);
        
        String numeroFoyer;
        Map<String, String> panelLetters = new Map<String, String>();
        panelLetters.put('A', '1');
        panelLetters.put('B', '4');
        panelLetters.put('C', '5');
        panelLetters.put('D', '2');
        panelLetters.put('H', '3');
        panelLetters.put('P', '6');
        panelLetters.put('Q', '7');
        panelLetters.put('R', '8');    
        
        for(Foyer_paneliste__c foyerPan:scope) {
                numeroFoyer = String.valueOf(foyerPan.Numero_foyer__c);
                if (numeroFoyer.length() != 4) {
                    if(numeroFoyer.length() == 1) {
                        numeroFoyer = '000' + numeroFoyer;
                    }
                    else if(numeroFoyer.length() == 2) {
                        numeroFoyer = '00' + numeroFoyer;
                    }
                    else {
                        numeroFoyer = '0' + numeroFoyer;
                    }
                }
            foyerPan.Identifiant_foyer_pame__c = Integer.valueOf(panelLetters.get(foyerPan.Lettre_operateur__c) + numeroFoyer);
            System.debug('$$$foyerPan.Identifiant_foyer_pame__c: ' + foyerPan.Identifiant_foyer_pame__c);
        }
        
        if(scope.size() > 0 && scope != null) {
            Update scope;
            /*try{ 
                database.update(scope, false);
            }Catch(exception ex){
                system.debug('Remplissage identifiant PaME Error:' + ex.getmessage());
            }*/
        }
    }
    
    public void finish(Database.BatchableContext BC) {}
}