force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer_Paneliste_ExtId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>Foyer_Paneliste_ExtId_SIPanel__c</fullName>
    <description>&quot;(UID) c&apos;est l&apos;id unique generé par SIPANEL du foyer panéliste 
Ce champ sert a faire l&apos;Upsert du foyer panéliste&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Foyer_Paneliste_ExtId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Date_de_chute_de_l_individu__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute_de_l_individu__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute de l&apos;individu</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Individu_Paneliste_ExtId_SIPanel_c__c.field-meta.xml
<CustomField>
    <fullName>Individu_Paneliste_ExtId_SIPanel_c__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>&quot;(UUID + ‘~’ + UID) c&apos;est une concatenation faite dans mulesoft de UUID et UID avec un tilde entre les 2 valeurs
Ce champ sert a faire l&apos;Upsert de Individu Panéliste&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Individu_Paneliste_ExtId_SIPanel__c</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AP02_IndividuPaneliste.cls
/** 
* @author: Marleine Abi Khalil
* @date: 16/03/2022 
* @description: Appeler mulesoft API pour le deprovisionning google suite a la chute du foyer paneliste
* @Test: Class AP02_IndividuPaneliste_Test
* History
* <Date of modification>   		<Author>   		 <Description of modification>
20/04/2022                   Téoman Sertçelik     Ajouté ids au endpoint // modifié methode future
24/05/2022  Hatime Ait ishaq : modification de la EndPoint


*/
public class AP02_IndividuPaneliste {
    public static void deprovisionningGoogle(List<Individu_Paneliste__c> listIndividuPaneliste, Map<Id, Individu_Paneliste__c> mapOldIndividuPaneliste){
        List<String> listID_IPforDeproviosining = new List<String>();
        
        for(Individu_Paneliste__c indPan : listIndividuPaneliste){
            if(indPan.Date_de_chute_de_l_individu__c != mapOldIndividuPaneliste.get(indPan.Id).Date_de_chute_de_l_individu__c 
               && indPan.Date_de_chute_de_l_individu__c != null){
                   listID_IPforDeproviosining.add(indPan.Id); 
               }
        }
        //TS : added isfuture isbatch 
        if(listID_IPforDeproviosining.size()>0 && !System.isBatch() && !System.isFuture()){
            AP02_IndividuPaneliste.sendForDeprovisionningGoogle(listID_IPforDeproviosining);
        }
    }
    
    @future (callout=true)
    public static void sendForDeprovisionningGoogle(List<String> listID_IPforDeproviosining){ 
        
        List<Individu_Paneliste__c> listIndividuPan = [SELECT Id, Individu_Paneliste_ExtId_SIPanel_c__c,
                                                       Composition_du_foyer__c,foyer_paneliste__r.Foyer_Paneliste_ExtId_SIPanel__c
                                                       FROM Individu_Paneliste__c
                                                       WHERE Id IN : listID_IPforDeproviosining];
        
        String method = 'DELETE';
        String endpoint;
        Http http = new Http();
        
        //TS
        for(Individu_Paneliste__c indPan : listIndividuPan) {
            //24/05/2022  Hatime Ait ishaq : modification de la EndPoint
            //x-mm-sync-google	/members/{uuid}?flow=sf-to-google&uid
            endpoint = 'callout:Mulesoft_experience_API/' + 'api/' +label.Mulesoft_Xapp_MM_Sync_Google+'/v1/'+ label.Mulesoft_expAPI_indivduPanPath 
                + '/' + indPan.Composition_du_foyer__c
                + '?flow=' + label.Mulesoft_flow_parameter_sf_to_google
                + '&uid=' + indPan.foyer_paneliste__r.Foyer_Paneliste_ExtId_SIPanel__c ; 
            //fin modification 24/05/2022
            
            HttpRequest req = new HttpRequest();
            req.setHeader('x-client-id', label.Mulesoft_expAPI_clientId);
            req.setHeader('x-client-secret', label.Mulesoft_expAPI_clientSecret);
            req.setEndpoint(endpoint);
            req.setMethod(method);
            HTTPResponse res = http.send(req);
            System.debug(res.getBody());
        }
    }
}