force-app/main/default/objects/Controle__c/Controle__c.object-meta.xml
<CustomObject>
    <label>Contrôle</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du contrôle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrôles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Controle__c/fields/Rep_ou_non_rep__c.field-meta.xml
<CustomField>
    <fullName>Rep_ou_non_rep__c</fullName>
    <label>Rep ou non rep</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Répondant</fullName>
            </value>
            <value>
                <fullName>Non répondant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Sous_type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Sous_type_de_controle__c</fullName>
    <label>Sous type de contrôle</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_de_controle__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>13</fullName>
                <label>Anomalie des données en base panel</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Anomalie lors du traitement des données d&apos;audience</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Audience individuelle &gt; 9h</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Individu sans activité Web cohérente</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>Individus sans audience depuis 28 jours ou plus</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Foyers sans audience depuis 6 jours ou plus</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Foyer avec audience sans abo</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Foyer avec abo C+ sans audience</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Foyer sans activité routeur</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Foyer sans activité Web cohérente</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Non envoyé au Médiamat</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Rejeté Médiamat</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>TV On &gt; 12h</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Autres usages</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Autre cause technique</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Foyer vacancier longue durée</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Audimètre non connecté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Audience individuelle &gt;7h</label>
            </value>
            <value>
                <fullName>-1</fullName>
                <label>Inconnu</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Foyers sans audience depuis 4 jours</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Foyers sans audience depuis plus de 4 jours</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Individus sans audience depuis 4 jours</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Individus sans audience depuis plus de 4 jours</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Statut audim. sans date</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Foyers sans audience depuis plus de 90 jours</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Foyers sans audience depuis plus de 180 jours</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Absence mouvement</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Absence collecte</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Pager OFF</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Pager éteint trop longtemps</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Tech_Priority__c.field-meta.xml
<CustomField>
    <fullName>Tech_Priority__c</fullName>
    <label>Priorité Contrôle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Type_de_controle__c</fullName>
    <label>Type de contrôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <label>Présence</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Autres usages</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Connexion</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Participation</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Réception/abonnement</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Non Répondant</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Participation Web</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Foyer vacancier longue durée</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Foyer vacancier</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Contrôle Beacon</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Installation SetMeter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Priorite__c/Priorite__c.object-meta.xml
<CustomObject>
    <label>Priorité</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Priorités</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Priorites_de_controles__c/Priorites_de_controles__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Priorités de contrôles</label>
</CustomObject>

force-app/main/default/objects/Priorites_de_controles__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Case Origin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Priorites_de_controles__c/fields/Priorite__c.field-meta.xml
<CustomField>
    <fullName>Priorite__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Priorité</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Priorites_de_controles__c/fields/Rep_ou_non_rep__c.field-meta.xml
<CustomField>
    <fullName>Rep_ou_non_rep__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Rep ou non rep</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Priorites_de_controles__c/fields/Sous_type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Sous_type_de_controle__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sous type de contrôle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Priorites_de_controles__c/fields/Type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Type_de_controle__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type de contrôle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Priorites_de_controles__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type de panel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ControleTriggerHandler.cls
/*
* @author: Elio Bou Habib
* @date: 29/03/2021
* @Description Controle Trigger handler updates controles' Tech_Priority__c
* @Ticket MEDIAMETRIE-9
* @Test Class: ControleTriggerHandler_Test
* @Coverage: 100 %
* History
* <Date of modification>   <Author>    <Description of modification>
*/
public class ControleTriggerHandler extends TriggerHandler implements ITriggerHandler
{
    private Map<Id, SObject> newMap;
    private Map<Id, SObject> oldMap;
    private List<SObject> triggerNew;
    private List<SObject> triggerOld;
    
    public ControleTriggerHandler(){
        this.newMap = (Map<Id, SObject>) Trigger.newMap;
        this.oldMap = (Map<Id, SObject>) Trigger.oldMap;
        this.triggerNew= (List<SObject>) Trigger.New;
        this.triggerOld= (List<SObject>) Trigger.Old;
    }
    public static Boolean TriggerDisabled = false;
    public Boolean isDisabled(){
        return TriggerDisabled;
    }
    public override void beforeInsert() {}
    
    public override void afterInsert() 
    {
        if(Trigger.new != null && 
           !Trigger.new.isEmpty() && 
           !isDisabled() && 
           !TriggerHandler.isBypassed('ControleTriggerHandler'))
        {
            updateTechPriority();
        }
    }
    
    public override void beforeUpdate() {}
    
    public override void afterUpdate() 
    {
        if(Trigger.new != null && 
           !Trigger.new.isEmpty() && 
           Trigger.oldMap != null && 
           !Trigger.oldMap.isEmpty() && 
           !isDisabled() && 
           !TriggerHandler.isBypassed('ControleTriggerHandler'))
        {
            updateTechPriority();
        }
    }
    
    public override void beforeDelete() {}
    
    public override void afterDelete() {}
    
    public override void afterUnDelete() {}
    
    /** 
	* @author Elio Bou Habib
	* @date 29/03/2021
	* @description updates controles' Tech_Priority__c to a number between 1 and 23 according to the custom setting Priorites_de_controles__c
	*/
    public static void updateTechPriority()
    {
        System.debug('Reached1');
        try
        {
            List <Controle__c> controlesToUpdate = new List <Controle__c> ();
            //Get all custom settings
            List <Priorites_de_controles__c> pdcs = [SELECT Id, Name, Origin__c, Type__c, Type_de_controle__c,
                                                     Sous_type_de_controle__c, Type_de_panel__c, Rep_ou_non_rep__c, Priorite__c
                                                     FROM Priorites_de_controles__c];
            if(pdcs != null && !pdcs.isEmpty())
            {
                System.debug('Reached2');
                //Place the custom settings in a map
                Map <String, String> pdcDefToPriorityMap = new Map <String, String>();
                for(Priorites_de_controles__c pdc: pdcs)
                {
                    if(pdc.Type_de_controle__c == Label.CTRL_Type_Connexion || 
                       pdc.Type_de_controle__c == Label.CTRL_Type_NonRepondant ||
                       pdc.Type_de_controle__c == Label.CTRL_Type_ParticipationWeb ||
                       pdc.Type_de_controle__c == Label.CTRL_Type_Foyer_Vacancier)
                    {
                        System.debug('@@@ key 1: ' + pdc.Type_de_controle__c +
                                                '-' + pdc.Type_de_panel__c + '-' +pdc.Rep_ou_non_rep__c);
                        pdcDefToPriorityMap.put(pdc.Type_de_controle__c +
                                                '-' + pdc.Type_de_panel__c + '-' +pdc.Rep_ou_non_rep__c, pdc.Priorite__c);                        
                    }
                    else
                    {
                        System.debug('@@@ key 2: ' + pdc.Type_de_controle__c + '-' + pdc.Sous_type_de_controle__c +
                                                '-' + pdc.Type_de_panel__c + '-' +pdc.Rep_ou_non_rep__c);
                        pdcDefToPriorityMap.put(pdc.Type_de_controle__c + '-' + pdc.Sous_type_de_controle__c +
                                                '-' + pdc.Type_de_panel__c + '-' +pdc.Rep_ou_non_rep__c, pdc.Priorite__c);
                    }
                }
                System.debug('Reached3');
                //Add to controlesToUpdate all controles that have their Tech_Priority__c outdated
                for(Controle__c controle: (List<Controle__c>)Trigger.new)
                {
                    if(Trigger.isInsert ||
                       controle.Rep_ou_non_rep__c != ((Controle__c)Trigger.oldMap.get(controle.Id)).Rep_ou_non_rep__c)
                    {
                        String controleKey;
                        if(controle.Type_de_controle__c == Label.CTRL_Type_Connexion ||
                           controle.Type_de_controle__c == Label.CTRL_Type_NonRepondant ||
                           controle.Type_de_controle__c == Label.CTRL_Type_ParticipationWeb || 
                           controle.Type_de_controle__c == Label.CTRL_Type_Foyer_Vacancier)
                        {
                            /*controleKey = controle.Type_de_controle__c +
                                '-' + controle.Type_de_panel__c + '-' +controle.Rep_ou_non_rep__c;*/                       
                        }
                        else
                        {
                            /*controleKey = controle.Type_de_controle__c + '-' + controle.Sous_type_de_controle__c + 
                                '-' + controle.Type_de_panel__c + '-' +controle.Rep_ou_non_rep__c;*/
                        }
                    	System.debug('Reached4 controleKey: ' + controleKey);
                        if(pdcDefToPriorityMap.containsKey(controleKey) &&
                           (String.isBlank(controle.Tech_Priority__c) || Integer.valueOf(controle.Tech_Priority__c) > Integer.valueOf(pdcDefToPriorityMap.get(controleKey))))
                        {
                            System.debug('Reached5');
                            Controle__c newControle = controle.clone(true, true, false, false);
                            newControle.Tech_Priority__c = pdcDefToPriorityMap.get(controleKey);
                            controlesToUpdate.add(newControle);
                        }
                    }
                }
                if(!controlesToUpdate.isEmpty())
                {
                    System.debug('Reached6');
                    update controlesToUpdate;
                }
            }
        }
        catch(Exception ex)
        {
            ex.setMessage('An error occured on the controle trigger handler:\n' + ex.getMessage());
            throw ex;
        }
    }
}