force-app/main/default/objects/Asset/fields/Audimetre__c.field-meta.xml
<CustomField>
    <fullName>Audimetre__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Audimètre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Date_de_desaffectation__c.field-meta.xml
<CustomField>
    <fullName>Date_de_desaffectation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de désaffectation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Localisation__c.field-meta.xml
<CustomField>
    <fullName>Localisation__c</fullName>
    <label>Localisation</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Foyer</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Station</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>SAV MM</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Prestataire SAV</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Prestataire logistique</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Pas de localisation</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Fabricant</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Requete__c.field-meta.xml
<CustomField>
    <fullName>Requete__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requête</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Case.Account.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Case.Type</field>
            <operation>equals</operation>
            <value>Réclamation matériel</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>quipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sous_type__c.field-meta.xml
<CustomField>
    <fullName>Sous_type__c</fullName>
    <label>Sous-type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Absence collecte</fullName>
            </value>
            <value>
                <fullName>Absence mouvement</fullName>
            </value>
            <value>
                <fullName>Adaptateur casque</fullName>
            </value>
            <value>
                <fullName>Anomalie affichage</fullName>
            </value>
            <value>
                <fullName>Anomalie autre</fullName>
            </value>
            <value>
                <fullName>Anomalie batterie</fullName>
            </value>
            <value>
                <fullName>Anomalie carte Sim</fullName>
            </value>
            <value>
                <fullName>Anomalie des données en base panel</fullName>
            </value>
            <value>
                <fullName>Anomalie horloge</fullName>
            </value>
            <value>
                <fullName>Anomalie informations</fullName>
            </value>
            <value>
                <fullName>Anomalie lors du traitement des données d&apos;audience</fullName>
            </value>
            <value>
                <fullName>A quitte la mesure</fullName>
            </value>
            <value>
                <fullName>Audience individuelle &gt;7h</fullName>
            </value>
            <value>
                <fullName>Audience individuelle &gt; 7h</fullName>
                <isActive>false</isActive>
                <label>Audience individuelle &gt; 7h</label>
            </value>
            <value>
                <fullName>Audimètre</fullName>
            </value>
            <value>
                <fullName>Audimètre non connecté</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon batterie faible</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon inactif</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon jamais détecté</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Autre cause technique</fullName>
            </value>
            <value>
                <fullName>Autre déplacement</fullName>
            </value>
            <value>
                <fullName>Autre déplacement hors zone de mesure</fullName>
            </value>
            <value>
                <fullName>Autres usages</fullName>
            </value>
            <value>
                <fullName>Avis</fullName>
            </value>
            <value>
                <fullName>Beacon</fullName>
            </value>
            <value>
                <fullName>Beacon (logement plus grand)</fullName>
            </value>
            <value>
                <fullName>Beacon(s) Réceptionné(s)</fullName>
            </value>
            <value>
                <fullName>Beacon (tv en plus)</fullName>
            </value>
            <value>
                <fullName>Beacon (vehicule supplémentaire)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Statut_Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Statut_Foyer_paneliste__c</fullName>
    <label>Statut Foyer Panéliste</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Foyer_equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Recruté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Installé</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Equipé</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Intégré</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Désinstallé</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chute temporaire</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Chute définitive</label>
            </value>
            <value>
                <fullName>Chute définitive et désinstallé</fullName>
                <isActive>false</isActive>
                <label>Chute définitive et désinstallé</label>
            </value>
            <value>
                <fullName>Désinstallé actif</fullName>
                <isActive>false</isActive>
                <label>Désinstallé actif</label>
            </value>
            <value>
                <fullName>Recruté en attente d&apos;installation</fullName>
                <isActive>false</isActive>
                <label>Recruté en attente d&apos;installation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/recordTypes/AIP.recordType-meta.xml
<RecordType>
    <fullName>AIP</fullName>
    <active>true</active>
    <label>AIP</label>
</RecordType>

force-app/main/default/classes/Batch010_RequeteProcessusRestit_test.cls
/*
* @date: 08/09/2021
* @ Description Class qui teste Batch010_RequeteProcessusRestitution45j 
* @version 1.00   
* pourcentage : 95%
* @Auteur Ayoub Ghammaz EIT
*/
@isTest
public class Batch010_RequeteProcessusRestit_test {
    @isTest static void testDAteInf21(){
        Id recordTypeIdPanelAIP =Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_AIP).getRecordTypeId();
        /*------------------------------- creation de 3 equipements desafectes moins de 45 jours , sa lication est au foyer et 3 equipements desafectes plus de 45 jours , sa lication est au foyer
		--------------------------------- ==> creation d'une requte Restitution Du Materiel et attacher les 3 equipements*/
        //creer foyer
        Account foyer1 = new Account(name='FoyerTest1');
        insert(foyer1);
        //creer foyer paneliste aip
        Foyer_paneliste__c paneliste1 = new Foyer_paneliste__c(name='PanelisteTest1',RecordTypeId=recordTypeIdPanelAIP,Foyer__c=foyer1.id,Statut_Foyer_paneliste__c = Label.PAN_Statut_panel);
        insert(paneliste1);
        // creer requete de type 
        Case req = new Case(RecordTypeId =Schema.SObjectType.Case.getRecordTypeInfosByName().get(label.CAS_Recordtype_DemandePanelisteAIP).getRecordTypeId(),
        Origin = Label.CAS_Origine_NouveauFoyer,
        AccountId=foyer1.id,
        Foyer_paneliste__c = paneliste1.id ,
        Type = Label.CAS_Type_Reclamation_Materiel,
        Sous_type__c = Label.CAS_Sous_type_Probleme_Equipement);
        insert(req );
        //creer equipements
        List<Asset> assetToInsert = new list<Asset>();
     
        asset equi1=new asset(recordtypeid=Schema.SObjectType.Asset.getRecordTypeInfosByName().get(label.ASS_RecordType_DispositifsMesureAudienceAIP).getRecordTypeId(),
                                        Name='test1 equi1',requete__c=req.id,Foyer_paneliste__c=paneliste1.id,audimetre__c='jikvv',AccountId=foyer1.id,Date_de_desaffectation__c=date.today().addDAys(-integer.valueOf(Label.Batch010_DateDesaffectation45))+4,status=Label.ASS_Statut_Desaffecte,localisation__c=Label.ASS_Localisation_Foyer);
        assetToInsert.add(equi1);
        
        asset equi2=new asset(recordtypeid=Schema.SObjectType.Asset.getRecordTypeInfosByName().get(label.ASS_RecordType_DispositifsMesureAudienceAIP).getRecordTypeId(),
                                        Name='test1 equi2',requete__c=req.id,audimetre__c='jizzfeékvv',Foyer_paneliste__c=paneliste1.id,AccountId=foyer1.id,Date_de_desaffectation__c=date.today().addDAys(-integer.valueOf(Label.Batch010_DateDesaffectation45))+4,status=Label.ASS_Statut_Desaffecte,localisation__c=Label.ASS_Localisation_Foyer);
        assetToInsert.add(equi2);
        
        asset equi3=new asset(recordtypeid=Schema.SObjectType.Asset.getRecordTypeInfosByName().get(label.ASS_RecordType_DispositifsMesureAudienceAIP).getRecordTypeId(),
                                        Name='test1 equi3',requete__c=req.id,audimetre__c='jikvzefv',Foyer_paneliste__c=paneliste1.id,AccountId=foyer1.id,Date_de_desaffectation__c=date.today().addDAys(-integer.valueOf(Label.Batch010_DateDesaffectation45))+4,status=Label.ASS_Statut_Desaffecte,localisation__c=Label.ASS_Localisation_Foyer);
        assetToInsert.add(equi3);
        
        
        asset equi5 = new asset(recordtypeid=Schema.SObjectType.Asset.getRecordTypeInfosByName().get(label.ASS_RecordType_DispositifsMesureAudienceAIP).getRecordTypeId(),
                                        Name='test1 equi5',requete__c=req.id,audimetre__c='jikvvee',Foyer_paneliste__c=paneliste1.id,AccountId=foyer1.id,Date_de_desaffectation__c=date.today().addDAys(-integer.valueOf(Label.Batch010_DateDesaffectation45)-1),status=Label.ASS_Statut_Desaffecte,localisation__c=Label.ASS_Localisation_Foyer);
        assetToInsert.add(equi5);
        
        asset equi6 = new asset(recordtypeid=Schema.SObjectType.Asset.getRecordTypeInfosByName().get(label.ASS_RecordType_DispositifsMesureAudienceAIP).getRecordTypeId(),
                                        Name='test1 equi6',requete__c=req.id,audimetre__c='jikéf"rgeeevv',Foyer_paneliste__c=paneliste1.id,AccountId=foyer1.id,Date_de_desaffectation__c=date.today().addDAys(-integer.valueOf(Label.Batch010_DateDesaffectation45)-1),status=Label.ASS_Statut_Desaffecte,localisation__c=Label.ASS_Localisation_Foyer);
        assetToInsert.add(equi6);
        
        asset equi7 = new asset(recordtypeid=Schema.SObjectType.Asset.getRecordTypeInfosByName().get(label.ASS_RecordType_DispositifsMesureAudienceAIP).getRecordTypeId(),
                                        Name='test1 equi7',requete__c=req.id,audimetre__c='jikvvffff',Foyer_paneliste__c=paneliste1.id,AccountId=foyer1.id,Date_de_desaffectation__c=date.today().addDAys(-integer.valueOf(Label.Batch010_DateDesaffectation45)-1),status=Label.ASS_Statut_Desaffecte,localisation__c=Label.ASS_Localisation_Foyer);
        assetToInsert.add(equi7);
        
        insert assetToInsert;
        Test.startTest();
        Batch010_RequeteProcessusRestitution45j bccfb = new Batch010_RequeteProcessusRestitution45j();
        Id batchId = Database.executeBatch(bccfb);
        Test.stopTest();
        // after the testing stops, assert records were updated properly
        System.assertEquals(1, [select id ,Sous_type__c,Status from case where Sous_type__c=:Label.CAS_SousType_RestitutionDuMateriel and type=:Label.CAS_Type_VieDuFoyer].size());
        //System.assertEquals(3, [select id ,Sous_type__c,Status,(select id from quipements__r) from case where Sous_type__c=:Label.CAS_SousType_RestitutionDuMateriel and type=:Label.CAS_Type_VieDuFoyer].quipements__r.size());
    }        

}