force-app/main/default/objects/Asset/fields/Audimetre__c.field-meta.xml
<CustomField>
    <fullName>Audimetre__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Audimètre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Requete__c.field-meta.xml
<CustomField>
    <fullName>Requete__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requête</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Case.Account.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Case.Type</field>
            <operation>equals</operation>
            <value>Réclamation matériel</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>quipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Type_d_audimetre__c.field-meta.xml
<CustomField>
    <fullName>Type_d_audimetre__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type d&apos;audimètre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contact_sur_place__c.field-meta.xml
<CustomField>
    <fullName>Contact_sur_place__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact principal</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Cet individu est un invité ou ne fait pas partie de ce foyer ou n&apos;existe pas.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Type__c</field>
            <operation>notEqual</operation>
            <value>Invité</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_principal__c</field>
            <operation>equals</operation>
            <value>true</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Contact sur place)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Type_de_controle__c</fullName>
    <label>Type de contrôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <label>Présence</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Autres usages</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Connexion</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Participation</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Réception/abonnement</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Non Répondant</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Participation Web</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Foyer vacancier longue durée</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Inconnu</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Foyer vacancier</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Contrôle Beacon</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Installation SetMeter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Controle__c/Controle__c.object-meta.xml
<CustomObject>
    <label>Contrôle</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du contrôle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrôles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Controle__c/fields/Audimetre__c.field-meta.xml
<CustomField>
    <fullName>Audimetre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audimètre</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Foyer_Paneliste_ExtId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>Foyer_Paneliste_ExtId_SIPanel__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Foyer_Paneliste_ExtId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Requete__c.field-meta.xml
<CustomField>
    <fullName>Requete__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requête</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actif</fullName>
                <default>true</default>
                <label>Actif</label>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>Pré-codé</fullName>
            </value>
            <value>
                <fullName>Traité</fullName>
            </value>
            <value>
                <fullName>Abandonné</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Type_de_controle__c</fullName>
    <label>Type de contrôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <label>Présence</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Autres usages</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Connexion</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Participation</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Réception/abonnement</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Non Répondant</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Participation Web</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Foyer vacancier longue durée</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Foyer vacancier</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Contrôle Beacon</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Installation SetMeter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer_Paneliste_ExtId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>Foyer_Paneliste_ExtId_SIPanel__c</fullName>
    <description>&quot;(UID) c&apos;est l&apos;id unique generé par SIPANEL du foyer panéliste 
Ce champ sert a faire l&apos;Upsert du foyer panéliste&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Foyer_Paneliste_ExtId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/recordTypes/AIP.recordType-meta.xml
<RecordType>
    <fullName>AIP</fullName>
    <active>true</active>
    <label>AIP</label>
</RecordType>

force-app/main/default/objects/Order/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer Panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Commandes</relationshipLabel>
    <relationshipName>Commandes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Requete__c.field-meta.xml
<CustomField>
    <fullName>Requete__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requête</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Commandes</relationshipLabel>
    <relationshipName>Commandes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Batch026_ClotureCaseSansControle.cls
/*
* @author: Mikael Chaaya
* @date: 20/07/2023
* @Description 
* @Coverage: 94%
* History
* <Date of modification>   		<Author>   		 <Description of modification>
*/
global  class Batch026_ClotureCaseSansControle implements Database.Batchable<sObject> {

    //Added for email notification - START
    global String errorTxt = '';
    global Boolean containsErrors = false;
    
    
    global List<Case> start(Database.BatchableContext bc) {
        // Query for inactive cases

        List<String> typeDeMaterielList = new List<String>{Label.ASS_TypeMateriel_Setmeter,Label.ASS_TypeMateriel_Pager};
        String typeDeControleNonRepondant=Label.CAS_TypeControle_Non_Repondant;
        List<String> statusList = new List<String>{Label.CAS_Statut_Cloture,'Clôturé partiel','Clôturé non traité'};
        String refPanelAIP=Label.RFP_Nom_AIP;
        List<String> typeList = new List<String>{Label.CAS_Type_NonRepondantSetMeter,Label.CAS_Type_Non_repondant,label.CAS_Type_Non_repondant_ROAV3};

        List<Case> scope = [SELECT id, Status
                            FROM Case
                            WHERE
                                id NOT IN (Select Requete__c from Controle__c where   CreatedDate = today)
                             AND Type_de_controle__c =  :typeDeControleNonRepondant
                             AND Status  NOT IN :statusList
                             AND Foyer_paneliste__r.Referentiel_Panel__r.Name=:refPanelAIP
                             AND Type IN :typeList];
        return scope;
        /*Select id,Status, Contact_sur_place__c,  CreatedDate,Type_de_controle__c,  Foyer_paneliste__r.Foyer_Paneliste_ExtId_SIPanel__c, Type 
        from Case 
        where 
        id not in ( Select Requete__c from Controle__c where 
                    CreatedDate = today  
                    and Statut__c <>'Pré-codé' 
                    and Audimetre__r.Type_d_audimetre__c IN ('24','34') ) 
        and Type_de_controle__c = '8' 
        and Status <> 'Clôturé' 
        and Foyer_paneliste__r.Referentiel_Panel__r.Name = 'AIP' 
        AND Type IN('Non-répondant' , 'Non-répondant SetMeter') 
        Order by CreatedDate ASC
    
        */
    }

    global void execute(Database.BatchableContext bc, List<Case> scope) {

        List<Case> casesToUpdate = new List<Case>();

        for(Case c : scope){
            c.Status=Label.CAS_Statut_Cloture;
            casesToUpdate.add(c);
        }

        if(casesToUpdate != null && casesToUpdate.size() > 0){
            try{ 
                database.update(casesToUpdate);
            }Catch(exception ex){    
                 System.debug('Erreur durant casesToUpdate : ' + ex.getMessage() );
            }
        }

    }


    global void finish(Database.BatchableContext bc) {
        
        //Added for notifications - START
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        List<String> toMailAddress = System.Label.BatchNotif_B026_ToAddress.split(';');
     
        mail.setToAddresses(toMailAddress);
        mail.setSenderDisplayName(System.Label.BatchNotif_B026_SenderName);
        mail.setSubject(System.Label.BatchNotif_B026_Subject);
        
        String emailBody = 'L\'exécution du batch Batch026_ClotureCaseSansControle s\'est terminée.\n';
        if(containsErrors) {
            emailBody += 'Les erreurs suivantes ont été rencontrées :\n\n';
            emailBody += errorTxt;
        } else {
            emailBody += 'Aucune erreur n\'a été relevée.\n';
            
        }
        mail.setPlainTextBody(emailBody);
        
        if(!Test.isRunningTest()) {
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
        //Added for notifications - END
    }
}