force-app/main/default/objects/Asset/fields/Audimetre__c.field-meta.xml
<CustomField>
    <fullName>Audimetre__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Audimètre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Requete__c.field-meta.xml
<CustomField>
    <fullName>Requete__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requête</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Case.Account.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Case.Type</field>
            <operation>equals</operation>
            <value>Réclamation matériel</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>quipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Poste.recordType-meta.xml
<RecordType>
    <fullName>Poste</fullName>
    <active>true</active>
    <label>Poste</label>
</RecordType>

force-app/main/default/objects/Case/fields/Sous_type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Sous_type_de_controle__c</fullName>
    <label>Sous type de contrôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>13</fullName>
                <label>Anomalie des données en base panel</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Anomalie lors du traitement des données d&apos;audience</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Audience individuelle &gt; 9h</label>
            </value>
            <value>
                <fullName>Audimètre non connecté</fullName>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Individu sans activité Web cohérente</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>Individus sans audience depuis 28 jours ou plus</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Foyers sans audience depuis 6 jours ou plus</label>
            </value>
            <value>
                <fullName>Foyer avec audience sans abo</fullName>
            </value>
            <value>
                <fullName>Foyer avec abo C+ sans audience</fullName>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Foyer sans activité routeur</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Foyer sans activité Web cohérente</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Non envoyé au Médiamat</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Rejeté Médiamat</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>TV On &gt; 12h</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Autres usages</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Audience incohérente</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Autre CauseTechnique</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Foyer vacancier longue durée</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Foyers non connectés</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Participation Audience Individuelle 6h-9h</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Perte abonnement</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Absence mouvement</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Absence collecte</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Pager OFF</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Pager éteint trop longtemps</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Autres</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>Tous beacons inactifs</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Tous beacons &lt;20%</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>Au moins 1 beacon inactif</label>
            </value>
            <value>
                <fullName>38</fullName>
                <label>Indice de qualité faible</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Controle.recordType-meta.xml
<RecordType>
    <fullName>Controle</fullName>
    <active>true</active>
    <businessProcess>Contrôle</businessProcess>
    <label>Contrôle</label>
</RecordType>

force-app/main/default/objects/Controle__c/Controle__c.object-meta.xml
<CustomObject>
    <label>Contrôle</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du contrôle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrôles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Controle__c/fields/Audimetre__c.field-meta.xml
<CustomField>
    <fullName>Audimetre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audimètre</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Date_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Date_de_controle__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de contrôle</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Requete__c.field-meta.xml
<CustomField>
    <fullName>Requete__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requête</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actif</fullName>
                <default>true</default>
                <label>Actif</label>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>Pré-codé</fullName>
            </value>
            <value>
                <fullName>Traité</fullName>
            </value>
            <value>
                <fullName>Abandonné</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Controle__c/fields/tech_reconnecte__c.field-meta.xml
<CustomField>
    <fullName>tech_reconnecte__c</fullName>
    <defaultValue>false</defaultValue>
    <label>tech_reconnecte</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Etiquette__c/Etiquette__c.object-meta.xml
<CustomObject>
    <label>Étiquette</label>
    <nameField>
        <displayFormat>ETQ - {000000}</displayFormat>
        <label>Numéro de l&apos;étiquette</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Étiquettes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Etiquette__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Etiquette__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Etiquette__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Etiquettes</relationshipLabel>
    <relationshipName>Etiquettes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Etiquette__c/fields/Nom_de_l_etiquette__c.field-meta.xml
<CustomField>
    <fullName>Nom_de_l_etiquette__c</fullName>
    <label>Nom de l&apos;étiquette</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abo en cours de changement</fullName>
                <isActive>false</isActive>
                <label>Abo en cours de changement</label>
            </value>
            <value>
                <fullName>Mauvaise réception</fullName>
                <label>AIP Mauvaise réception</label>
            </value>
            <value>
                <fullName>Mouvement atypique</fullName>
                <label>AIP Mouvement atypique</label>
            </value>
            <value>
                <fullName>Peu écoute casque</fullName>
                <label>AIP  Peu écoute casque</label>
            </value>
            <value>
                <fullName>Profession atypique</fullName>
                <label>AIP Profession atypique</label>
            </value>
            <value>
                <fullName>Refus temporaire de participation</fullName>
                <label>AIP Refus temporaire de participation</label>
            </value>
            <value>
                <fullName>Set meter(s) débranché(s)</fullName>
                <label>AIP Set meter(s) débranché(s)</label>
            </value>
            <value>
                <fullName>Attente intervention Ambassadeur pour installation du Meter</fullName>
            </value>
            <value>
                <fullName>Attente matériel MM</fullName>
            </value>
            <value>
                <fullName>Autodésinstallation</fullName>
            </value>
            <value>
                <fullName>Autres usages +</fullName>
            </value>
            <value>
                <fullName>Box monobloc</fullName>
            </value>
            <value>
                <fullName>Chgt FAI/Box</fullName>
            </value>
            <value>
                <fullName>Chgt TV</fullName>
            </value>
            <value>
                <fullName>Ctrl abonnement</fullName>
            </value>
            <value>
                <fullName>Débranchés</fullName>
            </value>
            <value>
                <fullName>Déménagement</fullName>
            </value>
            <value>
                <fullName>Device HS</fullName>
            </value>
            <value>
                <fullName>Device Incompatible</fullName>
            </value>
            <value>
                <fullName>Equipé Non Actif</fullName>
            </value>
            <value>
                <fullName>Foyer PaME à chuter</fullName>
            </value>
            <value>
                <fullName>Foyer témoin</fullName>
            </value>
            <value>
                <fullName>Foyer test</fullName>
            </value>
            <value>
                <fullName>Foyer vacancier</fullName>
            </value>
            <value>
                <fullName>Gros conso TV</fullName>
            </value>
            <value>
                <fullName>Indispo prochains jours</fullName>
            </value>
            <value>
                <fullName>INJ Step1</fullName>
            </value>
            <value>
                <fullName>INJ Step2</fullName>
            </value>
            <value>
                <fullName>INJ Step3</fullName>
            </value>
            <value>
                <fullName>INJ Step4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Etiquette__c/fields/Poste__c.field-meta.xml
<CustomField>
    <fullName>Poste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Poste</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Ce poste n&apos;existe pas ou ne fait pas partie du foyer choisi</errorMessage>
        <filterItems>
            <field>Asset.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Foyer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Etiquettes</relationshipLabel>
    <relationshipName>Etiquettes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Etiquette__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actif</fullName>
                <default>true</default>
                <label>Actif</label>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AP01_Equipement.cls
/*
* @author: Khaled Hammoudeh
* @date: 25/09/2020
* @ Description Class that updates the status of Étiquettes when the connection status on the equipments (Assets) is changed
* @TestClass: AP01_Equipement_Test
* @Coverage: 100 %
* History
* <Date of modification>   <Author>    <Description of modification>
* 28/07/2021				MZ			Ticket MEDIAMETRIE-257 - replaced updateEtiquettesStatus() with updateEtiquettesControlesRequetes()
*/
public class AP01_Equipement {
    
    public static void updateEtiquettesControlesRequetes(list<asset> listEquipements, List<Id> listIdEquipements, List<Id> listIdRelatedFoyers) {
        
        
        integer i=0;
        boolean asset_ctrl=false;
        list<Etiquette__c> listRelatedEtiquettes = [SELECT id, Date_de_debut__c, Date_de_fin__c, Nom_de_l_etiquette__c, Poste__c, Foyer__c, Statut__c 
                                                    FROM Etiquette__c
                                                    WHERE Date_de_fin__c >=: date.today()
                                                    AND Statut__c =: Label.ETI_Statut_Actif
                                                    AND Poste__c IN :listIdEquipements];
        
        list<Controle__c> listRelatedControles = [SELECT id, Statut__c, Date_de_controle__c, Requete__c,Audimetre__c
                                                  FROM Controle__c
                                                  Where Statut__c =: Label.CTRL_Statut_Actif 
                                                  AND createdDate >= yesterday AND tech_reconnecte__c=false
                                                  AND (Audimetre__c IN :listIdEquipements OR Foyer__c IN :listIdRelatedFoyers)
                                                  AND (Sous_type_de_controle__c	= '7' or Sous_type_de_controle__c='16')]; // sous type = audimetre non connecté
        
   		list<asset> AssetFoyer = [select id,Statut_de_connexion__c from asset where Foyer_paneliste__c in:listIdRelatedFoyers  and RecordType.name=:label.ASS_RecordType_PaMe ];
		list<controle__c> listCtrlToUpdate = new list<controle__c>();
        List<Id> listIdCases = new List<Id>();
        List<Id> listIdControls = new List<Id>();
        List<Case> listCaseToUpdate = new List<Case>();
        
        for(Etiquette__c etiquette : listRelatedEtiquettes)
        {
            etiquette.Statut__c = Label.ETI_Statut_Inactif;
        }
        
        for(Controle__c controle : listRelatedControles)
        {
            for (asset a: AssetFoyer){
               
                if (a.Statut_de_connexion__c=='ConnectedCol' || a.Statut_de_connexion__c=='ConnectedSup'|| a.Statut_de_connexion__c=='ConnectedExp' || a.Statut_de_connexion__c=='Connected') {
                    i=i+1; 
                    if (controle.Audimetre__c==a.Id){
                        
                        asset_ctrl=true;
                    }
                }
                
                
            }
            if (AssetFoyer.size()==i || asset_ctrl==true){
                controle.Libelle_de_pre_codage__c = Label.CTRL_LibellePrecodage_ReconnecteSeul;
                controle.Statut__c = Label.CTRL_Statut_Precode;
                listIdCases.add(controle.Requete__c);
                listIdControls.add(controle.Id);
                listCtrlToUpdate.add(controle);
            }
        }
        
        List<Case> listRelatedCases = [SELECT Id, status,
                                       (SELECT Id
                                        FROM Controles__r
                                        WHERE Statut__c =: Label.CTRL_Statut_Actif
                                        AND createdDate >= yesterday
                                        AND Id NOT IN :listIdControls)
                                       FROM Case
                                       WHERE Id IN :listIdCases];
        
        for(Case requete : listRelatedCases)
        {
            if(requete.Controles__r.size() == 0 && requete.Status!=label.CAS_Statut_En_cours)
            {
                requete.Status = Label.CAS_Statut_Cloture;
                requete.Motif_de_statut__c = Label.CTRL_LibellePrecodage_ReconnecteSeul;
                listCaseToUpdate.add(requete);
            }
        }
        
        if(listRelatedEtiquettes.size() > 0) 
        {
            update listRelatedEtiquettes;
        }
        
        if(listCtrlToUpdate.size() > 0) 
        {
            system.debug('liste '+listCtrlToUpdate);
            for(Case requete : listRelatedCases){
                if (requete.Status!=label.CAS_Statut_En_cours){
                	update listCtrlToUpdate;
                }
            }
            
        }
        
        if(listCaseToUpdate.size() > 0) 
        {
            update listCaseToUpdate;
        }
    }
    
    /*
    public static void updateEtiquettesStatus(list<asset> listEquipements)
    {
        system.debug('$$$ listEquipements ' + listEquipements);
        list<Asset> listEquipWithEtiquettes = [Select id, Statut_de_connexion__c, 
                                               (Select id, Date_de_debut__c, Date_de_fin__c, Nom_de_l_etiquette__c, Poste__c, Foyer__c, Statut__c 
                                                from Etiquettes__r
                                                Where Date_de_fin__c >=: date.today()
                                                AND Statut__c =: Label.ETI_Statut_Actif),
                                               (Select id, Statut__c, Date_de_controle__c, Requete__c
                                                FROM Controles__r
                                                Where Statut__c =: Label.CTRL_Statut_Actif AND createdDate >= yesterday)
                                               From Asset
                                               Where Id IN: listEquipements];
        
        list<Etiquette__c> listEtiquetteToUpdate = new list<Etiquette__c>();
        list<Controle__c> listControlsToUpdate = new list<Controle__c>();
        Map<Id,Id> mapControleRequete = new Map<Id,Id>(); //257
        
        for(Asset equipement : listEquipWithEtiquettes)
        {
            for(Etiquette__c etiquette : equipement.Etiquettes__r)
            {
                etiquette.Statut__c = Label.ETI_Statut_Inactif;
                listEtiquetteToUpdate.add(etiquette);
            }
            
            //Precode associated controls if the poste was connected on its own between 3 and 27 hours from the date of the control
            for(Controle__c controle : equipement.Controles__r)
            {
                //datetime dateControle = datetime.newInstance(2020, 10, 4, 14, 30, 00);
                Long timeNow = DateTime.now().getTime();
                Long timeControl = controle.Date_de_controle__c.getTime();
                Long milliseconds = timeNow - timeControl;
                Long seconds = milliseconds / 1000;
                Long minutes = seconds / 60;
                Long hours = minutes / 60;
                system.debug('$$$ KHA hours ' + hours);
                if(hours >= 3 && hours <= 27)
                {
                    controle.Libelle_de_pre_codage__c = Label.CTRL_LibellePrecodage_ReconnecteSeul;
                    controle.Statut__c = Label.CTRL_Statut_Precode;
                    listControlsToUpdate.add(controle);
                    mapControleRequete.put(controle.Id, controle.Requete__c);//257
                }
            }
        }
        
        if(listEtiquetteToUpdate.size() > 0)
        {
            update listEtiquetteToUpdate;
        }
        
        if(listControlsToUpdate.size() > 0)
        {
            update listControlsToUpdate;
        }
    }*/
}