force-app/main/default/objects/Asset/fields/Audimetre__c.field-meta.xml
<CustomField>
    <fullName>Audimetre__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Audimètre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_flows__c.field-meta.xml
<CustomField>
    <fullName>Bypass_flows__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass flows</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_triggers__c.field-meta.xml
<CustomField>
    <fullName>Bypass_triggers__c</fullName>
    <label>Bypass triggers</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AP01_BandeUsine</fullName>
            </value>
            <value>
                <fullName>AP01_Commande</fullName>
            </value>
            <value>
                <fullName>AP01_Conge</fullName>
            </value>
            <value>
                <fullName>AP01_Control</fullName>
                <isActive>false</isActive>
                <label>AP01_Control</label>
            </value>
            <value>
                <fullName>AP01_Controle</fullName>
            </value>
            <value>
                <fullName>AP01_Convention</fullName>
            </value>
            <value>
                <fullName>AP01_Equipement</fullName>
            </value>
            <value>
                <fullName>AP01_EquipementDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP01_Evenement</fullName>
            </value>
            <value>
                <fullName>AP01_Fidelisation</fullName>
            </value>
            <value>
                <fullName>AP01_Foyer</fullName>
            </value>
            <value>
                <fullName>AP01_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP01_IndividuPaneliste</fullName>
            </value>
            <value>
                <fullName>AP01_LienMeter</fullName>
            </value>
            <value>
                <fullName>AP01_MembreDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP01_Requete</fullName>
            </value>
            <value>
                <fullName>AP01_StockProduit</fullName>
            </value>
            <value>
                <fullName>AP01_SuiviStockSAV</fullName>
            </value>
            <value>
                <fullName>AP01_UpdatescheduledDate</fullName>
            </value>
            <value>
                <fullName>AP01_WorkOrder</fullName>
            </value>
            <value>
                <fullName>AP010_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP011_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP02_BandeUsine</fullName>
            </value>
            <value>
                <fullName>AP02_Commande</fullName>
            </value>
            <value>
                <fullName>AP02_Controle</fullName>
            </value>
            <value>
                <fullName>AP02_Convention</fullName>
            </value>
            <value>
                <fullName>AP02_Equipement</fullName>
            </value>
            <value>
                <fullName>AP02_EquipementDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP02_Foyer</fullName>
            </value>
            <value>
                <fullName>AP02_FoyerPaneliste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP05_Equipement_Test.cls
/** 
* @author: Marleine Abi Khalil
* @date: 29/03/2022 
* @description: Class that test AP05_Equipement . Associated Trigger : equipementAfterUpdate, equipementAfterInsert
*/
@isTest
public class AP05_Equipement_Test {
	@isTest
	static void dissociateAssetTest(){
        User u = [SELECT id, Bypass_triggers__c FROM User WHERE isActive = true and Profile.name like '%dministra%' limit 1];
        u.Bypass_flows__c = true;
        update u;
        
        System.runAs(u){
        	Account foyerTest = new Account(Name='testPanel');
            insert foyerTest;
        
            Asset equip = new Asset(Name='testPanel');
        	equip.AccountId = foyerTest.id;
            insert equip;
            
            Id recrdCarteSim = Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get(Label.ASS_RT_CarteSIM).getRecordTypeId();
            Asset carteSim = new Asset(Name='testPanel');
        	carteSim.AccountId = foyerTest.id;
            carteSim.RecordTypeId = recrdCarteSim;
            carteSim.ParentId = equip.Id;
            carteSim.Audimetre__c='lklza';
            insert carteSim;
            
            Asset carteSim2 = new Asset(Name='testPanel');
        	carteSim2.AccountId = foyerTest.id;
            carteSim2.RecordTypeId = recrdCarteSim;
            carteSim2.ParentId = equip.Id;
            carteSim2.Audimetre__c='l22klza';
            insert carteSim2;
            
            Asset equip2 = new Asset(Name='testPanel');
        	equip2.AccountId = foyerTest.id;
            equip2.Audimetre__c='uiplk';
            insert equip2;
            
            carteSim.ParentId = equip2.Id;
            carteSim2.ParentId = equip2.Id;
            List<Asset> listAss = new List<Asset>{carteSim, carteSim2};
            Test.startTest();
            update listAss; 
            Test.stopTest();
        }
    }
}