force-app/main/default/objects/Asset/fields/Bande_Usine__c.field-meta.xml
<CustomField>
    <fullName>Bande_Usine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bande Usine</label>
    <referenceTo>Bande_Usine__c</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>Equipements_de_mesure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Duree_de_la_garantie__c.field-meta.xml
<CustomField>
    <fullName>Duree_de_la_garantie__c</fullName>
    <label>Duree de la garantie</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Localisation__c.field-meta.xml
<CustomField>
    <fullName>Localisation__c</fullName>
    <label>Localisation</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Foyer</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Station</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>SAV MM</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Prestataire SAV</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Prestataire logistique</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Pas de localisation</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Fabricant</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Numero_IMEI__c.field-meta.xml
<CustomField>
    <fullName>Numero_IMEI__c</fullName>
    <externalId>true</externalId>
    <label>Numéro IMEI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/Type_de_materiel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_materiel__c</fullName>
    <label>Type de Matériel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>31</fullName>
                <label>Beacon</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Routeur</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>Soft Meter</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>Pager</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Carte SIM</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Setmeter</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>DMD</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>TV</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>TV Plat</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>TV TNT intégré</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>TVM3</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>TNT</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>MAG</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Syster</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Modem</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Tuner Externe</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Sonde NG</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Perte de marquage</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Ordinateur</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Console de jeux</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>DVD</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>DVD R sans HDD</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>DVD MAG</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Autre équipement</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>Streaming Meter</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>Antenne</label>
            </value>
            <value>
                <fullName>8</fullName>
                <isActive>false</isActive>
                <label>Connectique</label>
            </value>
            <value>
                <fullName>18</fullName>
                <isActive>false</isActive>
                <label>Convertisseur</label>
            </value>
            <value>
                <fullName>3</fullName>
                <isActive>false</isActive>
                <label>IRD</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>MCS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT ( Bande_Usine__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/carte_SIM.recordType-meta.xml
<RecordType>
    <fullName>carte_SIM</fullName>
    <active>true</active>
    <label>carte SIM</label>
</RecordType>

force-app/main/default/objects/Bande_Usine__c/Bande_Usine__c.object-meta.xml
<CustomObject>
    <label>Bande Usine</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du fichier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bande Usine</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bande_Usine__c/fields/Duree_de_la_garantie__c.field-meta.xml
<CustomField>
    <fullName>Duree_de_la_garantie__c</fullName>
    <label>Duree de la garantie</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bande_Usine__c/fields/Localisation__c.field-meta.xml
<CustomField>
    <fullName>Localisation__c</fullName>
    <label>Localisation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Foyer</fullName>
            </value>
            <value>
                <fullName>Station</fullName>
            </value>
            <value>
                <fullName>SAV MM</fullName>
            </value>
            <value>
                <fullName>Prestataire SAV</fullName>
            </value>
            <value>
                <fullName>Prestataire logistique</fullName>
            </value>
            <value>
                <fullName>Pas de localisation</fullName>
            </value>
            <value>
                <fullName>Fabricant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bande_Usine__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Bande Usine</relationshipLabel>
    <relationshipName>Bande_Usine</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bande_Usine__c/fields/Type_de_materiel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_materiel__c</fullName>
    <label>Type de matériel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>31</fullName>
                <label>Beacon</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Routeur</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>Soft Meter</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>Pager</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Carte SIM</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Setmeter</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>IRD</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>DMD</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>TVM3</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Autre équipement</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>Streaming Meter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bande_Usine__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mediamat</fullName>
            </value>
            <value>
                <fullName>PaMe</fullName>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bande_Usine_Erreur__c/Bande_Usine_Erreur__c.object-meta.xml
<CustomObject>
    <label>Bande Usine Erreur</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Référence de l&apos;Erreur</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bande Usine Erreurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bande_Usine_Erreur__c/fields/Bande_Usine__c.field-meta.xml
<CustomField>
    <fullName>Bande_Usine__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bande Usine</label>
    <referenceTo>Bande_Usine__c</referenceTo>
    <relationshipLabel>Erreurs lors du chargement de la Bande Usine</relationshipLabel>
    <relationshipName>Bande_Usine_Erreurs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BandeUsineXMLController_Test.cls
/*
* @author: Claire VEHRLE
* @date: 21/03/2022
* @ Description Class that test BandeUsineXMLController  
* History
* <Date of modification>   <Author>    <Description of modification>
*/
@isTest
public class BandeUsineXMLController_Test {
    
    public static String xmlCreation() {
        DOM.document doc = new DOM.Document();
        
        dom.XmlNode BU =doc.createRootElement('Delivery', null, null);
        
        dom.XmlNode equipement = BU.addChildElement('Meter', null, null);
        dom.XmlNode productReference = equipement.addChildElement('Product_Reference', null, null);
        productReference.addTextNode('ROA01V2');
        dom.XmlNode Serial_Number = equipement.addChildElement('Serial_Number', null, null);
        Serial_Number.addTextNode('352736070140382');
        dom.XmlNode Production_Date = equipement.addChildElement('Production_Date', null, null);
        Production_Date.addTextNode('2017-12-19');
        dom.XmlNode Software_Version = equipement.addChildElement('Software_Version', null, null);
        Software_Version.addTextNode('15.1.100');
        dom.XmlNode Meter_ID = equipement.addChildElement('Meter_ID', null, null);
        Meter_ID.addTextNode('242E4C96');
        dom.XmlNode IMEI = equipement.addChildElement('IMEI', null, null);
        IMEI.addTextNode('352736070140382');
        dom.XmlNode carte_SIM = equipement.addChildElement('SIM', null, null);
        dom.XmlNode Card_Id = carte_SIM.addChildElement('Card_Id', null, null);
        Card_Id.addTextNode('8931087415102538794');
        dom.XmlNode IMSI = carte_SIM.addChildElement('IMSI', null, null);
        IMSI.addTextNode('204080807028029');
        dom.XmlNode CCID = carte_SIM.addChildElement('CCID', null, null);
        CCID.addTextNode('8931087415102538794');
        
        return (doc.toXmlString());
    }
    
       public static String xmlCreationError() {
        DOM.document doc = new DOM.Document();
        
        dom.XmlNode BU =doc.createRootElement('Delivery', null, null);
        
        dom.XmlNode equipement = BU.addChildElement('Meter', null, null);
        dom.XmlNode productReference = equipement.addChildElement('Product_Reference', null, null);
        productReference.addTextNode('ROA01V2');
        dom.XmlNode Serial_Number = equipement.addChildElement('Serial_Number', null, null);
        Serial_Number.addTextNode('352736070140382');
        dom.XmlNode Production_Date = equipement.addChildElement('Production_Date', null, null);
        Production_Date.addTextNode('2017-12-19');
        dom.XmlNode Software_Version = equipement.addChildElement('Software_Version', null, null);
        Software_Version.addTextNode('15.1.100');
        dom.XmlNode Meter_ID = equipement.addChildElement('Meter_ID', null, null);
        Meter_ID.addTextNode('242E4C96');
        dom.XmlNode IMEI = equipement.addChildElement('IMEI', null, null);
        IMEI.addTextNode('352736070140382');
        dom.XmlNode carte_SIM = equipement.addChildElement('SIM', null, null);
        dom.XmlNode Card_Id = carte_SIM.addChildElement('Card_Id', null, null);
        Card_Id.addTextNode('8931087415102538794');
        dom.XmlNode IMSI = carte_SIM.addChildElement('IMSI', null, null);
        IMSI.addTextNode('204080807028029');
        dom.XmlNode CCID = carte_SIM.addChildElement('CCID', null, null);
        CCID.addTextNode('8931087415102538794');
        
        return (doc.toXmlString());
    }
    
    public static testMethod void bandeUsine_Test() {
        
        List<Account> foyerList = new List<Account>();
        Account ims = new Account();
        ims.name = 'ims';
        foyerList.add(ims);
        
        Account cordon = new Account();
        cordon.name = 'cordon';
        foyerList.add(cordon);
        
        insert foyerList;
        
        Referentiel_Panel__c refPanMMAT = new Referentiel_Panel__c();
        refPanMMAT.name = Label.RFP_Nom_MMAT;
        refPanMMAT.Type_de_panel__c = Label.RFP_TypePanel_MMAT;
        insert refPanMMAT;
        
        Bande_Usine__c bandeUsine = new Bande_Usine__c();
        bandeUsine.Name = 'Fichier_XML';
        bandeUsine.Referentiel_panel__c = refPanMMAT.Id;
        bandeUsine.Localisation__c = 'Foyer';
        bandeUsine.Type_de_materiel__c = '24';
        bandeUsine.Duree_de_la_garantie__c = 3;

        insert bandeUsine;
        
        List<Id> bandeUsineIdList = new List<Id>();
        bandeUsineIdList.add(bandeUsine.Id);
        
        String xmlTest = xmlCreation();
        
        System.debug(xmlTest);
        
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test_XML';
        cv.PathOnClient = 'TestXML.xml';
        cv.VersionData = Blob.valueOf(xmlTest);
        cv.IsMajorVersion = true;
        cv.FirstPublishLocationId = bandeUsine.Id;
        Insert cv;
        
        Test.startTest();
		BandeUsineXMLController.recuperationBandeUsine(bandeUsineIdList);
  Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(ims.id));

        List<Asset> equipementList = [SELECT Name, recordType.Name, Localisation__c, Type_de_materiel__c FROM Asset];
        //System.assertEquals(2, equipementList.size());
        Test.stopTest();
    }
    
        public static testMethod void bandeUsineErreur_Test() {
        
        List<Account> foyerList = new List<Account>();
        Account ims = new Account();
        ims.name = 'ims';
        foyerList.add(ims);
        
        Account cordon = new Account();
        cordon.name = 'cordon';
        foyerList.add(cordon);
        
        insert foyerList;
        
        Referentiel_Panel__c refPanMMAT = new Referentiel_Panel__c();
        refPanMMAT.name = Label.RFP_Nom_MMAT;
        refPanMMAT.Type_de_panel__c = Label.RFP_TypePanel_MMAT;
        insert refPanMMAT;
        
        Bande_Usine__c bandeUsine = new Bande_Usine__c();
        bandeUsine.Name = 'Fichier_XML';
        bandeUsine.Referentiel_panel__c = refPanMMAT.Id;
        bandeUsine.Localisation__c = 'Foyer';
        bandeUsine.Type_de_materiel__c = '24';
        bandeUsine.Duree_de_la_garantie__c = 3;

        insert bandeUsine;
            
        Asset newAsset = new Asset(AccountId=ims.id, Numero_IMEI__c =decimal.valueOf('352736070140382'), name = 'Test');
        insert newAsset;
            
        List<Id> bandeUsineIdList = new List<Id>();
        bandeUsineIdList.add(bandeUsine.Id);
        
        String xmlTest = xmlCreationError();
        
        System.debug(xmlTest);
        
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test_XML';
        cv.PathOnClient = 'TestXML.xml';
        cv.VersionData = Blob.valueOf(xmlTest);
        cv.IsMajorVersion = true;
        cv.FirstPublishLocationId = bandeUsine.Id;
        Insert cv;
        
        Test.startTest();
		BandeUsineXMLController.recuperationBandeUsine(bandeUsineIdList);
        List<Bande_Usine_Erreur__c> erreurList = [SELECT Name FROM Bande_Usine_Erreur__c];
        Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(cordon.id));
       Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(newAsset.id));
        //System.assertEquals(1, erreurList.size());
        Test.stopTest();
    }
}