force-app/main/default/objects/Asset/fields/Batterie__c.field-meta.xml
<CustomField>
    <fullName>Batterie__c</fullName>
    <label>Niveau de Batterie</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Date_de_premiere_installation__c.field-meta.xml
<CustomField>
    <fullName>Date_de_premiere_installation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de première installation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Emplacement_dans_le_foyer__c.field-meta.xml
<CustomField>
    <fullName>Emplacement_dans_le_foyer__c</fullName>
    <label>Emplacement dans le foyer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Salon</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Salle à manger</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Chambre des parents</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Chambre des enfants</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Cuisine</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Bureau</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Chambre d&apos;amis</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Salle de jeux</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Autre pièce</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Salle à Manger / Salon / Séjour</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Entrée / Couloir</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Ordinateur fixe</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Ordinateur portable</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Tablette</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Smartphone</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Type_de_materiel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_materiel__c</fullName>
    <label>Type de Matériel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>31</fullName>
                <label>Beacon</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Routeur</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>Soft Meter</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>Pager</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Carte SIM</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Setmeter</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>DMD</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>TV</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>TV Plat</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>TV TNT intégré</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>TVM3</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>TNT</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>MAG</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Syster</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Modem</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Tuner Externe</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Sonde NG</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Perte de marquage</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Ordinateur</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Console de jeux</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>DVD</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>DVD R sans HDD</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>DVD MAG</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Autre équipement</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>Streaming Meter</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>Antenne</label>
            </value>
            <value>
                <fullName>8</fullName>
                <isActive>false</isActive>
                <label>Connectique</label>
            </value>
            <value>
                <fullName>18</fullName>
                <isActive>false</isActive>
                <label>Convertisseur</label>
            </value>
            <value>
                <fullName>3</fullName>
                <isActive>false</isActive>
                <label>IRD</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>MCS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_principal__c.field-meta.xml
<CustomField>
    <fullName>Contact_principal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contact Principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Membre</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Invité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Non panéliste</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/Equipements_du_foyer__c.object-meta.xml
<CustomObject>
    <label>Equipement du foyer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;équipement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipements du foyer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Batterie__c.field-meta.xml
<CustomField>
    <fullName>Batterie__c</fullName>
    <label>Batterie</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Equipements du foyer</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Equipements du foyer</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>7</fullName>
                <label>Ordinateur fixe</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Ordinateur portable</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Tablette</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Mobile</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Poste TV</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Lecteur DVD</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Console de jeux</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Magnétoscope</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Décodeur</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Divers</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Box</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Caster</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Objet Connecté</label>
            </value>
            <value>
                <fullName>17</fullName>
                <isActive>false</isActive>
                <label>Autre équipement</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/recordTypes/AIP.recordType-meta.xml
<RecordType>
    <fullName>AIP</fullName>
    <active>true</active>
    <label>AIP</label>
</RecordType>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Individus Panélistes</relationshipLabel>
    <relationshipName>Individus_Paneliste</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invité</fullName>
            </value>
            <value>
                <fullName>Membre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer Panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Commandes</relationshipLabel>
    <relationshipName>Commandes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/getEquipementsduFoyer.cls
public with sharing class getEquipementsduFoyer {
    @AuraEnabled
    public static wrapperType getEquipementsduFoyer() {
        wrapperType tableData = new wrapperType();
        EquipmentWrapper equipmentWrapper = new EquipmentWrapper();
        Id contactId;
        
        List<user> connectedUser = [SELECT Id, contactId, Contact.Contact_principal__c, Contact.AccountId
                                    FROM user 
                                    WHERE Id = :UserInfo.getUserId()];
        if(connectedUser.size() > 0){
            contactId = connectedUser[0].contactId;
        }
        
        System.debug('contactId ' + contactId);
        if(String.isNotBlank(contactId)){
            for(Individu_Paneliste__c ind :[SELECT Id, Composition_du_foyer__c, Foyer_paneliste__r.RecordType.Name
                                            FROM Individu_Paneliste__c 
                                            WHERE Composition_du_foyer__c = :contactId
                                            LIMIT 1])
            {
                tableData.userRecordTypeName = ind.Foyer_paneliste__r.RecordType.Name;
            }
            
            if(String.isNotBlank(connectedUser[0].Contact.AccountId)){
                //Get equipment types Picklist labels
                Map<String, String> equipmentTypesMap = new Map<String, String>();
                for(ContactFormulaire.wrapperType equipement : ContactFormulaire.getPicklistValues(Equipements_du_foyer__c.Type__c)){
                    equipmentTypesMap.put(equipement.value, equipement.label);
                }
                String contactType = ContactFormulaire.contactType();
                if(contactType == 'AIP'){
                    String assetType;
                    for(Asset asset : [SELECT Id, ToLabel(Emplacement_dans_le_foyer__c), Batterie__c, Date_de_premiere_installation__c, 
                                       ToLabel(Type_de_materiel__c)
                                       FROM Asset
                                       WHERE AccountId = :connectedUser[0].Contact.AccountId
                                       ORDER BY Name ASC NULLS LAST ])
                    {
                        assetType = asset.Type_de_materiel__c == 'Pager' ? 'Audimètre porté' : asset.Type_de_materiel__c == 'Setmeter' ? 
                                    'Audimètre fixe' : asset.Type_de_materiel__c == 'Beacon' ? ' Borne de localisation' : asset.Type_de_materiel__c;

                        equipmentWrapper = new EquipmentWrapper(assetType, String.valueOf(asset.Batterie__c), 
                                                                asset.Emplacement_dans_le_foyer__c, 
                                                                String.valueOf(asset.Date_de_premiere_installation__c),
                                                                '-', '-');
                         tableData.equipements.add(equipmentWrapper);
                    }
                }else{
                    for(Equipements_du_foyer__c equipement :[SELECT Id, Name, ToLabel(Emplacement__c), ToLabel(Marque_TV__c),ToLabel(Marque_Tablette__c), 
                                                         ToLabel(Marque_du_magnetoscope__c), ToLabel(Marque_de_telephone__c),
                                                         ToLabel(Marque_d_ordinateur__c), Utilisateur_principal__r.FirstName,
                                                         Utilisateur_principal__r.Name, Batterie__c, Date_d_installation__c, ToLabel(Type__c)
                                                         FROM Equipements_du_foyer__c
                                                         WHERE Foyer__c =:connectedUser[0].Contact.AccountId
                                                         OR Utilisateur_principal__r.AccountId =: connectedUser[0].Contact.AccountId
                                                         ORDER BY Name ASC NULLS LAST 
                                                        ])
                    {
                        equipmentWrapper = new EquipmentWrapper(equipement.Type__c, String.valueOf(equipement.Batterie__c), equipement.Emplacement__c, 
                                                                String.valueOf(equipement.Date_d_installation__c), equipement.Utilisateur_principal__r.FirstName, '-');
                        
                        equipmentWrapper.marque = String.isNotBlank(equipement.Marque_TV__c) ? equipement.Marque_TV__c : 
                        String.isNotBlank(equipement.Marque_Tablette__c) ? equipement.Marque_Tablette__c :
                        String.isNotBlank(equipement.Marque_du_magnetoscope__c) ? equipement.Marque_du_magnetoscope__c :
                        String.isNotBlank(equipement.Marque_de_telephone__c) ? equipement.Marque_de_telephone__c :
                        String.isNotBlank(equipement.Marque_d_ordinateur__c) ? equipement.Marque_d_ordinateur__c :
                        String.isNotBlank(equipement.Marque_de_telephone__c) ? equipement.Marque_de_telephone__c : '-';
                        
                        tableData.equipements.add(equipmentWrapper);
                    }
                    
                }
                
                
            }
        }
        return tableData;
    }
    
    public class wrapperType {
        public wrapperType(){
            this.userRecordTypeName = '';
            this.equipements = new List<EquipmentWrapper>();
            this.totalEquipements = 0;
        }
        @AuraEnabled
        public String userRecordTypeName;
        @AuraEnabled
        public List<EquipmentWrapper> equipements;
        @AuraEnabled
        public Integer totalEquipements;
    }
    
    public class EquipmentWrapper {
        public EquipmentWrapper(){
            this.type = '-';
            this.batterie = '-';
            this.emplacement = '-';
            this.dateInstallation = '-';
            this.utilisateurPrincipal = '-';
            this.marque = '-';            
        }
        public EquipmentWrapper(String type, String batterie, String emplacement, String dateInstallation, String utilisateurPrincipal, String marque){
            this.type = type;
            this.batterie = batterie;
            this.emplacement = emplacement;
            this.dateInstallation = dateInstallation;
            this.utilisateurPrincipal = utilisateurPrincipal;
            this.marque = marque;            
        }
        @AuraEnabled
        public String type;
        @AuraEnabled
        public String batterie;
        @AuraEnabled
        public String emplacement;
        @AuraEnabled
        public String dateInstallation;
        @AuraEnabled
        public String utilisateurPrincipal;
        @AuraEnabled
        public String marque;
    }
}