force-app/main/default/objects/Asset/fields/Date_de_desaffectation__c.field-meta.xml
<CustomField>
    <fullName>Date_de_desaffectation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de désaffectation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Localisation__c.field-meta.xml
<CustomField>
    <fullName>Localisation__c</fullName>
    <label>Localisation</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Foyer</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Station</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>SAV MM</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Prestataire SAV</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Prestataire logistique</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Pas de localisation</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Fabricant</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Requete__c.field-meta.xml
<CustomField>
    <fullName>Requete__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requête</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Case.Account.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Case.Type</field>
            <operation>equals</operation>
            <value>Réclamation matériel</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>quipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sous_type__c.field-meta.xml
<CustomField>
    <fullName>Sous_type__c</fullName>
    <label>Sous-type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Absence collecte</fullName>
            </value>
            <value>
                <fullName>Absence mouvement</fullName>
            </value>
            <value>
                <fullName>Adaptateur casque</fullName>
            </value>
            <value>
                <fullName>Anomalie affichage</fullName>
            </value>
            <value>
                <fullName>Anomalie autre</fullName>
            </value>
            <value>
                <fullName>Anomalie batterie</fullName>
            </value>
            <value>
                <fullName>Anomalie carte Sim</fullName>
            </value>
            <value>
                <fullName>Anomalie des données en base panel</fullName>
            </value>
            <value>
                <fullName>Anomalie horloge</fullName>
            </value>
            <value>
                <fullName>Anomalie informations</fullName>
            </value>
            <value>
                <fullName>Anomalie lors du traitement des données d&apos;audience</fullName>
            </value>
            <value>
                <fullName>A quitte la mesure</fullName>
            </value>
            <value>
                <fullName>Audience individuelle &gt;7h</fullName>
            </value>
            <value>
                <fullName>Audience individuelle &gt; 7h</fullName>
                <isActive>false</isActive>
                <label>Audience individuelle &gt; 7h</label>
            </value>
            <value>
                <fullName>Audimètre</fullName>
            </value>
            <value>
                <fullName>Audimètre non connecté</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon batterie faible</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon inactif</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon jamais détecté</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Autre cause technique</fullName>
            </value>
            <value>
                <fullName>Autre déplacement</fullName>
            </value>
            <value>
                <fullName>Autre déplacement hors zone de mesure</fullName>
            </value>
            <value>
                <fullName>Autres usages</fullName>
            </value>
            <value>
                <fullName>Avis</fullName>
            </value>
            <value>
                <fullName>Beacon</fullName>
            </value>
            <value>
                <fullName>Beacon (logement plus grand)</fullName>
            </value>
            <value>
                <fullName>Beacon(s) Réceptionné(s)</fullName>
            </value>
            <value>
                <fullName>Beacon (tv en plus)</fullName>
            </value>
            <value>
                <fullName>Beacon (vehicule supplémentaire)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Batch010_RequeteProcessusRestitution45j.cls
/*
* @author: Ayoub GHAMMAZ
* @date: 07/09/2021
* @ Description: Ce batch permet de Créer une requête de type vie de foyer quand les équipements ne sont pas envoies par le paneliste 
suite une requête de chute ou problème équipement
* @TestClass: Batch010_RequeteProcessusRestit_test
* @Coverage: 95%
* History
* <Date of modification>   <Author>    <Description of modification>
* */
global class Batch010_RequeteProcessusRestitution45j implements Database.Batchable<sObject>, Database.AllowsCallouts  {
    //Added for email notification - START
    global String errorTxt = '';
    global Boolean containsErrors = false;

    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'select id , AccountId,type,Status,Foyer_paneliste__c ,(select id ,name,Foyer_paneliste__c,Requete__c,status,Date_de_desaffectation__c,Localisation__c from quipements__r where status='+'\''+Label.ASS_Statut_Desaffecte+'\''+'and localisation__c='+'\''+Label.ASS_Localisation_Foyer+'\''+') from case where (type='+'\''+Label.CAS_Type_Reclamation_Materiel+'\''+'or type='+'\''+Label.Cas_Type_DemandeChute+'\''+') and (status='+'\''+Label.CAS_Statut_En_cours+'\''+' or status='+'\''+Label.CAS_Statut_Nouveau+'\''+')';
        //String query = 'select id ,AccountId,type,Status,Foyer_paneliste__c,(select id,name,Foyer_paneliste__c,Requete__c,status,Date_de_desaffectation__c,Localisation__c from quipements__r) from case where id =\'5003H000008MO6NQAW\'';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext bc, List<Case> scope){
        //VAriables
        Database.DMLOptions dmo = new Database.DMLOptions();
        dmo.AssignmentRuleHeader.useDefaultRule = true; 
        Id recordTypeIdRequeteDemandePanelisteAIP =Schema.SObjectType.Case.getRecordTypeInfosByName().get(label.CAS_Recordtype_DemandePanelisteAIP).getRecordTypeId();
        list<Asset> ListAssetToUpdate = new list<Asset>();
        list<Asset> listAsset=new list<Asset>();
        List<Case> ListCaseToInsert = new List<Case>();
        //Logique
        for(Case cs : scope){
            system.debug('scope'+scope);
            List<Asset> ListAssetToCheck = new List<Asset>();
            system.debug('ass '+cs.quipements__r);
            if(cs.quipements__r!= null && cs.quipements__r.size()>0){
                for(Asset equ : cs.quipements__r){//Batch010_DateDesaffectation45
                    Integer nbJoursDateDesaffectation =0;
                    if(equ.Date_de_desaffectation__c!=null){// verifier combien de mois le beacon n'a pas transmit des données
                        nbJoursDateDesaffectation = equ.Date_de_desaffectation__c.daysBetween(date.today());
                        system.debug('nb jour '+nbJoursDateDesaffectation);
                    }
                    if(nbJoursDateDesaffectation > decimal.valueOf(Label.Batch010_DateDesaffectation45)){// si la date est sup a 45 jour on ajoute pour pouvoir comparer si un equipement de la requete a depasse  45j
                        system.debug('ass '+ListAssetToCheck);
                        ListAssetToCheck.add(equ);
                        listAsset.add(equ);
                    }
                }
                if(ListAssetToCheck!=null && ListAssetToCheck.size()>0){
                    ListCaseToInsert.add(new case(RecordTypeId=recordTypeIdRequeteDemandePanelisteAIP,Foyer_paneliste__c=cs.Foyer_paneliste__c , AccountId=cs.AccountId,Origin=Label.CAS_Origine_ProcessusDeRestitution,type=Label.CAS_Type_VieDuFoyer,Sous_type__c=Label.CAS_SousType_RestitutionDuMateriel));
                }
            }
            
        }
        system.debug('toinsert '+ListCaseToInsert);
        if(ListCaseToInsert.size()>0 && ListCaseToInsert!=null){
            try{ 
                database.Insert(ListCaseToInsert);
            }Catch(exception ex){
                system.debug('Insert requete (batche010) Exception Error:'+ex.getmessage());
            }
            for(Case cs :ListCaseToInsert ){
                for(Asset equ :listAsset ){
                    if(cs.Foyer_paneliste__c==equ.Foyer_paneliste__c){
                        equ.Requete__c=cs.id;
                        ListAssetToUpdate.add(equ);
                    }
                }
            }
        }
        if(ListAssetToUpdate.size()>0 && ListAssetToUpdate!=null){
            try{ 
                database.Update(ListAssetToUpdate);
            }Catch(exception ex){
                errorTxt += 'Erreur durant la MAJ : ' + ex.getMessage() + '\n';
                containsErrors = true;
                system.debug('Update Asset (batche010) Exception Error:'+ex.getmessage());
            }
        }
        
    }
    global void finish(Database.BatchableContext bc){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        List<String> toMailAddress = System.Label.BatchNotif_B010_ToAddress.split(';');
     
        mail.setToAddresses(toMailAddress);
        mail.setSenderDisplayName(System.Label.BatchNotif_B010_SenderName);
        mail.setSubject(System.Label.BatchNotif_B010_Subject);
        
        String emailBody = 'L\'exécution du batch Batch010_RequeteProcessusRestitution45j s\'est terminée.\n';
        if(containsErrors) {
            emailBody += 'Les erreurs suivantes ont été rencontrées :\n\n';
            emailBody += errorTxt;
        } else {
            emailBody += 'Aucune erreur n\'a été relevée.\n';
            
        }
        mail.setPlainTextBody(emailBody);
        if(!Test.isRunningTest()) {
        	Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }
}