force-app/main/default/objects/Asset/fields/Date_de_desaffectation__c.field-meta.xml
<CustomField>
    <fullName>Date_de_desaffectation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de désaffectation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Produit_commande__c.field-meta.xml
<CustomField>
    <fullName>Produit_commande__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit commandé</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Équipements</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Requete__c.field-meta.xml
<CustomField>
    <fullName>Requete__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requête</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Case.Account.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Case.Type</field>
            <operation>equals</operation>
            <value>Réclamation matériel</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>quipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT ( Bande_Usine__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sous_type__c.field-meta.xml
<CustomField>
    <fullName>Sous_type__c</fullName>
    <label>Sous-type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Absence collecte</fullName>
            </value>
            <value>
                <fullName>Absence mouvement</fullName>
            </value>
            <value>
                <fullName>Adaptateur casque</fullName>
            </value>
            <value>
                <fullName>Anomalie affichage</fullName>
            </value>
            <value>
                <fullName>Anomalie autre</fullName>
            </value>
            <value>
                <fullName>Anomalie batterie</fullName>
            </value>
            <value>
                <fullName>Anomalie carte Sim</fullName>
            </value>
            <value>
                <fullName>Anomalie des données en base panel</fullName>
            </value>
            <value>
                <fullName>Anomalie horloge</fullName>
            </value>
            <value>
                <fullName>Anomalie informations</fullName>
            </value>
            <value>
                <fullName>Anomalie lors du traitement des données d&apos;audience</fullName>
            </value>
            <value>
                <fullName>A quitte la mesure</fullName>
            </value>
            <value>
                <fullName>Audience individuelle &gt;7h</fullName>
            </value>
            <value>
                <fullName>Audience individuelle &gt; 7h</fullName>
                <isActive>false</isActive>
                <label>Audience individuelle &gt; 7h</label>
            </value>
            <value>
                <fullName>Audimètre</fullName>
            </value>
            <value>
                <fullName>Audimètre non connecté</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon batterie faible</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon inactif</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon jamais détecté</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Autre cause technique</fullName>
            </value>
            <value>
                <fullName>Autre déplacement</fullName>
            </value>
            <value>
                <fullName>Autre déplacement hors zone de mesure</fullName>
            </value>
            <value>
                <fullName>Autres usages</fullName>
            </value>
            <value>
                <fullName>Avis</fullName>
            </value>
            <value>
                <fullName>Beacon</fullName>
            </value>
            <value>
                <fullName>Beacon (logement plus grand)</fullName>
            </value>
            <value>
                <fullName>Beacon(s) Réceptionné(s)</fullName>
            </value>
            <value>
                <fullName>Beacon (tv en plus)</fullName>
            </value>
            <value>
                <fullName>Beacon (vehicule supplémentaire)</fullName>
            </value>
            <value>
                <fullName>Pager</fullName>
            </value>
            <value>
                <fullName>Setmeter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Nombre_de_beacons__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_beacons__c</fullName>
    <label>Nombre de beacons</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Nombre_de_pagers__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_pagers__c</fullName>
    <defaultValue>IF( $RecordType.Name =&apos;AIP&apos;, 1,0 )</defaultValue>
    <label>Nombre de pagers</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Nombre_de_set_meters__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_set_meters__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nombre de set meters</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer Panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Commandes</relationshipLabel>
    <relationshipName>Commandes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Requete__c.field-meta.xml
<CustomField>
    <fullName>Requete__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requête</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Commandes</relationshipLabel>
    <relationshipName>Commandes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Chute__c.field-meta.xml
<CustomField>
    <fullName>Chute__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Chute</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Pack_Initial_Pager__c.field-meta.xml
<CustomField>
    <fullName>Pack_Initial_Pager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pack Initial Pager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Pack_initial_pager_et_setmeter__c.field-meta.xml
<CustomField>
    <fullName>Pack_initial_pager_et_setmeter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pack initial pager et setmeter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Pack_Initial_Pager_ROAv3__c.field-meta.xml
<CustomField>
    <fullName>Pack_Initial_Pager_ROAv3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pack Initial Pager ROAv3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Pack_Initial_Pager_ROAv3_Setmeter__c.field-meta.xml
<CustomField>
    <fullName>Pack_Initial_Pager_ROAv3_Setmeter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pack Initial Pager ROAv3 Setmeter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Renvoi_Beacon__c.field-meta.xml
<CustomField>
    <fullName>Renvoi_Beacon__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Renvoi Beacon</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_de_produit__c.field-meta.xml
<CustomField>
    <fullName>Type_de_produit__c</fullName>
    <label>Type de produit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beacon</fullName>
            </value>
            <value>
                <fullName>Routeur Google</fullName>
            </value>
            <value>
                <fullName>Pager</fullName>
            </value>
            <value>
                <fullName>Setmeter</fullName>
            </value>
            <value>
                <fullName>TVM3</fullName>
            </value>
            <value>
                <fullName>Accessoire</fullName>
            </value>
            <value>
                <fullName>Périphérique</fullName>
            </value>
            <value>
                <fullName>Consommable</fullName>
            </value>
            <value>
                <fullName>Composant</fullName>
            </value>
            <value>
                <fullName>Pack Pager</fullName>
            </value>
            <value>
                <fullName>Pack SetMeter</fullName>
            </value>
            <value>
                <fullName>DMD NON COM</fullName>
            </value>
            <value>
                <fullName>DMD COM</fullName>
            </value>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>Streaming Meter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP01_Commande.cls
/*
* @date: 21/07/2021
* @ Description : creer des commandes reliee a des requetes
* @version 1.00   
* @Auteur Ayoub Ghammaz EIT
* @TestClass: AP01_Commande_Test
* @Coverage: 95%
History
* <Date of modification>   		<Author>    		<Description of modification>
* 		05/01/2022   			Claire VEHRLE  		Ajout des produit commandé aux commande de pack initial
* 		16/03/2023   			Bastien Pinard      Condition cordon cou PNL-4511
*		09/05/2023				Marliat.D			MAJ Règle de calcul chargeurs & usb
*/
public class AP01_Commande {
    public static void creerCommandePackInitial(List<Case> listCase) {
        List<Order> ListCommandeToInsert = new List<Order>();
        Map<String, List<PricebookEntry>> mapProducts = new Map<String, List<PricebookEntry>>();
        System.debug('$$$AP01_Commande listCase : ' + listCase);
        
        
        List<PricebookEntry> products = [SELECT id, Product2.Name, UnitPrice, Product2.Family, Product2.Type_de_produit__c, Product2.Pack_Initial_Pager__c
                                         FROM pricebookentry WHERE  IsActive=true AND Product2.Pack_Initial_Pager__c = TRUE];
        
        mapProducts.put('Pager', products);
        
        List<PricebookEntry> productsSetMeter = [SELECT id, Product2.Name, UnitPrice, Product2.Family, Product2.Type_de_produit__c, Product2.Pack_initial_pager_et_setmeter__c
                                                 FROM pricebookentry WHERE  IsActive=true AND Product2.Pack_initial_pager_et_setmeter__c = TRUE];
        
        mapProducts.put('Setmeter', productsSetMeter);
        
        List<PricebookEntry> productsROAv3 = [SELECT id, Product2.Name, UnitPrice, Product2.Family, Product2.Type_de_produit__c, Product2.Pack_Initial_Pager_ROAv3__c
                                              FROM pricebookentry WHERE  IsActive=true AND Product2.Pack_Initial_Pager_ROAv3__c = TRUE];
        
        mapProducts.put('ROAv3', productsROAv3);
        
        List<PricebookEntry> productsROAv3Setmeter = [SELECT id, Product2.Name, UnitPrice, Product2.Family, Product2.Type_de_produit__c, Product2.Pack_Initial_Pager_ROAv3_Setmeter__c
                                                      FROM pricebookentry WHERE  IsActive=true AND Product2.Pack_Initial_Pager_ROAv3_Setmeter__c = TRUE];
        
        mapProducts.put('ROAv3Setmeter', productsROAv3Setmeter);
        
        
        for(Case cs : listCase){
            Order commandeToInsert = new Order();
            commandeToInsert.AccountId = cs.AccountId;
            commandeToInsert.Foyer_paneliste__c = cs.Foyer_paneliste__c;
            commandeToInsert.Status =Label.Ord_Status_VersionPreliminaire;
            commandeToInsert.EffectiveDate = date.today();
            commandeToInsert.Requete__c = cs.Id;
            commandeToInsert.Pricebook2Id=Label.Catalogue_de_prix_standard;
            if(cs.Sous_type__c == Label.CAS_Sous_type_PackInitial) {
                commandeToInsert.Type = Label.Ord_Type_PackInitialPager;
            }
            else if (cs.Sous_type__c == Label.CAS_Sous_type_PackInitial_SetMeter) {
                commandeToInsert.Type = Label.Ord_Type_PackInitialPagerSetmeter;
            }
            else if (cs.Sous_type__c == Label.CAS_Sous_type_PackInitial_ROAv3_Setmeter) {
                commandeToInsert.Type = Label.ORD_Type_PackInitial_ROAv3_Setmeter;
            }
            else if (cs.Sous_type__c == Label.CAS_Sous_type_PackInitial_ROAv3) {
                commandeToInsert.Type = Label.ORD_Type_PackInitial_ROAv3;
            }
            ListCommandeToInsert.add(commandeToInsert);
        }
        
        System.debug('$$$AP01_Commande ListCommandeToInsert : ' + ListCommandeToInsert);
        if(ListCommandeToInsert.size()>0 && ListCommandeToInsert !=null){
            try{ 
                database.insert(ListCommandeToInsert);
            }Catch(exception ex){
                system.debug('Insert commande Exception Error:'+ex.getmessage());
            }
        }
        
        // ajouter les equipements a recuperer
        List<OrderItem> produitsCommandes = new List<OrderItem>();
        List<order> orderList = [
            SELECT  id, type, Foyer_paneliste__r.Nombre_de_set_meters__c , Foyer_paneliste__r.Nombre_de_beacons__c,
            Foyer_paneliste__r.Nombre_de_pagers__c
            FROM order WHERE id IN :ListCommandeToInsert
        ];
        
        for(Order ordr :orderList){// nb foyer paneliste = nb commande
            List<PricebookEntry> productsListToUse = new List<PricebookEntry>();
            
            if(ordr.Type == Label.Ord_Type_PackInitialPager) {
                System.debug('***Pager');
                productsListToUse = mapProducts.get('Pager');
            }
            else if (ordr.Type == Label.Ord_Type_PackInitialPagerSetmeter) {
                System.debug('***Setmeter');
                productsListToUse = mapProducts.get('Setmeter');
            }
            else if (ordr.Type == Label.ORD_Type_PackInitial_ROAv3_Setmeter) {
                System.debug('***ROAv3Setmeter');
                productsListToUse = mapProducts.get('ROAv3Setmeter');
            }
            else if (ordr.Type == Label.ORD_Type_PackInitial_ROAv3) {
                System.debug('***ROAv3');
                productsListToUse = mapProducts.get('ROAv3');
            }
            
            for(PricebookEntry pbe :productsListToUse ){
                System.debug('***pbe.Product2.Name: ' + pbe.Product2.Name);
                OrderItem orderItem = new OrderItem();
                orderItem.OrderId = ordr.id;
                orderItem.Product2Id = pbe.id;
                orderItem.UnitPrice = pbe.UnitPrice;
                if(ordr.Foyer_paneliste__r.Nombre_de_beacons__c >0 && pbe.Product2.Type_de_produit__c==Label.Pro_type_Beacon) { 
                    orderItem.Quantity = ordr.Foyer_paneliste__r.Nombre_de_beacons__c;
                    System.debug('***MD In OrderItem beacon ' + orderItem);
                    produitsCommandes.add(OrderItem);
                }
                else if (ordr.Foyer_paneliste__r.Nombre_de_set_meters__c > 0 && pbe.Product2.Type_de_produit__c == Label.Pro_type_SetMeter) {
                    orderItem.Quantity = ordr.Foyer_paneliste__r.Nombre_de_set_meters__c;
                    System.debug('**MD In OrderItem setMeter ' + orderItem);
                    produitsCommandes.add(OrderItem);
                }               
                
                else if((pbe.Product2.name.contains('hargeur') || pbe.Product2.name.contains('usb'))) {
                    if((ordr.Foyer_paneliste__r.Nombre_de_set_meters__c > 0)
                       && ((ordr.Type == Label.ORD_Type_PackInitial_ROAv3) ||(ordr.Type == Label.ORD_Type_PackInitial_ROAv3_Setmeter))) {
                           orderItem.Quantity = ordr.Foyer_paneliste__r.Nombre_de_set_meters__c; 
                           System.debug('**MD In OrderItem Chargeur ou USB setMeter & Pager > 0' + orderItem);
                           produitsCommandes.add(OrderItem);
                       }
                    else if ((ordr.Type == Label.Ord_Type_PackInitialPager) ||(ordr.Type == Label.Ord_Type_PackInitialPagerSetmeter)) {
                        orderItem.Quantity = ordr.Foyer_paneliste__r.Nombre_de_set_meters__c + 1;
                        System.debug('***MD In OrderItem Chargeur ou USB Initial Pager ' + orderItem);
                        produitsCommandes.add(OrderItem);
                    }
                }
                else {
                    System.debug('***Else');
                    orderItem.Quantity = 1;
                    produitsCommandes.add(OrderItem);
                    System.debug('***MD In OrderItem ELSE FINAL ' + orderItem);
                }
                
                System.debug('***OrderItem: ' + OrderItem);
                
            }
        }
        
        
        system.debug('$$$produitsCommandes ' + produitsCommandes);
        if(produitsCommandes!=null && produitsCommandes.size()>0){
            try{ 
                database.insert(produitsCommandes);
            }Catch(exception ex){
                system.debug('Insert commande Pack Initial Exception Error:'+ex.getmessage());
            }
        }
        
    }
    
    
    public static void creerCommandeChuteFoyerPan(List<foyer_Paneliste__c> listFoyerPaneliste) {
        List<Order> ListCommandeToInsert = new List<Order>();
        List<Order> ListCommandeToUpdate = new List<Order>();
        List<Id> FoyerPanelisteID= new List<Id>();
        List<foyer_Paneliste__c> listFoyerPanReq = new List<foyer_Paneliste__c>();
        Set<Id> setIdFoyerPan = new Set<Id>();
        List<Case> caseFPanList = new List<Case>();
        Map<Id, List<Case>> mapIdFoyerPanToListCase = new Map<Id, List<Case>>();
        Map<Id, Id> mapIdFPanCaseId = new Map<Id, Id>();
        Case caselastCreated = new Case(); 
        
        List<PricebookEntry> products=[SELECT id, UnitPrice FROM pricebookentry WHERE IsActive=true AND Product2.Chute__c = TRUE];
        
        
        If(listFoyerPaneliste.size()>0) {
            For(foyer_Paneliste__c fp : listFoyerPaneliste){
                setIdFoyerPan.add(fp.Id);
            }
        }
        
        If(listFoyerPaneliste.size()>0){  
            listFoyerPanReq = [SELECT Id, Name, Foyer__c, referentiel_panel__c,
                               (select Id, status, type, CreatedDate from Requetes__r order by CreatedDate desc Limit 1)
                               FROM foyer_paneliste__c 
                               WHERE Id IN :setIdFoyerPan 
                               AND referentiel_panel__r.type_de_panel__c =:Label.RFP_TypePanel_AIP];
        }  
        
        If(listFoyerPanReq.size()>0){
            For(foyer_Paneliste__c fp : listFoyerPanReq){
                for(Case req : fp.Requetes__r){
                    caselastCreated = req;
                }
                if(!mapIdFPanCaseId.containsKey(fp.Id) && caselastCreated != null){       
                    mapIdFPanCaseId.put(fp.Id,caselastCreated.Id);
                }
                caselastCreated = null;
            }
        }         
        For(foyer_Paneliste__c fp : listFoyerPanReq){
            Order commandeToInsert = new Order();
            commandeToInsert.AccountId = fp.Foyer__c;
            commandeToInsert.Foyer_paneliste__c = fp.Id; 
            commandeToInsert.Status = Label.Ord_Status_VersionPreliminaire; 
            commandeToInsert.Type = Label.Ord_Type_PackChute;
            commandeToInsert.EffectiveDate = date.today();
            commandeToInsert.Requete__c =  mapIdFPanCaseId.get(fp.Id);
            commandeToInsert.Pricebook2Id=Label.Catalogue_de_prix_standard;
            FoyerPanelisteID.add(fp.Id);
            ListCommandeToInsert.add(commandeToInsert);            
        }
        
        if(ListCommandeToInsert.size()>0 && ListCommandeToInsert !=null){
            System.debug('ListCommandeToInsert : ' + ListCommandeToInsert);
            try{ 
                database.insert(ListCommandeToInsert);
            }Catch(exception ex){
                system.debug('Insert commande Exception Error:'+ex.getmessage());
            }            
        }
        
        // ajouter les equipements a recuperer
        List<OrderItem> produitsCommandes = new List<OrderItem>();
        List<order> orderList = [SELECT id, Foyer_paneliste__r.id ,requete__c, Type
                                 FROM order WHERE id IN :ListCommandeToInsert];
        List<Foyer_paneliste__c> foyerpAsset= [select id , (select id , requete__c,status from equipements__r) from Foyer_paneliste__c where id in :FoyerPanelisteID];
        List<Asset> equToUpdate = new List<Asset>();
        for(Order ordr :orderList){// nb foyer paneliste = nb commande
            if(ordr.Type == Label.Ord_Type_PackChute ){// si commande de chute
                for(PricebookEntry pbe:products ){                    
                    OrderItem orderItem = new OrderItem(OrderId = ordr.id, Product2Id = pbe.id, Quantity = 1, UnitPrice = pbe.UnitPrice);
                    produitsCommandes.add(orderItem);
                    for(Foyer_paneliste__c fop: foyerpAsset){
                        if(fop.id == ordr.Foyer_paneliste__c){
                            for(Asset equ :  fop.equipements__r){
                                equ.Requete__c=ordr.requete__c;
                                equ.status = Label.ASS_Statut_Desaffecte;
                                equ.Date_de_desaffectation__c=System.today();
                                if(!equToUpdate.contains(equ)){
                                    equToUpdate.add(equ);
                                }
                            }
                        }
                    }
                }
            }
        }
        
        
        if(produitsCommandes!=null && produitsCommandes.size()>0){
            try{ 
                database.insert(produitsCommandes);
            }Catch(exception ex){
                system.debug('Insert commande Chute Exception Error:'+ex.getmessage());
            }
        }
        system.debug('$$$KA ' + equToUpdate);
        if(equToUpdate!=null && equToUpdate.size()>0){
            try{ 
                database.update(equToUpdate);
            }Catch(exception ex){
                system.debug('Update equipements  Exception Error:'+ex.getmessage());
            }
        }
        
        //MD     
        
        
    }
    
    
    public static void creerCommandeRenvoieBeacon(List<Case> listCase) {
        List<Order> ListCommandeToInsert = new List<Order>();
        Pricebook2 stdPriceBook    = [select id, name from Pricebook2 where isStandard = true limit 1];
        List<Id> FoyerPanelisteID= new List<Id>();
        List<PricebookEntry> products = [SELECT id, UnitPrice , name , Product2.Type_de_produit__c FROM pricebookentry WHERE IsActive=true AND Product2.Renvoi_Beacon__c = TRUE];
        for(Case cs : listCase){
            Order commandeToInsert = new Order();
            commandeToInsert.AccountId = cs.AccountId;
            commandeToInsert.Foyer_paneliste__c = cs.Foyer_paneliste__c;
            commandeToInsert.Status =Label.Ord_Status_VersionPreliminaire;
            commandeToInsert.Type = Label.Ord_TypeCommande_RenvoiBeacon;
            commandeToInsert.EffectiveDate = date.today();
            commandeToInsert.Requete__c = cs.Id;
            commandeToInsert.Pricebook2Id=stdPriceBook.id;
            FoyerPanelisteID.add(cs.Foyer_paneliste__c);
            ListCommandeToInsert.add(commandeToInsert);
        }
        if(ListCommandeToInsert.size()>0 && ListCommandeToInsert !=null){
            try{ 
                database.insert(ListCommandeToInsert);
            }Catch(exception ex){
                system.debug('Insert commande Exception Error:'+ex.getmessage());
            }
        }
        // ajouter les equipements a recuperer
        List<OrderItem> produitsCommandes = new List<OrderItem>();
        List<order> orderList = [SELECT id, Foyer_paneliste__r.id, Foyer_paneliste__r.Nombre_de_beacons__c FROM order WHERE id IN :ListCommandeToInsert];
        for(Order ordr :orderList){// nb foyer paneliste = nb commande
            for(PricebookEntry pbe : products ){
                if(ordr.Foyer_paneliste__r.Nombre_de_beacons__c != null && ordr.Foyer_paneliste__r.Nombre_de_beacons__c != 0 && pbe.Product2.Type_de_produit__c == Label.Pro_type_Beacon){// ajout de beacon si le foyer paneliste a plus que 0 
                    OrderItem orderItem = new OrderItem(OrderId = ordr.id, Product2Id = pbe.id, Quantity = ordr.Foyer_paneliste__r.Nombre_de_beacons__c ,UnitPrice = pbe.UnitPrice);
                    produitsCommandes.add(orderItem);
                }
            }
        }
        
        if(produitsCommandes!=null && produitsCommandes.size()>0){
            try{ 
                database.insert(produitsCommandes);
            }Catch(exception ex){
                system.debug('Insert commande Renvoie Beacon Exception Error:'+ex.getmessage());
            }
        }
    }
    
    
    
}