force-app/main/default/objects/Asset/fields/Equipement_de_mesure__c.field-meta.xml
<CustomField>
    <fullName>Equipement_de_mesure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Équipement de mesure</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Équipements de mesure (Équipement de mesure)</relationshipLabel>
    <relationshipName>Equipements_de_mesure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Equipement_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Equipement_du_foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipement du foyer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>L&apos;équipement foyer n&apos;appartient pas au foyer choisit.</errorMessage>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Equipements_du_foyer__c.Foyer__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Equipements_du_foyer__c</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>quipements_de_mesure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/Equipements_du_foyer__c.object-meta.xml
<CustomObject>
    <label>Equipement du foyer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;équipement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipements du foyer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Equipements du foyer</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Statut_Device_Equipement_Mesure__c/Statut_Device_Equipement_Mesure__c.object-meta.xml
<CustomObject>
    <label>Device rattaché à l&apos;équipement de mesure</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Numéro de Statut Device Equipement de Me</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Device rattaché à l&apos;équipement de mesure</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Statut_Device_Equipement_Mesure__c/fields/Equipement_de_mesure__c.field-meta.xml
<CustomField>
    <fullName>Equipement_de_mesure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipement de mesure</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Device rattaché à l&apos;équipement de mesure</relationshipLabel>
    <relationshipName>Statuts_Device_Equipement_de_Mesure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Statut_Device_Equipement_Mesure__c/fields/Equipement_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Equipement_du_foyer__c</fullName>
    <label>Équipement du foyer</label>
    <referenceTo>Equipements_du_foyer__c</referenceTo>
    <relationshipName>Statuts_Device_Equipement_de_Mesure</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AP07_Equipement.cls
/*
* @date: 04/08/2023
* @ Description : Lorsque le champ foyer panéliste d’un équipement de mesure Streaming Meter est rempli il faut affecté l'équipement de mesure à tous les enregistrements
					Device rattaché à l'équipement de mesure qui corresponde à des équipements du foyer du foyer du foyer panéliste 
* @version 1.00   
* @Auteur Claire VEHRLE
* @TestClass: AP07_Equipement_Test
* @Coverage: --%
History
* <Date of modification> <Author> 	<Description of modification>
*/
public class AP07_Equipement {

    public static void associationAssetStatutDevice (List<Asset> assetList) {
        List<Statut_Device_Equipement_Mesure__c> statutDeviceARemplir = new List<Statut_Device_Equipement_Mesure__c>();
        List<Id> foyerIdList = new List<Id>();
        Map<Id, Id> assetIdFoyerIdMap = new Map<Id, Id>();
        for(Asset eqtMesure: assetList) {
            foyerIdList.add(eqtMesure.AccountId);
            assetIdFoyerIdMap.put(eqtMesure.AccountId, eqtMesure.Id);
        }
        statutDeviceARemplir = [SELECT Id, Equipement_du_foyer__r.foyer__c, Equipement_de_mesure__c FROM Statut_Device_Equipement_Mesure__c WHERE Equipement_du_foyer__r.foyer__c IN :foyerIdList];
        
        System.debug('$$$AP07 assetList: ' + assetList);
        System.debug('$$$AP07 assetIdFoyerIdMap: ' + assetIdFoyerIdMap);
        for(Statut_Device_Equipement_Mesure__c statutDevice: statutDeviceARemplir) {
            
            System.debug('$$$AP07 statutDevice.Equipement_du_foyer__r.foyer__c: ' + statutDevice.Equipement_du_foyer__r.foyer__c);
            System.debug('$$$AP07 assetIdFoyerIdMap.get(statutDevice.Equipement_du_foyer__r.foyer__c): ' + assetIdFoyerIdMap.get(statutDevice.Equipement_du_foyer__r.foyer__c));
            statutDevice.Equipement_de_mesure__c = assetIdFoyerIdMap.get(statutDevice.Equipement_du_foyer__r.foyer__c);
        }
        
        System.debug('$$$AP07 statutDeviceARemplir: ' + statutDeviceARemplir);
        if(statutDeviceARemplir.size()>0 && statutDeviceARemplir !=null){
            try{ 
                database.update(statutDeviceARemplir);
            }Catch(exception ex){
                system.debug('$$$Update Equipement de mesure Device rattaché à l\'équipement de mesure Exception Error:'+ex.getmessage());
            }
        }
    }
}