force-app/main/default/objects/Asset/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Localisation__c.field-meta.xml
<CustomField>
    <fullName>Localisation__c</fullName>
    <label>Localisation</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Foyer</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Station</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>SAV MM</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Prestataire SAV</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Prestataire logistique</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Pas de localisation</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Fabricant</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AP05_FoyerPaneliste.cls
/*
* @date: 05/10/2021
* @ Description : Mise à jour de la localisation de l’équipement de mesure à « Perdu » si le statut du foyer paneliste est 'chute definitive' et le statut audimetrique est non-repondant 
* @version 1.00   
* @Auteur Ayoub Ghammaz EIT
* @TestClass: AP05_FoyerPaneliste_Test
* @Coverage: 88%
History
* <Date of modification> <Author> 	<Description of modification>
*/
public class AP05_FoyerPaneliste {
    
    public static void MajStatusEquipementPerdu (List<Foyer_paneliste__c> listFoyerPAn){
        List<Asset> assetToUpdate = new List<Asset>();
        for(asset equi : [select id , localisation__c from asset where localisation__c=:label.ASS_Localisation_Foyer and Status=:Label.ASS_Statut_Valide and Foyer_paneliste__c IN :listFoyerPAn]){
            equi.Status= Label.ASS_Statut_Perdu;
            assetToUpdate.add(equi);
        }
        if(assetToUpdate.size()>0 && assetToUpdate!=null){
            try{ 
                database.update(assetToUpdate);
            }Catch(exception ex){
                
                system.debug('Update asset to perdu Exception Error:'+ex.getmessage());
            }
        }
        
    }
}