force-app/main/default/objects/Asset/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Ordinateur fixe</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Ordinateur portable</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Tablette</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Smartphone</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT ( Bande_Usine__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequence_de_connexion_mobile__c.field-meta.xml
<CustomField>
    <fullName>Frequence_de_connexion_mobile__c</fullName>
    <label>Fréquence de connexion mobile</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequence_d_utilisation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequence_de_connexion_ordinateur__c.field-meta.xml
<CustomField>
    <fullName>Frequence_de_connexion_ordinateur__c</fullName>
    <label>Fréquence de connexion ordinateur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequence_d_utilisation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Lien_parente__c.field-meta.xml
<CustomField>
    <fullName>Lien_parente__c</fullName>
    <label>Lien parenté</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Chef de famille</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Conjoint</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Enfant</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Ascendant</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Autre</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Membre</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Invité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Non panéliste</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/Equipements_du_foyer__c.object-meta.xml
<CustomObject>
    <label>Equipement du foyer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;équipement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipements du foyer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Equipements du foyer</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Equipements du foyer</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>7</fullName>
                <label>Ordinateur fixe</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Ordinateur portable</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Tablette</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Mobile</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Poste TV</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Lecteur DVD</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Console de jeux</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Magnétoscope</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Décodeur</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Divers</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Box</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Caster</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Objet Connecté</label>
            </value>
            <value>
                <fullName>17</fullName>
                <isActive>false</isActive>
                <label>Autre équipement</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Statut_Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Statut_Foyer_paneliste__c</fullName>
    <label>Statut Foyer Panéliste</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Foyer_equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Recruté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Installé</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Equipé</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Intégré</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Désinstallé</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chute temporaire</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Chute définitive</label>
            </value>
            <value>
                <fullName>Chute définitive et désinstallé</fullName>
                <isActive>false</isActive>
                <label>Chute définitive et désinstallé</label>
            </value>
            <value>
                <fullName>Désinstallé actif</fullName>
                <isActive>false</isActive>
                <label>Désinstallé actif</label>
            </value>
            <value>
                <fullName>Recruté en attente d&apos;installation</fullName>
                <isActive>false</isActive>
                <label>Recruté en attente d&apos;installation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Individus Panélistes</relationshipLabel>
    <relationshipName>Individus_Paneliste</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Frequence_de_connexion_mobile__c.field-meta.xml
<CustomField>
    <fullName>Frequence_de_connexion_mobile__c</fullName>
    <label>Fréquence de connexion mobile</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tous les jours</fullName>
            </value>
            <value>
                <fullName>Presque tous les jours</fullName>
            </value>
            <value>
                <fullName>1 à 2 fois par semaine</fullName>
            </value>
            <value>
                <fullName>1 à 3 fois par mois</fullName>
            </value>
            <value>
                <fullName>Moins souvent</fullName>
            </value>
            <value>
                <fullName>Jamais</fullName>
            </value>
            <value>
                <fullName>NSP/Refus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invité</fullName>
            </value>
            <value>
                <fullName>Membre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT( Foyer_paneliste__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Frequence_d_utilisation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tous les jours</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Presque tous les jours</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>1 à 2 fois par semaine</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>1 à 3 fois par mois</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Moins souvent</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Jamais</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>NSP/Refus</label>
    </customValue>
    <masterLabel>Fréquence d&apos;utilisation</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Batch017_InstallControlesSoftMeters_test.cls
/*
* @Auteur : Jérôme HE EIT
* @date: 29/01/2022
* @Classe: Batch017_InstallControlesSoftMeters
* @Coverage: 94%
* * History
* <Date of modification>   		<Author>    		<Description of modification>
* 31-1-2023                      Mikael 					Adaptaion au chagement 
*/
@isTest
public class Batch017_InstallControlesSoftMeters_test {
    
    
    @isTest 
    static void testBatch17NonCreationRequeteReqNonRep() {
        
                
        List<Account> 				  foyerToInsert 			= new List<Account>();
        List<Referentiel_Panel__c>    refPanToInsert			= new List<Referentiel_Panel__c>();
        List<Foyer_paneliste__c>      foyerPanToInsert   		= new List<Foyer_paneliste__c>();
        List<Contact> 				  contactToInsert			= new List<Contact>();
        List<Individu_Paneliste__c>   indPanToInsert  			= new List<Individu_Paneliste__c>();
        List<Asset> 				  assetToInsert		 		= new List<Asset>();
        List<Case>					  caseToInsert				= new List<Case>();
        List<Equipements_du_foyer__c> eqfToInsert				= new List<Equipements_du_foyer__c>();
        List<Equipement_du_foyer_de_l_individu__c> eqtIndToInsert = new List<Equipement_du_foyer_de_l_individu__c>();
        
        List <String> ExternalIds = new List <String>();

        Id recordTypeIdFoyerPanMMPaME  = Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(Label.PAN_recordType_mediamatpame).getRecordTypeId();
        Id recordTypeIdRequeteControle = Schema.SObjectType.Case.getRecordTypeInfosByName().get(Label.CAS_Recordtype_Controle).getRecordTypeId();
        Id recordTypeIdEquipementDuFoyerDevice = Schema.SObjectType.Equipements_du_foyer__c.getRecordTypeInfosByName().get(Label.EQF_RecodType_Device).getRecordTypeId();

        Account foyerTest = new Account();
        foyerTest.Name = 'foyerTest';
        foyerToInsert.add(foyerTest);
        insert foyerToInsert;

        Referentiel_Panel__c refPanTest = new Referentiel_Panel__c();
        refPanTest.Type_de_panel__c 	= Label.RFP_TypePanel_PaME;
        refPanTest.Name					= Label.RFP_Nom_PaME;
        refPanToInsert.add(refPanTest);
        insert refPanToInsert;
        
        Foyer_paneliste__c foyerPanTest     = new Foyer_paneliste__c();
        foyerPanTest.foyer__c				= foyerTest.id;
        foyerPanTest.Referentiel_Panel__c = refPanTest.id;
        foyerPanTest.Name = 'foyerPanTest';
        //foyerPanTest.Statut_Foyer_paneliste__c	='4';
        foyerPanTest.RecordTypeId = recordTypeIdFoyerPanMMPaME;
        foyerPanToInsert.add(foyerPanTest);
        insert foyerPanToInsert;
        
        Contact compoFoyerTest = new Contact();
        compoFoyerTest.AccountId = foyerTest.id;
        compoFoyerTest.Lastname = 'compoFoyer1';
        compoFoyerTest.FirstName='cc';
        compoFoyerTest.Type__c = Label.CON_Type_MEMBRE;
        compoFoyerTest.Lien_parente__c = Label.CON_LienParente_ChefDeFamille;
        compoFoyerTest.Birthdate = date.today().addDays(- 10000);
        compoFoyerTest.Frequence_de_connexion_mobile__c=label.Acc_Freq_Conx_Mobile_PresqueTousLesJours;
        compoFoyerTest.Frequence_de_connexion_ordinateur__c=label.Acc_Freq_Conx_Ordi_TousLesJours;
        compoFoyerTest.Frequence_de_connexion_tablette__c=label.Acc_Freq_Conx_Tablette_TousLesJours;
        contactToInsert.add(compoFoyerTest);
        
        Contact compoFoyerTest2 = new Contact();
        compoFoyerTest2.AccountId = foyerTest.id;
        compoFoyerTest2.Lastname = 'compoFoyerTest2';
        compoFoyerTest2.FirstName='cc';
        compoFoyerTest2.Type__c = Label.CON_Type_MEMBRE;
        compoFoyerTest2.Lien_parente__c = Label.CON_LienParente_ChefDeFamille;
        compoFoyerTest2.Birthdate = date.today().addDays(- 10000);
        compoFoyerTest2.Frequence_de_connexion_mobile__c=label.Acc_Freq_Conx_Mobile_PresqueTousLesJours;
        compoFoyerTest2.Frequence_de_connexion_ordinateur__c=label.Acc_Freq_Conx_Ordi_TousLesJours;
        compoFoyerTest2.Frequence_de_connexion_tablette__c=label.Acc_Freq_Conx_Tablette_TousLesJours;
        contactToInsert.add(compoFoyerTest2);
        
        Contact compoFoyerTest3 = new Contact();
        compoFoyerTest3.AccountId = foyerTest.id;
        compoFoyerTest3.Lastname = 'compoFoyerTest3';
        compoFoyerTest3.FirstName='cc';
        compoFoyerTest3.Type__c = Label.CON_Type_MEMBRE;
        compoFoyerTest3.Lien_parente__c = Label.CON_LienParente_ChefDeFamille;
        compoFoyerTest3.Birthdate = date.today().addDays(- 10000);
        compoFoyerTest3.Frequence_de_connexion_mobile__c=label.Acc_Freq_Conx_Mobile_PresqueTousLesJours;
        compoFoyerTest3.Frequence_de_connexion_ordinateur__c=label.Acc_Freq_Conx_Ordi_TousLesJours;
        compoFoyerTest3.Frequence_de_connexion_tablette__c=label.Acc_Freq_Conx_Tablette_TousLesJours;
        contactToInsert.add(compoFoyerTest3);
        
        insert compoFoyerTest;
        insert compoFoyerTest2;
        insert compoFoyerTest3;
        
        Individu_Paneliste__c indPanTest = new Individu_Paneliste__c();
        indPanTest.name = 'indPanTest';
        indPanTest.Lettre__c = 'D';
        indPanTest.Date_de_derniere_activite_mobile__c  = date.today()-2;
        indPanTest.Foyer_paneliste__c = foyerPanTest.id;
        indPanTest.Composition_du_foyer__c = compoFoyerTest.id;
        indPanToInsert.add(indPanTest);
        
        Individu_Paneliste__c indPanTest2 = new Individu_Paneliste__c();
        indPanTest2.name = 'indPanTest2';
        indPanTest2.Lettre__c = 'E';
        indPanTest2.Date_de_derniere_activite_browser__c = date.today()-2;
        indPanTest2.Foyer_paneliste__c = foyerPanTest.id;
        indPanTest2.Composition_du_foyer__c = compoFoyerTest2.id;
        indPanToInsert.add(indPanTest2);
        
        Individu_Paneliste__c indPanTest3 = new Individu_Paneliste__c();
        indPanTest3.name = 'indPanTest3';
        indPanTest3.Lettre__c = 'F';
        indPanTest3.Date_de_derniere_activite_browser__c = date.today()-2;
        indPanTest3.Date_de_derniere_activite_mobile__c  = date.today()-2;
        indPanTest3.Foyer_paneliste__c = foyerPanTest.id;
        indPanTest3.Composition_du_foyer__c = compoFoyerTest3.id;
        indPanToInsert.add(indPanTest3);
        
        insert indPanToInsert;

        Equipements_du_foyer__c eqf1 = new Equipements_du_foyer__c();
        eqf1.RecordTypeId = recordTypeIdEquipementDuFoyerDevice;
        eqf1.foyer__c= foyerTest.id;
        eqf1.Type__c = Label.EQF_Type_Smartphone;
        eqf1.Utilisateur_principal__c = compoFoyerTest.id;
        eqfToInsert.add(eqf1);

        Equipements_du_foyer__c eqf2= new Equipements_du_foyer__c();
        eqf2.RecordTypeId = recordTypeIdEquipementDuFoyerDevice;
        eqf2.foyer__c= foyerTest.id;
        eqf2.Type__c = Label.EQF_Type_Tablette;
        eqf2.Utilisateur_principal__c = compoFoyerTest3.id;
        eqfToInsert.add(eqf2);

        Equipements_du_foyer__c eqf3= new Equipements_du_foyer__c();
        eqf3.RecordTypeId = recordTypeIdEquipementDuFoyerDevice;
        eqf3.foyer__c = foyerTest.id;
        eqf3.Type__c = Label.EQF_Type_OrdinateurPortable;
        eqf3.Utilisateur_principal__c = compoFoyerTest2.id;
        eqfToInsert.add(eqf3);

        insert eqfToInsert;        
        
        /*Equipement_du_foyer_de_l_individu__c eqtInd1 = new Equipement_du_foyer_de_l_individu__c();
        eqtInd1.Composition_du_foyer__c = compoFoyerTest.id;
        eqtInd1.Equipement_du_foyer__c = eqf1.id;
        eqtInd1.Utilisation_de_l_equipement__c = 'Oui';
        eqtIndToInsert.add(eqtInd1);
        
        Equipement_du_foyer_de_l_individu__c eqtInd2 = new Equipement_du_foyer_de_l_individu__c();
        eqtInd2.Composition_du_foyer__c = compoFoyerTest2.id;
        eqtInd2.Equipement_du_foyer__c = eqf3.id;
        eqtInd2.Utilisation_de_l_equipement__c = 'Oui';
        eqtIndToInsert.add(eqtInd2);
        
        Equipement_du_foyer_de_l_individu__c eqtInd3 = new Equipement_du_foyer_de_l_individu__c();
        eqtInd3.Composition_du_foyer__c = compoFoyerTest3.id;
        eqtInd3.Equipement_du_foyer__c = eqf2.id;
        eqtInd3.Utilisation_de_l_equipement__c = 'Oui';
        eqtIndToInsert.add(eqtInd3);
        
        Equipement_du_foyer_de_l_individu__c eqtInd4 = new Equipement_du_foyer_de_l_individu__c();
        eqtInd4.Composition_du_foyer__c = compoFoyerTest3.id;
        eqtInd4.Equipement_du_foyer__c = eqf3.id;
        eqtInd4.Utilisation_de_l_equipement__c = 'Oui';
        eqtIndToInsert.add(eqtInd4);
        
        insert eqtIndToInsert;*/
    
        Case caseTest70 = new Case();
        caseTest70.foyer_paneliste__c = foyerPanTest.id;
        caseTest70.AccountId		  = foyerTest.id;
        caseTest70.RecordTypeId		  = recordTypeIdRequeteControle;
        caseTest70.type=label.CAS_Type_Inactif_Meter_J_1;
        caseToInsert.add(caseTest70);
        
        Case caseTest90 = new Case();
        caseTest90.foyer_paneliste__c = foyerPanTest.id;
        caseTest90.AccountId		  = foyerTest.id;
        caseTest90.RecordTypeId		  = recordTypeIdRequeteControle;
        caseTest90.type=label.CAS_Type_Inactif_Meter_J_1;
        caseToInsert.add(caseTest90); 
        
        insert caseToInsert;
        
		Test.setCreatedDate(caseTest70.id, Date.Today() - 69);
        Test.setCreatedDate(caseTest90.id, Date.Today() - 89);
        
        System.debug('c.Jour_de_traitement__c');
		List<Case> caseTest=[SELECT id,Jour_de_traitement__c FROM CASE];
        for (Case c:caseTest) {
            System.debug('c.Jour_de_traitement__c: ' + c.Jour_de_traitement__c);
        }
        
        //System.debug(caseTest);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(compoFoyerTest.Id));
        //AP01_MembreDuFoyer.getContactFromSipanel(ExternalIds); 
        Batch017_InstallControlesSoftMeters batch = new Batch017_InstallControlesSoftMeters();
        Id batchId = Database.executeBatch(batch);
        Test.stopTest();
        
        List<Case> caseListToTest = [Select id from Case];
        List<Task> tastListToTest = [Select id from Task];
        
        //System.assertEquals(4, caseListToTest.size());
        //System.assertEquals(1, tastListToTest.size());
    }
    
}