force-app/main/default/objects/Product2/fields/Code_article__c.field-meta.xml
<CustomField>
    <fullName>Code_article__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code article</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_de_produit__c/Stock_de_produit__c.object-meta.xml
<CustomObject>
    <label>Stock de produit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks de produits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_de_produit__c/fields/Code_Article__c.field-meta.xml
<CustomField>
    <fullName>Code_Article__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code Article</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_de_produit__c/fields/Produit__c.field-meta.xml
<CustomField>
    <fullName>Produit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks de produits</relationshipLabel>
    <relationshipName>Stocks_de_produits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AP02_StockProduit.cls
/*
* @author: Claire VEHRLE
* @date: 10/08/2022 
* @ Description: Classe appelé par le Trigger SuiviStockSAVAfterInsert
* @TestClass: AP01_StockProduit_Test
* @Coverage: --%
* History
* <Date of modification>   		<Author>   		 <Description of modification>
*
* */
public class AP02_StockProduit {

    public static void associeProduit(List<Stock_de_Produit__c> stockProduitList) {
        
        List<String> codeArticleList = new List<String>();
        List<Product2> productList = new List<Product2>();
        Map<String, Id> codeArticleProduitMap = new Map<String, Id>();
        for(Stock_de_Produit__c stockProduit:stockProduitList) {
            codeArticleList.add(stockProduit.Code_Article__c);
        }
        system.debug('***codeArticleList: ' +codeArticleList);
        
        productList = [SELECT Id, code_Article__c FROM Product2 WHERE code_Article__c IN :codeArticleList];
        
        system.debug('***productList: ' +productList);
        
        for (Product2 produit:productList) {
            codeArticleProduitMap.put(produit.code_article__c, produit.Id);
        }
        
        for(Stock_de_Produit__c stockProduit:stockProduitList) {
            stockProduit.Produit__c = codeArticleProduitMap.get(stockProduit.Code_Article__c);
        }
        
        try{ 
            database.update(stockProduitList);
        }Catch(exception ex){
            system.debug('Update Stock de produit Ajout du produit Exception Error:' + ex.getmessage());
        }
    }
}