force-app/main/default/objects/Product2/fields/Code_article__c.field-meta.xml
<CustomField>
    <fullName>Code_article__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code article</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_de_produit__c/Stock_de_produit__c.object-meta.xml
<CustomObject>
    <label>Stock de produit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks de produits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_de_produit__c/fields/Code_Article__c.field-meta.xml
<CustomField>
    <fullName>Code_Article__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code Article</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_de_produit__c/fields/Produit__c.field-meta.xml
<CustomField>
    <fullName>Produit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks de produits</relationshipLabel>
    <relationshipName>Stocks_de_produits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_de_produit__c/fields/Valeur_du_stock__c.field-meta.xml
<CustomField>
    <fullName>Valeur_du_stock__c</fullName>
    <label>Valeur du stock</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AP02_StockProduit_Test.cls
/*
* @author: Claire VEHRLE
* @date: 10/08/2022
* @ Description Class that test AP01_SuiviStockSAV . Associated Trigger : StockDeProduitAfterInsert
* History
* <Date of modification>	   <Author> 	   <Description of modification>
* <Description of modification>
*/
@isTest
public class AP02_StockProduit_Test {

    @isTest
    static void Test() {
        
        List<Product2> productToInsert = new List<Product2>();
        Product2 produit1 = new Product2();
        produit1.name = 'Produit Test';
        produit1.Code_article__c = '1A2B3C';
        productToInsert.add(produit1);
        
        Product2 produit2 = new Product2();
        produit2.name = 'Produit Test';
        produit2.Code_article__c = '4D5E6F';
        productToInsert.add(produit2);
        
        Product2 produit3 = new Product2();
        produit3.name = 'Produit Test';
        produit3.Code_article__c = '7G8H9I';
        productToInsert.add(produit3);
        
        insert productToInsert;
        
        List<Stock_de_produit__c> stockProduitList = new List<Stock_de_produit__c>();
        Stock_de_produit__c stockProduit1 = new Stock_de_produit__c();
        stockProduit1.Quantite__c = 123;
        stockProduit1.Valeur_du_stock__c = 1230;
        stockProduit1.Code_article__c = '1A2B3C';
        stockProduitList.add(stockProduit1);
        Stock_de_produit__c stockProduit2 = new Stock_de_produit__c();
        stockProduit2.Quantite__c = 223;
        stockProduit2.Valeur_du_stock__c = 2230;
        stockProduit2.Code_article__c = '4D5E6F';
        stockProduitList.add(stockProduit2);
        Stock_de_produit__c stockProduit3 = new Stock_de_produit__c();
        stockProduit3.Quantite__c = 323;
        stockProduit3.Valeur_du_stock__c = 3230;
        stockProduit3.Code_article__c = '7G8H9I';
        stockProduitList.add(stockProduit3);
        
        insert stockProduitList;
        
        List<Stock_de_produit__c> stockProduitToCheck = new List<Stock_de_produit__c>();
        stockProduitToCheck = [SELECT Id FROM Stock_de_produit__c WHERE Produit__c != null];
        
        System.assertEquals(3, stockProduitToCheck.size());
    }
}