force-app/main/default/objects/Account/fields/Abonnement_canal_motive_par_le_cinema__c.field-meta.xml
<CustomField>
    <fullName>Abonnement_canal_motive_par_le_cinema__c</fullName>
    <label>Abonnement Canal+ motivé par le CINEMA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Abonnement_Canal_plus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Abonnement_canal_motive_par_le_sport__c.field-meta.xml
<CustomField>
    <fullName>Abonnement_canal_motive_par_le_sport__c</fullName>
    <label>Abonnement Canal+ motivé par le SPORT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Abonnement_Canal_plus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Abonnement_canal_motive_par_les_series__c.field-meta.xml
<CustomField>
    <fullName>Abonnement_canal_motive_par_les_series__c</fullName>
    <label>Abonnement Canal+ motivé par les SERIES</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Abonnement_Canal_plus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ACC_ExtId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>ACC_ExtId_SIPanel__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ACC_ExtId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Adresse_e_mail_principale__c.field-meta.xml
<CustomField>
    <fullName>Adresse_e_mail_principale__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Adresse e-mail principale</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Complement_d_adresse__c.field-meta.xml
<CustomField>
    <fullName>Complement_d_adresse__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Complément d&apos;adresse</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_d_anonymisation__c.field-meta.xml
<CustomField>
    <fullName>Date_d_anonymisation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;anonymisation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_de_visite_de_courtoisie__c.field-meta.xml
<CustomField>
    <fullName>Date_de_visite_de_courtoisie__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de visite de courtoisie</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Equipe_barre_de_son__c.field-meta.xml
<CustomField>
    <fullName>Equipe_barre_de_son__c</fullName>
    <label>Equipé barre de son</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Non concerné</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Oui</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Non</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fournisseur_acces_internet__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur_acces_internet__c</fullName>
    <label>Fournisseur d&apos;accès internet</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>-1</fullName>
                <label>Non renseigné</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Non abonné internet</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Alice/Tiscali</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>AOL</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Bouygues</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Darty</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Free</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Numéricable</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Orange</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>SFR/NEUF</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>TELE 2</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Autre</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>NSP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Jardin__c.field-meta.xml
<CustomField>
    <fullName>Jardin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Jardin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_pc__c.field-meta.xml
<CustomField>
    <fullName>Nombre_pc__c</fullName>
    <label>Nombre d&apos;ordinateurs</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_smartphone__c.field-meta.xml
<CustomField>
    <fullName>Nombre_smartphone__c</fullName>
    <label>Nombre de smartphones</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_tablette__c.field-meta.xml
<CustomField>
    <fullName>Nombre_tablette__c</fullName>
    <label>Nombre de tablettes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_TV__c.field-meta.xml
<CustomField>
    <fullName>Nombre_TV__c</fullName>
    <label>Nombre de TV actives</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_tv_total__c.field-meta.xml
<CustomField>
    <fullName>Nombre_tv_total__c</fullName>
    <label>Nombre TV total dans le foyer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Aucune TV</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1 TV</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>2 TV</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>3 TV</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>4 TV</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>5 TV ou plus</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_de_portable__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_portable__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Numéro de téléphone portable</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_de_telephone_fixe__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_telephone_fixe__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Numéro de téléphone fixe</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Personne_de_reference__c.field-meta.xml
<CustomField>
    <fullName>Personne_de_reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personne de référence</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Cet individu n&apos;existe pas ou n&apos;est pas rattaché à ce foyer.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Foyers</relationshipLabel>
    <relationshipName>Foyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Statut_d_occupation__c.field-meta.xml
<CustomField>
    <fullName>Statut_d_occupation__c</fullName>
    <label>Statut d’occupation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>LOCATAIRE</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>PROPRIETAIRE OU ACCEDANT A LA PROPRIETE</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>AUTRE</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>REFUS</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Non renseignée</label>
            </value>
            <value>
                <fullName>Propriétaire</fullName>
                <isActive>false</isActive>
                <label>Propriétaire</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TECH_CongePrincipal__c.field-meta.xml
<CustomField>
    <fullName>TECH_CongePrincipal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TECH_CongePrincipal</label>
    <referenceTo>Conge__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Foyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/TECHi_is_WorkOrder_Changed__c.field-meta.xml
<CustomField>
    <fullName>TECHi_is_WorkOrder_Changed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECHi s WorkOrder Changed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type_acces_internet__c.field-meta.xml
<CustomField>
    <fullName>Type_acces_internet__c</fullName>
    <label>Type d&apos;accès internet</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Non réponse</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Pas d&apos;accès Internet</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Modem classique (RTC)</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Connexion câble</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Connexion ADSL</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Satellite</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Ligne Numéris (RNIS)</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Fibre optique</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>NSP</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Clé 3G</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Type_d_habitation__c.field-meta.xml
<CustomField>
    <fullName>Type_d_habitation__c</fullName>
    <label>Type d&apos;habitation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
                <label>MAISON INDIVIDUELLE</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>IMMEUBLE</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>FERME</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Non renseignée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/ACC_EXTId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>ACC_EXTId_SIPanel__c</fullName>
    <description>(GID) c&apos;est l&apos;id salesforce de l&apos;enregistrement Foyer Parent
Ce champ sert a identifier l&apos;enregistrement Foyer parent du foyer Paneliste</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ACC_EXTId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Date_de_visite_de_courtoisie__c.field-meta.xml
<CustomField>
    <fullName>Date_de_visite_de_courtoisie__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de visite de courtoisie</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Abonnement_Canal_plus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tout à fait</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Plutôt</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Plutôt pas</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Pas du tout</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Non abonné</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <label>Non réponse</label>
    </customValue>
    <masterLabel>Abonnement Canal +</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP05_Foyer.cls
/*
* @date: 10/08/2021
* @ Description : Appeler mulesoft API pour envoyer les foyers panélistes d'un compte à la modification de l'un de ses foyers panélistes
* @version 1.00   
* @Auteur Claire VEHRLE EIT
* @TestClass: AP05_Foyer_Test
* @Coverage: --%
 History
* <Date of modification>   	     <Author>    		  <Description of modification>
*/
public class AP05_Foyer {

        public static void envoyerFoyerMulesoft(List<Account> listFoyer, Map<Id,Account> mapOldFoyer) {
        Set<String> setExtIds = new Set<String>();
        List<Schema.FieldSetMember> fields = Schema.SObjectType.Account.fieldSets.Champs_envoyes_vers_sipanel.getFields();
        List<Id> foyerId = new List<Id>();
        for(Account foyer: listFoyer) {
            foyerId.add(foyer.Id);
        }
            //Ajouter les champs de l'ensemble de champ
        List<Account> ListIndPan = [SELECT Id, ACC_ExtId_SIPanel__c, TECH_CongePrincipal__c, Name, Complement_d_adresse__c, ShippingCity, 
                                    ShippingCountry, ShippingPostalCode, ShippingStreet, ShippingState, Date_d_anonymisation__c,
                                    Adresse_e_mail_principale__c, Personne_de_reference__c, Type_d_habitation__c, Jardin__c, Statut_d_occupation__c,
                                    Abonnement_canal_motive_par_le_cinema__c, Abonnement_canal_motive_par_le_sport__c, Numero_de_telephone_fixe__c,
                                    Abonnement_canal_motive_par_les_series__c, TECHi_is_WorkOrder_Changed__c,Date_de_visite_de_courtoisie__c,
                                    Nombre_TV__c, Nombre_tv_total__c, Nombre_pc__c, Nombre_smartphone__c, Nombre_tablette__c, Numero_de_portable__c,
                                    Fournisseur_acces_internet__c, Type_acces_internet__c, Equipe_barre_de_son__c, Equipe_enceintes_TV__c, 
                                    Equipe_home_cinema__c, Equipe_internet__c, Equipe_ordinateur__c, Equipe_tablette__c, Equipe_smartphone__c, Equipe_filaire__c
                                    FROM Account
                                    WHERE Id in : foyerId];
        for(Account foyer : ListIndPan){
            for(Schema.FieldSetMember foyerField : fields) {
                //Vérifier si l'un des champs à envoyer à Mulesoft a été mis à jour
                if(foyer.get(foyerField.getFieldPath()) != mapOldFoyer.get(foyer.Id).get(foyerField.getFieldPath()) && foyer.Date_d_anonymisation__c ==null) {
                    setExtIds.add(foyer.Id); // to be modified accordingly
                }
            }
        }
        System.debug('***setExtIds: '  + setExtIds);
        if(setExtIds.size() > 0 && setExtIds!= null){
            envoyerAMulesoft(setExtIds);
        }
    }
    
        @future (callout=true)
    public static void envoyerAMulesoft(Set<String> setExtIds){
        
        List<Account> ListIndPan = [SELECT Id, (SELECT Id, Foyer_Paneliste_ExtId_SIPanel__c FROM Panelistes__r)
                                               FROM Account
                                               WHERE Id in : setExtIds];
        for(Account foyer :ListIndPan ){
            for(Foyer_Paneliste__c foyerPan:foyer.Panelistes__r) {
                String endpoint = 'callout:Mulesoft_experience_API/' +'api/'+label.Mulesoft_Xapp_MM_Sync_Sipanel+'/v1/'+ label.Mulesoft_expAPI_houseHolds + '/'+ foyer.Id
                    + '?flow='+label.Mulesoft_flow_parameter_sf_to_sipanel+'&uid='+foyerPan.Foyer_Paneliste_ExtId_SIPanel__c;
                String method = 'PUT';
                
                Http http = new Http();
                HttpRequest req = new HttpRequest();
                req.setHeader('x-client-id', label.Mulesoft_expAPI_clientId);
                req.setHeader('x-client-secret', label.Mulesoft_expAPI_clientSecret);
                req.setHeader('Accept', 'application/json');
                req.setHeader('Content-Type', 'application/json');
                req.setEndpoint(endpoint);
                req.setMethod(method);
                JSONGenerator gen = JSON.createGenerator(true);
                gen.writeStartObject();
                gen.writeStringField('description', 'test');
                gen.writeEndObject();
                req.setBody(gen.getAsString());
                
                req.setEndpoint(endpoint);
                req.setMethod(method);
                
                HTTPResponse res = http.send(req);
                System.debug('***Http response: ' + res.getBody());
            }
            
        }
    }
    
        /*public static void envoyerAMulesoftBatch(Set<String> setExtIds){
        
        List<Account> ListIndPan = [SELECT Id, (SELECT Id, Foyer_Paneliste_ExtId_SIPanel__c FROM Panelistes__r)
                                               FROM Account
                                               WHERE Id in : setExtIds];
        for(Account foyer :ListIndPan ){
            for(Foyer_Paneliste__c foyerPan:foyer.Panelistes__r) {
                String endpoint = 'callout:Mulesoft_experience_API/' +'api/'+label.Mulesoft_Xapp_MM_Sync_Sipanel+'/v1/'+ label.Mulesoft_expAPI_houseHolds + '/'+ foyer.Id
                    + '?flow='+label.Mulesoft_flow_parameter_sf_to_sipanel+'&uid='+foyerPan.Foyer_Paneliste_ExtId_SIPanel__c;
                String method = 'PUT';
                
                Http http = new Http();
                HttpRequest req = new HttpRequest();
                req.setHeader('x-client-id', label.Mulesoft_expAPI_clientId);
                req.setHeader('x-client-secret', label.Mulesoft_expAPI_clientSecret);
                req.setHeader('Accept', 'application/json');
                req.setHeader('Content-Type', 'application/json');
                req.setEndpoint(endpoint);
                req.setMethod(method);
                JSONGenerator gen = JSON.createGenerator(true);
                gen.writeStartObject();
                gen.writeStringField('description', 'test');
                gen.writeEndObject();
                req.setBody(gen.getAsString());
                
                req.setEndpoint(endpoint);
                req.setMethod(method);
                
                HTTPResponse res = http.send(req);
                System.debug('***Http response: ' + res.getBody());
            }
            
        }
    }*/
}