force-app/main/default/objects/Account/fields/ACC_ExtId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>ACC_ExtId_SIPanel__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ACC_ExtId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Contact_principal__c.field-meta.xml
<CustomField>
    <fullName>Contact_principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact principal</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Cet individu (Contact Principal) n&apos;existe pas ou n&apos;est pas rattaché à ce foyer.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Foyers (Contact principal)</relationshipLabel>
    <relationshipName>Foyers_en_tant_que_contact_principal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_de_chute__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Solde_de_points__c.field-meta.xml
<CustomField>
    <fullName>Solde_de_points__c</fullName>
    <formula>Nombre_de_points_cumules__c - Nombre_de_points_debites__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Solde de points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ACC_EXTId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>ACC_EXTId_SIPanel__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Numéro du foyer</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_principal__c.field-meta.xml
<CustomField>
    <fullName>Contact_principal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contact Principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Solde_de_points__c.field-meta.xml
<CustomField>
    <fullName>Solde_de_points__c</fullName>
    <formula>Nombre_de_points_cr_dit_s__c - Nombre_de_points_debites__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Solde de points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/Fidelisation__c.object-meta.xml
<CustomObject>
    <label>Fidélisation</label>
    <nameField>
        <displayFormat>FID-{0000}</displayFormat>
        <label>Nom de Fidélisation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fidélisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fidelisation__c/fields/ACC_EXTId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>ACC_EXTId_SIPanel__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Numéro du foyer</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Composition du foyer</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Ce membre de foyer ne fait pas partie de ce foyer ou il n&apos;existe pas</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Foyer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fidelisations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fid_lisations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fidelisations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Individu_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Individu_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individu Panéliste</label>
    <referenceTo>Individu_Paneliste__c</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fid_lisations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Points_debites__c.field-meta.xml
<CustomField>
    <fullName>Points_debites__c</fullName>
    <label>Points Débités</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Solde_de_points_a_creation__c.field-meta.xml
<CustomField>
    <fullName>Solde_de_points_a_creation__c</fullName>
    <label>Solde de points</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Type_de_mouvement__c.field-meta.xml
<CustomField>
    <fullName>Type_de_mouvement__c</fullName>
    <label>Type de mouvement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Commande</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Crédit automatique</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Crédit exceptionnel</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Crédit manuel</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Débit automatique</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Débit des points fin de contrat</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Débit exceptionnel</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Débit manuel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fidelisation__c/recordTypes/Debit.recordType-meta.xml
<RecordType>
    <fullName>Debit</fullName>
    <active>true</active>
    <description>Points de fidélisation qu&apos;on retire du compte</description>
    <label>Débit</label>
</RecordType>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/ACC_EXTId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>ACC_EXTId_SIPanel__c</fullName>
    <description>(GID) c&apos;est l&apos;id salesforce de l&apos;enregistrement Foyer Parent
Ce champ sert a identifier l&apos;enregistrement Foyer parent du foyer Paneliste</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ACC_EXTId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Date_de_chute__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Membre_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Membre_du_foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membre du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Statut_Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Statut_Foyer_paneliste__c</fullName>
    <label>Statut Foyer Panéliste</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Foyer_equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Recruté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Installé</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Equipé</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Intégré</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Désinstallé</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chute temporaire</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Chute définitive</label>
            </value>
            <value>
                <fullName>Chute définitive et désinstallé</fullName>
                <isActive>false</isActive>
                <label>Chute définitive et désinstallé</label>
            </value>
            <value>
                <fullName>Désinstallé actif</fullName>
                <isActive>false</isActive>
                <label>Désinstallé actif</label>
            </value>
            <value>
                <fullName>Recruté en attente d&apos;installation</fullName>
                <isActive>false</isActive>
                <label>Recruté en attente d&apos;installation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/TECH_TypePanel__c.field-meta.xml
<CustomField>
    <fullName>TECH_TypePanel__c</fullName>
    <formula>TEXT(Referentiel_Panel__r.Type_de_panel__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_TypePanel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Individus Panélistes</relationshipLabel>
    <relationshipName>Individus_Paneliste</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_validation_rules__c.field-meta.xml
<CustomField>
    <fullName>Bypass_validation_rules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass validation rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Batch009_Debit_RemiseSoldeAZero.cls
/*
* @author: Maribelle ZARAZIR EI
* @date: 08/2021
* @ Description Batch quotidien qui crée des lignes de débits pour mettre à 0 les soldes des Foyers chutés il y plus de 70 jours
* @TestClass: Batch009_Debit_RemiseSoldeAZero_Test
* @Coverage: 88%
* History
* <Date of modification>   <Author>    <Description of modification>
*/
global class Batch009_Debit_RemiseSoldeAZero implements Database.Batchable<sObject>, Database.Stateful {
    
    //Added for email notification - START
    global String errorTxt = '';
    global Boolean containsErrors = false;
    //Added for email notification - END
    global Boolean userByPass;
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        User currentUser = [SELECT Id, Bypass_validation_rules__c FROM User WHERE Id = :UserInfo.getUserId()];
        userByPass = currentUser.Bypass_validation_rules__c; //saved for later
        currentUser.Bypass_validation_rules__c = True;
        update currentUser;
        
        //Passer sur les Foyers qui ont été chutés il y a plus de 70 jours et dont le solde n'a pas encore été remise à 0
        String query = 'SELECT Id, Solde_de_points__c, ACC_EXTId_SIPanel__c,(select id,Date_de_chute__c,ACC_EXTId_SIPanel__c,Foyer__c,Foyer__r.Solde_de_points__c,TECH_TypePanel__c ,foyer__r.Contact_principal__r.id from Panelistes__r ) '+
            + 'FROM Account  '
            + 'WHERE   Solde_de_points__c > 0 and id in (select Foyer__c from Foyer_paneliste__c where Statut_Foyer_paneliste__c =\'5\')  ';
          // String query = 'select id, (select id,Date_de_chute__c,ACC_EXTId_SIPanel__c,Foyer__c,Foyer__r.Solde_de_points__c,TECH_TypePanel__c ,foyer__r.Contact_principal__r.id from Panelistes__r )  from account where id=\'0013X00003QhBtvQAF\'';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Account> scope){
        system.debug('$$$ scope ' + scope);
        
        List<Fidelisation__c> listeLignesDebits = new List<Fidelisation__c>();
        Fidelisation__c ligneDeDebit;
        
        Id debitRecordTypeId = Schema.SObjectType.Fidelisation__c.getRecordTypeInfosByDeveloperName().get('Debit').getRecordTypeId();
        map<account,id> accountFoyerpan = new map<account,id>();
       
       List<account> NotAllchute =new list<account>();
       List<account> Allchute = new list<account>();
        Foyer_paneliste__c  fp;
       map<account,list<Foyer_paneliste__c>> AccFoyerpan = new map<account,list<Foyer_paneliste__c>>();
        for(Account acc : scope)
              
        {
            system.debug('aa'+acc);
            for (Foyer_paneliste__c f: acc.Panelistes__r ){
                if (f.Date_de_chute__c!=null && f.Date_de_chute__c > system.today().adddays(-70)){
                    system.debug('ttt'+f.Date_de_chute__c );
                     NotAllchute.add(acc);
                }
            }
        }
        for(Account acc : scope){
            if(!NotAllchute.contains(acc)){
                Allchute.add(acc);
            }    
        }
        
        for (account acc: Allchute){
                    AccFoyerpan.put(acc,acc.panelistes__r);
        }
        system.debug(' aa'+Allchute.size());
        for (account acc:Allchute )  {
           fp=dernierChute(AccFoyerpan.get(acc));
           listeLignesDebits.add(NewFID(fp.id,fp.Foyer__c,debitRecordTypeId, '5',fp.Foyer__r.Solde_de_points__c,fp.Foyer__r.Solde_de_points__c));
        }

            //listeLignesDebits.add(ligneDeDebit);
        
        if(listeLignesDebits != null && listeLignesDebits.size() > 0)
        {
            try
            { 
               insert listeLignesDebits;
            }
            Catch(exception ex)
            {
                system.debug('Insert FID Exception Error: ' + ex.getmessage());
                //added for notification
                errorTxt += 'Erreur durant la création des lignes de débit : ' + ex.getMessage() + '\n';
                containsErrors = true;
            }  
        }
        }
    
    
    
        
    global void finish(Database.BatchableContext bc){
        
        //Added for notifications - START
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        List<String> toMailAddress = System.Label.BatchNotif_B009_ToAddress.split(';');
        
        mail.setToAddresses(toMailAddress);
        mail.setSenderDisplayName(System.Label.BatchNotif_B009_SenderName);
        mail.setSubject(System.Label.BatchNotif_B009_Subject+'-'+date.today().format());
        
        String emailBody = 'L\'exécution du batch Batch009_Debit_RemiseSoldeAZero s\'est terminée.\n';
        if(containsErrors) {
            emailBody += 'Les erreurs suivantes ont été rencontrées :\n\n';
            emailBody += errorTxt;
        } else {
            emailBody += 'Aucune erreur n\'a été relevée.';
        }
        mail.setPlainTextBody(emailBody);
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        //Added for notifications - END
    }


public static Fidelisation__c NewFID(ID foyerPanId,ID AccounId,Id recordTypeIdFIDcredit,String TypeMouvement,Decimal Pointsdebites,Decimal Soldecreation) {
        Fidelisation__c FID = new Fidelisation__c();
            Id debitRecordTypeId = Schema.SObjectType.Fidelisation__c.getRecordTypeInfosByDeveloperName().get('Debit').getRecordTypeId();

        List <Individu_Paneliste__c> ind = new List <Individu_Paneliste__c>();
        if(TypeMouvement!=null  && Pointsdebites!=null)
        {
                ind = [select id,Composition_du_foyer__c from Individu_Paneliste__c where Foyer_paneliste__c =:foyerPanId ];
     
            system.debug(ind); 
            // system.debug(ind[0].Id);
            FID.Foyer_paneliste__c=foyerPanId;
            FID.Type_de_mouvement__c=TypeMouvement;
            FID.RecordTypeId = debitRecordTypeId;
            FID.Foyer__c=AccounId;
            FID.Points_debites__c=Pointsdebites;
            FID.Solde_de_points_a_creation__c=Pointsdebites;
            if(ind.size()> 0) {
                FID.Composition_du_foyer__c	=ind[0].Composition_du_foyer__c ;
            }
            if( (ind.size() > 0) ){
                FID.Individu_paneliste__c = ind[0].Id;
            }
            
        }

        return FID;
    }
    
    Public static Foyer_paneliste__c dernierChute(list<Foyer_paneliste__c> FoyerPan){
        Foyer_paneliste__c dernier=FoyerPan[0];
        for (Foyer_paneliste__c pan:FoyerPan ){
            if (pan.Date_de_chute__c > dernier.Date_de_chute__c){
                dernier= pan;
            }
        }
        return dernier;
    }
}