force-app/main/default/objects/Account/fields/ACC_ExtId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>ACC_ExtId_SIPanel__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ACC_ExtId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Date_d_installation__c.field-meta.xml
<CustomField>
    <fullName>Date_d_installation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;installation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_de_portable__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_portable__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Numéro de téléphone portable</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/ACC_EXTId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>ACC_EXTId_SIPanel__c</fullName>
    <description>(GID) c&apos;est l&apos;id salesforce de l&apos;enregistrement Foyer Parent
Ce champ sert a identifier l&apos;enregistrement Foyer parent du foyer Paneliste</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ACC_EXTId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Date_d_installation__c.field-meta.xml
<CustomField>
    <fullName>Date_d_installation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;installation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Statut_Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Statut_Foyer_paneliste__c</fullName>
    <label>Statut Foyer Panéliste</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Foyer_equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Recruté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Installé</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Equipé</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Intégré</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Désinstallé</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chute temporaire</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Chute définitive</label>
            </value>
            <value>
                <fullName>Chute définitive et désinstallé</fullName>
                <isActive>false</isActive>
                <label>Chute définitive et désinstallé</label>
            </value>
            <value>
                <fullName>Désinstallé actif</fullName>
                <isActive>false</isActive>
                <label>Désinstallé actif</label>
            </value>
            <value>
                <fullName>Recruté en attente d&apos;installation</fullName>
                <isActive>false</isActive>
                <label>Recruté en attente d&apos;installation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_triggers__c.field-meta.xml
<CustomField>
    <fullName>Bypass_triggers__c</fullName>
    <label>Bypass triggers</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AP01_BandeUsine</fullName>
            </value>
            <value>
                <fullName>AP01_Commande</fullName>
            </value>
            <value>
                <fullName>AP01_Conge</fullName>
            </value>
            <value>
                <fullName>AP01_Control</fullName>
                <isActive>false</isActive>
                <label>AP01_Control</label>
            </value>
            <value>
                <fullName>AP01_Controle</fullName>
            </value>
            <value>
                <fullName>AP01_Convention</fullName>
            </value>
            <value>
                <fullName>AP01_Equipement</fullName>
            </value>
            <value>
                <fullName>AP01_EquipementDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP01_Evenement</fullName>
            </value>
            <value>
                <fullName>AP01_Fidelisation</fullName>
            </value>
            <value>
                <fullName>AP01_Foyer</fullName>
            </value>
            <value>
                <fullName>AP01_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP01_IndividuPaneliste</fullName>
            </value>
            <value>
                <fullName>AP01_LienMeter</fullName>
            </value>
            <value>
                <fullName>AP01_MembreDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP01_Requete</fullName>
            </value>
            <value>
                <fullName>AP01_StockProduit</fullName>
            </value>
            <value>
                <fullName>AP01_SuiviStockSAV</fullName>
            </value>
            <value>
                <fullName>AP01_UpdatescheduledDate</fullName>
            </value>
            <value>
                <fullName>AP01_WorkOrder</fullName>
            </value>
            <value>
                <fullName>AP010_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP011_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP02_BandeUsine</fullName>
            </value>
            <value>
                <fullName>AP02_Commande</fullName>
            </value>
            <value>
                <fullName>AP02_Controle</fullName>
            </value>
            <value>
                <fullName>AP02_Convention</fullName>
            </value>
            <value>
                <fullName>AP02_Equipement</fullName>
            </value>
            <value>
                <fullName>AP02_EquipementDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP02_Foyer</fullName>
            </value>
            <value>
                <fullName>AP02_FoyerPaneliste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP07_FoyerPaneliste_Test.cls
/** 
* @author: Marleine Abi Khalil
* @date: 21/03/2022 
* @description: Class that test AP07_FoyerPaneliste . Associated Trigger : FoyerPanelisteAfterUpdate
*/
@isTest
global class AP07_FoyerPaneliste_Test implements HttpCalloutMock {
	// Implement this interface method
    global HTTPResponse respond(HTTPRequest request) {
        // Create a fake response
        HttpResponse response = new HttpResponse();
        response.setHeader('Content-Type', 'application/json');
        response.setBody('Successfull');
        response.setStatusCode(200);
        return response; 
    }
    
    @isTest
	static void deprovisionningGoogleTest(){
        User u = [SELECT id, Bypass_triggers__c FROM User WHERE isActive = true and Profile.name like '%dministra%' limit 1];
        u.Bypass_triggers__c = 'AP02_Foyer';
        update u;
        
        System.runAs(u){
            Account foyerTest = new Account();
            foyerTest.Name='testPanel';
            foyerTest.ACC_ExtId_SIPanel__c='ABC1254158545';
            foyerTest.Numero_de_portable__c = '0123456789';
            insert foyerTest;
            
            Id recordTypeIdPanelMediamatPame =Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_mediamatpame).getRecordTypeId();
            
            List<Referentiel_Panel__c> referentielPanelToInsert = new List<Referentiel_Panel__c>();
            Referentiel_Panel__c refPanMMAT = new Referentiel_Panel__c();
            refPanMMAT.Name = 'MMAT';
            refPanMMAT.Type_de_panel__c = Label.RFP_TypePanel_MMAT;
            referentielPanelToInsert.add(refPanMMAT);
            
            insert referentielPanelToInsert;
            
            Foyer_paneliste__c foyerPan = new Foyer_paneliste__c();
            foyerPan.RecordTypeId = recordTypeIdPanelMediamatPame;
            foyerPan.Name='testMMAT';
            foyerPan.Foyer__c = foyerTest.id;
            foyerPan.Referentiel_Panel__c = refPanMMAT.Id;
            insert foyerPan;
            
            foyerPan.Date_d_installation__c= date.today();
            foyerPan.Statut_Foyer_paneliste__c = Label.PAN_Statut_panel;
                        
            IndividuPanelisteCallout_Mock fakeGetfoyerPaneliteTest = new IndividuPanelisteCallout_Mock(foyerPan.Id);
            
            Test.startTest();
            update foyerPan;
            Test.setMock(HttpCalloutMock.class, fakeGetfoyerPaneliteTest); 
            Test.stopTest();
        }
    }  

}