force-app/main/default/objects/Account/fields/Adresse_e_mail_principale__c.field-meta.xml
<CustomField>
    <fullName>Adresse_e_mail_principale__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Adresse e-mail principale</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_de_smartphone__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_smartphone__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nombre de smartphones</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_de_tablette__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_tablette__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nombre de tablettes</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_pc__c.field-meta.xml
<CustomField>
    <fullName>Nombre_pc__c</fullName>
    <label>Nombre d&apos;ordinateurs</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_smartphone__c.field-meta.xml
<CustomField>
    <fullName>Nombre_smartphone__c</fullName>
    <label>Nombre de smartphones</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_tablette__c.field-meta.xml
<CustomField>
    <fullName>Nombre_tablette__c</fullName>
    <label>Nombre de tablettes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_TV__c.field-meta.xml
<CustomField>
    <fullName>Nombre_TV__c</fullName>
    <label>Nombre de TV actives</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Territoire_de_service__c.field-meta.xml
<CustomField>
    <fullName>Territoire_de_service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territoire de service</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Foyers</relationshipLabel>
    <relationshipName>Foyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Date_de_premiere_collecte_d_audience__c.field-meta.xml
<CustomField>
    <fullName>Date_de_premiere_collecte_d_audience__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de première collecte d&apos;audience</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Produit_commande__c.field-meta.xml
<CustomField>
    <fullName>Produit_commande__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit commandé</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Équipements</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Requete__c.field-meta.xml
<CustomField>
    <fullName>Requete__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requête</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Case.Account.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Case.Type</field>
            <operation>equals</operation>
            <value>Réclamation matériel</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>quipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Utilisateur_principal__c.field-meta.xml
<CustomField>
    <fullName>Utilisateur_principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utilisateur principal</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Cet individu n&apos;existe pas dans la base de données ou ne fait pas partie de ce foyer.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Équipements</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Lien_parente__c.field-meta.xml
<CustomField>
    <fullName>Lien_parente__c</fullName>
    <label>Lien parenté</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Chef de famille</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Conjoint</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Enfant</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Ascendant</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Autre</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer Panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Commandes</relationshipLabel>
    <relationshipName>Commandes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Requete__c.field-meta.xml
<CustomField>
    <fullName>Requete__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requête</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Commandes</relationshipLabel>
    <relationshipName>Commandes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territoire_de_Service__c/Territoire_de_Service__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Territoire de Service</label>
</CustomObject>

force-app/main/default/objects/WorkOrder/fields/Actions__c.field-meta.xml
<CustomField>
    <fullName>Actions__c</fullName>
    <label>Actions</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_de_l_intervention__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>21</fullName>
                <label>Ajout de poste</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Auto désinstallation</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Changement (TV, barre de son ect …)</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Configuration Meters (si boite mail ok)</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Configuration routeur (connexion des equipements au routeur Mediametrie )</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>Configuration routeur (connexion des equipements au routeur Mediametrie ) 2 et +</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Configuration Routeur (Pame)</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Contrôle audience</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Contrôle de connexion</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Contrôle de l&apos;installation</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Contrôle qualité</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Déménagement</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Désinstallation définitive</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Mise à jour équipement</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Modification Abonnement</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Mutation Audimètre</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Nouveau foyer</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Paramétrage Meters 2 à 4</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Paramétrage Meters 5 à 8</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Passage Improviste</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Pb Sonde Tv (Déclaration)</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Réinstallation</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Routeur ne s&apos;allume plus</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Suppression d&apos;un poste</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Vérification de l&apos;initialisation</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Vérification des éléments</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>Visite de courtoisie</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>Streaming Meter</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>Contrôle Streaming Meter</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>Réinstallation Streaming Meter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Le foyer sélectionné n&apos;est pas celui du foyer panéliste</errorMessage>
        <filterItems>
            <field>Foyer_paneliste__c.Foyer__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Interventions</relationshipLabel>
    <relationshipName>Interventions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Nombre_d_ordinateur__c.field-meta.xml
<CustomField>
    <fullName>Nombre_d_ordinateur__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nombre d&apos;ordinateurs</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Nombre_TV__c.field-meta.xml
<CustomField>
    <fullName>Nombre_TV__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nombre TV active</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Tech_RV03__c.field-meta.xml
<CustomField>
    <fullName>Tech_RV03__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tech_RV03</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Type_de_l_intervention__c.field-meta.xml
<CustomField>
    <fullName>Type_de_l_intervention__c</fullName>
    <label>Type d&apos;intervention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_d_intervention</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Type_d_intervention.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Installation</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Désinstallation</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Dépannage/Support</label>
    </customValue>
    <customValue>
        <fullName>Intervention</fullName>
        <isActive>false</isActive>
        <label>Intervention</label>
    </customValue>
    <customValue>
        <fullName>Visite de courtoisie</fullName>
        <isActive>false</isActive>
        <label>Visite de courtoisie</label>
    </customValue>
    <masterLabel>Type d&apos;intervention</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP01_Requete.cls
/*
* @author: Joyce Saidy
* @date: 02/09/2020
* @ Description Class that create workOrder on case creation with description "Installation nouveau foyer"
* @TestClass: AP01_Requete_Test
* @Coverage: 95 %
* History
* <Date of modification>   <Author>    <Description of modification>
*       27/09/2021               ER         Corrections faites pour renseigner les champs ajoutés avec les valeurs de ces champs sur le foyer (retour ticket MEDIAMETRIE-261)
* 		28/09/2021   		Claire VEHRLE  		  Clôture des requêtes de type Remplacement de matériel dès la collecte d'audience du nouvel équipement (de remplacement)
*/
public class AP01_Requete {
    
     public static void NouvelleIntervention(List<Case> ListNewCases) {
        List<workOrder> listWOToInsert = new List<workOrder>();
         //Added by ER for MEDIAMETRIE-261 - Start
        List<Case> listCaseDetails = [SELECT Id, AccountId,Foyer_paneliste__c,account.Nombre_TV__c,account.Nombre_pc__c,Account.Territoire_de_service__c, account.Nombre_smartphone__c , account.Nombre_tablette__c 
                                        FROM Case
                                        Where Id in : ListNewCases]; 
        //Added by ER for MEDIAMETRIE-261 - End
        for(Case cs:listCaseDetails ) //Changed by ER for MEDIAMETRIE-261
        {
            workOrder WO = new workOrder();
            WO.AccountId=cs.AccountId;
            WO.CaseId=cs.id;
            WO.ServiceTerritoryId=cs.Account.Territoire_de_service__c;
            WO.Foyer_paneliste__c=cs.Foyer_paneliste__c;
            WO.Type_de_l_intervention__c=Label.WOR_Type_d_intervention_Installation;
            WO.Actions__c=Label.WOR_Sous_type_d_intervention_Nouveau_foyer;  
            WO.Tech_RV03__c=true;
            
            //Added by ER for MEDIAMETRIE-261 - Start
            WO.Nombre_TV__c = Integer.ValueOf(cs.Account.Nombre_TV__c); 
            WO.Nombre_d_ordinateur__c = cs.Account.Nombre_pc__c;
            WO.Nombre_de_smartphone__c = cs.Account.Nombre_smartphone__c;
            WO.Nombre_de_tablette__c = cs .Account.Nombre_tablette__c;
            //Added by ER for MEDIAMETRIE-261 - End
            
            listWOToInsert.add(WO);
        }
        if(listWOToInsert!=null && listWOToInsert.size()>0)
        {
            try{ 
                database.insert(listWOToInsert);
            }Catch(exception ex){
                system.debug('Insert WO Nouveau Foyer Exception Error: '+ex.getmessage());
            }
        }
    }
    
    public static void associerCaseContact(List<Case> ListNewCases){
       
        list<case> listetoupdate = new list<case>();
        list<contact> listeCont = new list<contact>();
        list<account> listeFoy = new list<account>();
        list<String> Casemail= new list<string>();
        /*List<Case> listCaseDetails = [SELECT Id, AccountId, contactid,SuppliedEmail
                                        FROM Case
                                        Where Id in : ListNewCases];*/
        for (case cs:ListNewCases){
            if(!String.isBlank(cs.SuppliedEmail))
            Casemail.add(cs.SuppliedEmail);
        }
        if (Casemail.size()>0){
            listeCont = [select id, email,Lien_parente__c from contact where email in:CaseMail];
        }
            
        System.debug('size'+listeCont.size());
        listeFoy   	= [select id, Adresse_e_mail_principale__c from account where Adresse_e_mail_principale__c in:CaseMail];
        
        for (case cs:ListNewCases){
            list<contact> listeConCase = new list<contact>();
            list<account> listeFoyCase = new list<account>();
            for (contact con:listeCont ){
                if (cs.SuppliedEmail==con.Email){
                    listeConCase.add(con);
                }
            }
            for (account acc:listeFoy){
                if (cs.SuppliedEmail==acc.Adresse_e_mail_principale__c){
                    listeFoyCase.add(acc);
                }
            }
          
          //mapcontact.putall(listeConCase);
          //mapFoyer.putall(listeFoyCase);
            if ( listeConCase.size()>1){
                for (contact c:listeConCase){
                    if(c.Lien_parente__c=='1'){
                        cs.ContactId=c.id;
                        system.debug('test youssef');
                        listetoupdate.add(cs);
                       break;
                    }
                }
            }
            else if (listeFoyCase.size()==0){
                if (listeFoyCase.size()>0){
                    for (account foy:listeFoyCase){
                        	cs.AccountId=foy.id;
                        	system.debug('test2');
                        	listetoupdate.add(cs);
                      		break;
                	}	
                }
            }
            
        }
         system.debug('siz'+listetoupdate.size());
        update(listetoupdate);
    }
    
    public static void clotureRequete() {
        
        List<Id> requeteIdToUpdate = new List<Id>();
        List <Case> requeteToUpdate = new List<Case>();
        Boolean pasEquipement = true;
        
        Map<Id, Boolean> orderProductMap = new Map<Id, Boolean>();
        
        Map<String, OrderItem> produitCommandeList = new Map<String, OrderItem>([SELECT Id, Order.Requete__c, OrderId, 
                                                                                 (SELECT Id, Date_de_premiere_collecte_d_audience__c FROM Equipements__r)
                                                                                 FROM OrderItem WHERE Order.Requete__r.Type = :Label.CAS_Type_Anomalie 
                                                                                 AND Order.Requete__r.Status != :Label.CAS_Statut_Cloture]);
     
        System.debug('produitCommandeList.size(): ' + produitCommandeList.size());
        
        
        for (OrderItem produitCommande :produitCommandeList.values()) {     
            if (!produitCommande.Equipements__r.isEmpty() && produitCommande.Equipements__r.size() != 0) {      
            	requeteIdToUpdate.add(produitCommande.Order.Requete__c);     
                if(orderProductMap.containsKey(produitCommande.OrderId)) {
                    if (produitCommande.Equipements__r[0].Date_de_premiere_collecte_d_audience__c == null) {
                        orderProductMap.put(produitCommande.OrderId, false);
                    }
                }
                else {
                    if (produitCommande.Equipements__r[0].Date_de_premiere_collecte_d_audience__c == null) {
                        orderProductMap.put(produitCommande.OrderId, false);
                    }
                    else {
                        orderProductMap.put(produitCommande.OrderId, true);
                    }
                }
                pasEquipement = false;
            }
        }
        
        if (!pasEquipement) {
            requeteToUpdate = [SELECT Id, Subject, Status,(SELECT Id FROM Commandes__r) FROM Case WHERE Id IN :requeteIdToUpdate];
            
            for (Case requete:requeteToUpdate) {
                Boolean allOrderOk = true;    
                for (Order commande: requete.Commandes__r) {
                    try {
                        if(!orderProductMap.get(commande.Id)) {
                            allOrderOk = false;
                        }
                        if(allOrderOk) {
                            requete.Status = Label.CAS_Statut_Cloture;
                        }
                    } catch (exception ex) {
                        system.debug('Error: ' + ex.getmessage() + '\n Originine possible: Les produits commandés ne sont ratachés à aucun équipement de mesure');
                    }
                } 
                
                
            }
            
            update requeteToUpdate;
        }
       
    }
   
}