force-app/main/default/objects/Account/fields/Adresse_e_mail_principale__c.field-meta.xml
<CustomField>
    <fullName>Adresse_e_mail_principale__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Adresse e-mail principale</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_de_portable__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_portable__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Numéro de téléphone portable</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sous_type_d_intervention__c.field-meta.xml
<CustomField>
    <fullName>Sous_type_d_intervention__c</fullName>
    <label>Sous-type d&apos;intervention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Nouveau foyer</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Ajout Equipement</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Suppression d&apos;un poste</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Définitive</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Déménagement</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Réinstallation</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Mutation Audimètre</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Vérification des éléments</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Contrôle audience</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Recensement</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Passage Improviste</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>Visite de courtoisie</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Changement</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Contrôle de connexion</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Contrôle de l&apos;installation</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Vérification de l&apos;initialisation</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>14</fullName>
                <isActive>false</isActive>
                <label>14</label>
            </value>
            <value>
                <fullName>24</fullName>
                <isActive>false</isActive>
                <label>24</label>
            </value>
            <value>
                <fullName>25</fullName>
                <isActive>false</isActive>
                <label>25</label>
            </value>
            <value>
                <fullName>26</fullName>
                <isActive>false</isActive>
                <label>26</label>
            </value>
            <value>
                <fullName>27</fullName>
                <isActive>false</isActive>
                <label>27</label>
            </value>
            <value>
                <fullName>28</fullName>
                <isActive>false</isActive>
                <label>28</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>30</fullName>
                <isActive>false</isActive>
                <label>30</label>
            </value>
            <value>
                <fullName>31</fullName>
                <isActive>false</isActive>
                <label>31</label>
            </value>
            <value>
                <fullName>32</fullName>
                <isActive>false</isActive>
                <label>32</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Sous_type_d_intervention__c.field-meta.xml
<CustomField>
    <fullName>Sous_type_d_intervention__c</fullName>
    <description>OBSOLETE A NE PLUS UTILISER</description>
    <formula>IF( TEXT(Intervention__r.Sous_type_d_intervention__c) == &apos;1&apos;, $Label.WOR_Sous_type_d_intervention_Nouveau_foyer_etiquette,
IF( TEXT(Intervention__r.Sous_type_d_intervention__c) == &apos;3&apos;, $Label.WOR_Sous_type_d_intervention_Suppression_d_un_poste_etiquette,
IF( TEXT(Intervention__r.Sous_type_d_intervention__c) == &apos;4&apos;, $Label.WOR_Sous_type_d_intervention_Changement_etiquette,
IF( TEXT(Intervention__r.Sous_type_d_intervention__c) == &apos;5&apos;, $Label.WOR_Sous_type_d_intervention_Controle_de_l_installation_etiquette,
IF( TEXT(Intervention__r.Sous_type_d_intervention__c) == &apos;6&apos;, $Label.WOR_Sous_type_d_intervention_Demenagement_etiquette,
IF( TEXT(Intervention__r.Sous_type_d_intervention__c) == &apos;7&apos;, $Label.WOR_Sous_type_d_intervention_Reinstallation_etiquette,
IF( TEXT(Intervention__r.Sous_type_d_intervention__c) == &apos;8&apos;, $Label.WOR_Sous_type_d_intervention_Definitive_etiquette,
IF( TEXT(Intervention__r.Sous_type_d_intervention__c) == &apos;10&apos;, $Label.WOR_Sous_type_d_intervention_Verification_Initialisation_etiquette,
IF( TEXT(Intervention__r.Sous_type_d_intervention__c) == &apos;11&apos;, $Label.WOR_Sous_type_d_intervention_Verification_des_elements_etiquette,
IF( TEXT(Intervention__r.Sous_type_d_intervention__c) == &apos;12&apos;, $Label.WOR_Sous_type_d_intervention_Controle_de_connexion_etiquette,
IF( TEXT(Intervention__r.Sous_type_d_intervention__c) == &apos;16&apos;, $Label.WOR_Sous_type_d_intervention_Controle_d_audience_etiquette,
IF( TEXT(Intervention__r.Sous_type_d_intervention__c) == &apos;18&apos;, $Label.WOR_Sous_type_d_intervention_Recensement_etiquette,
IF( TEXT(Intervention__r.Sous_type_d_intervention__c) == &apos;19&apos;, $Label.WOR_Sous_type_d_intervention_Mutation_audimetre_etiquette,
IF( TEXT(Intervention__r.Sous_type_d_intervention__c) == &apos;21&apos;, $Label.WOR_Sous_type_d_intervention_Ajout_equipement_etiquette,
IF( TEXT(Intervention__r.Sous_type_d_intervention__c) == &apos;22&apos;, $Label.WOR_Sous_type_d_intervention_Visite_de_courtoisie_etiquette,
IF( TEXT(Intervention__r.Sous_type_d_intervention__c) == &apos;23&apos;, $Label.WOR_Sous_type_d_intervention_Passage_improviste_etiquette, &apos;&apos;
))))))))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sous-type d&apos;intervention</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Batch008_SMSviaNP6.cls
/*
* @author: Joyce Saidy/Khaled Hammoudeh
* @date: 05/10/2020
* @ Description Batch pour la récuperation des rendez-vous planifié à J-1 de la début planifiée 
* @TestClass: Batch008_SMSviaNP6_Test
* @Coverage: 77 %
* History
* <Date of modification>   <Author>    <Description of modification>
*/ 
global class Batch008_SMSviaNP6 implements Database.Batchable<sObject>,    Database.AllowsCallouts, Database.Stateful{
    //Added for email notification - START
    global String errorTxt = '';
    global Boolean containsErrors = false;
    //Added for email notification - END
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        // ticket 51 : staut dispatché
        String statutRDVPlanifie = System.Label.RDV_Statut_Dispatche;
        
        String query = 'Select id,Sous_type_d_intervention__c, SchedStartTime, Contact.Email, Contact.MobilePhone,Account.Adresse_e_mail_principale__c,account.Numero_de_portable__c from ' +
            ' serviceAppointment where status = :statutRDVPlanifie AND SchedStartTime =TOMORROW and Sous_type_d_intervention__c !=\'Passage Improviste\' ';
        
        // query = 'Select id,Sous_type_d_intervention__c, SchedStartTime, Contact.Email, Contact.MobilePhone,Account.Adresse_e_mail_principale__c,account.Numero_de_portable__c from ' +
          //  'serviceAppointment where id =\'08p7T000001XAQ0QAO\'';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<serviceAppointment> scope){
        List <serviceAppointment> listRendezVous = new  List <serviceAppointment>();
        
        if(scope.size() > 0)
        {
            
           
               try{
                	AP01_SendSMS.sendSMSViaNP6(scope);
                system.debug('ttt'+scope);
                }
                catch(exception ex){
                system.debug(' SMS Sent Failed:'+ex.getmessage());
               //added for notification
                errorTxt += 'Erreur durant l\'envoie du sms : ' + ex.getMessage() + '\n';
                containsErrors = true;
                }
                
            
        }
        
    }
    
    global void finish(Database.BatchableContext bc){
        //Added for notifications - START
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        List<String> toMailAddress = System.Label.BatchNotif_B008_ToAddress.split(';');
        
        mail.setToAddresses(toMailAddress);
        mail.setSenderDisplayName(System.Label.BatchNotif_B008_SenderName);
        mail.setSubject(System.Label.BatchNotif_B008_Subject+'-'+date.today().format());
        
        String emailBody = 'L\'exécution du batch Batch008_SMSviaNP6 s\'est terminée en Prep2.\n';
        if(containsErrors) {
            emailBody += 'Les erreurs suivantes ont été rencontrées :\n\n'+errorTxt;
           
        } else {
            emailBody += 'Aucune erreur n\'a été relevée.';
        }
        mail.setPlainTextBody(emailBody);
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        //Added for notifications - END
    }
}