force-app/main/default/objects/Account/fields/Avaya_UUI_tech__c.field-meta.xml
<CustomField>
    <fullName>Avaya_UUI_tech__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Avaya UUI tech</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Avaya_UUI_tech__c.field-meta.xml
<CustomField>
    <fullName>Avaya_UUI_tech__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Avaya_UUI_tech</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/qualificationCase__c.field-meta.xml
<CustomField>
    <fullName>qualificationCase__c</fullName>
    <label>Qualification de l&apos;appel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPRO</fullName>
                <label>Réalisé</label>
            </value>
            <value>
                <fullName>CBUS</fullName>
                <label>Occupé</label>
            </value>
            <value>
                <fullName>CFAI</fullName>
                <label>Erreur technique</label>
            </value>
            <value>
                <fullName>CINX</fullName>
                <label>Abandonné</label>
            </value>
            <value>
                <fullName>TWRG</fullName>
                <label>Composer Téléphone 2</label>
            </value>
            <value>
                <fullName>TANO</fullName>
                <label>Rejeté</label>
            </value>
            <value>
                <fullName>TANM</fullName>
                <label>Répondeur</label>
            </value>
            <value>
                <fullName>TMOD</fullName>
                <label>Fax/Modem</label>
            </value>
            <value>
                <fullName>CNDO</fullName>
                <label>NJPC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_validation_rules__c.field-meta.xml
<CustomField>
    <fullName>Bypass_validation_rules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass validation rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHandler_Test.cls
/**
* @description       : 
* @author            : Anes BOUZOUINA
* @group             : 
* @last modified on  : 11-17-2022
* @last modified by  : Anes BOUZOUINA
**/
@istest
public with sharing class CaseTriggerHandler_Test {
    @istest

    public static void CaseTriggerHandler() {
        User adminUser =[SELECT Id,UserRoleId FROM User WHERE (Profile.Name='System Administrator' OR Profile.Name='Administrateur Système') And IsActive=true Limit 1];
        adminUser.Bypass_validation_rules__c=true;
        update adminUser;
        
         System.runAs(adminUser){
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('QualifyTryRessource');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        // Associate the callout with a mock response
        Test.setMock(HttpCalloutMock.class, mock);
        
        Account acc= Test_Utils.createFoyer();
        insert acc; 
        case req = Test_Utils.createCase(acc.Id);
        req.Avaya_UUI_tech__c='131|20220906175345989D10D6';
        insert req;
        test.startTest();
        req.qualificationCase__c='CPRO';
        update req;
        test.stopTest();
    }
}
}