force-app/main/default/objects/Account/fields/Commentaire__c.field-meta.xml
<CustomField>
    <fullName>Commentaire__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Commentaire</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_d_installation__c.field-meta.xml
<CustomField>
    <fullName>Date_d_installation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;installation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Freeze__c.field-meta.xml
<CustomField>
    <fullName>Freeze__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Cette case à cocher permet de bloquer l&apos;attribution de points du foyer</description>
    <label>Freeze</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Statut_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Statut_du_foyer__c</fullName>
    <label>Statut du foyer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Recruté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Installé</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Equipé</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Integré</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Désinstallé</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Chute définitive</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chute temporaire</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fidelisation__c/Fidelisation__c.object-meta.xml
<CustomObject>
    <label>Fidélisation</label>
    <nameField>
        <displayFormat>FID-{0000}</displayFormat>
        <label>Nom de Fidélisation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fidélisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fidelisation__c/fields/Commentaire__c.field-meta.xml
<CustomField>
    <fullName>Commentaire__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Commentaire</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fid_lisations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Motif_de_credit__c.field-meta.xml
<CustomField>
    <fullName>Motif_de_credit__c</fullName>
    <label>Motif de crédit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_de_mouvement__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Bonus Installation</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Bonus mensuel TV</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Recensement</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Noël</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Vacances été</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Anniv entrée Panel</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Bonus mensuel web</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Quiz Règle OR</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Smile Me</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Defreeze</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Rentrée</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Auto désinstallation</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Anniv panéliste</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Pilote</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Points mensuels AIP</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Badge Bronze jeune</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Badge Argent jeune</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Badge Or jeune</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Badge Platine jeune</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Badge Bronze 25+</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Badge Argent 25+</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>Badge Or 25+</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Badge Platine 25+</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Parrainage Parrain</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Parrainage Filleul</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Dédommagement</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Autre crédit</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Crédit Energie</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Noce MM</label>
            </value>
            <value>
                <fullName>Commande</fullName>
                <isActive>false</isActive>
                <label>Commande</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Points_credites__c.field-meta.xml
<CustomField>
    <fullName>Points_credites__c</fullName>
    <label>Points Crédités</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Type_de_mouvement__c.field-meta.xml
<CustomField>
    <fullName>Type_de_mouvement__c</fullName>
    <label>Type de mouvement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Commande</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Crédit automatique</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Crédit exceptionnel</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Crédit manuel</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Débit automatique</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Débit des points fin de contrat</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Débit exceptionnel</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Débit manuel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fidelisation__c/recordTypes/Credit.recordType-meta.xml
<RecordType>
    <fullName>Credit</fullName>
    <active>true</active>
    <description>Points de fidélisation qu&apos;on ajoute sur le compte</description>
    <label>Crédit</label>
</RecordType>

force-app/main/default/objects/Statut_du_foyer__c/Statut_du_foyer__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Ensemble clé-valeur pour le champ Statut du foyer de l&apos;objet Foyer</description>
    <label>Statut du foyer</label>
</CustomObject>

force-app/main/default/classes/Batch005_CreditAutomatique1foisparAn.cls
/*
* @author: Joyce Saidy 
* @date: 24/09/2020
* @ Description Batch pour le credit automatique des fidelisation 1 fois par An le 1er septembre
* @TestClass: Batch004_CreditAutomatique_Test
* @Coverage: 87 %
* History
* <Date of modification>   <Author>    <Description of modification>
    10/08/2021               ER         Corrections faites pour pouvoir lancer le batch avec les foyer équipés seulement (ticket MEDIAMETRIE-261)
*/ 
global class Batch005_CreditAutomatique1foisparAn implements Database.Batchable<sObject>, Database.Stateful {
    
    //Added for email notification - START
    global String errorTxt = '';
    global Boolean containsErrors = false;
    //Added for email notification - END
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        Id recordTypeIdNonEquipe = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(label.Acc_TypeD_Enregistrement_NonEquipe).getRecordTypeId(); //Added by ER for MEDIAMETRIE-261
        String query = 'Select id,Freeze__c ,Date_d_installation__c from account where  RecordTypeId !=: recordTypeIdNonEquipe AND Date_d_installation__c!=null  and (Statut_du_foyer__c=\'1\' or Statut_du_foyer__c=\'2\' or Statut_du_foyer__c=\'3\')' ; //Changed by ER for MEDIAMETRIE-261
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext bc, List<account> scope){
        Id recordTypeIdFIDcredit =Schema.SObjectType.Fidelisation__c.getRecordTypeInfosByName().get(label.FID_Type_d_enregistrement_Credit).getRecordTypeId();
        list<Fidelisation__c> listFIDtoInsert = new  list<Fidelisation__c>();
        for(Account Acc :scope)
        {
            if (acc.Freeze__c==false){
            listFIDtoInsert.add(NewFID(acc.id,recordTypeIdFIDcredit,Label.FID_TypeMouvement_CreditExceptionnel,Label.FID_Motifcredit_Rentree,integer.valueof(Label.FID_NbrPoints_50)));
       
            }
        // YH 340
        else {
            system.debug('frrez'+acc.id);
            listFIDtoInsert.add(NewFID_freez(acc.id,recordTypeIdFIDcredit,Label.FID_TypeMouvement_CreditExceptionnel,Label.FID_Motifcredit_Rentree,integer.valueof(Label.FID_NbrPoints_0)));

        	}
        }
         system.debug('ttttt'+listFIDtoInsert.size());
        if(listFIDtoInsert!=null && listFIDtoInsert.size()>0)
        {
             try{ 
                database.insert(listFIDtoInsert, false);
                 system.debug('aaaa'+listFIDtoInsert);
            }Catch(exception ex){
                system.debug('Insert FID Exception Error:'+ex.getmessage());
                //added for notification
                errorTxt += 'Erreur durant la création des requêtes : ' + ex.getMessage() + '\n';
                containsErrors = true;
            }  
        }
    }
    global static Fidelisation__c NewFID(Id AccounId,Id recordTypeIdFIDcredit,String TypeMouvement,String MotifCredit,Integer NbrsPoints)
    {
        Fidelisation__c FID = new Fidelisation__c();
        if(TypeMouvement!=null && MotifCredit!=null && NbrsPoints!=null)
        {
            FID.Type_de_mouvement__c=TypeMouvement;
            FID.Motif_de_credit__c=MotifCredit;
            FID.Points_credites__c=NbrsPoints;
            FID.RecordTypeId = recordTypeIdFIDcredit;
            FID.Foyer__c=AccounId;
        }
        return FID;
    }
    // YH 340
           Global static Fidelisation__c NewFID_freez(ID AccounId,Id recordTypeIdFIDcredit, String TypeMouvement,String MotifCredit,Integer NbrsPoints)
    {
        Fidelisation__c FID = new Fidelisation__c();
        if(TypeMouvement!=null && MotifCredit!=null && NbrsPoints!=null)
        {
            FID.Type_de_mouvement__c=TypeMouvement;
            FID.Motif_de_credit__c=MotifCredit;
            FID.Points_credites__c=NbrsPoints;
            FID.Commentaire__c='Aucun bonus annuel car le foyer est freeze';
            FID.RecordTypeId = recordTypeIdFIDcredit;
            FID.Foyer__c=AccounId;
            system.debug('fiiid');
        }
        return FID;
        
    }
    
    global void finish(Database.BatchableContext bc){
        
        
        //Added for notifications - START
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        List<String> toMailAddress = System.Label.BatchNotif_B005_ToAddress.split(';');
        
        mail.setToAddresses(toMailAddress);
        mail.setSenderDisplayName(System.Label.BatchNotif_B005_SenderName);
        mail.setSubject(System.Label.BatchNotif_B005_Subject+'-'+date.today().format());
        
        String emailBody = 'L\'exécution du batch Batch005_CreditAutomatique1foisparAn s\'est terminée.\n';
        if(containsErrors) {
            emailBody += 'Les erreurs suivantes ont été rencontrées :\n\n';
            emailBody += errorTxt;
        } else {
            emailBody += 'Aucune erreur n\'a été relevée.';
        }
        mail.setPlainTextBody(emailBody);
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        //Added for notifications - END        
    }
   
}