force-app/main/default/objects/Account/fields/Commentaire__c.field-meta.xml
<CustomField>
    <fullName>Commentaire__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Commentaire</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_d_anonymisation__c.field-meta.xml
<CustomField>
    <fullName>Date_d_anonymisation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;anonymisation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contact_sur_place__c.field-meta.xml
<CustomField>
    <fullName>Contact_sur_place__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact principal</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Cet individu est un invité ou ne fait pas partie de ce foyer ou n&apos;existe pas.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Type__c</field>
            <operation>notEqual</operation>
            <value>Invité</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_principal__c</field>
            <operation>equals</operation>
            <value>true</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Contact sur place)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_d_anonymisation__c.field-meta.xml
<CustomField>
    <fullName>Date_d_anonymisation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;anonymisation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Telephone_fixe__c.field-meta.xml
<CustomField>
    <fullName>Telephone_fixe__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Téléphone Fixe</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/A_anonymiser__c.field-meta.xml
<CustomField>
    <fullName>A_anonymiser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>A anonymiser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Autre_activite__c.field-meta.xml
<CustomField>
    <fullName>Autre_activite__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Autre activité</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Domaine_d_activite__c.field-meta.xml
<CustomField>
    <fullName>Domaine_d_activite__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Domaine d&apos;activité</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Id_google__c.field-meta.xml
<CustomField>
    <fullName>Id_google__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>ID Google</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Lien_meter__c.field-meta.xml
<CustomField>
    <fullName>Lien_meter__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Lien meter</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Profession__c.field-meta.xml
<CustomField>
    <fullName>Profession__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Profession</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Statut_individu__c.field-meta.xml
<CustomField>
    <fullName>Statut_individu__c</fullName>
    <label>Statut de l&apos;individu</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Présent</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Vacancier</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Absent</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Inactif</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Ne fait plus partie du panel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipement_du_foyer_de_l_individu__c/Equipement_du_foyer_de_l_individu__c.object-meta.xml
<CustomObject>
    <label>Équipement du foyer de l&apos;individu</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de É</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Équipements du foyer des individus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipement_du_foyer_de_l_individu__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Équipements du foyer des individus</relationshipLabel>
    <relationshipName>Equipements_du_foyer_des_individus</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Equipement_du_foyer_de_l_individu__c/fields/Equipement_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Equipement_du_foyer__c</fullName>
    <label>Équipement du foyer</label>
    <referenceTo>Equipements_du_foyer__c</referenceTo>
    <relationshipLabel>Équipements du foyer des individus</relationshipLabel>
    <relationshipName>Equipements_du_foyer_des_individus</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/Equipements_du_foyer__c.object-meta.xml
<CustomObject>
    <label>Equipement du foyer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;équipement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipements du foyer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Commentaire__c.field-meta.xml
<CustomField>
    <fullName>Commentaire__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Commentaire</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Equipements du foyer</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Mode_de_communication__c.field-meta.xml
<CustomField>
    <fullName>Mode_de_communication__c</fullName>
    <label>Mode de communication</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
                <label>GSM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>WIFI</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Câble Ethernet</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Boitier CPL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Poste_TV__c.field-meta.xml
<CustomField>
    <fullName>Poste_TV__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Poste TV</label>
    <referenceTo>Equipements_du_foyer__c</referenceTo>
    <relationshipLabel>Périphériques</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Utilisateur_principal__c.field-meta.xml
<CustomField>
    <fullName>Utilisateur_principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utilisateur principal</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Ce contact n&apos;appartient au foyer de l&apos;équipement.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Foyer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Equipements du foyer</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/A_anonymiser__c.field-meta.xml
<CustomField>
    <fullName>A_anonymiser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>A anonymiser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/ID_Google__c.field-meta.xml
<CustomField>
    <fullName>ID_Google__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ID Google</label>
    <length>233</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Lien_meter__c.field-meta.xml
<CustomField>
    <fullName>Lien_meter__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Lien meter</label>
    <length>233</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Batch019_CompositionFoyerAnonymisation.cls
/*
* @date: 02/02/2022
* @ Description : Anonymiser les foyer lorsque la case à cocher "Anonymisation confirmée" a été cochée
* @Auteur : Téoman Sertçelik
* @Scheduler : SCHD019_CompositionFoyerAnonymisation
* @TestClass: Batch019_CompositionFoyerAnonymisation
* @Coverage: 100 %
History
* <Date of modification> 		<Author> 			<Description of modification>
*/

public with sharing class Batch019_CompositionFoyerAnonymisation implements Database.Batchable<sObject>, Database.AllowsCallouts {

    public Database.QueryLocator start(Database.BatchableContext bC)
    {
        boolean aAnnonymiser = true;

        String query =
         'SELECT Id, Account.Id, FirstName, LastName, Birthdate, Email, Phone, HomePhone, Profession__c, ' +
         'Domaine_d_activite__c, Autre_activite__c, Date_d_anonymisation__c, A_anonymiser__c,  ' +
              /* '(SELECT Id, Date_d_anonymisation__c, Commentaire__c ' + 
                 'FROM Equipements_du_foyer__r ' +  
                 'WHERE Date_d_anonymisation__c = null), ' + */
                '(SELECT Id, Telephone_fixe__c, SuppliedPhone, ContactPhone, SuppliedEmail, SuppliedName, SuppliedCompany, Description, Date_d_anonymisation__c ' + 
                 'FROM Cases__r ' + 
                 'WHERE Date_d_anonymisation__c = null), ' +
                '(SELECT Id, Date_d_anonymisation__c ' + 
                 'FROM Paneliste__r ' + 
                 'WHERE Date_d_anonymisation__c = null) ' + 
         'FROM Contact ' +
         'WHERE Date_d_anonymisation__c = null ' + 
         'AND A_anonymiser__c = : aAnnonymiser';

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bC, List<Contact> listContactInit)
    {
        final Date DATETOPASSCONTACT = Date.newInstance(1900, 01, 01);
        Date dateAnonymized = Date.today();
        List<Contact> listContactToUpdate = new List<Contact>();
        List<Equipements_du_foyer__c> listEquipFoyerToUpdate = new List<Equipements_du_foyer__c>();
        List<Equipement_du_foyer_de_l_individu__c> listEquipFoyerIndToUpdate = new List<Equipement_du_foyer_de_l_individu__c>();
        List<Case> listCaseToUpdate = new List<Case>(); 
        List<Individu_Paneliste__c> listIndividuPanToUpdate = new List<Individu_Paneliste__c>();

        //Téoman Sertçelik : added to take in consideration many to many relationship beetwen contact and  Equipements_du_foyer__c
        List<Equipement_du_foyer_de_l_individu__c> listEquipementFoyerInd = [SELECT Id, Composition_du_foyer__c,  Equipement_du_foyer__c//, Date_d_anonymisation__c
                                                                             FROM Equipement_du_foyer_de_l_individu__c
                                                                             WHERE Composition_du_foyer__c IN : listContactInit
                                                                             /*AND Date_d_anonymisation__c = null*/];

     
        for(Contact compFoyer : listContactInit ) {
          		//if(compFoyer.Statut_individu__c)
                //anonymization
                //***contact fields***
                compFoyer.FirstName = 'FirstName' + compFoyer.Account.Id;
                compFoyer.LastName = 'LastName' +  compFoyer.Account.Id;
                compFoyer.Birthdate = DATETOPASSCONTACT;
                compFoyer.Email = '';
                compFoyer.Phone = '';
                compFoyer.HomePhone = '';
                compFoyer.Profession__c = '';
                compFoyer.Domaine_d_activite__c = '';
                compFoyer.Autre_activite__c = '';
                //populate date d'anonymisation
                compFoyer.Date_d_anonymisation__c = dateAnonymized; 
                listContactToUpdate.add(compFoyer);

                //Téoman Sertçelik : added to take in consideration many to many relationship beetwen contact and  Equipements_du_foyer__c
                for(Equipement_du_foyer_de_l_individu__c eqmtFoyerInd : listEquipementFoyerInd) {

                   /*  eqmtFoyerInd.Date_d_anonymisation__c = dateAnonymized;
                    listEquipFoyerIndToUpdate.add(eqmtFoyerInd); */

                  //  if(eqmtFoyerInd.Date_d_anonymisation__c != null) {

                        Equipements_du_foyer__c equipementFoyerToAnonymize = new Equipements_du_foyer__c();

                        equipementFoyerToAnonymize.Id = eqmtFoyerInd.Equipement_du_foyer__c;
                        equipementFoyerToAnonymize.Date_d_anonymisation__c = dateAnonymized;
                        equipementFoyerToAnonymize.Commentaire__c = '';

                        listEquipFoyerToUpdate.add(equipementFoyerToAnonymize);
                   // }
                }
               // for(Equipements_du_foyer__c equipFoyer : compFoyer.Equipements_du_foyer__r){
                 //   equipFoyer.Commentaire__c = '';
                    /*  equipFoyer.Mode_de_communication__c = null;
                    equipFoyer.Modele_liste_limitee__c = null;
                    equipFoyer.Mod_le_de_console_de_jeux__c = null;
                    equipFoyer.Mod_le_de_tablette__c = null;
                    equipFoyer.Modele_de_telephone__c = null;
                    equipFoyer.Mod_le_magn_toscope__c = null; */
                    //populate date d'anonymisation
                   // equipFoyer.Date_d_anonymisation__c = dateAnonymized;
                //    listEquipFoyerToUpdate.add(equipFoyer);
                //}
                for(Case cs : compFoyer.Cases__r){
                    //anonymization
                    cs.Telephone_fixe__c = '';
                    cs.SuppliedPhone = '';
                    //cs.ContactPhone = ''; //field is not writeable
                    cs.SuppliedEmail = '';
                    cs.SuppliedCompany = ''; 
                    cs.SuppliedName = '';
                    cs.Description = '';
                    //populate date d'anonymisation
                    cs.Date_d_anonymisation__c = dateAnonymized;
                    listCaseToUpdate.add(cs);
                }
                for(Individu_Paneliste__c indPan : compFoyer.Paneliste__r) {
                    //LA250123 handeled by condition in batch 020 line 141 / on ne le prend plus en compte sur le bacth 020
                    /*if(compFoyer.Paneliste__r.size()>1)
                    {*/
                        //anonymization
                    //***individu paneliste fields***
                    //TODO : fields to anonymize to specify
                    //populate date d'anonymisation
                    indPan.Date_d_anonymisation__c = dateAnonymized;
                    //LA add fields ton anonymize
                    indPan.Name ='';
                    indPan.ID_Google__c ='';
                    indPan.Lien_meter__c = '';
                    listIndividuPanToUpdate.add(indPan);
                        
                    //}
                    
                    
                    
                }
            
        }

        if(listContactToUpdate.size() > 0)
        {
            update listContactToUpdate;
        }
        if(listEquipFoyerToUpdate.size() > 0)
        {
            update listEquipFoyerToUpdate;
        }
        if (listCaseToUpdate.size() > 0)
        {
            update listCaseToUpdate;
        }
        if (listIndividuPanToUpdate.size() > 0)
        {
            update listIndividuPanToUpdate;
        }
       /*  if(listEquipFoyerIndToUpdate.size()>0) 
        {
            update listEquipFoyerIndToUpdate;
        } */
    }

    public void finish(Database.BatchableContext bC){
        system.debug('Batch019_CompositionFoyerAnonymisation finished');
    }
}