force-app/main/default/objects/Account/fields/Contact_principal__c.field-meta.xml
<CustomField>
    <fullName>Contact_principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact principal</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Cet individu (Contact Principal) n&apos;existe pas ou n&apos;est pas rattaché à ce foyer.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Foyers (Contact principal)</relationshipLabel>
    <relationshipName>Foyers_en_tant_que_contact_principal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_de_reception_de_la_convention__c.field-meta.xml
<CustomField>
    <fullName>Date_de_reception_de_la_convention__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de réception de la convention</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_principal__c.field-meta.xml
<CustomField>
    <fullName>Contact_principal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contact Principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Lettre__c.field-meta.xml
<CustomField>
    <fullName>Lettre__c</fullName>
    <label>Lettre</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Lien_parente__c.field-meta.xml
<CustomField>
    <fullName>Lien_parente__c</fullName>
    <label>Lien parenté</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Chef de famille</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Conjoint</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Enfant</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Ascendant</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Autre</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Signature_convention_individuelle_meter__c.field-meta.xml
<CustomField>
    <fullName>Signature_convention_individuelle_meter__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Signature convention individuelle Meter</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Membre</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Invité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Non panéliste</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/PaME.recordType-meta.xml
<RecordType>
    <fullName>PaME</fullName>
    <active>true</active>
    <label>PaME</label>
</RecordType>

force-app/main/default/objects/Convention__c/Convention__c.object-meta.xml
<CustomObject>
    <label>Convention</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de Convention</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conventions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Convention__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Conventions</relationshipLabel>
    <relationshipName>Conventions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convention__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Conventions</relationshipLabel>
    <relationshipName>Conventions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convention__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Conventions</relationshipLabel>
    <relationshipName>Conventions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convention__c/fields/Individu_Paneliste__c.field-meta.xml
<CustomField>
    <fullName>Individu_Paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individu Panéliste</label>
    <referenceTo>Individu_Paneliste__c</referenceTo>
    <relationshipLabel>Conventions</relationshipLabel>
    <relationshipName>Conventions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convention__c/fields/Referentiel_convention__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_convention__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel convention</label>
    <referenceTo>Referentiel_convention__c</referenceTo>
    <relationshipLabel>Conventions</relationshipLabel>
    <relationshipName>Conventions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convention__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT( Referentiel_convention__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Individus Panélistes</relationshipLabel>
    <relationshipName>Individus_Paneliste</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Lettre__c.field-meta.xml
<CustomField>
    <fullName>Lettre__c</fullName>
    <label>Lettre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Signature_convention_individuelle_Meter__c.field-meta.xml
<CustomField>
    <fullName>Signature_convention_individuelle_Meter__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Signature convention individuelle Meter</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invité</fullName>
            </value>
            <value>
                <fullName>Membre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT( Foyer_paneliste__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referentiel_convention__c/Referentiel_convention__c.object-meta.xml
<CustomObject>
    <label>Référentiel convention</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du modèle de convention</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel convention</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_convention__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de début</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Referentiel_convention__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Référentiel convention</relationshipLabel>
    <relationshipName>Referentiel_convention</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referentiel_convention__c/fields/Type_de_la_convention__c.field-meta.xml
<CustomField>
    <fullName>Type_de_la_convention__c</fullName>
    <label>Type de la convention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Foyer</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Individu</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Routeur</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referentiel_convention__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Version</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchRDD13_ConventionsIndividu_Test.cls
/*
* @author: Bastien Pinard
* @date: 09/01/2023
* @ Description 
* @Classe: BatchRDD13_ConventionsIndividu
* * History
* <Date of modification>   		<Author>    		<Description of modification>
*/
@isTest
public class BatchRDD13_ConventionsIndividu_Test {
    
    
    @isTest
    Static void RDD_ConventionPAME() {
        Id recordTypeIdFoyerPanelistePaME = Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_mediamatpame).getRecordTypeId();
                
        Account foyer1 = new Account();
        foyer1.Name = 'Foyer1';
        foyer1.Date_de_reception_de_la_convention__c=Date.today();
        insert foyer1;
        
        Referentiel_Panel__c refPanPaME = new Referentiel_Panel__c();
        refPanPaME.Name = 'PaME';
        refPanPaME.Type_de_panel__c = Label.RFP_TypePanel_PaME;
        insert refPanPaME;
        
        Foyer_Paneliste__c foyerPaneliste1 = new Foyer_Paneliste__c();
        foyerPaneliste1.Name = 'Foyer Paneliste 1';
        foyerPaneliste1.Foyer__c = Foyer1.Id;
        foyerPaneliste1.RecordTypeId = recordTypeIdFoyerPanelistePaME;
        foyerPaneliste1.Referentiel_Panel__c = refPanPaME.Id;
        insert foyerPaneliste1;
        
        Contact compoFoyer1 = new Contact();
        compoFoyer1.AccountId = Foyer1.Id;
        compoFoyer1.LastName = 'Composition';
        compoFoyer1.FirstName = 'Foyer 1';
        compoFoyer1.Birthdate = Date.today();
        compoFoyer1.Lien_parente__c = Label.CON_LienParente_ChefDeFamille;
        compoFoyer1.Type__c = Label.CON_Type_Invite;
        compoFoyer1.Contact_principal__c = true;
        compoFoyer1.Signature_convention_individuelle_meter__c= Date.today();
        System.debug('insert ComoFoyer');
        insert compoFoyer1;
        
        Individu_Paneliste__c indPan = new Individu_Paneliste__c();
        indPan.Composition_du_foyer__c = compoFoyer1.Id;
        indPan.Foyer_paneliste__c = foyerPaneliste1.Id;
        indPan.name = 'indPan Test';
        indPan.lettre__c = 'B';
        insert indPan;
        
        List<Referentiel_convention__c> refConvList =  new List<Referentiel_convention__c>();
        Referentiel_convention__c refConv = new Referentiel_convention__c();
        refConv.Name = 'Individu PaME';
        refConv.Referentiel_Panel__c = refPanPaME.Id;
        refConv.Type_de_la_convention__c = Label.RFC_Type_Convention_Individu;
        refConv.Date_de_debut__c  = date.newInstance(2005, 02, 22);
        refConv.Version__c = '35';
        refConvList.add(refConv);
        
        insert refConvList;
        
        IndividuPanelisteCallout_Mock fakeGetIndividuPanel = new IndividuPanelisteCallout_Mock(compoFoyer1.Id);
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, fakeGetIndividuPanel);         
        BatchRDD13_ConventionsIndividu btch = new BatchRDD13_ConventionsIndividu();
        database.executeBatch(btch);
        Test.stopTest();
        
        Integer conventionBatch = [SELECT COUNT() FROM Convention__c];
        
       // System.assertEquals(1, conventionBatch);
    }
    
}