force-app/main/default/objects/Account/fields/Contact_principal__c.field-meta.xml
<CustomField>
    <fullName>Contact_principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact principal</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Cet individu (Contact Principal) n&apos;existe pas ou n&apos;est pas rattaché à ce foyer.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Foyers (Contact principal)</relationshipLabel>
    <relationshipName>Foyers_en_tant_que_contact_principal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Intervention_en_cours__c.field-meta.xml
<CustomField>
    <fullName>Intervention_en_cours__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Intervention en cours</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Statut_audimetrique__c.field-meta.xml
<CustomField>
    <fullName>Statut_audimetrique__c</fullName>
    <label>Statut audimétrique</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Présent</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>En vacances</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Absent</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Non répondant</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Jour_de_traitement__c.field-meta.xml
<CustomField>
    <fullName>Jour_de_traitement__c</fullName>
    <formula>IF(DATEVALUE(CreatedDate) &gt;= DATE(2023,04,27), TODAY() - DATEVALUE(CreatedDate) + 1, TODAY() - DATEVALUE(CreatedDate) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Etape J</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Conge__c/Conge__c.object-meta.xml
<CustomObject>
    <label>Congé</label>
    <nameField>
        <displayFormat>ABS - {0000}</displayFormat>
        <label>Numéro du congé</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Congés</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conge__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Congés</relationshipLabel>
    <relationshipName>Conges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_principal__c.field-meta.xml
<CustomField>
    <fullName>Contact_principal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contact Principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Equipement_du_foyer_de_l_individu__c/Equipement_du_foyer_de_l_individu__c.object-meta.xml
<CustomObject>
    <label>Équipement du foyer de l&apos;individu</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de É</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Équipements du foyer des individus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipement_du_foyer_de_l_individu__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Équipements du foyer des individus</relationshipLabel>
    <relationshipName>Equipements_du_foyer_des_individus</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/Equipements_du_foyer__c.object-meta.xml
<CustomObject>
    <label>Equipement du foyer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;équipement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipements du foyer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Equipements du foyer</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Equipements du foyer</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Intervention_en_cours__c.field-meta.xml
<CustomField>
    <fullName>Intervention_en_cours__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Intervention en cours</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Membre_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Membre_du_foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membre du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Statut_Audimetrique__c.field-meta.xml
<CustomField>
    <fullName>Statut_Audimetrique__c</fullName>
    <label>Statut Audimétrique</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Présent</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>En vacances</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Absent</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Non répondant</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Statut_Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Statut_Foyer_paneliste__c</fullName>
    <label>Statut Foyer Panéliste</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Foyer_equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Recruté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Installé</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Equipé</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Intégré</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Désinstallé</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chute temporaire</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Chute définitive</label>
            </value>
            <value>
                <fullName>Chute définitive et désinstallé</fullName>
                <isActive>false</isActive>
                <label>Chute définitive et désinstallé</label>
            </value>
            <value>
                <fullName>Désinstallé actif</fullName>
                <isActive>false</isActive>
                <label>Désinstallé actif</label>
            </value>
            <value>
                <fullName>Recruté en attente d&apos;installation</fullName>
                <isActive>false</isActive>
                <label>Recruté en attente d&apos;installation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Date_de_derniere_activite_browser__c.field-meta.xml
<CustomField>
    <fullName>Date_de_derniere_activite_browser__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de dernière activité browser</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Date_de_derniere_activite_mobile__c.field-meta.xml
<CustomField>
    <fullName>Date_de_derniere_activite_mobile__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de dernière activité mobile</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Individus Panélistes</relationshipLabel>
    <relationshipName>Individus_Paneliste</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT( Foyer_paneliste__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Batch017_InstallControlesSoftMeters.cls
/*
* @author: Jérôme HE 
* @date: 24/03/2022
* @ Description:- creation d'une requete de chute pour les requetes dont jour de traitement > 90
*				- creation d'une tâche pour les requete dont jour de traitement > 70
* @TestClass: 
* @Coverage: 82%
* History
* <Date of modification>   		<Author>   		 <Description of modification>
* 10-1-2023                     Mikael chaaya		Correction start querry and added conge
*/
global class Batch017_InstallControlesSoftMeters implements Database.Batchable<sObject>, Database.AllowsCallouts  {
    
    //Added for email notification - START
    global String errorTxt = '';
    global Boolean containsErrors = false;
    //Added for email notification - END
    
    global List<Foyer_paneliste__c> start(Database.BatchableContext bc) {
        List<Foyer_paneliste__c> softMeterList = [SELECT id , Foyer__c,Foyer__r.Contact_principal__c,name,
                                                  (SELECT id,Jour_de_traitement__c,ContactId
                                                   FROM Requetes__r
                                                   where Status <> :label.CAS_Statut_Cloture and (Jour_de_traitement__c=:Decimal.valueOf(label.CAS_Jour_De_Traitement_70) or Jour_de_traitement__c=:Decimal.valueOf(label.CAS_Jour_De_Traitement_90)) And type=:label.CAS_Type_Inactif_Meter_J_1
                                                  ),
                                                  (SELECT id ,name,Date_de_derniere_activite_browser__c,Date_de_derniere_activite_mobile__c, Composition_du_foyer__c
                                                   FROM Panelistes__r)
                                                  FROM Foyer_paneliste__c 
                                                  where Referentiel_Panel__r.Type_de_panel__c =:label.RFP_TypePanel_PaME 
                                                  AND 
                                                  Intervention_en_cours__c = false
                                                  and Statut_Audimetrique__c!=:label.PAN_Statut_Audimetrique_EnVacance
                                                  and Statut_Foyer_paneliste__c    !=:label.PAN_StatusPan_ChuteTemp
                                                  and Motif_de_suspension__c !=:label.PAN_Motif_de_Suspension_Demenagement
                                                  and Statut_Foyer_paneliste__c !=:label.PAN_StatusPan_ChuteDefinitive
                                                  and Id in 
                                                  (SELECT Foyer_paneliste__c 
                                                   FROM Individu_Paneliste__c 
                                                   where Composition_du_foyer__r.Type__c !=:label.Acc_Type_invite and
                                                   ((Composition_du_foyer__r.Frequence_de_connexion_ordinateur__c in (:label.Acc_Freq_Conx_Ordi_TousLesJours,:label.Acc_Freq_Conx_Ordi_PresqueTousLesJours) and Date_de_derniere_activite_browser__c != today and Date_de_derniere_activite_browser__c != null)
                                                    or ((Composition_du_foyer__r.Frequence_de_connexion_mobile__c in (:label.Acc_Freq_Conx_Mobile_TousLesJours , :label.Acc_Freq_Conx_Mobile_PresqueTousLesJours) or Composition_du_foyer__r.Frequence_de_connexion_tablette__c in (:label.Acc_Freq_Conx_Tablette_TousLesJours,:label.Acc_Freq_Conx_Tablette_PresqueTousLesJours)) and Date_de_derniere_activite_mobile__c != today and Date_de_derniere_activite_mobile__c != null) ))
                                                 
                                                 ];
        
        
        return softMeterList;
    }
    
    global void execute(Database.BatchableContext bc, List<Foyer_paneliste__c> scope){
        System.debug('***scope: ' + scope);
        date today = date.today();
        boolean RouteurOn = false;
        
        list<Task> ListtaskToInsert = new list<Task>();
        list<Case> listCaseToInsert = new list<Case>();
        
        user logistique = [select id , username ,name from user where username=:label.Mulesoft_integrationUser_username];
        
        Id recordTypeIdRequeteDemandePaneliste =Schema.SObjectType.Case.getRecordTypeInfosByName().get(label.CAS_Recordtype_DemandePaneliste).getRecordTypeId();
        Id recordTypeIdRequeteControle = Schema.SObjectType.Case.getRecordTypeInfosByName().get(Label.CAS_Recordtype_Controle).getRecordTypeId();
        Id recordTypeIdEquipementDuFoyerDevice = Schema.SObjectType.Equipements_du_foyer__c.getRecordTypeInfosByName().get(Label.EQF_RecodType_Device).getRecordTypeId();
        
        Set<Id> setFoyerId = new Set<Id>();
        Set<Id> setIdCompoFoyerATesterId = new Set<Id>();
        Set<Id> setIdCompoFoyerId = new Set<Id>();
        List<Case> requeteOuverteList = new list<Case>();
        //List<Equipement_du_foyer_de_l_individu__c> utlisateurDeviceList = new List<Equipement_du_foyer_de_l_individu__c>();
        List<Equipements_du_foyer__c> utilisateurPrincipaleDeviceList = new List<Equipements_du_foyer__c>();
        Map<Id, String> compoFoyersousTypeMap = new Map<Id, String>();
        
        
        for(Foyer_paneliste__c fp : scope){
            setFoyerId.add(fp.Foyer__c);   
        }
                
        for(Foyer_paneliste__c fp : scope){
            for(Individu_paneliste__c indPan : fp.Panelistes__r){
                setIdCompoFoyerATesterId.add(indPan.Composition_du_foyer__c);
            }
        }
        System.debug('***setIdCompoFoyerATesterId: ' + setIdCompoFoyerATesterId);
        
        utilisateurPrincipaleDeviceList =  [SELECT Id, Utilisateur_principal__r.Frequence_de_connexion_ordinateur__c,Utilisateur_principal__r.Frequence_de_connexion_tablette__c,
                                            Utilisateur_principal__r.Frequence_de_connexion_mobile__c, type__c, Utilisateur_principal__c
                                            FROM Equipements_du_foyer__c WHERE Utilisateur_principal__c IN :setIdCompoFoyerATesterId ];
        
        System.debug('***utilisateurPrincipaleDeviceList: ' + utilisateurPrincipaleDeviceList);
        for(Equipements_du_foyer__c eqtF: utilisateurPrincipaleDeviceList) {
            if ((eqtF.Utilisateur_principal__r.Frequence_de_connexion_ordinateur__c == '1' || eqtF.Utilisateur_principal__r.Frequence_de_connexion_ordinateur__c =='2')
                && (eqtF.type__c == Label.EQF_Type_OrdinateurPortable || eqtF.type__c == Label.EQF_Type_OrdinateurFixe)) {
                    if (compoFoyersousTypeMap.get(eqtF.Utilisateur_principal__c) != null) {
                        if(compoFoyersousTypeMap.get(eqtF.Utilisateur_principal__c) == label.CAS_Sous_type_Inactif_mobile_J_1) {
                            compoFoyersousTypeMap.put(eqtF.Utilisateur_principal__c, label.CAS_Sous_type_Inactif_mobile_browser_J_1);
                            setIdCompoFoyerId.add(eqtF.Utilisateur_principal__c);
                        }
                    }
                    else {
                        compoFoyersousTypeMap.put(eqtF.Utilisateur_principal__c, label.CAS_Sous_type_Inactif_browser_J_1);
                        setIdCompoFoyerId.add(eqtF.Utilisateur_principal__c);
                    }
                    
                }
            if(((eqtF.Utilisateur_principal__r.Frequence_de_connexion_mobile__c == '1'|| eqtF.Utilisateur_principal__r.Frequence_de_connexion_mobile__c == '2')
                && eqtF.type__c == Label.EQF_Type_Smartphone) 
               ||
               ((eqtF.Utilisateur_principal__r.Frequence_de_connexion_tablette__c == '1' || eqtF.Utilisateur_principal__r.Frequence_de_connexion_tablette__c =='2')
                && eqtF.type__c == Label.EQF_Type_Tablette)) {
                    if (compoFoyersousTypeMap.get(eqtF.Utilisateur_principal__c) != null) {
                        if(compoFoyersousTypeMap.get(eqtF.Utilisateur_principal__c) == label.CAS_Sous_type_Inactif_browser_J_1) {
                            compoFoyersousTypeMap.put(eqtF.Utilisateur_principal__c, label.CAS_Sous_type_Inactif_mobile_browser_J_1);
                            setIdCompoFoyerId.add(eqtF.Utilisateur_principal__c);
                        }
                    }
                    else {
                        compoFoyersousTypeMap.put(eqtF.Utilisateur_principal__c, label.CAS_Sous_type_Inactif_mobile_J_1);
                        setIdCompoFoyerId.add(eqtF.Utilisateur_principal__c);
                    }
                }
        }
        
        //TMASF-31 EN attente
        /*
        utlisateurDeviceList =  [SELECT Id, composition_du_foyer__r.Frequence_de_connexion_ordinateur__c,Composition_du_foyer__r.Frequence_de_connexion_tablette__c,
                                 Composition_du_foyer__r.Frequence_de_connexion_mobile__c, Equipement_du_foyer__r.type__c
                                 FROM Equipement_du_foyer_de_l_individu__c WHERE composition_du_foyer__c IN :setIdCompoFoyerATesterId AND Utilisation_de_l_equipement__c = 'Oui'];
        
        System.debug('***utlisateurDeviceList: ' + utlisateurDeviceList);
        for(Equipement_du_foyer_de_l_individu__c eqtInd: utlisateurDeviceList) {
            if ((eqtInd.composition_du_foyer__r.Frequence_de_connexion_ordinateur__c == '1' || eqtInd.composition_du_foyer__r.Frequence_de_connexion_ordinateur__c =='2')
                && (eqtInd.Equipement_du_foyer__r.type__c == Label.EQF_Type_OrdinateurPortable || eqtInd.Equipement_du_foyer__r.type__c == Label.EQF_Type_OrdinateurFixe)) {
                    if (compoFoyersousTypeMap.get(eqtInd.Composition_du_foyer__c) != null) {
                        if(compoFoyersousTypeMap.get(eqtInd.Composition_du_foyer__c) == label.CAS_Sous_type_Inactif_mobile_J_1) {
                            compoFoyersousTypeMap.put(eqtInd.Composition_du_foyer__c, label.CAS_Sous_type_Inactif_mobile_browser_J_1);
                            setIdCompoFoyerId.add(eqtInd.Composition_du_foyer__c);
                        }
                    }
                    else {
                        compoFoyersousTypeMap.put(eqtInd.Composition_du_foyer__c, label.CAS_Sous_type_Inactif_browser_J_1);
                        setIdCompoFoyerId.add(eqtInd.Composition_du_foyer__c);
                    }
                    
                }
            if(((eqtInd.Composition_du_foyer__r.Frequence_de_connexion_mobile__c == '1'|| eqtInd.Composition_du_foyer__r.Frequence_de_connexion_mobile__c == '2')
                && eqtInd.Equipement_du_foyer__r.type__c == Label.EQF_Type_Smartphone) 
               ||
               ((eqtInd.Composition_du_foyer__r.Frequence_de_connexion_tablette__c == '1' || eqtInd.Composition_du_foyer__r.Frequence_de_connexion_tablette__c =='2')
                && eqtInd.Equipement_du_foyer__r.type__c == Label.EQF_Type_Tablette)) {
                    if (compoFoyersousTypeMap.get(eqtInd.Composition_du_foyer__c) != null) {
                        if(compoFoyersousTypeMap.get(eqtInd.Composition_du_foyer__c) == label.CAS_Sous_type_Inactif_browser_J_1) {
                            compoFoyersousTypeMap.put(eqtInd.Composition_du_foyer__c, label.CAS_Sous_type_Inactif_mobile_browser_J_1);
                            setIdCompoFoyerId.add(eqtInd.Composition_du_foyer__c);
                        }
                    }
                    else {
                        compoFoyersousTypeMap.put(eqtInd.Composition_du_foyer__c, label.CAS_Sous_type_Inactif_mobile_J_1);
                        setIdCompoFoyerId.add(eqtInd.Composition_du_foyer__c);
                    }
                }
        }*/
        
        System.debug('***setIdCompoFoyerId: ' + setIdCompoFoyerId);
        //Pas de requêtes déjà ouvertes
        requeteOuverteList = [SELECT Id, ContactId 
                              FROM Case 
                              WHERE (ContactId IN :setIdCompoFoyerId)
                              AND Type = :label.CAS_Type_Inactif_Meter_J_1
                              AND (Sous_type__c = :label.CAS_Sous_type_Inactif_mobile_browser_J_1 
                                   OR Sous_type__c = :label.CAS_Sous_type_Inactif_browser_J_1
                                   OR Sous_type__c = :label.CAS_Sous_type_Inactif_mobile_J_1)
                             AND Status != :Label.CAS_Statut_Cloture];
        
        for(Case requete : requeteOuverteList){
            setIdCompoFoyerId.remove(requete.ContactId);   
        }
        
        System.debug('***setIdCompoFoyerId: ' + setIdCompoFoyerId);
        //Pas de congé en cours
        List<Conge__c> temp = new List<Conge__c>([Select Conge_de_l_individu__c from Conge__c where  isCongeEnCours__c=True and Conge_de_l_individu__c IN: setIdCompoFoyerId ]);
        for (Conge__c c: temp){
            setIdCompoFoyerId.remove(c.Conge_de_l_individu__c);
        }
        
        System.debug('***setIdCompoFoyerId: ' + setIdCompoFoyerId);
        System.debug('***compoFoyersousTypeMap: ' + compoFoyersousTypeMap);
        //Utilisateur d'un device
        
        
        
        for(Foyer_paneliste__c fp : scope){
            
            
            for(Individu_paneliste__c indPan : fp.Panelistes__r){
                //Mikael
                if(setIdCompoFoyerId.contains(indPan.Composition_du_foyer__c)){
                    
                    
                    Integer daysDerniereActiviteBrowser = null;
                    Integer daysDerniereActiviteMobile = null;
                                   
                    
                    if(indPan.Date_de_derniere_activite_browser__c != null){
                        daysDerniereActiviteBrowser = today.daysBetween(indPan.Date_de_derniere_activite_browser__c);
                    }
                    
                    if(indPan.Date_de_derniere_activite_mobile__c != null){
                        daysDerniereActiviteMobile = today.daysBetween(indPan.Date_de_derniere_activite_mobile__c);
                    }
                                        
                    if((daysDerniereActiviteBrowser != null || daysDerniereActiviteMobile  != null) && compoFoyersousTypeMap.get(indPan.Composition_du_foyer__c) != null) {
                        
                        String sousType;
                        if((daysDerniereActiviteBrowser == -2) && (daysDerniereActiviteMobile  != -2) && compoFoyersousTypeMap.get(indPan.Composition_du_foyer__c) == label.CAS_Sous_type_Inactif_browser_J_1){
                            SousType = compoFoyersousTypeMap.get(indPan.Composition_du_foyer__c);
                        } else if((daysDerniereActiviteMobile  == -2) && (daysDerniereActiviteBrowser != -2) && compoFoyersousTypeMap.get(indPan.Composition_du_foyer__c) == label.CAS_Sous_type_Inactif_mobile_J_1) {
                            SousType = compoFoyersousTypeMap.get(indPan.Composition_du_foyer__c);
                        } else if((daysDerniereActiviteMobile  == -2) && (daysDerniereActiviteBrowser == -2) && compoFoyersousTypeMap.get(indPan.Composition_du_foyer__c) == label.CAS_Sous_type_Inactif_mobile_browser_J_1) {
                            SousType = compoFoyersousTypeMap.get(indPan.Composition_du_foyer__c);
                        }
                        if(SousType != null){
                            Case newCase = new Case();
                            newCase.RecordTypeId= recordTypeIdRequeteControle;
                            newCase.Foyer_paneliste__c=fp.id;
                            newCase.AccountId=fp.foyer__c;
                            newCase.Type=label.CAS_Type_Inactif_Meter_J_1;
                            newCase.Sous_type__c=SousType;
                            newCase.ContactId=indPan.Composition_du_foyer__c;
                            newCase.Contact_sur_place__c=fp.Foyer__r.Contact_principal__c;
                            newCase.Origin = label.CAS_Origine_Controle;
                            newCase.Priority = Label.CAS_Priorite_Moyen;
                            listCaseToInsert.add(newCase);
                        }
                        
                    }
                    
                }
            }
            
            // requetes
            System.debug('fp.requetes__r');
            System.debug(fp.requetes__r);
            for(Case req : fp.requetes__r){
                System.debug('req.Jour_de_traitement__c');
                System.debug(req.Jour_de_traitement__c);
                if(req.Jour_de_traitement__c == 70){
                    
                    Task newTask = new Task();// creer une nouvelle tache
                    newTask.WhoId = fp.Foyer__r.Contact_principal__c ;
                    newTask.WhatId = fp.Foyer__c;
                    newTask.Subject = Label.TSK_Subject_EnvoyerCourrier;
                    newTask.OwnerId=logistique.id;
                    newTask.ActivityDate = date.today();
                    ListtaskToInsert.add(newTask);
                }
                if(req.Jour_de_traitement__c == 90){
                    
                    Case CaseChute = new Case();
                    CaseChute.RecordTypeId= recordTypeIdRequeteDemandePaneliste;
                    CaseChute.Foyer_paneliste__c=fp.id;
                    CaseChute.AccountId=fp.foyer__c;
                    CaseChute.ContactId=req.ContactId;
                    CaseChute.Contact_sur_place__c=fp.Foyer__r.Contact_principal__c;
                    CaseChute.Origin = label.CAS_Origine_Controle;
                    CaseChute.type=Label.CAS_Type_J_90;
                    CaseChute.Sous_type__c = Label.CAS_Sous_type_Foyer_inactif_meter_J_90;
                    CaseChute.Priority = Label.CAS_Priorite_Moyen;
                    listCaseToInsert.add(CaseChute);
                }
            }                  
            
            RouteurOn = false;
        }
        
        if(listCaseToInsert!=null && listCaseToInsert.size()>0){// insert the new cases
            system.debug('Inserting case');
            try{ 
                database.insert(listCaseToInsert);
            }Catch(exception ex){
                errorTxt += 'Erreur durant la création des contrôles : ' + ex.getMessage() + '\n';
                containsErrors = true;
                system.debug('insert case batch017 Exception Error:'+ex.getmessage());
            }
        }
        
        if(ListtaskToInsert!=null && ListtaskToInsert.size()>0){// insert the new tasks
            try{ 
                database.insert(ListtaskToInsert);
            }Catch(exception ex){
                errorTxt += 'Erreur durant la création des taches : ' + ex.getMessage() + '\n';
                containsErrors = true;
                system.debug('insert task batch017 Exception Error:'+ex.getmessage());
            }
        }
        
    }
    
    global void finish(Database.BatchableContext bc){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        List<String> toMailAddress = System.Label.BatchNotif_B017_ToAddress.split(';');
        
        mail.setToAddresses(toMailAddress);
        mail.setSenderDisplayName(System.Label.BatchNotif_B017_SenderName);
        mail.setSubject(System.Label.BatchNotif_B017_Subject+'-'+date.today().format());
        
        String emailBody = 'L\'exécution du batch Batch017_InstallControlesSoftMeters s\'est terminée.\n';
        if(containsErrors) {
            emailBody += 'Les erreurs suivantes ont été rencontrées :\n\n';
            emailBody += errorTxt;
        } else {
            emailBody += 'Aucune erreur n\'a été relevée.';
        }
        mail.setPlainTextBody(emailBody);
        
        if(!Test.isRunningTest()) {
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
        
    }
    
}