force-app/main/default/objects/Account/fields/Contact_principal__c.field-meta.xml
<CustomField>
    <fullName>Contact_principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact principal</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Cet individu (Contact Principal) n&apos;existe pas ou n&apos;est pas rattaché à ce foyer.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Foyers (Contact principal)</relationshipLabel>
    <relationshipName>Foyers_en_tant_que_contact_principal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_d_anonymisation__c.field-meta.xml
<CustomField>
    <fullName>Date_d_anonymisation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;anonymisation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_principal__c.field-meta.xml
<CustomField>
    <fullName>Contact_principal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contact Principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Membre_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Membre_du_foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membre du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Statut_Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Statut_Foyer_paneliste__c</fullName>
    <label>Statut Foyer Panéliste</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Foyer_equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Recruté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Installé</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Equipé</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Intégré</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Désinstallé</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chute temporaire</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Chute définitive</label>
            </value>
            <value>
                <fullName>Chute définitive et désinstallé</fullName>
                <isActive>false</isActive>
                <label>Chute définitive et désinstallé</label>
            </value>
            <value>
                <fullName>Désinstallé actif</fullName>
                <isActive>false</isActive>
                <label>Désinstallé actif</label>
            </value>
            <value>
                <fullName>Recruté en attente d&apos;installation</fullName>
                <isActive>false</isActive>
                <label>Recruté en attente d&apos;installation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Date_de_chute_de_l_individu__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute_de_l_individu__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute de l&apos;individu</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AP04_IndividuPaneliste.cls
/*
* @author: Claire VEHRLE
* @date: 22/03/2022
* @ Description 
* @TestClass: AP04_IndividuPaneliste_Test
* @Coverage: -- %
* History
* <Date of modification>   		<Author>   		 <Description of modification>
*/ 
public class AP04_IndividuPaneliste {

    public static List<Individu_paneliste__c> empecherChuteCompositionFoyerMonopanel (List<Id> individuPanelisteIdChute) {
        
        List<Id> foyerIdList = new List<Id>();
        List<Account> foyerList = new List<Account>();
        Map<Individu_paneliste__c, Integer> monoOuMultipanelMap = new Map<Individu_paneliste__c, Integer>();
        List<Individu_Paneliste__c> individuPanelisteToCheckList = new List<Individu_Paneliste__c>();
        Id recordTypeIdFoyerPanelisteMediamatPame =Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_mediamatpame).getRecordTypeId();
                
        individuPanelisteToCheckList = [SELECT Id, Name, Composition_du_foyer__r.Contact_principal__c, Composition_du_foyer__r.AccountId, Foyer_paneliste__c
                                        FROM Individu_Paneliste__c WHERE Id IN :individuPanelisteIdChute];
        
        for (Individu_Paneliste__c indpan: individuPanelisteToCheckList) {
            if (indpan.Composition_du_foyer__r.Contact_principal__c) {
                foyerIdList.add(indpan.Composition_du_foyer__r.AccountId);
            }
        }
        foyerList = [SELECT Id, Name, 
                     (SELECT Id FROM Panelistes__r 
                      WHERE Statut_Foyer_paneliste__c != :Label.PAN_Statut_Panel_Chute_definitive 
                      AND Date_d_anonymisation__c = null 
                      AND RecordTypeId = :recordTypeIdFoyerPanelisteMediamatPame) 
                     FROM Account WHERE Id IN :foyerIdList];
        
        for (Account foyer: foyerList) {
            for (Foyer_Paneliste__c foyerPaneliste:foyer.Panelistes__r) {
                System.debug('$$$foyerPaneliste: ' + foyerPaneliste);
                for(Individu_paneliste__c indpan : individuPanelisteToCheckList) {
                    System.debug('$$$indpan: ' + indpan);
                    if(foyerPaneliste.Id == indpan.Foyer_paneliste__c) {
                        monoOuMultipanelMap.put(indpan, foyer.Panelistes__r.size());
                    }
                }
            }
        }
        
        List<Individu_Paneliste__c> individuPanelisteANePasChuter = new List<Individu_Paneliste__c>();
        for(Individu_Paneliste__c indPan:monoOuMultipanelMap.keySet()) {
            if(monoOuMultipanelMap.get(indPan) == 1) {
                indPan.Date_de_chute_de_l_individu__c = null;
                individuPanelisteANePasChuter.add(indPan);
            }
        }
        
        return individuPanelisteANePasChuter;
    }
}