force-app/main/default/objects/Account/fields/Contact_principal__c.field-meta.xml
<CustomField>
    <fullName>Contact_principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact principal</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Cet individu (Contact Principal) n&apos;existe pas ou n&apos;est pas rattaché à ce foyer.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Foyers (Contact principal)</relationshipLabel>
    <relationshipName>Foyers_en_tant_que_contact_principal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_d_anonymisation__c.field-meta.xml
<CustomField>
    <fullName>Date_d_anonymisation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;anonymisation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_de_chute_temporaire__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute_temporaire__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute temporaire</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Types_de_Panel__c.field-meta.xml
<CustomField>
    <fullName>Types_de_Panel__c</fullName>
    <label>Types de Panel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>PaME</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_principal__c.field-meta.xml
<CustomField>
    <fullName>Contact_principal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contact Principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CSP42__c.field-meta.xml
<CustomField>
    <fullName>CSP42__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code profession CSP42</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CSP4__c.field-meta.xml
<CustomField>
    <fullName>CSP4__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code profession CSP4</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Lettre__c.field-meta.xml
<CustomField>
    <fullName>Lettre__c</fullName>
    <label>Lettre</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Lien_de_parente_stat__c.field-meta.xml
<CustomField>
    <fullName>Lien_de_parente_stat__c</fullName>
    <label>Lien de parenté stat</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Couple</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Parent</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Enfant</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Famille</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Isolé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Lien_parente__c.field-meta.xml
<CustomField>
    <fullName>Lien_parente__c</fullName>
    <label>Lien parenté</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Chef de famille</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Conjoint</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Enfant</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Ascendant</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Autre</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Membre</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Invité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Non panéliste</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Date_de_chute_temporaire__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute_temporaire__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute temporaire</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Statut_Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Statut_Foyer_paneliste__c</fullName>
    <label>Statut Foyer Panéliste</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Foyer_equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Recruté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Installé</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Equipé</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Intégré</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Désinstallé</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chute temporaire</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Chute définitive</label>
            </value>
            <value>
                <fullName>Chute définitive et désinstallé</fullName>
                <isActive>false</isActive>
                <label>Chute définitive et désinstallé</label>
            </value>
            <value>
                <fullName>Désinstallé actif</fullName>
                <isActive>false</isActive>
                <label>Désinstallé actif</label>
            </value>
            <value>
                <fullName>Recruté en attente d&apos;installation</fullName>
                <isActive>false</isActive>
                <label>Recruté en attente d&apos;installation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Date_de_chute_de_l_individu__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute_de_l_individu__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute de l&apos;individu</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Individus Panélistes</relationshipLabel>
    <relationshipName>Individus_Paneliste</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Lettre__c.field-meta.xml
<CustomField>
    <fullName>Lettre__c</fullName>
    <label>Lettre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invité</fullName>
            </value>
            <value>
                <fullName>Membre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AP04_IndividuPaneliste_Test.cls
/*
* @author: Claire VEHRLE
* @date: 23/03/2022
* @ Description Class that test AP04_IndividuPaneliste  
* History
* <Date of modification>   <Author>    <Description of modification>
*/
@isTest
public class AP04_IndividuPaneliste_Test {

    public static testMethod void pasChuteIndividuPaneliste() {
        
        Id recordTypeIdFoyerPanelisteAIP = Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_AIP).getRecordTypeId();
        Id recordTypeIdFoyerPanelisteMediamatPame =Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_mediamatpame).getRecordTypeId();
        
        List<Account> foyerListToInsert = new List<Account>();
        Account foyer1 = new Account();
        foyer1.Name = 'Foyer1';
        foyerListToInsert.add(Foyer1);
        
        Account foyer2 = new Account();
        foyer2.Name = 'foyer2';
        foyer2.Types_de_Panel__c = 'MMT';
        foyerListToInsert.add(foyer2);
        
        Account foyer3 = new Account();
        foyer3.Name = 'foyer3';
        foyerListToInsert.add(foyer3);
        
        insert foyerListToInsert;
        
        List<Contact> contactToInsertList = new List<Contact>();
        Contact compoFoyer1 = new Contact();
        compoFoyer1.AccountId = Foyer1.Id;
        compoFoyer1.LastName = 'Composition';
        compoFoyer1.FirstName = 'Foyer 1';
        compoFoyer1.Birthdate = Date.today();
        compoFoyer1.CSP4__c = '1';
        compoFoyer1.CSP42__c = '3';
        compoFoyer1.Lien_parente__c = Label.CON_LienParente_ChefDeFamille;
        compoFoyer1.Type__c = Label.CON_Type_Invite;
        compoFoyer1.Contact_principal__c = true;
        compoFoyer1.Lien_de_parente_stat__c = Label.CON_LienParenteStat_Parent;
        contactToInsertList.add(compoFoyer1);
        
        Contact compoFoyer2 = new Contact();
        compoFoyer2.AccountId = Foyer2.Id;
        compoFoyer2.LastName = 'Composition';
        compoFoyer2.FirstName = 'Foyer 2';
        compoFoyer2.Birthdate = Date.today();
        compoFoyer2.CSP4__c = '1';
        compoFoyer2.CSP42__c = '3';
        compoFoyer2.Lien_parente__c = Label.CON_LienParente_ChefDeFamille;
        compoFoyer2.Type__c = Label.CON_Type_Invite;
        compoFoyer2.Contact_principal__c = true;
        compoFoyer2.Lien_de_parente_stat__c = Label.CON_LienParenteStat_Parent;
        contactToInsertList.add(compoFoyer2);
        
        Contact compoFoyer3 = new Contact();
        compoFoyer3.AccountId = Foyer3.Id;
        compoFoyer3.LastName = 'Composition';
        compoFoyer3.FirstName = 'Foyer 3';
        compoFoyer3.Birthdate = Date.today();
        compoFoyer3.CSP4__c = '1';
        compoFoyer3.CSP42__c = '3';
        compoFoyer3.Lien_parente__c = Label.CON_LienParente_ChefDeFamille;
        compoFoyer3.Type__c = Label.CON_Type_Invite;
        compoFoyer3.Contact_principal__c = false;
        compoFoyer3.Lien_de_parente_stat__c = Label.CON_LienParenteStat_Parent;
        contactToInsertList.add(compoFoyer3);
        
        insert contactToInsertList;
        
        List<Referentiel_Panel__c> listReferentielPanelToInsert = new List<Referentiel_Panel__c>();
        Referentiel_Panel__c refPanelPaME = Test_Utils.createRefPanel(Label.RFP_TypePanel_PaME, Label.RFP_TypePanel_PaME);
        listReferentielPanelToInsert.add(refPanelPaME);
        
        Referentiel_Panel__c refPanelMMAT = Test_Utils.createRefPanel(Label.RFP_TypePanel_MMAT, Label.RFP_TypePanel_MMAT);
        listReferentielPanelToInsert.add(refPanelMMAT);
        
        Referentiel_Panel__c refPanelAIP = Test_Utils.createRefPanel(Label.RFP_TypePanel_AIP, Label.RFP_TypePanel_AIP);
        listReferentielPanelToInsert.add(refPanelAIP);
        
        insert listReferentielPanelToInsert;
        
        List<Foyer_Paneliste__c> foyerPanelisteToInsert = new List<Foyer_Paneliste__c>();
        Foyer_Paneliste__c foyerPaneliste1 = new Foyer_Paneliste__c();
        foyerPaneliste1.Name = 'Foyer Paneliste 1';
        foyerPaneliste1.Foyer__c = Foyer1.Id;
        foyerPaneliste1.RecordTypeId = recordTypeIdFoyerPanelisteAIP;
        foyerPaneliste1.Referentiel_Panel__c = refPanelAIP.Id;
        foyerPaneliste1.Statut_Foyer_Paneliste__c = Label.PAN_Statut_panel;
        foyerPanelisteToInsert.add(foyerPaneliste1);
        
        Foyer_Paneliste__c foyerPaneliste2A = new Foyer_Paneliste__c();
        foyerPaneliste2A.Name = 'Foyer Paneliste 2A';
        foyerPaneliste2A.Foyer__c = Foyer2.Id;
        foyerPaneliste2A.RecordTypeId = recordTypeIdFoyerPanelisteAIP;
        foyerPaneliste2A.Referentiel_Panel__c = refPanelAIP.Id;
        foyerPaneliste2A.Statut_Foyer_Paneliste__c = Label.PAN_Statut_panel;
        foyerPanelisteToInsert.add(foyerPaneliste2A);
        
        Foyer_Paneliste__c foyerPaneliste2B = new Foyer_Paneliste__c();
        foyerPaneliste2B.Name = 'Foyer Paneliste 2B';
        foyerPaneliste2B.Foyer__c = Foyer2.Id;
        foyerPaneliste2B.RecordTypeId = recordTypeIdFoyerPanelisteMediamatPame;
        foyerPaneliste2B.Referentiel_Panel__c = refPanelMMAT.Id;
        foyerPaneliste2B.Date_de_chute_temporaire__c= Date.today(); //MD
        foyerPaneliste2B.Statut_Foyer_paneliste__c = Label.PAN_Statut_Panel_Chute_definitive;
        foyerPanelisteToInsert.add(foyerPaneliste2B);
        
        Foyer_Paneliste__c foyerPaneliste2C = new Foyer_Paneliste__c();
        foyerPaneliste2C.Name = 'Foyer Paneliste 2C';
        foyerPaneliste2C.Foyer__c = Foyer2.Id;
        foyerPaneliste2C.RecordTypeId = recordTypeIdFoyerPanelisteMediamatPame;
        foyerPaneliste2C.Referentiel_Panel__c = refPanelPaME.Id;
        foyerPaneliste2C.Date_d_anonymisation__c = Date.today() - 10;
        foyerPanelisteToInsert.add(foyerPaneliste2C);
        
        Foyer_Paneliste__c foyerPaneliste3 = new Foyer_Paneliste__c();
        foyerPaneliste3.Name = 'Foyer Paneliste 3';
        foyerPaneliste3.Foyer__c = Foyer3.Id;
        foyerPaneliste3.RecordTypeId = recordTypeIdFoyerPanelisteAIP;
        foyerPaneliste3.Referentiel_Panel__c = refPanelAIP.Id;
        foyerPanelisteToInsert.add(foyerPaneliste3);
        
        insert foyerPanelisteToInsert;
        
        List<Individu_Paneliste__c> individuPanelisteToInsert = new List<Individu_Paneliste__c>();
        Individu_Paneliste__c individuPaneliste1 = new Individu_Paneliste__c();
        individuPaneliste1.Name = 'Individu Paneliste 1';
        individuPaneliste1.Foyer_paneliste__c = foyerPaneliste1.Id;
        individuPaneliste1.Composition_du_foyer__c = compoFoyer1.Id;
        individuPaneliste1.Lettre__c = 'A';
        individuPanelisteToInsert.add(individuPaneliste1);
        
        Individu_Paneliste__c individuPaneliste2 = new Individu_Paneliste__c();
        individuPaneliste2.Name = 'Individu Paneliste 2';
        individuPaneliste2.Foyer_paneliste__c = foyerPAneliste2A.Id;
        individuPaneliste2.Composition_du_foyer__c = compoFoyer2.Id;
        individuPaneliste2.Lettre__c = 'A';
        individuPanelisteToInsert.add(individuPaneliste2);
        
        Individu_Paneliste__c individuPaneliste3 = new Individu_Paneliste__c();
        individuPaneliste3.Name = 'Individu Paneliste 3';
        individuPaneliste3.Foyer_paneliste__c = foyerPAneliste3.Id;
        individuPaneliste3.Composition_du_foyer__c = compoFoyer3.Id;
        individuPaneliste3.Lettre__c = 'A';
        individuPanelisteToInsert.add(individuPaneliste3);
        
        Insert individuPanelisteToInsert;
        
        List<Individu_paneliste__c> individuPanelisteToUpdate = new List<Individu_Paneliste__c>();
        individuPaneliste1.Date_de_chute_de_l_individu__c = Date.today();
        individuPanelisteToUpdate.add(individuPaneliste1);
        individuPaneliste2.Date_de_chute_de_l_individu__c = Date.today();
        individuPanelisteToUpdate.add(individuPaneliste2);
        individuPaneliste3.Date_de_chute_de_l_individu__c = Date.today();
        individuPanelisteToUpdate.add(individuPaneliste3);
                
        Database.SaveResult[] results = Database.update(individuPanelisteToUpdate, false);
        for(Database.SaveResult resultIndPan:results) {
            if (resultIndPan.isSuccess()) {
                System.debug('$$$ result.getId(): ' + resultIndPan.getId());
            } else {
                for(Database.Error err : resultIndPan.getErrors()) {
                    System.debug('$$$ err.getStatusCode(): ' + err.getStatusCode());
                    System.debug('$$$ err.getMessage(): '+ err.getMessage());
                    System.assert(err.getMessage().contains('individu paneliste'));
                }
            }
        }
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(compoFoyer1.id));
        Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(compoFoyer2.id));
        Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(compoFoyer3.id));
        Test.stopTest();
        
    }
}