force-app/main/default/objects/Account/fields/Contact_principal__c.field-meta.xml
<CustomField>
    <fullName>Contact_principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact principal</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Cet individu (Contact Principal) n&apos;existe pas ou n&apos;est pas rattaché à ce foyer.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Foyers (Contact principal)</relationshipLabel>
    <relationshipName>Foyers_en_tant_que_contact_principal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_d_installation__c.field-meta.xml
<CustomField>
    <fullName>Date_d_installation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;installation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_d_integration__c.field-meta.xml
<CustomField>
    <fullName>Date_d_integration__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;intégration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_de_creation__c.field-meta.xml
<CustomField>
    <fullName>Date_de_creation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de creation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_de_recensement__c.field-meta.xml
<CustomField>
    <fullName>Date_de_recensement__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de recensement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Freeze__c.field-meta.xml
<CustomField>
    <fullName>Freeze__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Cette case à cocher permet de bloquer l&apos;attribution de points du foyer</description>
    <label>Freeze</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_de_portable__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_portable__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Numéro de téléphone portable</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_principal__c.field-meta.xml
<CustomField>
    <fullName>Contact_principal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contact Principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CSP4__c.field-meta.xml
<CustomField>
    <fullName>CSP4__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code profession CSP4</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Freeze__c.field-meta.xml
<CustomField>
    <fullName>Freeze__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Freeze</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Date_d_installation__c.field-meta.xml
<CustomField>
    <fullName>Date_d_installation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;installation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Date_d_integration__c.field-meta.xml
<CustomField>
    <fullName>Date_d_integration__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;intégration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Date_de_creation__c.field-meta.xml
<CustomField>
    <fullName>Date_de_creation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de création</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Date_de_recensement__c.field-meta.xml
<CustomField>
    <fullName>Date_de_recensement__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de recensement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Freeze__c.field-meta.xml
<CustomField>
    <fullName>Freeze__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Freeze</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Statut_Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Statut_Foyer_paneliste__c</fullName>
    <label>Statut Foyer Panéliste</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Foyer_equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Recruté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Installé</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Equipé</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Intégré</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Désinstallé</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chute temporaire</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Chute définitive</label>
            </value>
            <value>
                <fullName>Chute définitive et désinstallé</fullName>
                <isActive>false</isActive>
                <label>Chute définitive et désinstallé</label>
            </value>
            <value>
                <fullName>Désinstallé actif</fullName>
                <isActive>false</isActive>
                <label>Désinstallé actif</label>
            </value>
            <value>
                <fullName>Recruté en attente d&apos;installation</fullName>
                <isActive>false</isActive>
                <label>Recruté en attente d&apos;installation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Individus Panélistes</relationshipLabel>
    <relationshipName>Individus_Paneliste</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Freeze__c.field-meta.xml
<CustomField>
    <fullName>Freeze__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Freeze</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Batch016_CreditAutomatique_Test.cls
/*
* @author: Nancy Al Kalach
* @date: 09/12/2021
* @ Description Class that test Batch016_CreditAutomatique 
* History
* <Date of modification>   <Author>    <Description of modification>
*/

@isTest
public class Batch016_CreditAutomatique_Test {
    public static testMethod void Batch016_CreditAutomatiqueTest(){
        
        //insert Account(foyer)
        list<Account> listFoyersToInsert = new list<Account>();
        account testAccount = Test_Utils.createFoyer();
        testAccount.Date_d_installation__c=system.today()-60;
        testAccount.Numero_de_portable__c = '0611111121';
        listFoyersToInsert.add(testAccount);
        
        account testAccount2 = Test_Utils.createFoyer();
        testAccount2.Date_d_installation__c=Date.today().addMonths(-1).addDays(-1);
        testAccount2.Date_de_recensement__c=Date.today().addMonths(-1);
        testAccount2.Date_d_integration__c=Date.today().addDays(-21);
        testAccount2.Numero_de_portable__c = '0611111121';
        listFoyersToInsert.add(testAccount2);
        
      	account testAccount3 = Test_Utils.createFoyer();
      	testAccount3.Date_d_installation__c = date.newInstance(system.today().year() - 2, system.today().month() - 1, system.today().day());
       	testAccount3.Numero_de_portable__c = '0611131121';
      	listFoyersToInsert.add(testAccount3);//Date.today().addDays(-30)
        insert listFoyersToInsert;
        
        
        List<Referentiel_Panel__c> listRefPanelToInsert = new List <Referentiel_Panel__c>();
        Referentiel_Panel__c testRefAIP = Test_Utils.createRefPanel(Label.RFP_Nom_AIP, Label.RFP_TypePanel_AIP);
        Referentiel_Panel__c testRefMMAT = Test_Utils.createRefPanel(Label.RFP_Nom_MMAT, Label.RFP_TypePanel_MMAT);
        Referentiel_Panel__c testRefPAME = Test_Utils.createRefPanel(Label.RFP_Nom_PAME, Label.RFP_TypePanel_PaME);
        listRefPanelToInsert.add(testRefAIP);
        listRefPanelToInsert.add(testRefMMAT);        
        listRefPanelToInsert.add(testRefPAME); 
        insert listRefPanelToInsert;
        
        List<Contact> listContactToInsert = new List<Contact>();
        Contact con = Test_Utils.createMembreFoyer(testAccount.Id);
        Contact con2 = Test_Utils.createMembreFoyer(testAccount2.Id);
        con.CSP4__c='1';
        con2.CSP4__c='2';
        listContactToInsert.add(con);
        listContactToInsert.add(con2);
        insert listContactToInsert;
        
        List<Account> listAccountToUpdate = new List<Account>();
        testAccount.Contact_principal__c = con.Id;
        listAccountToUpdate.add(testAccount);
        testAccount2.Contact_principal__c = con2.Id;
        listAccountToUpdate.add(testAccount2);
        update listAccountToUpdate;
        
        List<Foyer_paneliste__c> listFPToInsert= new list<Foyer_paneliste__c>();
      	Foyer_paneliste__c testFoyerPan = new Foyer_paneliste__c (name='TestFP',foyer__c=testAccount.id, Referentiel_Panel__c = testRefAIP.Id);
        testFoyerPan.Freeze__c=false;
        testFoyerPan.Date_de_creation__c = system.today()-61;
        testFoyerPan.Date_d_installation__c=system.today().addMonths(-2);
        testFoyerPan.Statut_Foyer_paneliste__c='1';
      	listFPToInsert.add(testFoyerPan);
        
        Foyer_paneliste__c testFoyerP = new Foyer_paneliste__c (name='TestFP',foyer__c=testAccount2.id, Referentiel_Panel__c = testRefAIP.Id);
        testFoyerP.Freeze__c=true;
        testFoyerP.Date_de_creation__c = system.today().addMonths(-13);
        testFoyerP.Date_d_installation__c=system.today().addMonths(-2);
   		testFoyerP.Statut_Foyer_paneliste__c='1';
        testFoyerP.Date_de_recensement__c=Date.today().addMonths(-1);
        listFPToInsert.add(testFoyerP); 
        
        Foyer_paneliste__c testFoyerPanelisteMediamat = new Foyer_paneliste__c (name='TestFP',foyer__c=testAccount2.id, Referentiel_Panel__c = testRefMMAT.Id);
        testFoyerPanelisteMediamat.Freeze__c=false;
        testFoyerPanelisteMediamat.Date_de_creation__c = system.today().addMonths(-13);
        testFoyerPanelisteMediamat.Date_d_installation__c=system.today().addMonths(-2);
        testFoyerPanelisteMediamat.Statut_Foyer_paneliste__c='1';
        testFoyerPanelisteMediamat.Date_de_recensement__c=Date.today().addMonths(-1);
        listFPToInsert.add(testFoyerPanelisteMediamat); 
        
        Foyer_paneliste__c testFoyerPanelistePame = new Foyer_paneliste__c (name='TestFP',foyer__c=testAccount2.id, Referentiel_Panel__c = testRefPAME.Id);
        testFoyerPanelistePame.Freeze__c=true;
        testFoyerPanelistePame.Date_de_creation__c = system.today().addMonths(-13);
        testFoyerPanelistePame.Statut_Foyer_paneliste__c='2';
        testFoyerPanelistePame.Date_de_recensement__c=Date.today().addMonths(-1);
        listFPToInsert.add(testFoyerPanelistePame); 
        
        insert listFPToInsert;
        
        List<Individu_Paneliste__c> listIndividuPanelisteToInsert = new List<Individu_Paneliste__c>();
      	Individu_Paneliste__c individuPaneliste = Test_Utils.createIndividuPaneliste(con.Id, testFoyerPan.Id, 'A');
        listIndividuPanelisteToInsert.add(individuPaneliste);
        Individu_Paneliste__c individuPaneliste2 = Test_Utils.createIndividuPaneliste(con2.Id, testFoyerP.Id, 'B');
        listIndividuPanelisteToInsert.add(individuPaneliste2);
        Individu_Paneliste__c individuPaneliste3 = Test_Utils.createIndividuPaneliste(con2.Id, testFoyerPanelisteMediamat.Id, 'C');
        listIndividuPanelisteToInsert.add(individuPaneliste3);
        insert listIndividuPanelisteToInsert;
        
        Test.startTest();
        Batch016_CreditAutomatique btch = new Batch016_CreditAutomatique();
        database.executeBatch(btch);
        Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(testAccount.id)); 
        Test.stopTest();
    }
}