force-app/main/default/objects/Account/fields/Contact_principal__c.field-meta.xml
<CustomField>
    <fullName>Contact_principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact principal</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Cet individu (Contact Principal) n&apos;existe pas ou n&apos;est pas rattaché à ce foyer.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Foyers (Contact principal)</relationshipLabel>
    <relationshipName>Foyers_en_tant_que_contact_principal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Personne_de_reference__c.field-meta.xml
<CustomField>
    <fullName>Personne_de_reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personne de référence</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Cet individu n&apos;existe pas ou n&apos;est pas rattaché à ce foyer.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Foyers</relationshipLabel>
    <relationshipName>Foyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Solde_de_points__c.field-meta.xml
<CustomField>
    <fullName>Solde_de_points__c</fullName>
    <formula>Nombre_de_points_cumules__c - Nombre_de_points_debites__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Solde de points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_principal__c.field-meta.xml
<CustomField>
    <fullName>Contact_principal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contact Principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Personne_de_Reference__c.field-meta.xml
<CustomField>
    <fullName>Personne_de_Reference__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Personne de Référence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Solde_de_points__c.field-meta.xml
<CustomField>
    <fullName>Solde_de_points__c</fullName>
    <formula>Nombre_de_points_cr_dit_s__c - Nombre_de_points_debites__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Solde de points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/Fidelisation__c.object-meta.xml
<CustomObject>
    <label>Fidélisation</label>
    <nameField>
        <displayFormat>FID-{0000}</displayFormat>
        <label>Nom de Fidélisation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fidélisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fidelisation__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Composition du foyer</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Ce membre de foyer ne fait pas partie de ce foyer ou il n&apos;existe pas</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Foyer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fidelisations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Date_de_traitement__c.field-meta.xml
<CustomField>
    <fullName>Date_de_traitement__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de traitement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fidelisations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Individu_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Individu_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individu Panéliste</label>
    <referenceTo>Individu_Paneliste__c</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fid_lisations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Points_debites__c.field-meta.xml
<CustomField>
    <fullName>Points_debites__c</fullName>
    <label>Points Débités</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/recordTypes/Debit.recordType-meta.xml
<RecordType>
    <fullName>Debit</fullName>
    <active>true</active>
    <description>Points de fidélisation qu&apos;on retire du compte</description>
    <label>Débit</label>
</RecordType>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer Panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Commandes</relationshipLabel>
    <relationshipName>Commandes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/getFoyerPanelisteInformations.cls
public with sharing class getFoyerPanelisteInformations {
    
    @AuraEnabled
    public static wrapperType getInformations(Integer pageNumber, Boolean fromSolde) {
        wrapperType tableData = new wrapperType();
        Integer recordsPerPage = Integer.valueOf(Label.SoldeDesPointRecords);
        tableData.recordsPerPage = recordsPerPage;
        
        //tableData.recordsPerPage = 1;
        pageNumber = pageNumber - 1;
        Integer requestOffset = recordsPerPage * pageNumber;
        
        User connectedUser = [SELECT id, contactId, Contact.Contact_principal__c , Contact.Account.Personne_de_reference__c 
                              FROM user 
                              WHERE id = :UserInfo.getUserId()];
        
        Id contactId = connectedUser.contactId;
        if(String.isNotBlank(contactId)){
            Id foyerId = [SELECT id, Foyer_paneliste__r.Id 
                          FROM Individu_Paneliste__c 
                          WHERE Composition_du_foyer__c = :contactId].get(0).Foyer_paneliste__r.Id;
            
            if(String.isNotBlank(foyerId)){
                tableData.tableRows = [SELECT COUNT() 
                                        FROM Individu_Paneliste__c 
                                        WHERE Foyer_paneliste__c=:foyerId];
	
                List<userWrapperType> newList = new List<userWrapperType>();
                List<String> CompositionDuFoyerIds = new List<String>();
                
                if(tableData.tableRows > 0){
                    String individuPenalisteQuery = 'SELECT Composition_du_foyer__c, Composition_du_foyer__r.Name, Composition_du_foyer__r.Solde_de_points__c ' +
                        							'FROM Individu_Paneliste__c ' +
                        							'WHERE Foyer_paneliste__c = :foyerId ';
                    if(fromSolde && (connectedUser.Contact.Account.Personne_de_reference__c != contactId)){
                        individuPenalisteQuery += 'AND Composition_du_foyer__c = :contactId ';
                    }
                    individuPenalisteQuery += fromSolde ? 'ORDER BY Name ASC NULLS LAST LIMIT :recordsPerPage OFFSET :requestOffset ' : '';
                    System.debug('individuPenalisteQuery ' + individuPenalisteQuery);
                    for (Individu_Paneliste__c individuPenaliste : Database.query(individuPenalisteQuery)) {
                        if(fromSolde){
                            userWrapperType utilisateur = new userWrapperType();
                            utilisateur.Name = individuPenaliste.Composition_du_foyer__r.Name;
                            utilisateur.Solde = String.valueOf(individuPenaliste.Composition_du_foyer__r.Solde_de_points__c);
                            newList.add(utilisateur);
                        }else{
                            CompositionDuFoyerIds.add(individuPenaliste.Composition_du_foyer__c);
                        }
                    }
                    
                    Id debitRecordTypeId = Schema.SObjectType.Fidelisation__c.getRecordTypeInfosByDeveloperName().get('Debit').getRecordTypeId();
                    if(!fromSolde){
                        WRP_Commande wrapperCommande = new WRP_Commande();
                        for(Fidelisation__c fidelisation : [SELECT  Name , CreatedDate, Date_de_traitement__c, Points_debites__c  
                                                            FROM Fidelisation__c 
                                                            WHERE Composition_du_foyer__c IN: CompositionDuFoyerIds AND RecordTypeId = :debitRecordTypeId
                                                            ORDER BY Points_debites__c ASC NULLS LAST 
                                                            LIMIT :recordsPerPage OFFSET :requestOffset]){
                            wrapperCommande = new WRP_Commande(fidelisation.Name, String.valueOf(fidelisation.Points_debites__c/10) + ' €', fidelisation.Date_de_traitement__c,
                                                               fidelisation.CreatedDate.date());
                            tableData.listCommande.add(wrapperCommande);
                        }
                        tableData.tableRows = [SELECT COUNT() 
                                               FROM Fidelisation__c 
                                               WHERE Composition_du_foyer__c IN: CompositionDuFoyerIds AND RecordTypeId = :debitRecordTypeId];
                    }                    
                }
                
                tableData.listUsers = newList;
            }
        }
        return tableData;
    }
    
    public class wrapperType {
        public wrapperType(){
            this.listUsers = new List<userWrapperType>();
            this.tableRows = 0;
            this.listCommande = new List<WRP_Commande>();
        }
        @AuraEnabled
        public List<userWrapperType> listUsers;
        @AuraEnabled
        public Integer tableRows;
        @AuraEnabled
        public Integer recordsPerPage;
        @AuraEnabled
        public List<WRP_Commande> listCommande;
    }
    
    public class userWrapperType {
        @AuraEnabled
        public String Name;
        @AuraEnabled
        public String Solde;
    }
    
    public class WRP_Commande {
        public WRP_Commande(){
            this.numeroOperation = '-';
            this.pointsDebites = '-';
        }
        public WRP_Commande(String numeroOperation, String pointsDebites, Date dateDeTraitement, Date createdDate){
            this.numeroOperation = numeroOperation;
            this.pointsDebites = pointsDebites;
            this.dateDeTraitement = dateDeTraitement;
            this.createdDate = createdDate;
        }
        @AuraEnabled
        public String numeroOperation;
        @AuraEnabled
        public Date createdDate;
        @AuraEnabled
        public Date dateDeTraitement;
        @AuraEnabled
        public String pointsDebites;
    }
}