force-app/main/default/objects/Account/fields/Contact_principal__c.field-meta.xml
<CustomField>
    <fullName>Contact_principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact principal</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Cet individu (Contact Principal) n&apos;existe pas ou n&apos;est pas rattaché à ce foyer.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Foyers (Contact principal)</relationshipLabel>
    <relationshipName>Foyers_en_tant_que_contact_principal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_de_reception_de_la_convention__c.field-meta.xml
<CustomField>
    <fullName>Date_de_reception_de_la_convention__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de réception de la convention</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_de_signature_de_la_convention__c.field-meta.xml
<CustomField>
    <fullName>Date_de_signature_de_la_convention__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de signature de la convention</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Personne_de_reference__c.field-meta.xml
<CustomField>
    <fullName>Personne_de_reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personne de référence</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Cet individu n&apos;existe pas ou n&apos;est pas rattaché à ce foyer.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Foyers</relationshipLabel>
    <relationshipName>Foyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF(
				NOT(ISBLANK(Birthdate)),
				IF(
								DATE(2000, MONTH(Birthdate), DAY(Birthdate)) &lt;= DATE(2000, MONTH(TODAY()), DAY(TODAY())),
        YEAR (Today()) - YEAR ( Birthdate ),
        YEAR (Today()) - YEAR ( Birthdate ) -1
				),
				null
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Âge</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_principal__c.field-meta.xml
<CustomField>
    <fullName>Contact_principal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contact Principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Personne_de_Reference__c.field-meta.xml
<CustomField>
    <fullName>Personne_de_Reference__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Personne de Référence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Membre</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Invité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Non panéliste</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/PaME.recordType-meta.xml
<RecordType>
    <fullName>PaME</fullName>
    <active>true</active>
    <label>PaME</label>
</RecordType>

force-app/main/default/objects/Convention__c/Convention__c.object-meta.xml
<CustomObject>
    <label>Convention</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de Convention</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conventions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Convention__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Conventions</relationshipLabel>
    <relationshipName>Conventions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convention__c/fields/Date_de_signature_de_la_convention__c.field-meta.xml
<CustomField>
    <fullName>Date_de_signature_de_la_convention__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de signature de la convention</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Convention__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Conventions</relationshipLabel>
    <relationshipName>Conventions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convention__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Conventions</relationshipLabel>
    <relationshipName>Conventions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convention__c/fields/Referentiel_convention__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_convention__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel convention</label>
    <referenceTo>Referentiel_convention__c</referenceTo>
    <relationshipLabel>Conventions</relationshipLabel>
    <relationshipName>Conventions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convention__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT( Referentiel_convention__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Convention__c/fields/Type_de_signature__c.field-meta.xml
<CustomField>
    <fullName>Type_de_signature__c</fullName>
    <label>Type de signature</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Electronique</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Papier</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Date_de_signature_de_la_convention__c.field-meta.xml
<CustomField>
    <fullName>Date_de_signature_de_la_convention__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de signature de la convention</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referentiel_convention__c/Referentiel_convention__c.object-meta.xml
<CustomObject>
    <label>Référentiel convention</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du modèle de convention</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel convention</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_convention__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Référentiel convention</relationshipLabel>
    <relationshipName>Referentiel_convention</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referentiel_convention__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <description>Si la date de fin est supérieure à la date d’aujourd’hui, le statut passe à « inactif »</description>
    <formula>IF( AND(Date_de_debut__c &lt;= TODAY(), OR(TODAY() &lt;= Date_de_fin__c,  ISNULL(Date_de_fin__c) )), &apos;Actif&apos;, &apos;Inactif&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Statut</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referentiel_convention__c/fields/Type_de_la_convention__c.field-meta.xml
<CustomField>
    <fullName>Type_de_la_convention__c</fullName>
    <label>Type de la convention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Foyer</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Individu</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Routeur</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchRDD13_ConventionsFoyerRouteur.cls
/*
* @author: Bastien Pinard
* @date: 22/12/2022
* @ Description 
* @TestClass: BatchRDD013_Conventions_Test
* @Coverage: 
* History
* <Date of modification>   		<Author>   		 <Description of modification>
*/
public class BatchRDD13_ConventionsFoyerRouteur implements Database.Batchable<sObject> { 
    
    public Database.Querylocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, Foyer__r.Date_de_reception_de_la_convention__c, Foyer__r.Date_de_signature_de_la_convention__c, 
            Foyer__r.Contact_principal__c, Foyer__r.personne_de_reference__c, Referentiel_Panel__r.Type_de_panel__c, Foyer__c, foyer__r.name
            FROM Foyer_Paneliste__c 
            WHERE Foyer__r.Date_de_reception_de_la_convention__c != null OR Foyer__r.Date_de_signature_de_la_convention__c != null
        ]);
    }
    
    public void execute(Database.BatchableContext bc, List<Foyer_Paneliste__c> scope) {
        System.debug('$$$BatchRDD013_Conventions scope : '+ scope);
        List<Referentiel_convention__c> refConvList = [SELECT Id, Referentiel_Panel__r.Type_de_panel__c, Type_de_la_convention__c  
                                                       FROM Referentiel_convention__c 
                                                       WHERE Statut__c=:label.Ref_Conv_Statut_Actif];
        
        List<Convention__c> conventionToInsertList = new List<Convention__c>();
        List<Contact> compositionFoyerList = new List<Contact>();
        Map<Id, Id> foyerIdFoyerPanelisteIdMap = new map<Id, Id>();
        Map<Id, Id> foyerPanelisteIdCompositionFoyerIdMap = new Map<Id, Id>();
        for(Foyer_Paneliste__c foyerPan: scope) {
            if(foyerPan.Referentiel_Panel__r.Type_de_panel__c == label.RFP_TypePanel_AIP) {
                foyerIdFoyerPanelisteIdMap.put(foyerPan.Foyer__c, FoyerPan.Id);
            }
        }
            
        compositionFoyerList = [SELECT Id, AccountId, Account.personne_de_reference__c,age__c 
                                FROM Contact 
                                WHERE (AccountId IN :foyerIdFoyerPanelisteIdMap.keySet()) AND Type__c = :Label.CON_Type_Membre];
        for(Contact compoFoyer:compositionFoyerList) {
            if(compofoyer.age__c >= 18) {
                foyerPanelisteIdCompositionFoyerIdMap.put(foyerIdFoyerPanelisteIdMap.get(compoFoyer.AccountId), compoFoyer.Id);
            }
            else {
                foyerPanelisteIdCompositionFoyerIdMap.put(foyerIdFoyerPanelisteIdMap.get(compoFoyer.AccountId), compoFoyer.Account.personne_de_reference__c);
            }
            
        }
        
        for(Foyer_Paneliste__c foyerPan: scope) {
            Convention__c convention = new Convention__c();
            //Convention Foyer MMT
            if (foyerPan.Referentiel_Panel__r.Type_de_panel__c == label.RFP_TypePanel_MMAT) {
                for(Referentiel_convention__c refConv : refConvList){
                    if(refConv.Referentiel_Panel__r.Type_de_panel__c == label.RFP_TypePanel_MMAT && refConv.Type_de_la_convention__c == Label.RFC_Type_Convention_Foyer){
                        convention.Referentiel_convention__c = refConv.Id;
                    }
                }
                convention.name = 'Convention Foyer ' +  foyerPan.foyer__r.name + ' ' + label.RFP_TypePanel_MMAT;
                convention.foyer_Paneliste__c = foyerPan.Id;
                convention.composition_du_Foyer__c = foyerPan.Foyer__r.Contact_principal__c;
                convention.Type_de_signature__c = Label.RFC_Type_Signature_Electronique;
                if(foyerPan.Foyer__r.Date_de_signature_de_la_convention__c != null) {
                    convention.Date_de_signature_de_la_convention__c = foyerPan.Foyer__r.Date_de_signature_de_la_convention__c;
                }
                else {
                    convention.Date_de_signature_de_la_convention__c = foyerPan.Foyer__r.Date_de_reception_de_la_convention__c;
                }
            }
            
            //Convention PaME
            else if (foyerPan.Referentiel_Panel__r.Type_de_panel__c == label.RFP_TypePanel_PaME) {
                //Convention Foyer PaME
                for(Referentiel_convention__c refConv : refConvList){
                    if(refConv.Referentiel_Panel__r.Type_de_panel__c == label.RFP_TypePanel_PaME && refConv.Type_de_la_convention__c == Label.RFC_Type_Convention_Foyer){
                        convention.Referentiel_convention__c = refConv.Id;
                    }
                }
                convention.name = 'Convention Foyer ' +  foyerPan.foyer__r.name + ' ' + label.RFP_TypePanel_PaME;
                convention.foyer_Paneliste__c = foyerPan.Id;
                convention.composition_du_Foyer__c = foyerPan.Foyer__r.Contact_principal__c;
                if(foyerPan.Foyer__r.Date_de_signature_de_la_convention__c != null) {
                    convention.Date_de_signature_de_la_convention__c = foyerPan.Foyer__r.Date_de_signature_de_la_convention__c;
                	convention.Type_de_signature__c = Label.RFC_Type_Signature_Electronique;
                }
                else {
                    convention.Date_de_signature_de_la_convention__c = foyerPan.Foyer__r.Date_de_reception_de_la_convention__c;
                	convention.Type_de_signature__c = Label.RFC_Type_Signature_Papier;
                }
                
                //Convention Routeur PaME
                Convention__c conventionRouteur = new Convention__c();
                for(Referentiel_convention__c refConv : refConvList){
                    if(refConv.Referentiel_Panel__r.Type_de_panel__c == label.RFP_TypePanel_PaME && refConv.Type_de_la_convention__c == Label.RFC_Type_Convention_Routeur){
                        conventionRouteur.Referentiel_convention__c = refConv.Id;
                    }
                }
                conventionRouteur.name = 'Convention Routeur ' +  foyerPan.foyer__r.name + ' ' + label.RFP_TypePanel_PaME;
                conventionRouteur.foyer_Paneliste__c = foyerPan.Id;
                conventionRouteur.composition_du_Foyer__c = foyerPan.Foyer__r.Contact_principal__c;
                conventionRouteur.Type_de_signature__c = Label.RFC_Type_Signature_Electronique;
                if(foyerPan.Foyer__r.Date_de_signature_de_la_convention__c != null) {
                    conventionRouteur.Date_de_signature_de_la_convention__c = foyerPan.Foyer__r.Date_de_signature_de_la_convention__c;
                }
                else {
                    conventionRouteur.Date_de_signature_de_la_convention__c = foyerPan.Foyer__r.Date_de_reception_de_la_convention__c;
                }
                conventionToInsertList.add(conventionRouteur);
            }
            conventionToInsertList.add(convention);
        }
                
        if(conventionToInsertList.size() > 0 && conventionToInsertList != null) {
            try{ 
                database.insert(conventionToInsertList, true);
            }Catch(exception ex){
                system.debug('Insert convention Exception Error:' + ex.getmessage());
            }
        }
        
    }
    
    public void finish(Database.BatchableContext bc) {
    }
}