force-app/main/default/objects/Account/fields/Contact_principal__c.field-meta.xml
<CustomField>
    <fullName>Contact_principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact principal</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Cet individu (Contact Principal) n&apos;existe pas ou n&apos;est pas rattaché à ce foyer.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Foyers (Contact principal)</relationshipLabel>
    <relationshipName>Foyers_en_tant_que_contact_principal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Chute_confirmee__c.field-meta.xml
<CustomField>
    <fullName>Chute_confirmee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Chute confirmée</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contact_sur_place__c.field-meta.xml
<CustomField>
    <fullName>Contact_sur_place__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact principal</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Cet individu est un invité ou ne fait pas partie de ce foyer ou n&apos;existe pas.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Type__c</field>
            <operation>notEqual</operation>
            <value>Invité</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_principal__c</field>
            <operation>equals</operation>
            <value>true</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Contact sur place)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Jour_de_traitement__c.field-meta.xml
<CustomField>
    <fullName>Jour_de_traitement__c</fullName>
    <formula>IF(DATEVALUE(CreatedDate) &gt;= DATE(2023,04,27), TODAY() - DATEVALUE(CreatedDate) + 1, TODAY() - DATEVALUE(CreatedDate) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Etape J</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sous_type__c.field-meta.xml
<CustomField>
    <fullName>Sous_type__c</fullName>
    <label>Sous-type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Absence collecte</fullName>
            </value>
            <value>
                <fullName>Absence mouvement</fullName>
            </value>
            <value>
                <fullName>Adaptateur casque</fullName>
            </value>
            <value>
                <fullName>Anomalie affichage</fullName>
            </value>
            <value>
                <fullName>Anomalie autre</fullName>
            </value>
            <value>
                <fullName>Anomalie batterie</fullName>
            </value>
            <value>
                <fullName>Anomalie carte Sim</fullName>
            </value>
            <value>
                <fullName>Anomalie des données en base panel</fullName>
            </value>
            <value>
                <fullName>Anomalie horloge</fullName>
            </value>
            <value>
                <fullName>Anomalie informations</fullName>
            </value>
            <value>
                <fullName>Anomalie lors du traitement des données d&apos;audience</fullName>
            </value>
            <value>
                <fullName>A quitte la mesure</fullName>
            </value>
            <value>
                <fullName>Audience individuelle &gt;7h</fullName>
            </value>
            <value>
                <fullName>Audience individuelle &gt; 7h</fullName>
                <isActive>false</isActive>
                <label>Audience individuelle &gt; 7h</label>
            </value>
            <value>
                <fullName>Audimètre</fullName>
            </value>
            <value>
                <fullName>Audimètre non connecté</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon batterie faible</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon inactif</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon jamais détecté</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Autre cause technique</fullName>
            </value>
            <value>
                <fullName>Autre déplacement</fullName>
            </value>
            <value>
                <fullName>Autre déplacement hors zone de mesure</fullName>
            </value>
            <value>
                <fullName>Autres usages</fullName>
            </value>
            <value>
                <fullName>Avis</fullName>
            </value>
            <value>
                <fullName>Beacon</fullName>
            </value>
            <value>
                <fullName>Beacon (logement plus grand)</fullName>
            </value>
            <value>
                <fullName>Beacon(s) Réceptionné(s)</fullName>
            </value>
            <value>
                <fullName>Beacon (tv en plus)</fullName>
            </value>
            <value>
                <fullName>Beacon (vehicule supplémentaire)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Batch022_CreationRequete_RetourMateriel.cls
/*
YH 19/01/2023
batch pour créer un case retour matériel (type suivi retour materiel chute) après 46j

*/

global class Batch022_CreationRequete_RetourMateriel implements Database.Batchable<sObject>, Database.AllowsCallouts{

    //Added for email notification - START
    global String errorTxt = '';
    global Boolean containsErrors = false;
    //Added for email notification - END
    
             Id recordTypeIdRequeteDemandePanelisteAIP =Schema.SObjectType.Case.getRecordTypeInfosByName().get(label.CAS_Recordtype_DemandePanelisteAIP).getRecordTypeId();

    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        integer jour_trait=46;
        string query = 'select id,Foyer_paneliste__c,AccountId, Account.Contact_principal__c,Contact_sur_place__c  from case where RecordTypeId =:recordTypeIdRequeteDemandePanelisteAIP and Chute_confirmee__c=true and Jour_de_traitement__c=:jour_trait';
     
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Case> scope){
        boolean inserer=false;
 		list <case> caseToInsert = new list <case>();
        set<id> idFoyPan = new set<id>();
        list<Foyer_paneliste__c> foyPanel = new list<Foyer_paneliste__c>();
        map<id,list<asset>> mapFoyAss = new map <id,list<asset>>();
        for (case cs:scope){
            idFoyPan.add(cs.Foyer_paneliste__c);
        }
       foyPanel = [select id , (select id ,status from  Equipements__r) from Foyer_paneliste__c where id in :idFoyPan];
        for (Foyer_paneliste__c foy:foyPanel){
            mapFoyAss.put(foy.id,foy.Equipements__r);
        }
        for (case cs:scope){
            for (asset equip:mapFoyAss.get(cs.Foyer_paneliste__c)){
                if (equip.status==label.ASS_Statut_Installe){
                   
					caseToInsert.add(new case(RecordTypeId=recordTypeIdRequeteDemandePanelisteAIP,Foyer_paneliste__c=cs.Foyer_paneliste__c , AccountId=cs.AccountId,Origin=Label.CAS_Origine_ProcessusDeRestitution,type=Label.CAS_Type_Suivi_Chute,Sous_type__c=Label.CAS_SousType_RestitutionDuMateriel));
					break;
                }
               
            }
        }
        
       
        if(caseToInsert.size()>0 && caseToInsert!=null){
            try{ 
                system.debug('insert'+caseToInsert);
                database.Insert(caseToInsert);
            }Catch(exception ex){
                
                errorTxt += 'Erreur durant la création des requêtes : ' + ex.getMessage() + '\n';
                containsErrors = true;
            }
        }
    }
    global void finish(Database.BatchableContext bc){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        List<String> toMailAddress = System.Label.BatchNotif_B022_ToAddress.split(';');
        
        mail.setToAddresses(toMailAddress);
        mail.setSenderDisplayName(System.Label.BatchNotif_B022_SenderName);
        mail.setSubject(System.Label.BatchNotif_B022_Subject+'-'+date.today().format());
        
        String emailBody = 'L\'exécution du batch Batch022_CreationRequete_RetourMateriel s\'est terminée.\n';
        if(containsErrors) {
            emailBody += 'Les erreurs suivantes ont été rencontrées :\n\n';
            emailBody += errorTxt;
        } else {
            emailBody += 'Aucune erreur n\'a été relevée.';
        }
        mail.setPlainTextBody(emailBody);
        
        if(!Test.isRunningTest()) {
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }
}