force-app/main/default/objects/Account/fields/Date_de_chute__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Personne_de_reference__c.field-meta.xml
<CustomField>
    <fullName>Personne_de_reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personne de référence</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Cet individu n&apos;existe pas ou n&apos;est pas rattaché à ce foyer.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Foyers</relationshipLabel>
    <relationshipName>Foyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Personne_de_Reference__c.field-meta.xml
<CustomField>
    <fullName>Personne_de_Reference__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Personne de Référence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/Fidelisation__c.object-meta.xml
<CustomObject>
    <label>Fidélisation</label>
    <nameField>
        <displayFormat>FID-{0000}</displayFormat>
        <label>Nom de Fidélisation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fidélisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fidelisation__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Composition du foyer</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Ce membre de foyer ne fait pas partie de ce foyer ou il n&apos;existe pas</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Foyer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fidelisations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fid_lisations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fidelisations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Individu_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Individu_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individu Panéliste</label>
    <referenceTo>Individu_Paneliste__c</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fid_lisations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Date_de_chute__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Date_de_chute_de_l_individu__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute_de_l_individu__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute de l&apos;individu</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Individus Panélistes</relationshipLabel>
    <relationshipName>Individus_Paneliste</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchRDD016_FidelisationChampObligatoire.cls
/*
* @author: Mikael Chaaya
* @date: 31/05/2023
* @ Description Batch pour la RDD de l'objet Fidelisation pour remplire les champ Individu paneliste et Composition Foyer :
		si Composition_foyer__c = null and Individu_paneliste__c = null 
			=> Reprendre les id de la PDR
		si Composition_foyer__c = null and Individu_paneliste__c <> null 
			=> Reprendre l’id Composition_foyer__c correspondant à l’Individu_paneliste__c / Composition_foyer__c = Individu_paneliste__r.Composition_foyer__c
		si Composition_foyer__c <> null and Individu_paneliste__c = null 
			=> Reprendre l’id Individu_paneliste__c correspondant à l’id Composition_foyer__c / Individu_paneliste__c = Select id from Individu_paneliste__c where Composition_foyer__c = Composition_foyer__c
* @TestClass: BatchRDD016_FidelisationChampOblTest
* @Coverage: 96%
* History
* <Date of modification>   		<Author>   		 <Description of modification>
*/
public class BatchRDD016_FidelisationChampObligatoire implements Database.Batchable<sObject>{

    public Database.QueryLocator start(Database.BatchableContext bc) {
        String refPanelAIP=Label.RFP_Nom_AIP;
            return Database.getQueryLocator([SELECT Id, Foyer__c, Foyer__r.Personne_de_reference__c,Foyer__r.Personne_de_reference__r.AccountId, Foyer_Paneliste__c,Composition_du_foyer__c,
                                                     Foyer_paneliste__r.Referentiel_Panel__r.Name,Individu_paneliste__c, Individu_paneliste__r.Date_de_chute_de_l_individu__c ,
                                                     Individu_paneliste__r.Composition_du_foyer__c,Composition_du_foyer__r.AccountId
                                             FROM Fidelisation__c 
                                             WHERE ((Composition_du_foyer__c=null
                                                     AND 
                                                    Individu_paneliste__c<>null
                                                    AND
                                                    Individu_paneliste__r.Date_de_chute_de_l_individu__c=null
                                                      )
                                                 OR(Composition_du_foyer__c<>null
                                                     AND 
                                                    Individu_paneliste__c=null
                                                    AND 
                                                    Composition_du_foyer__r.AccountId <>null
                                                  )
                                                 OR(Composition_du_foyer__c=null
                                                   AND Individu_paneliste__c=null
                                                   AND Foyer__r.Personne_de_reference__c<> null
                                                  )
                                                OR(Composition_du_foyer__c=null
                                                   AND Individu_paneliste__c=null
                                                   AND Foyer_paneliste__r.Referentiel_Panel__r.Name=:refPanelAIP
                                                  )
                                                )
                                                  AND  Foyer__r.Name<>'Foyer anonymisé'
                                                  AND Foyer__r.Date_de_chute__c =null
                                                  AND Foyer__r.Personne_de_reference__r.AccountId <>null
    
                                            ]);
     
        }
        
        public void execute(Database.BatchableContext bc, List<Fidelisation__c> scope) {
            
           //Map<Id, Account> foyerMap = new Map<Id, Account>();
            Set<Id> contactIdSet=new Set<Id>();
            Set<Id> fpIdSet=new Set<Id>();
            String refPanelAIP=Label.RFP_Nom_AIP;
            List<Fidelisation__c> fidToUpdate = new List<Fidelisation__c>();
            Map<Id,Individu_paneliste__c> contactIdToIndivPanMap=new Map<Id,Individu_paneliste__c>();
            Map<Id,Individu_paneliste__c> fpIdToIndivPanMap=new Map<Id,Individu_paneliste__c>();
            for(Fidelisation__c f: scope) {
                contactIdSet.add(f.Foyer__r.Personne_de_reference__c);
                contactIdSet.add(f.Composition_du_foyer__c);
                System.debug('MM');
                System.debug(f.Foyer_paneliste__r.Referentiel_Panel__r.Name);
                System.debug(refPanelAIP);
                if(f.Foyer_paneliste__r.Referentiel_Panel__r.Name.contains(refPanelAIP)){
                    fpIdSet.add(f.Foyer_paneliste__c); 
                }    
            }
            
            List<Individu_paneliste__c> individuList = [SELECT Id,Foyer_paneliste__c, Composition_du_foyer__c,Date_de_chute_de_l_individu__c
                                                        FROM Individu_paneliste__c
                                                        WHERE Composition_du_foyer__c IN :contactIdSet
                                                            OR Foyer_paneliste__c IN :fpIdSet
                                                       ];
            for(Individu_paneliste__c ind : individuList){
                if(fpIdSet.contains(ind.Foyer_paneliste__c))
                {
                    fpIdToIndivPanMap.put(ind.Foyer_paneliste__c, ind);
                }
                else{
                    contactIdToIndivPanMap.put(ind.Composition_du_foyer__c, ind);
                }
                
            }
            
            
            for(Fidelisation__c f: scope) {
                if (f.Composition_du_foyer__c == null && f.Individu_paneliste__c==null) { 
                    if(f.Foyer_paneliste__r.Referentiel_Panel__r.Name==refPanelAIP){
                        //f.Composition_du_foyer__c=f.Foyer__r.Personne_de_reference__c;
                        f.Individu_paneliste__c=fpIdToIndivPanMap.get(f.Foyer_paneliste__c)?.Id;
                        f.Composition_du_foyer__c=fpIdToIndivPanMap.get(f.Foyer_paneliste__c)?.Composition_du_foyer__c;
                        fidToUpdate.add(f);
                    }
                    else{
                        f.Composition_du_foyer__c=f.Foyer__r.Personne_de_reference__c;
                        f.Individu_paneliste__c=contactIdToIndivPanMap.get(f.Foyer__r.Personne_de_reference__c)?.Id;
                        fidToUpdate.add(f);
                    }
                }
                else if(f.Composition_du_foyer__c == null && f.Individu_paneliste__c!=null){
                    if( f.Individu_paneliste__r.Date_de_chute_de_l_individu__c==null)
                    {
                        f.Composition_du_foyer__c=f.Individu_paneliste__r.Composition_du_foyer__c;
                        fidToUpdate.add(f);
                    }        
                }
                 else if(f.Composition_du_foyer__c != null && f.Individu_paneliste__c==null){
                    
                    if(contactIdToIndivPanMap.get(f.Composition_du_foyer__c)?.Date_de_chute_de_l_individu__c==null){
                        f.Individu_paneliste__c=contactIdToIndivPanMap.get(f.Composition_du_foyer__c)?.Id;
                        fidToUpdate.add(f);
                    }
                     
                }
            }
            
            if(scope.size() > 0 && scope != null) {
                try{ 
                    update fidToUpdate;
                }Catch(exception ex){
                    system.debug('RDD016 Update Fidelisation Exception Error:' + ex.getmessage());
                }
            }
        }
        
        public void finish(Database.BatchableContext bc) {
            
        }    
        
    }