force-app/main/default/objects/Account/fields/Date_d_installation__c.field-meta.xml
<CustomField>
    <fullName>Date_d_installation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;installation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_de_portable__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_portable__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Numéro de téléphone portable</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/Batch00X_BatchModifiable_Test.cls
/*
* @author: Maribelle ZARAZIR
* @date: 27/05/2021
* @ Description Class that test Batch00X_BatchModifiable 
*/

@isTest
public class Batch00X_BatchModifiable_Test {
    public static testMethod void Batch00X_CreditAutomatiqueTest(){
        
        //insert Account(foyer)
        list<Account> listFoyersToInsert = new list<Account>();
        account testAccount = Test_Utils.createFoyer();
        testAccount.Date_d_installation__c = date.newInstance(2021, 4, 21); //system.today()-60;
        testAccount.Numero_de_portable__c = '0611111121';
        listFoyersToInsert.add(testAccount);
        
        insert listFoyersToInsert;	 
        Test.startTest();
        Batch00X_BatchModifiable batch = new Batch00X_BatchModifiable();
        database.executeBatch(batch);
        Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(testAccount.id)); 
        Test.stopTest();
    }
}