force-app/main/default/objects/Account/fields/Date_d_installation__c.field-meta.xml
<CustomField>
    <fullName>Date_d_installation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;installation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_de_chute__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_de_chute_temporaire__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute_temporaire__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute temporaire</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Intervention_en_cours__c.field-meta.xml
<CustomField>
    <fullName>Intervention_en_cours__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Intervention en cours</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_de_portable__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_portable__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Numéro de téléphone portable</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Statut_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Statut_du_foyer__c</fullName>
    <label>Statut du foyer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Recruté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Installé</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Equipé</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Integré</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Désinstallé</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Chute définitive</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chute temporaire</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CON_ExtId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>CON_ExtId_SIPanel__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>CON_ExtId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/CSP42__c.field-meta.xml
<CustomField>
    <fullName>CSP42__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code profession CSP42</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CSP4__c.field-meta.xml
<CustomField>
    <fullName>CSP4__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code profession CSP4</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Lien_parente__c.field-meta.xml
<CustomField>
    <fullName>Lien_parente__c</fullName>
    <label>Lien parenté</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Chef de famille</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Conjoint</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Enfant</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Ascendant</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Autre</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Membre</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Invité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Non panéliste</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fidelisation__c/Fidelisation__c.object-meta.xml
<CustomObject>
    <label>Fidélisation</label>
    <nameField>
        <displayFormat>FID-{0000}</displayFormat>
        <label>Nom de Fidélisation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fidélisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fidelisation__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fid_lisations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fidelisations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT(Foyer_paneliste__r.Referentiel_Panel__r.Type_de_panel__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/recordTypes/Credit.recordType-meta.xml
<RecordType>
    <fullName>Credit</fullName>
    <active>true</active>
    <description>Points de fidélisation qu&apos;on ajoute sur le compte</description>
    <label>Crédit</label>
</RecordType>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Date_d_installation__c.field-meta.xml
<CustomField>
    <fullName>Date_d_installation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;installation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Date_de_chute__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Date_de_chute_temporaire__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute_temporaire__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute temporaire</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Intervention_en_cours__c.field-meta.xml
<CustomField>
    <fullName>Intervention_en_cours__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Intervention en cours</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Statut_Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Statut_Foyer_paneliste__c</fullName>
    <label>Statut Foyer Panéliste</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Foyer_equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Recruté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Installé</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Equipé</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Intégré</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Désinstallé</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chute temporaire</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Chute définitive</label>
            </value>
            <value>
                <fullName>Chute définitive et désinstallé</fullName>
                <isActive>false</isActive>
                <label>Chute définitive et désinstallé</label>
            </value>
            <value>
                <fullName>Désinstallé actif</fullName>
                <isActive>false</isActive>
                <label>Désinstallé actif</label>
            </value>
            <value>
                <fullName>Recruté en attente d&apos;installation</fullName>
                <isActive>false</isActive>
                <label>Recruté en attente d&apos;installation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Individus Panélistes</relationshipLabel>
    <relationshipName>Individus_Paneliste</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invité</fullName>
            </value>
            <value>
                <fullName>Membre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT( Foyer_paneliste__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_flows__c.field-meta.xml
<CustomField>
    <fullName>Bypass_flows__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass flows</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_validation_rules__c.field-meta.xml
<CustomField>
    <fullName>Bypass_validation_rules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass validation rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Batch009_Debit_RemiseSoldeAZero_Test.cls
/*
* @author: Maribelle ZARAZIR EI
* @date: 08/2021
* @ Description Test class for Batch009_Debit_RemiseSoldeAZero
* @Coverage: 88%
* History
* <Date of modification>   <Author>    <Description of modification>
*/

@isTest
public class Batch009_Debit_RemiseSoldeAZero_Test {
   
    
     @istest
    static void createTestData() {
        
        User u= [SELECT Id, Bypass_validation_rules__c FROM User where  isactive=true and Profile.Name like '%admin%' limit 1];
    u.Bypass_flows__c=true;
        u.Bypass_validation_rules__c=true;
    update u;
        system.runAs(u){
        list<Account> listFoyersToInsert = new list<Account>();
        
        account testAccount = Test_Utils.createFoyer();
        testAccount.Date_d_installation__c = system.today() - 120;
        testAccount.Numero_de_portable__c = '0611111121';
        testAccount.Date_de_chute__c = system.today() - 80;
        //testAccount.Statut_du_foyer__c='5';
        listFoyersToInsert.add(testAccount);
        
        insert listFoyersToInsert;
        
        Referentiel_Panel__c refPanPaME = new Referentiel_Panel__c();
        refPanPaME.name = Label.RFP_Nom_PaME;
        refPanPaME.Type_de_panel__c = Label.RFP_TypePanel_PaME;
        insert refPanPaME;
        
        Foyer_Paneliste__c foyerPaneliste = new Foyer_Paneliste__c();
        foyerPaneliste.foyer__c = testAccount.Id;
        foyerPaneliste.name = 'FOyer Pan';
        foyerPaneliste.Statut_Foyer_paneliste__c='5';
        foyerPaneliste.Date_de_chute__c=Date.today().adddays(-80);
        foyerPaneliste.Date_de_chute_temporaire__c=Date.today().adddays(-80);
        foyerPaneliste.referentiel_panel__c = refPanPaME.Id;
        foyerPaneliste.Intervention_en_cours__c = false;
        Insert foyerPaneliste;
            
        foyerPaneliste.Date_de_chute__c=Date.today().adddays(-80);
        foyerPaneliste.Date_de_chute_temporaire__c=Date.today().adddays(-80);
            update foyerPaneliste;
        system.debug('fp'+foyerPaneliste.Date_de_chute__c);
        //compo foyer
        list<Contact> listMembreFoyerToInsert = new list<Contact>();
            Contact Cont = new Contact();
            Cont.AccountId = testAccount.id;
            Cont.Lastname = 'compoFoyerLastName1';
            Cont.FirstName='cc';
            Cont.Lien_parente__c='1';
            Cont.Type__c='1';
            Cont.CSP42__c='ttt';
            Cont.CSP4__c='ddd';
            Cont.Birthdate = date.today().addDays(- 10000);
            Cont.CON_ExtId_SIPanel__c = '122221111';
            Cont.Lien_de_parente_stat__c=Label.CON_LienParenteStat_Parent;
            Cont.Lettre__c='A'; 
                listMembreFoyerToInsert.add(Cont);
        
        insert listMembreFoyerToInsert;
        
        
       
        list<Individu_Paneliste__c> listIndividuPanelisteToInsert = new list<Individu_Paneliste__c>();
            Individu_Paneliste__c indPantest = new Individu_Paneliste__c();
                indPanTest.name = 'indPanTest1';
                indPanTest.Lettre__c = 'B';
                indPanTest.Foyer_paneliste__c = foyerPaneliste.id;
                indPanTest.Composition_du_foyer__c = cont.id;
                indPanTest.Date_de_chute_de_l_individu__c = null;
                indPanTest.Date_de_derniere_activite_mobile__c=Date.today().addDays(-1);
                listIndividuPanelisteToInsert.add(indPanTest);
        
        insert listIndividuPanelisteToInsert;
        
        
        Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(testAccount.id)); 
        
        Id creditRecordTypeId = Schema.SObjectType.Fidelisation__c.getRecordTypeInfosByDeveloperName().get('Credit').getRecordTypeId();
        
        list<Fidelisation__c> listFidelisationsToInsert = new list<Fidelisation__c>();
        
        Fidelisation__c ligneCredit = new Fidelisation__c(
            ACC_EXTId_SIPanel__c = testAccount.ACC_EXTId_SIPanel__c,
            Foyer__c = testAccount.Id,
            Points_credites__c = 2500,
            Composition_du_foyer__c=Cont.Id,
            Individu_paneliste__c=indPanTest.Id,
            Foyer_paneliste__c=foyerPaneliste.id,
            Solde_de_points_a_creation__c = testAccount.Solde_de_points__c,
            RecordTypeId = creditRecordTypeId,
            Motif_de_credit__c='1',
            Type_de_mouvement__c = '6' //credit automatique
        );
        
        listFidelisationsToInsert.add(ligneCredit);
        
        insert ligneCredit;

        
        //Account testAccount = [SELECT Id, Solde_de_points__c FROM Account LIMIT 1]; 
        
        
        Test.startTest();
        Batch009_Debit_RemiseSoldeAZero btch = new Batch009_Debit_RemiseSoldeAZero();
           
        database.executeBatch(btch);
        Test.stopTest();
        }
    }
}