force-app/main/default/objects/Account/fields/Date_d_installation__c.field-meta.xml
<CustomField>
    <fullName>Date_d_installation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;installation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Batterie__c.field-meta.xml
<CustomField>
    <fullName>Batterie__c</fullName>
    <label>Niveau de Batterie</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Ordinateur fixe</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Ordinateur portable</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Tablette</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Smartphone</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT ( Bande_Usine__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Utilisateur_principal__c.field-meta.xml
<CustomField>
    <fullName>Utilisateur_principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utilisateur principal</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Cet individu n&apos;existe pas dans la base de données ou ne fait pas partie de ce foyer.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Équipements</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Poste.recordType-meta.xml
<RecordType>
    <fullName>Poste</fullName>
    <active>true</active>
    <label>Poste</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Membre</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Invité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Non panéliste</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/Equipements_du_foyer__c.object-meta.xml
<CustomObject>
    <label>Equipement du foyer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;équipement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipements du foyer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Batterie__c.field-meta.xml
<CustomField>
    <fullName>Batterie__c</fullName>
    <label>Batterie</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Date_d_installation__c.field-meta.xml
<CustomField>
    <fullName>Date_d_installation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;installation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Emplacement__c.field-meta.xml
<CustomField>
    <fullName>Emplacement__c</fullName>
    <label>Emplacement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Salon</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Chambre parent(s)</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Chambre enfant(s)</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Cuisine</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Autre pièce</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Bureau</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Chambre d&apos;amis</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Salle à manger</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Salle de jeux</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Séjour/salon/salle à manger</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Entrée/Couloir</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Equipements du foyer</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Equipements du foyer</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>7</fullName>
                <label>Ordinateur fixe</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Ordinateur portable</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Tablette</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Mobile</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Poste TV</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Lecteur DVD</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Console de jeux</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Magnétoscope</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Décodeur</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Divers</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Box</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Caster</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Objet Connecté</label>
            </value>
            <value>
                <fullName>17</fullName>
                <isActive>false</isActive>
                <label>Autre équipement</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Utilisateur_principal__c.field-meta.xml
<CustomField>
    <fullName>Utilisateur_principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utilisateur principal</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Ce contact n&apos;appartient au foyer de l&apos;équipement.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Foyer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Equipements du foyer</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Date_d_installation__c.field-meta.xml
<CustomField>
    <fullName>Date_d_installation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;installation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Numero_foyer__c.field-meta.xml
<CustomField>
    <fullName>Numero_foyer__c</fullName>
    <label>Numéro foyer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/recordTypes/AIP.recordType-meta.xml
<RecordType>
    <fullName>AIP</fullName>
    <active>true</active>
    <label>AIP</label>
</RecordType>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Individus Panélistes</relationshipLabel>
    <relationshipName>Individus_Paneliste</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invité</fullName>
            </value>
            <value>
                <fullName>Membre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT( Foyer_paneliste__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/getEquipementsduFoyer_Test.cls
@isTest
public class getEquipementsduFoyer_Test {
    @isTest
    static void tesEquipementsduFoyer(){
        
        Id RecordTypeAIP= Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get('AIP').getRecordTypeId();
        //Id RecordTypeAIP=[SELECT Id from RecordType where DeveloperName ='AIP' ];
        // Create test data
       Profile testProfile = [SELECT Id FROM Profile WHERE UserType = 'CspLitePortal' LIMIT 1];
        UserLicense ul = [SELECT Id FROM UserLicense WHERE Name = 'Customer Community' LIMIT 1];
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        
        Contact testContact = new Contact(
            AccountId = testAccount.Id,
            FirstName = 'Test First Name',
            LastName = 'Test Last Name',
            Birthdate = Date.newInstance(1990, 5, 2),
            Type__c = '1'
        );
        insert testContact;
        Referentiel_Panel__c referentiel = new Referentiel_Panel__c(Type_de_panel__c = 'AIP');
            insert referentiel;
        
        
        Foyer_paneliste__c testFoyerPaneliste = new Foyer_paneliste__c(
            Numero_foyer__c = 765438,
            RecordTypeId = RecordTypeAIP,
            Referentiel_Panel__c = referentiel.Id
        );
        insert testFoyerPaneliste;
        
        Individu_Paneliste__c testIndividuPaneliste = new Individu_Paneliste__c(
            Composition_du_foyer__c = testContact.Id,
            Foyer_paneliste__c = testFoyerPaneliste.Id
        );
        insert testIndividuPaneliste;
        
        Equipements_du_foyer__c testEquipement = new Equipements_du_foyer__c(
            Foyer__c = testAccount.Id,
            Type__c = '1',
            Batterie__c = 100,
            Emplacement__c = '1',
            Date_d_installation__c = Date.today(),
            Utilisateur_principal__r = testContact
        );
        insert testEquipement;
        asset poste = new asset();
        poste.AccountId=testAccount.id;
        poste.Foyer_paneliste__c=testFoyerPaneliste.id;
        poste.Type_de_materiel__c='34';
        poste.Audimetre__c='lkjo';
        insert poste;
        
        asset poste1 = new asset();
        poste1.AccountId=testAccount.id;
        poste1.Foyer_paneliste__c=testFoyerPaneliste.id;
        poste1.Type_de_materiel__c='31';
        poste1.Audimetre__c='ljhkojh';
        insert poste1;
        
        User testUser = new User(
            FirstName = 'Test UserBz',
            LastName = 'Test UserBz',
            Email = 'UserBz@example.com',
            Username = 'UserBz@example.com',
            Alias = 'tuser',
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = testProfile.Id,
            LanguageLocaleKey = 'en_US',
              ContactId = testContact.Id,
            Bypass_flows__c = true
        );
        insert testUser;
        
        Test.startTest();
        System.runAs(testUser) {
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
            
            getEquipementsduFoyer.wrapperType result = getEquipementsduFoyer.getEquipementsduFoyer();
            
            
            if (result.equipements.size()>0){
                getEquipementsduFoyer.EquipmentWrapper equipment = result.equipements[0];
            
            //System.assertEquals('Poste TV', equipment.type);
            
                
            }
        }
        Test.stopTest();
    }
}