force-app/main/default/objects/Account/fields/Date_de_chute__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_de_chute_temporaire__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute_temporaire__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute temporaire</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Statut_audimetrique__c.field-meta.xml
<CustomField>
    <fullName>Statut_audimetrique__c</fullName>
    <label>Statut audimétrique</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Présent</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>En vacances</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Absent</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Non répondant</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Localisation__c.field-meta.xml
<CustomField>
    <fullName>Localisation__c</fullName>
    <label>Localisation</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Foyer</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Station</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>SAV MM</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Prestataire SAV</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Prestataire logistique</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Pas de localisation</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Fabricant</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Date_de_chute__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Date_de_chute_temporaire__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute_temporaire__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute temporaire</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Statut_Audimetrique__c.field-meta.xml
<CustomField>
    <fullName>Statut_Audimetrique__c</fullName>
    <label>Statut Audimétrique</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Présent</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>En vacances</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Absent</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Non répondant</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Statut_Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Statut_Foyer_paneliste__c</fullName>
    <label>Statut Foyer Panéliste</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Foyer_equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Recruté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Installé</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Equipé</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Intégré</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Désinstallé</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chute temporaire</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Chute définitive</label>
            </value>
            <value>
                <fullName>Chute définitive et désinstallé</fullName>
                <isActive>false</isActive>
                <label>Chute définitive et désinstallé</label>
            </value>
            <value>
                <fullName>Désinstallé actif</fullName>
                <isActive>false</isActive>
                <label>Désinstallé actif</label>
            </value>
            <value>
                <fullName>Recruté en attente d&apos;installation</fullName>
                <isActive>false</isActive>
                <label>Recruté en attente d&apos;installation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/recordTypes/AIP.recordType-meta.xml
<RecordType>
    <fullName>AIP</fullName>
    <active>true</active>
    <label>AIP</label>
</RecordType>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AP05_FoyerPaneliste_Test.cls
/*
* @date: 05/10/2021
* @ Description : tester la classe AP05_FoyerPaneliste
* @version 1.00   
* @Auteur Ayoub Ghammaz EIT
* @Coverage: 88%
History
* <Date of modification> <Author> 	<Description of modification>
*/
@isTest
public class AP05_FoyerPaneliste_Test {
    @isTest static void testMajSatutAsset() {// tester la methode FoyerPAnelisteChute
        Id recordTypeIdAssetAip =Schema.SObjectType.Asset.getRecordTypeInfosByName().get(label.ASS_RecordType_DispositifsMesureAudienceAIP).getRecordTypeId();
        Id recordTypeIdPanelAIP =Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_AIP).getRecordTypeId();
        // Créer un foyer pour l'insérer dans le panel
        Account foyerTest = new Account(Name='testPanel');
        insert foyerTest;
        
        //Référentiel Panel
        List<Referentiel_Panel__c> listReferentielPanelToInsert = new List<Referentiel_Panel__c>();
        
        Referentiel_Panel__c refPanelAIP = Test_Utils.createRefPanel(Label.RFP_Nom_AIP, Label.RFP_Nom_AIP);
        listReferentielPanelToInsert.add(refPanelAIP);
        
        insert listReferentielPanelToInsert;
        
        // Créer un panel Aip  PAN_Statut_Panel_Chute_definitive
        List<Foyer_paneliste__c> testPanelAip = new List<Foyer_paneliste__c>(); 
        testPanelAip.add(new Foyer_paneliste__c(RecordTypeId = recordTypeIdPanelAIP,Name='testAip',Foyer__c=foyerTest.id,Statut_Foyer_paneliste__c=Label.PAN_Statut_panel,
                                                Statut_Audimetrique__c = Label.PAN_Statut_Audimetrique_nonRepondant, referentiel_panel__c = refPanelAIP.Id));
        System.debug('-->'+testPanelAip);
        insert testPanelAip;
        //creer equipements
        List<Asset> assetToInsert = new list<Asset>();
        assetToInsert.add(new asset(recordtypeid=recordTypeIdAssetAip,Name='test12 equi',Foyer_paneliste__c=testPanelAip[0].id,AccountId=foyerTest.id,
                                    status=LAbel.ASS_Statut_Valide,localisation__c=label.ASS_Localisation_Foyer));
        
        insert assetToInsert;
        
        testPanelAip[0].Statut_Foyer_paneliste__c=Label.PAN_Statut_Panel_Chute_definitive;
        testPanelAip[0].Date_de_chute__c= Date.today();
        testPanelAip[0].Date_de_chute_temporaire__c=date.today();
        update testPanelAip;
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(foyerTest.id));  
        System.assertEquals(1,[select id , status from asset where status=:Label.ASS_Statut_Perdu].size());
        Test.stopTest();
    }
    
}