force-app/main/default/objects/Account/fields/Date_de_derniere_commande__c.field-meta.xml
<CustomField>
    <fullName>Date_de_derniere_commande__c</fullName>
    <label>Date de dernière commande</label>
    <summarizedField>Fidelisation__c.CreatedDate</summarizedField>
    <summaryFilterItems>
        <field>Fidelisation__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Débit</value>
    </summaryFilterItems>
    <summaryForeignKey>Fidelisation__c.Foyer__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type_de_foyer__c.field-meta.xml
<CustomField>
    <fullName>Type_de_foyer__c</fullName>
    <label>Type de foyer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Médiamat</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Single Source</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>AIP</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Multi panel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchRDD01_FoyerPanelisteAIP_Test.cls
/*
* @Auteur Calire VEHRLE
* @date: 02/06/2022
* @Classe: BatchRDD01_FoyerPanelisteAIP
* * History
* <Date of modification>   		<Author>    		<Description of modification>
*/
@IsTest
public class BatchRDD01_FoyerPanelisteAIP_Test {
    static testMethod void testMethod1() {
        List<Account> lstAccount= new List<Account>();
        for(Integer i=0 ;i <200;i++) {
            Account acc = new Account();
            acc.Name ='Name'+i;
            acc.Type_de_foyer__c = '4';
            //acc.Date_de_derniere_commande__c = 2020/10/01;
            lstAccount.add(acc);
        }
        
        insert lstAccount;
        
        Test.startTest();
        
        BatchRDD01_FoyerPanelisteAIP obj = new BatchRDD01_FoyerPanelisteAIP();
        DataBase.executeBatch(obj); 
        
        Test.stopTest();
    }
}