force-app/main/default/objects/Account/fields/Date_d_installation__c.field-meta.xml
<CustomField>
    <fullName>Date_d_installation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;installation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_de_recensement__c.field-meta.xml
<CustomField>
    <fullName>Date_de_recensement__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de recensement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Freeze__c.field-meta.xml
<CustomField>
    <fullName>Freeze__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Cette case à cocher permet de bloquer l&apos;attribution de points du foyer</description>
    <label>Freeze</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/Fidelisation__c.object-meta.xml
<CustomObject>
    <label>Fidélisation</label>
    <nameField>
        <displayFormat>FID-{0000}</displayFormat>
        <label>Nom de Fidélisation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fidélisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fidelisation__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fid_lisations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Motif_de_credit__c.field-meta.xml
<CustomField>
    <fullName>Motif_de_credit__c</fullName>
    <label>Motif de crédit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_de_mouvement__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Bonus Installation</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Bonus mensuel TV</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Recensement</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Noël</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Vacances été</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Anniv entrée Panel</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Bonus mensuel web</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Quiz Règle OR</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Smile Me</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Defreeze</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Rentrée</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Auto désinstallation</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Anniv panéliste</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Pilote</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Points mensuels AIP</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Badge Bronze jeune</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Badge Argent jeune</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Badge Or jeune</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Badge Platine jeune</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Badge Bronze 25+</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Badge Argent 25+</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>Badge Or 25+</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Badge Platine 25+</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Parrainage Parrain</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Parrainage Filleul</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Dédommagement</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Autre crédit</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Crédit Energie</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Noce MM</label>
            </value>
            <value>
                <fullName>Commande</fullName>
                <isActive>false</isActive>
                <label>Commande</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Points_credites__c.field-meta.xml
<CustomField>
    <fullName>Points_credites__c</fullName>
    <label>Points Crédités</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Type_de_mouvement__c.field-meta.xml
<CustomField>
    <fullName>Type_de_mouvement__c</fullName>
    <label>Type de mouvement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Commande</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Crédit automatique</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Crédit exceptionnel</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Crédit manuel</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Débit automatique</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Débit des points fin de contrat</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Débit exceptionnel</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Débit manuel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Batch00X_BatchModifiable.cls
/*
* @author: Maribelle ZARAZIR 
* @date: 27/05/2021
* @Description : Batch utilisé pour les Tickets de TMA
* @TestClass: 
* @Coverage: 
* History
* <Date of modification>   <Author>    <Description of modification>
* 		27/05/2021			 MZ			Used as Batch004_CreditAutomatique1foisparMois - Ticket MEDIAMETRIE-187
*										Fidélisations mois d'Avril 2021
*/ 

global class Batch00X_BatchModifiable implements Database.Batchable<sObject>, Database.Stateful {
    
    //Added for email notification - START
    global String errorTxt = '';
    global Boolean containsErrors = false;
    //Added for email notification - END

    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'Select id ,Date_d_installation__c,Date_de_recensement__c from account where Freeze__c=false and (Date_de_recensement__c!=null OR Date_d_installation__c!=null)';
        return Database.getQueryLocator(query);
    }
    
        global void execute(Database.BatchableContext bc, List<account> scope) {
        system.debug('$$$ Scope ' + scope);
        Id recordTypeIdFIDcredit =Schema.SObjectType.Fidelisation__c.getRecordTypeInfosByName().get(label.FID_Type_d_enregistrement_Credit).getRecordTypeId();
        list<Fidelisation__c> listFIDtoInsert = new  list<Fidelisation__c>();
        map<string, Account> mapIdFoyerFoyer = new map<string, account>([Select id, name, 
                                                                         (Select id from Fid_lisations__r
                                                                          Where   Motif_de_credit__c= :Label.FID_Motifcredit_BonusInstallation)
                                                                         From Account 
                                                                         Where ID IN: scope]); 
        for(Account acc:scope)
        {  
            if(mapIdFoyerFoyer.containskey(acc.id) && mapIdFoyerFoyer.get(acc.id).Fid_lisations__r.size()==0 && (acc.Date_d_installation__c.month() == 4) && (acc.Date_d_installation__c.year() == 2021))
            {
                system.debug('$$$ in 1');
                listFIDtoInsert.add(NewFID(acc.id,recordTypeIdFIDcredit,Label.FID_TypeMouvement_CreditExceptionnel,Label.FID_Motifcredit_BonusInstallation,integer.valueof(Label.FID_NbrPoints_100)));
            }
            /*
            if(acc.Date_d_installation__c!=null && GetMonthsBetween(acc.Date_d_installation__c) >=2)
            {
                system.debug('$$$ in 2');
                listFIDtoInsert.add(NewFID(acc.id,recordTypeIdFIDcredit,Label.FID_TypeMouvement_CreditExceptionnel,Label.FID_Motifcredit_BonusMensuelTV,integer.valueof(Label.FID_NbrPoints_30)));
            }
            if(acc.Date_de_recensement__c!=null && (acc.Date_de_recensement__c.month() == 4) && (acc.Date_de_recensement__c.year() == 2021))
            {
                system.debug('$$$ in 3');
                listFIDtoInsert.add(NewFID(acc.id,recordTypeIdFIDcredit,Label.FID_TypeMouvement_CreditExceptionnel,Label.FID_Motifcredit_Recensement,integer.valueof(Label.FID_NbrPoints_90)));
            } 
*/
        }
        if(listFIDtoInsert!=null && listFIDtoInsert.size()>0)
        {
            try{ 
               database.insert(listFIDtoInsert, false);
            }Catch(exception ex){
                system.debug('Insert FID Exception Error:'+ex.getmessage());
                //added for notification
                errorTxt += 'Erreur durant la création des requêtes : ' + ex.getMessage() + '\n';
                containsErrors = true;
            }  
        }
    }
    
        global void finish(Database.BatchableContext bc){
        //Added for notifications - START
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        List<String> toMailAddress = new List<String>();
        toMailAddress.add('DSI-DCP-EIT-ReportingChargementSalesforce@mediametrie.fr');
        toMailAddress.add('tma.mediametrie@ei-technologies.com');
        toMailAddress.add('maribelle.zarazir@eit-mena.com');
        
        mail.setToAddresses(toMailAddress);
        mail.setSenderDisplayName('Batch de Crédit Automatique - Avril');
        mail.setSubject('Batch de Crédit Automatique - Avril');
        
        String emailBody = 'L\'exécution du batch de Crédit Automatique (Bonus Installation - Avril) s\'est terminée.\n';
        if(containsErrors) {
            emailBody += 'Les erreurs suivantes ont été rencontrées :\n\n';
            emailBody += errorTxt;
        } else {
            emailBody += 'Aucune erreur n\'a été relevée.';
        }
        mail.setPlainTextBody(emailBody);
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        //Added for notifications - END
    }
    
    public static Fidelisation__c NewFID(ID AccounId,Id recordTypeIdFIDcredit, String TypeMouvement,String MotifCredit,Integer NbrsPoints)
    {
        Fidelisation__c FID = new Fidelisation__c();
        if(TypeMouvement!=null && MotifCredit!=null && NbrsPoints!=null)
        {
            FID.Type_de_mouvement__c=TypeMouvement;
            FID.Motif_de_credit__c=MotifCredit;
            FID.Points_credites__c=NbrsPoints;
            FID.RecordTypeId = recordTypeIdFIDcredit;
            FID.Foyer__c=AccounId;
        }
        return FID;
    }
    /*
    public static integer GetMonthsBetween(date duedate )
    {
        decimal monthsBetweenDates = 0;
        
        if(duedate!=null && duedate <= date.newInstance(2021, 5, 1))
        {
            integer DaysBetween = duedate.monthsbetween(date.newInstance(2021, 5, 1)); 
            return DaysBetween;
        }
        else{
            return null;
        }
    }
*/
}