force-app/main/default/objects/Account/fields/Foyer_equipe__c.field-meta.xml
<CustomField>
    <fullName>Foyer_equipe__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Foyer équipé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Bande_Usine__c.field-meta.xml
<CustomField>
    <fullName>Bande_Usine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bande Usine</label>
    <referenceTo>Bande_Usine__c</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>Equipements_de_mesure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT ( Bande_Usine__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bande_Usine__c/Bande_Usine__c.object-meta.xml
<CustomObject>
    <label>Bande Usine</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du fichier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bande Usine</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bande_Usine__c/fields/Date_declaration_OCOM__c.field-meta.xml
<CustomField>
    <fullName>Date_declaration_OCOM__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date déclaration OCOM</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bande_Usine__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Bande Usine</relationshipLabel>
    <relationshipName>Bande_Usine</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bande_Usine__c/fields/Statut_de_l_import__c.field-meta.xml
<CustomField>
    <fullName>Statut_de_l_import__c</fullName>
    <label>Statut de l&apos;import</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Validée</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Rejetée</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Partiellement Validée</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Partiellement rejetée</label>
            </value>
            <value>
                <fullName>A activer</fullName>
                <isActive>false</isActive>
                <label>A activer</label>
            </value>
            <value>
                <fullName>A contrôler</fullName>
                <isActive>false</isActive>
                <label>A contrôler</label>
            </value>
            <value>
                <fullName>A valider</fullName>
                <isActive>false</isActive>
                <label>A valider</label>
            </value>
            <value>
                <fullName>Accepté</fullName>
                <isActive>false</isActive>
                <label>Accepté</label>
            </value>
            <value>
                <fullName>Rejeté Import</fullName>
                <isActive>false</isActive>
                <label>Rejeté Import</label>
            </value>
            <value>
                <fullName>Rejeté QA</fullName>
                <isActive>false</isActive>
                <label>Rejeté QA</label>
            </value>
            <value>
                <fullName>Rejeté Validation</fullName>
                <isActive>false</isActive>
                <label>Rejeté Validation</label>
            </value>
            <value>
                <fullName>Validé/Rejeté</fullName>
                <isActive>false</isActive>
                <label>Validé/Rejeté</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bande_Usine__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mediamat</fullName>
            </value>
            <value>
                <fullName>PaMe</fullName>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer_equipe__c.field-meta.xml
<CustomField>
    <fullName>Foyer_equipe__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Foyer équipé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Statut_Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Statut_Foyer_paneliste__c</fullName>
    <label>Statut Foyer Panéliste</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Foyer_equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Recruté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Installé</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Equipé</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Intégré</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Désinstallé</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chute temporaire</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Chute définitive</label>
            </value>
            <value>
                <fullName>Chute définitive et désinstallé</fullName>
                <isActive>false</isActive>
                <label>Chute définitive et désinstallé</label>
            </value>
            <value>
                <fullName>Désinstallé actif</fullName>
                <isActive>false</isActive>
                <label>Désinstallé actif</label>
            </value>
            <value>
                <fullName>Recruté en attente d&apos;installation</fullName>
                <isActive>false</isActive>
                <label>Recruté en attente d&apos;installation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP02_BandeUsine_Test.cls
/*
* @author: Claire VEHRLE
* @date: 20/01/2023
* @ Description: Classe qui test AP01_BandeUsine les méthodes : getBandeUsine // sendBandeUsineToOCOM // createHttpRequest
* @TestClass: 
* @Coverage:
* History
* <Date of modification>   		<Author>   		 <Description of modification>
* */
@isTest
public class AP02_BandeUsine_Test {
    
    @isTest
    static void buProvisionner() {
        Id recordTypeIdFoyerPanelisteMMATPame =Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_mediamatpame).getRecordTypeId();
        
        List<Referentiel_Panel__c> referentielPanelToInsert = new List<Referentiel_Panel__c>();
        Referentiel_Panel__c refPanMMAT = new Referentiel_Panel__c();
        refPanMMAT.Name = 'MMAT';
        refPanMMAT.Type_de_panel__c = Label.RFP_TypePanel_MMAT;
        referentielPanelToInsert.add(refPanMMAT);
        
        insert referentielPanelToInsert;
        
        Account foyer = new Account();
        foyer.Name = 'Test BU provisionner';
        insert foyer;
        
        List<Foyer_Paneliste__c> foyerPanelisteToInsert = new List<Foyer_Paneliste__c>();
        Foyer_Paneliste__c foyerPanelisteMMAT = new Foyer_Paneliste__c();
        foyerPanelisteMMAT.recordTypeId = recordTypeIdFoyerPanelisteMMATPame;
        foyerPanelisteMMAT.Name = 'FP MMAT';
        foyerPanelisteMMAT.Foyer__c = foyer.Id;
        foyerPanelisteMMAT.Foyer_equipe__c = true;
        foyerPanelisteMMAT.Statut_Foyer_paneliste__c = Label.PAN_Statut_panel;
        foyerPanelisteMMAT.Referentiel_Panel__c = refPanMMAT.Id;
        foyerPanelisteToInsert.add(foyerPanelisteMMAT);
        
        insert foyerPanelisteToInsert;
        
        Bande_Usine__c BU = new Bande_Usine__c();
        BU.Name = 'bandeUTest';
        BU.Date_declaration_OCOM__c = date.today();
        BU.Statut_de_l_import__c = Label.BandeUsine_statut_Valide;
        BU.Referentiel_Panel__c = refPanMMAT.Id;
        
        insert BU;
        
        Asset eqt = new Asset();
        Eqt.AccountId = foyer.Id;
        eqt.Foyer_paneliste__c = foyerPanelisteMMAT.Id;
        eqt.Bande_Usine__c = BU.Id;
        eqt.Name='1432';
        //
        insert eqt;
        
        IndividuPanelisteCallout_Mock fakeGetBandeUsine = new IndividuPanelisteCallout_Mock(BU.Id);
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, fakeGetBandeUsine);
        BU.Statut_de_l_import__c = Label.BandeUsine_statut_Rejete;
        
        Update BU;
        Test.stopTest();
    }
    
    @isTest
    static void buNonProvisionner() {
        Id recordTypeIdFoyerPanelisteMMATPame =Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_mediamatpame).getRecordTypeId();
        
        
        List<Referentiel_Panel__c> referentielPanelToInsert = new List<Referentiel_Panel__c>();
        Referentiel_Panel__c refPanMMAT = new Referentiel_Panel__c();
        refPanMMAT.Name = 'MMAT';
        refPanMMAT.Type_de_panel__c = Label.RFP_TypePanel_MMAT;
        referentielPanelToInsert.add(refPanMMAT);
        
        insert referentielPanelToInsert;
        
        Account foyer = new Account();
        foyer.Name = 'Test BU provisionner';
        insert foyer;
        
        List<Foyer_Paneliste__c> foyerPanelisteToInsert = new List<Foyer_Paneliste__c>();
        Foyer_Paneliste__c foyerPanelisteMMAT = new Foyer_Paneliste__c();
        foyerPanelisteMMAT.recordTypeId = recordTypeIdFoyerPanelisteMMATPame;
        foyerPanelisteMMAT.Name = 'FP MMAT';
        foyerPanelisteMMAT.Foyer__c = foyer.Id;
        foyerPanelisteMMAT.Foyer_equipe__c = true;
        foyerPanelisteMMAT.Statut_Foyer_paneliste__c = Label.PAN_Statut_panel;
        foyerPanelisteMMAT.Referentiel_Panel__c = refPanMMAT.Id;
        foyerPanelisteToInsert.add(foyerPanelisteMMAT);
        
        insert foyerPanelisteToInsert;
        
        Bande_Usine__c BU = new Bande_Usine__c();
        BU.Name = 'bandeUTest';
        BU.Date_declaration_OCOM__c = null;
        BU.Statut_de_l_import__c = Label.BandeUsine_statut_Valide;
        BU.Referentiel_Panel__c = refPanMMAT.Id;
        
        insert BU;
        
        Asset eqt = new Asset();
        Eqt.AccountId = foyer.Id;
        eqt.Foyer_paneliste__c = foyerPanelisteMMAT.Id;
        eqt.Bande_Usine__c = BU.Id;
        eqt.Name='123';
        //
        insert eqt;
        
        IndividuPanelisteCallout_Mock fakeGetBandeUsine = new IndividuPanelisteCallout_Mock(BU.Id);
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, fakeGetBandeUsine); 
        BU.Statut_de_l_import__c = Label.BandeUsine_statut_Rejete;
        
        Update BU;
        Test.stopTest();
    }
    
}