force-app/main/default/objects/Account/fields/foyer_stock__c.field-meta.xml
<CustomField>
    <fullName>foyer_stock__c</fullName>
    <defaultValue>false</defaultValue>
    <label>foyer stock</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/ASS_ExtId_Ocom__c.field-meta.xml
<CustomField>
    <fullName>ASS_ExtId_Ocom__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ASS_ExtId_Ocom</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/Audimetre__c.field-meta.xml
<CustomField>
    <fullName>Audimetre__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Audimètre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Batterie__c.field-meta.xml
<CustomField>
    <fullName>Batterie__c</fullName>
    <label>Niveau de Batterie</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Date_de_derniere_detection__c.field-meta.xml
<CustomField>
    <fullName>Date_de_derniere_detection__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de dernière détection</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Type_de_materiel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_materiel__c</fullName>
    <label>Type de Matériel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>31</fullName>
                <label>Beacon</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Routeur</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>Soft Meter</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>Pager</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Carte SIM</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Setmeter</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>DMD</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>TV</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>TV Plat</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>TV TNT intégré</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>TVM3</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>TNT</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>MAG</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Syster</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Modem</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Tuner Externe</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Sonde NG</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Perte de marquage</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Ordinateur</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Console de jeux</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>DVD</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>DVD R sans HDD</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>DVD MAG</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Autre équipement</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>Streaming Meter</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>Antenne</label>
            </value>
            <value>
                <fullName>8</fullName>
                <isActive>false</isActive>
                <label>Connectique</label>
            </value>
            <value>
                <fullName>18</fullName>
                <isActive>false</isActive>
                <label>Convertisseur</label>
            </value>
            <value>
                <fullName>3</fullName>
                <isActive>false</isActive>
                <label>IRD</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>MCS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_flows__c.field-meta.xml
<CustomField>
    <fullName>Bypass_flows__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass flows</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_triggers__c.field-meta.xml
<CustomField>
    <fullName>Bypass_triggers__c</fullName>
    <label>Bypass triggers</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AP01_BandeUsine</fullName>
            </value>
            <value>
                <fullName>AP01_Commande</fullName>
            </value>
            <value>
                <fullName>AP01_Conge</fullName>
            </value>
            <value>
                <fullName>AP01_Control</fullName>
                <isActive>false</isActive>
                <label>AP01_Control</label>
            </value>
            <value>
                <fullName>AP01_Controle</fullName>
            </value>
            <value>
                <fullName>AP01_Convention</fullName>
            </value>
            <value>
                <fullName>AP01_Equipement</fullName>
            </value>
            <value>
                <fullName>AP01_EquipementDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP01_Evenement</fullName>
            </value>
            <value>
                <fullName>AP01_Fidelisation</fullName>
            </value>
            <value>
                <fullName>AP01_Foyer</fullName>
            </value>
            <value>
                <fullName>AP01_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP01_IndividuPaneliste</fullName>
            </value>
            <value>
                <fullName>AP01_LienMeter</fullName>
            </value>
            <value>
                <fullName>AP01_MembreDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP01_Requete</fullName>
            </value>
            <value>
                <fullName>AP01_StockProduit</fullName>
            </value>
            <value>
                <fullName>AP01_SuiviStockSAV</fullName>
            </value>
            <value>
                <fullName>AP01_UpdatescheduledDate</fullName>
            </value>
            <value>
                <fullName>AP01_WorkOrder</fullName>
            </value>
            <value>
                <fullName>AP010_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP011_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP02_BandeUsine</fullName>
            </value>
            <value>
                <fullName>AP02_Commande</fullName>
            </value>
            <value>
                <fullName>AP02_Controle</fullName>
            </value>
            <value>
                <fullName>AP02_Convention</fullName>
            </value>
            <value>
                <fullName>AP02_Equipement</fullName>
            </value>
            <value>
                <fullName>AP02_EquipementDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP02_Foyer</fullName>
            </value>
            <value>
                <fullName>AP02_FoyerPaneliste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_validation_rules__c.field-meta.xml
<CustomField>
    <fullName>Bypass_validation_rules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass validation rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AP02_Equipement_Test.cls
/*
* @date: 19/10/2021
* @ Description Class qui teste AP02_Equipement 
* @version 1.00   
* pourcentage : 95%
* @Auteur Ayoub Ghammaz EIT
History
* <Date of modification> <Author> 	<Description of modification>
*/
@isTest
public class AP02_Equipement_Test {
    @isTest
    static void AP02_SendAsset(){
        
        User u = [SELECT id, Bypass_triggers__c, Bypass_flows__c FROM User WHERE isActive = true and Profile.name like '%dministra%' limit 1];
        u.Bypass_validation_rules__c = true;
        u.Bypass_flows__c = true;
        update u;
        
         System.runAs(u){
        Id recordTypeIdEquipementDeMesureAIP = Schema.SObjectType.Asset.getRecordTypeInfosByName().get(Label.ASS_RecordType_DispositifsMesureAudienceAIP).getRecordTypeId();
        Id recordTypeIdFoyerPanelisteAIP = Schema.SObjectType.Foyer_Paneliste__c.getRecordTypeInfosByName().get(Label.PAN_recordType_AIP).getRecordTypeId();
        List<Account> foyerToInsert = new List<Account>();
        Account foyer1 = new Account();
        foyer1.Name = 'Foyer1';
        foyerToInsert.add(foyer1);
        
        Account foyer2 = new Account();
        foyer2.Name = 'Foyer2';
        foyer2.foyer_stock__c = true;
        foyerToInsert.add(foyer2);
        insert foyerToInsert;
        
        Foyer_paneliste__c foyerPaneliste11 = Test_Utils.createFoyerPaneliste();
        foyerPaneliste11.RecordTypeId = recordTypeIdFoyerPanelisteAIP;
        foyerPaneliste11.Foyer__c = foyer1.Id;
        insert foyerPaneliste11;
        
        list<Asset> listAssetToInsert = new list<Asset>();
        Asset asset11 = Test_Utils.createEquipement(foyer1.Id);
        asset11.RecordTypeId = recordTypeIdEquipementDeMesureAIP;
        asset11.Batterie__c = 0;
        asset11.Foyer_paneliste__c = foyerPaneliste11.Id;
        asset11.Type_de_materiel__c = Label.ASS_Type_De_Materiel_Beacon;
        asset11.Date_de_derniere_detection__c = Date.today() - 33;
        asset11.Audimetre__c = '243EAA'; 
        asset11.ASS_ExtId_Ocom__c='0011j000012iqI3AAI';
        listAssetToInsert.add(asset11);
        
        Asset asset2 = Test_Utils.createEquipement(foyer2.Id);
        asset2.RecordTypeId = recordTypeIdEquipementDeMesureAIP;
        asset2.Batterie__c = 0;
        asset2.Type_de_materiel__c = Label.ASS_Type_De_Materiel_Beacon;
        asset2.Date_de_derniere_detection__c = Date.today() - 33;
        asset2.Audimetre__c = '213EA'; 
        asset2.ASS_ExtId_Ocom__c='1234567'; 
        listAssetToInsert.add(asset2);
        
        insert listAssetToInsert;
        
        List<Asset> listAssetToUpdate = new list<Asset>();
        asset11.AccountId = foyer2.Id;
		asset11.Foyer_paneliste__c = null; 
        asset11.Audimetre__c = '243EA';  
        listAssetToUpdate.add(asset11);
        
        asset2.AccountId = foyer1.Id;
        asset2.Foyer_paneliste__c = foyerPaneliste11.Id;
        listAssetToUpdate.add(asset2);
        
        MembreFoyerCallout_Mock fakeSendAsset11 = new MembreFoyerCallout_Mock(asset11.Id);
        MembreFoyerCallout_Mock fakeSendAsset2 = new MembreFoyerCallout_Mock(asset2.Id);
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, fakeSendAsset11);
        Test.setMock(HttpCalloutMock.class, fakeSendAsset2);
        Update listAssetToUpdate;
        Test.stopTest();
        
        /*String assId = '0011j000012iqI3AAI';
        
        List <String> ListAssExternalIds = new List <String>();
        ListAssExternalIds.add(assId);
        
        MembreFoyerCallout_Mock fakeSendAss = new MembreFoyerCallout_Mock(assId);
        
        Test.startTest(); 
        Test.setMock(HttpCalloutMock.class, fakeSendAss);
        AP02_Equipement.DissocierEquipementOcom(ListAssExternalIds);
        AP02_Equipement.PutMeterConfMetier(ListAssExternalIds);
        AP02_Equipement.checkSendAssetToOcom(listAsset);
        Test.stopTest();*/
         }
    }
}