force-app/main/default/objects/Account/fields/Foyer_equipe__c.field-meta.xml
<CustomField>
    <fullName>Foyer_equipe__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Foyer équipé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_de_portable__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_portable__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Numéro de téléphone portable</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Audimetre__c.field-meta.xml
<CustomField>
    <fullName>Audimetre__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Audimètre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Type_de_materiel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_materiel__c</fullName>
    <label>Type de Matériel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>31</fullName>
                <label>Beacon</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Routeur</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>Soft Meter</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>Pager</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Carte SIM</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Setmeter</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>DMD</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>TV</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>TV Plat</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>TV TNT intégré</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>TVM3</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>TNT</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>MAG</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Syster</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Modem</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Tuner Externe</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Sonde NG</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Perte de marquage</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Ordinateur</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Console de jeux</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>DVD</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>DVD R sans HDD</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>DVD MAG</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Autre équipement</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>Streaming Meter</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>Antenne</label>
            </value>
            <value>
                <fullName>8</fullName>
                <isActive>false</isActive>
                <label>Connectique</label>
            </value>
            <value>
                <fullName>18</fullName>
                <isActive>false</isActive>
                <label>Convertisseur</label>
            </value>
            <value>
                <fullName>3</fullName>
                <isActive>false</isActive>
                <label>IRD</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>MCS</label>
            </value>
            <value>
                <fullName>6</fullName>
                <isActive>false</isActive>
                <label>Multi-Peritel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT ( Bande_Usine__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Controle.recordType-meta.xml
<RecordType>
    <fullName>Controle</fullName>
    <active>true</active>
    <businessProcess>Contrôle</businessProcess>
    <label>Contrôle</label>
</RecordType>

force-app/main/default/objects/Controle__c/Controle__c.object-meta.xml
<CustomObject>
    <label>Contrôle</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du contrôle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrôles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Controle__c/fields/Audimetre__c.field-meta.xml
<CustomField>
    <fullName>Audimetre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audimètre</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Date_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Date_de_controle__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de contrôle</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actif</fullName>
                <default>true</default>
                <label>Actif</label>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>Pré-codé</fullName>
            </value>
            <value>
                <fullName>Traité</fullName>
            </value>
            <value>
                <fullName>Abandonné</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer_equipe__c.field-meta.xml
<CustomField>
    <fullName>Foyer_equipe__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Foyer équipé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Statut_Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Statut_Foyer_paneliste__c</fullName>
    <label>Statut Foyer Panéliste</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Foyer_equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Recruté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Installé</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Equipé</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Intégré</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Désinstallé</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chute temporaire</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Chute définitive</label>
            </value>
            <value>
                <fullName>Chute définitive et désinstallé</fullName>
                <isActive>false</isActive>
                <label>Chute définitive et désinstallé</label>
            </value>
            <value>
                <fullName>Désinstallé actif</fullName>
                <isActive>false</isActive>
                <label>Désinstallé actif</label>
            </value>
            <value>
                <fullName>Recruté en attente d&apos;installation</fullName>
                <isActive>false</isActive>
                <label>Recruté en attente d&apos;installation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/recordTypes/AIP.recordType-meta.xml
<RecordType>
    <fullName>AIP</fullName>
    <active>true</active>
    <label>AIP</label>
</RecordType>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Batch003YTEST.cls
/*
* @author: Joyce Saidy
* @date: 21/09/2020
* @ Description Class that test Batch003_CreationRequeteControle  
* History
* <Date of modification>   <Author>    <Description of modification>
* 		06/10/2021   			Claire VEHRLE  		   Création des requêtes pour les contrôle de type Contrôle AIP
*/
@isTest
public class Batch003YTEST {
    public static testMethod void Batch003_CreationRequeteControleTest(){
       
        Id recordTypeIdControleControleAIP =Schema.SObjectType.Controle__c.getRecordTypeInfosByName().get(Label.CTRL_RecordType_ControleAIP).getRecordTypeId();
        Id recordTypeIdControleControleMediamat_PaME =Schema.SObjectType.Controle__c.getRecordTypeInfosByName().get(Label.CTRL_RecordType_ControleMediamat_PaME).getRecordTypeId();
        Id recordTypeIdFoyerPanelisteMMATPame =Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_mediamatpame).getRecordTypeId();
        Id recordTypeIdFoyerPanelisteAIP =Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_AIP).getRecordTypeId();
        Id recordTypeIdAsseteAIP =Schema.SObjectType.Asset.getRecordTypeInfosByName().get(label.ASS_RecordType_DispositifsMesureAudienceAIP).getRecordTypeId();
                
        //Create foyer
        list<Account> listFoyersToInsert = new list<Account>();
        account testAccount = Test_Utils.createFoyer();
        testAccount.Numero_de_portable__c = '0611111121';
        listFoyersToInsert.add(testAccount); 
        account testAccount2 = Test_Utils.createFoyer();
        testAccount2.Numero_de_portable__c = '0611111121';
        listFoyersToInsert.add(testAccount2); 
        insert listFoyersToInsert;
        System.debug('acc1: ' + testAccount);
        System.debug('acc2: ' + testAccount2);
        
        
        List<Referentiel_Panel__c> referentielPanelToInsert = new List<Referentiel_Panel__c>();
        Referentiel_Panel__c refPanMMAT = new Referentiel_Panel__c();
        refPanMMAT.Name = 'MMAT';
        refPanMMAT.Type_de_panel__c = Label.RFP_TypePanel_MMAT;
        referentielPanelToInsert.add(refPanMMAT);
        
        Referentiel_Panel__c refPanAIP = new Referentiel_Panel__c();
        refPanAIP.Name = 'AIP';
        refPanAIP.Type_de_panel__c = Label.RFP_TypePanel_AIP;
        referentielPanelToInsert.add(refPanAIP);
        
        insert referentielPanelToInsert;
        
        List<Foyer_Paneliste__c> foyerPanelisteToInsert = new List<Foyer_Paneliste__c>();
        Foyer_Paneliste__c foyerPanelisteMMAT = new Foyer_Paneliste__c();
        foyerPanelisteMMAT.recordTypeId = recordTypeIdFoyerPanelisteMMATPame;
        foyerPanelisteMMAT.Name = 'FP MMAT';
        foyerPanelisteMMAT.Foyer__c = testAccount.Id;
        foyerPanelisteMMAT.Foyer_equipe__c = true;
        foyerPanelisteMMAT.Statut_Foyer_paneliste__c = Label.PAN_Statut_panel;
        foyerPanelisteMMAT.Referentiel_Panel__c = refPanMMAT.Id;
        foyerPanelisteToInsert.add(foyerPanelisteMMAT);
        
        Foyer_Paneliste__c foyerPanelisteAIP = new Foyer_Paneliste__c();
        foyerPanelisteAIP.recordTypeId = recordTypeIdFoyerPanelisteAIP;
        foyerPanelisteAIP.Name = 'FP AIP';
        foyerPanelisteAIP.Foyer__c = testAccount2.Id;
        foyerPanelisteAIP.Foyer_equipe__c = true;
        foyerPanelisteAIP.Statut_Foyer_paneliste__c = Label.PAN_Statut_panel_Chute_temporaire;
        foyerPanelisteAIP.Referentiel_Panel__c = refPanAIP.Id;
        foyerPanelisteToInsert.add(foyerPanelisteAIP);
        
        insert foyerPanelisteToInsert;
        
       //Create Case
       
        Id recordTypeIdRequeteControleAIP =Schema.SObjectType.Case.getRecordTypeInfosByName().get(Label.CAS_Recordtype_ControleAIP).getRecordTypeId();
       
        list<Case> listCaseToInsert = new list<Case>();
        Case testCase = Test_Utils.createCase(testAccount2.id);
        testCase.foyer_paneliste__c = foyerPanelisteAIP.Id;
        testCase.Status = Label.CAS_Statut_Nouveau;
        testCase.RecordtypeId = recordTypeIdRequeteControleAIP;
        testCase.Type =Label.CAS_Type_Non_repondant;
        listCaseToInsert.add(testCase); 
        insert listCaseToInsert;
        
        //Mikael
        //Create asset
        list<asset> listassetToInsert = new list<asset>();
        
        
        Asset ass1=Test_Utils.createEquipement(testAccount.id);
        ass1.Type_de_materiel__c=Label.ASS_TypeMateriel_Pager;
        ass1.Audimetre__c='lnlnklne';
        ass1.recordTypeId = recordTypeIdAsseteAIP;
        listassetToInsert.add(ass1);
        
        Asset ass2=Test_Utils.createEquipement(testAccount.id);
        ass2.Type_de_materiel__c=Label.ASS_TypeMateriel_Pager;
        ass2.Audimetre__c='lnlnAZFTNYklne';
        ass2.recordTypeId = recordTypeIdAsseteAIP;
        listassetToInsert.add(ass2);
        
        Asset ass3=Test_Utils.createEquipement(testAccount2.id);
        ass3.Type_de_materiel__c=Label.ASS_TypeMateriel_Pager;
        ass3.Audimetre__c='lnSDZlnklne';
        ass3.recordTypeId = recordTypeIdAsseteAIP;
        listassetToInsert.add(ass3);
        
        Asset ass4=Test_Utils.createEquipement(testAccount2.id);
        ass4.Type_de_materiel__c=Label.ASS_TypeMateriel_Pager;
        ass4.Audimetre__c='lFEnlnklne';
        ass4.recordTypeId = recordTypeIdAsseteAIP;
        listassetToInsert.add(ass4);
        
        Asset ass5=Test_Utils.createEquipement(testAccount2.id);
        ass5.Type_de_materiel__c=Label.ASS_TypeMateriel_Pager;
        ass5.Audimetre__c='lFEnlnklne12';
        ass5.recordTypeId = recordTypeIdAsseteAIP;
        listassetToInsert.add(ass5);

        insert listassetToInsert; 
        //Create Controle
        list<Controle__c> listControleToInsert = new list<Controle__c>();
        Controle__c testCtrl1 = Test_Utils.createControle(testAccount.id,null,null,null,System.today());
        testCtrl1.RecordTypeId = recordTypeIdControleControleMediamat_PaME;
        testCtrl1.Date_de_controle__c=system.now();
        testCtrl1.Statut__c=Label.CTRL_StatutActif;
        testCtrl1.Tech_Priority__c='1';
        testCtrl1.Type_de_controle__c=Label.CTRL_Type_NonRepondant;
        testCtrl1.Date_de_controle__c=system.now();
        testCtrl1.foyer_paneliste__c=foyerPanelisteMMAT.Id;
        testCtrl1.Audimetre__c=ass1.Id;
        listControleToInsert.add(testCtrl1);  
         
        Controle__c testCtrl2 = Test_Utils.createControle(testAccount.id,null,null,null,System.today());
        testCtrl2.RecordTypeId = recordTypeIdControleControleMediamat_PaME;
        testCtrl2.Date_de_controle__c=system.now();
        testCtrl2.Statut__c=Label.CTRL_StatutActif;
        testCtrl2.Tech_Priority__c='2';
        testCtrl2.Type_de_controle__c=Label.CTRL_Type_NonRepondant; 
        testCtrl2.Date_de_controle__c=system.now();
        testCtrl2.foyer_paneliste__c=foyerPanelisteMMAT.Id;
        testCtrl2.Audimetre__c=ass2.Id;
        listControleToInsert.add(testCtrl2);
        
        Controle__c testCtrl4 = Test_Utils.createControle(testAccount2.id,null,null,null,System.today());
        testCtrl4.RecordTypeId = recordTypeIdControleControleAIP;
        testCtrl4.Date_de_controle__c=system.now();
        testCtrl4.Statut__c=Label.CTRL_StatutActif;
        testCtrl4.Tech_Priority__c='4';
        testCtrl4.Type_de_controle__c=Label.CTRL_Type_NonRepondant; 
        testCtrl4.Date_de_controle__c=system.now();
        testCtrl4.foyer_paneliste__c=foyerPanelisteAIP.Id;
        testCtrl4.Audimetre__c=ass4.Id;
        listControleToInsert.add(testCtrl4);
        
        Controle__c testCtrl3 = Test_Utils.createControle(testAccount2.id,null,null,null,System.today());
        testCtrl3.RecordTypeId = recordTypeIdControleControleAIP;
        testCtrl3.Date_de_controle__c=system.now();
        testCtrl3.Statut__c=Label.CTRL_StatutActif;
        testCtrl3.Tech_Priority__c='3';
        testCtrl3.Type_de_controle__c=Label.CTRL_Type_NonRepondant; 
        testCtrl3.Date_de_controle__c=system.now();
        testCtrl3.foyer_paneliste__c=foyerPanelisteAIP.Id;
        testCtrl3.Audimetre__c=ass3.Id;
        listControleToInsert.add(testCtrl3);
        
        Controle__c testCtrl5 = Test_Utils.createControle(testAccount2.id,null,null,null,System.today());
        testCtrl5.RecordTypeId = recordTypeIdControleControleAIP;
        testCtrl5.Date_de_controle__c=system.now();
        testCtrl5.Statut__c=Label.CTRL_Statut_Precode;
        testCtrl5.Libelle_de_pre_codage__c=Label.CTRL_LibellePrecodage_JourFerie;
        testCtrl5.Tech_Priority__c='6';
        testCtrl5.Type_de_controle__c=Label.CTRL_Type_NonRepondant; 
        testCtrl5.Date_de_controle__c=system.now();
        testCtrl5.foyer_paneliste__c=foyerPanelisteAIP.Id;
        testCtrl5.Audimetre__c=ass5.Id;
        listControleToInsert.add(testCtrl5);
        
        
        insert listControleToInsert; 
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(testAccount.id)); 
        Batch003Y btch = new Batch003Y();
        database.executeBatch(btch);
        Test.stopTest();
        
        
        List<Case> createCase = [SELECT id, AccountId, RecordType.Name, Nombre_de_controles__c, foyer_paneliste__c FROM Case];
        System.debug('createCase: ' + createCase);
       // System.assertEquals(2, createCase.size());
    } 
}