force-app/main/default/objects/Account/fields/Motif_de_chute__c.field-meta.xml
<CustomField>
    <fullName>Motif_de_chute__c</fullName>
    <label>Motif de chute</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acquisition d’une TV</fullName>
            </value>
            <value>
                <fullName>A l’initiative de MM</fullName>
            </value>
            <value>
                <fullName>A l’initiative du panéliste</fullName>
            </value>
            <value>
                <fullName>Aucun accès Internet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Chute_confirmee__c.field-meta.xml
<CustomField>
    <fullName>Chute_confirmee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Chute confirmée</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Jour_de_traitement__c.field-meta.xml
<CustomField>
    <fullName>Jour_de_traitement__c</fullName>
    <formula>IF(DATEVALUE(CreatedDate) &gt;= DATE(2023,04,27), TODAY() - DATEVALUE(CreatedDate) + 1, TODAY() - DATEVALUE(CreatedDate) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Etape J</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Motif_de_chute__c.field-meta.xml
<CustomField>
    <fullName>Motif_de_chute__c</fullName>
    <label>Motif de chute</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Chute_confirmee__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Contrainte du casque (filaire ou bluetooth)</fullName>
            </value>
            <value>
                <fullName>Déménagement hors zone de mesure</fullName>
            </value>
            <value>
                <fullName>Etude trop longue</fullName>
            </value>
            <value>
                <fullName>Mauvaise participation</fullName>
            </value>
            <value>
                <fullName>Ondes</fullName>
            </value>
            <value>
                <fullName>Oubli trop régulier</fullName>
            </value>
            <value>
                <fullName>Pager trop gros, inesthétique, indiscret...</fullName>
            </value>
            <value>
                <fullName>Pas de motif précisé</fullName>
            </value>
            <value>
                <fullName>Profession inadaptée</fullName>
            </value>
            <value>
                <fullName>Programme de fid peu motivant</fullName>
            </value>
            <value>
                <fullName>Raisons personnelles</fullName>
            </value>
            <value>
                <fullName>Set meter : problèmes techniques</fullName>
            </value>
            <value>
                <fullName>Set meter : refus installation</fullName>
            </value>
            <value>
                <fullName>Set meter : utilisation trop contraignante</fullName>
            </value>
            <value>
                <fullName>Structure du panel</fullName>
            </value>
            <value>
                <fullName>Sursollicitation</fullName>
            </value>
            <value>
                <fullName>Trop contraignant port et chargement</fullName>
            </value>
            <value>
                <fullName>Trop contraignant sans précision</fullName>
            </value>
            <value>
                <fullName>Trop contraignant à charger</fullName>
            </value>
            <value>
                <fullName>Trop contraignant à porter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sous_type__c.field-meta.xml
<CustomField>
    <fullName>Sous_type__c</fullName>
    <label>Sous-type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Absence collecte</fullName>
            </value>
            <value>
                <fullName>Absence mouvement</fullName>
            </value>
            <value>
                <fullName>Adaptateur casque</fullName>
            </value>
            <value>
                <fullName>Anomalie affichage</fullName>
            </value>
            <value>
                <fullName>Anomalie autre</fullName>
            </value>
            <value>
                <fullName>Anomalie batterie</fullName>
            </value>
            <value>
                <fullName>Anomalie carte Sim</fullName>
            </value>
            <value>
                <fullName>Anomalie des données en base panel</fullName>
            </value>
            <value>
                <fullName>Anomalie horloge</fullName>
            </value>
            <value>
                <fullName>Anomalie informations</fullName>
            </value>
            <value>
                <fullName>Anomalie lors du traitement des données d&apos;audience</fullName>
            </value>
            <value>
                <fullName>A quitte la mesure</fullName>
            </value>
            <value>
                <fullName>Audience individuelle &gt;7h</fullName>
            </value>
            <value>
                <fullName>Audience individuelle &gt; 7h</fullName>
                <isActive>false</isActive>
                <label>Audience individuelle &gt; 7h</label>
            </value>
            <value>
                <fullName>Audimètre</fullName>
            </value>
            <value>
                <fullName>Audimètre non connecté</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon batterie faible</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon inactif</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon jamais détecté</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Autre cause technique</fullName>
            </value>
            <value>
                <fullName>Autre déplacement</fullName>
            </value>
            <value>
                <fullName>Autre déplacement hors zone de mesure</fullName>
            </value>
            <value>
                <fullName>Autres usages</fullName>
            </value>
            <value>
                <fullName>Avis</fullName>
            </value>
            <value>
                <fullName>Beacon</fullName>
            </value>
            <value>
                <fullName>Beacon (logement plus grand)</fullName>
            </value>
            <value>
                <fullName>Beacon(s) Réceptionné(s)</fullName>
            </value>
            <value>
                <fullName>Beacon (tv en plus)</fullName>
            </value>
            <value>
                <fullName>Beacon (vehicule supplémentaire)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Motif_de_chute__c.field-meta.xml
<CustomField>
    <fullName>Motif_de_chute__c</fullName>
    <label>Motif de chute</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Contrainte du casque (filaire ou bluetooth)</fullName>
            </value>
            <value>
                <fullName>Déménagement hors zone de mesure</fullName>
            </value>
            <value>
                <fullName>Etude trop longue</fullName>
            </value>
            <value>
                <fullName>Mauvaise participation</fullName>
            </value>
            <value>
                <fullName>Ondes</fullName>
            </value>
            <value>
                <fullName>Oubli trop régulier</fullName>
            </value>
            <value>
                <fullName>Pager trop gros, inesthétique, indiscret...</fullName>
            </value>
            <value>
                <fullName>Pas de motif précisé</fullName>
            </value>
            <value>
                <fullName>Profession inadaptée</fullName>
            </value>
            <value>
                <fullName>Programme de fid peu motivant</fullName>
            </value>
            <value>
                <fullName>Raisons personnelles</fullName>
            </value>
            <value>
                <fullName>Set meter : problèmes techniques</fullName>
            </value>
            <value>
                <fullName>Set meter : refus installation</fullName>
            </value>
            <value>
                <fullName>Set meter : utilisation trop contraignante</fullName>
            </value>
            <value>
                <fullName>Structure du panel</fullName>
            </value>
            <value>
                <fullName>Sursollicitation</fullName>
            </value>
            <value>
                <fullName>Trop contraignant port et chargement</fullName>
            </value>
            <value>
                <fullName>Trop contraignant sans précision</fullName>
            </value>
            <value>
                <fullName>Trop contraignant à charger</fullName>
            </value>
            <value>
                <fullName>Trop contraignant à porter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Batch022_CreationRequete_RetourMat_Test.cls
@istest
public class Batch022_CreationRequete_RetourMat_Test {

    public static testmethod void Batch022_CreationRequete_RetourMat_Test(){
        
       Id recordTypeIdRequeteDemandePanelisteAIP =Schema.SObjectType.Case.getRecordTypeInfosByName().get(label.CAS_Recordtype_DemandePanelisteAIP).getRecordTypeId();


        
    account acc= new account();
        acc.name='acc';
        insert acc;
        
        Foyer_Paneliste__c fp = new Foyer_Paneliste__c();
        fp.Name='test';
        fp.Foyer__c=acc.id;
        insert fp;
        
        
        
        case cs = new case();
        cs.RecordTypeId=recordTypeIdRequeteDemandePanelisteAIP;
        cs.CreatedDate=Datetime.now().addDays(-45);
        cs.Chute_confirmee__c=true;
        cs.Motif_de_chute__c='Ondes';
        cs.Foyer_paneliste__c=fp.id;
        cs.AccountId=acc.id;
        insert cs;
        //cs.AccountId=acc.id;
		//update cs;
        
        case c= [select id,Jour_de_traitement__c from case where id =: cs.id];
        system.debug('ss '+c.Jour_de_traitement__c);
        upsert c;
        asset equip = new asset();
        equip.name='tv';
        equip.Status='2';
        equip.AccountId=acc.Id;
        equip.Foyer_paneliste__c=fp.id;
        insert equip;
        
        Test.startTest();
        Batch022_CreationRequete_RetourMateriel btch = new Batch022_CreationRequete_RetourMateriel();
        database.executeBatch(btch);
        Test.stopTest();
        
        case ca = [select id,Foyer_paneliste__c,Sous_type__c from case where type=:Label.CAS_Type_Suivi_Chute];
        
        system.assertEquals(ca.Foyer_paneliste__c,fp.id);
        system.assertEquals(Label.CAS_SousType_RestitutionDuMateriel, ca.Sous_type__c);
    }
    
}