force-app/main/default/objects/Account/fields/Nom_de_famille__c.field-meta.xml
<CustomField>
    <fullName>Nom_de_famille__c</fullName>
    <formula>Personne_de_reference__r.LastName</formula>
    <label>Nom de famille</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/Fidelisation__c.object-meta.xml
<CustomObject>
    <label>Fidélisation</label>
    <nameField>
        <displayFormat>FID-{0000}</displayFormat>
        <label>Nom de Fidélisation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fidélisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fidelisation__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fid_lisations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Batch_Delete_Fid_FoyAnonym.cls
/*
* @author: YH
* @date: 12/2021
* @ Description Batch POUR supprimer LES fidélisations des foyers anonymisés
* @TestClass: 
* @Coverage: 
* History
* <Date of modification>   <Author>    <Description of modification>
*/
global class Batch_Delete_Fid_FoyAnonym implements Database.Batchable<sObject>, Database.Stateful{
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        string query = 'select  id ,Nom_de_famille__c from Account  where Nom_de_famille__c like \'nom\\_%\'    ';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Account> scope){
        List<fidelisation__c> listfidtodelete = [select id from fidelisation__c where Foyer__c in:scope];
        
        system.debug('scope size'+scope.size());
        system.debug('scope'+scope);

        system.debug('fide'+listfidtodelete.size());
       
        
        delete(listfidtodelete);
        delete(scope);

    }
    
    global void finish(Database.BatchableContext bc){
        
    }
}