force-app/main/default/objects/Account/fields/Nombre_pc__c.field-meta.xml
<CustomField>
    <fullName>Nombre_pc__c</fullName>
    <label>Nombre d&apos;ordinateurs</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_smartphone__c.field-meta.xml
<CustomField>
    <fullName>Nombre_smartphone__c</fullName>
    <label>Nombre de smartphones</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_tablette__c.field-meta.xml
<CustomField>
    <fullName>Nombre_tablette__c</fullName>
    <label>Nombre de tablettes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_TV__c.field-meta.xml
<CustomField>
    <fullName>Nombre_TV__c</fullName>
    <label>Nombre de TV actives</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer Panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Commandes</relationshipLabel>
    <relationshipName>Commandes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Actions__c.field-meta.xml
<CustomField>
    <fullName>Actions__c</fullName>
    <label>Actions</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_de_l_intervention__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>21</fullName>
                <label>Ajout de poste</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Auto désinstallation</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Changement (TV, barre de son ect …)</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Configuration Meters (si boite mail ok)</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Configuration routeur (connexion des equipements au routeur Mediametrie )</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>Configuration routeur (connexion des equipements au routeur Mediametrie ) 2 et +</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Configuration Routeur (Pame)</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Contrôle audience</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Contrôle de connexion</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Contrôle de l&apos;installation</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Contrôle qualité</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Déménagement</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Désinstallation définitive</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Mise à jour équipement</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Modification Abonnement</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Mutation Audimètre</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Nouveau foyer</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Paramétrage Meters 2 à 4</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Paramétrage Meters 5 à 8</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Passage Improviste</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Pb Sonde Tv (Déclaration)</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Réinstallation</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Routeur ne s&apos;allume plus</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Suppression d&apos;un poste</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Vérification de l&apos;initialisation</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Vérification des éléments</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>Visite de courtoisie</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>Streaming Meter</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>Contrôle Streaming Meter</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>Réinstallation Streaming Meter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Le foyer sélectionné n&apos;est pas celui du foyer panéliste</errorMessage>
        <filterItems>
            <field>Foyer_paneliste__c.Foyer__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Interventions</relationshipLabel>
    <relationshipName>Interventions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Nombre_d_equipements__c.field-meta.xml
<CustomField>
    <fullName>Nombre_d_equipements__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nombre de Postes</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Nombre_TV__c.field-meta.xml
<CustomField>
    <fullName>Nombre_TV__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nombre TV active</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Remarques__c.field-meta.xml
<CustomField>
    <fullName>Remarques__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Remarques</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Type_de_l_intervention__c.field-meta.xml
<CustomField>
    <fullName>Type_de_l_intervention__c</fullName>
    <label>Type d&apos;intervention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_d_intervention</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Actions__c.field-meta.xml
<CustomField>
    <fullName>Actions__c</fullName>
    <label>Actions</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>21</fullName>
                <label>Ajout de poste</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Auto désinstallation</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Changement (TV, barre de son etc …)</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Configuration Meters  (si boite mail ok)</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Configuration routeur  (connexion des equipements au routeur Mediametrie )</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>Configuration routeur (connexion des equipements au routeur Mediametrie ) 2 et +</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Configuration Routeur (Pame)</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Contrôle audience</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Contrôle de connexion</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Contrôle de l&apos;installation</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Contrôle qualité</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Déménagement</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Désinstallation Définitive</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Mise à jour des èquipements</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Modification Abonnement</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Mutation audimétre</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Nouveau foyer</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Paramétrage Meters  2 à 4</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Paramétrage Meters  5 à 8</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Passage improviste</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Pb Sonde Tv (Déclaration)</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Réinstallation</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Routeur ne s&apos;allume plus</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Suppression d&apos;un poste</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>Visite de courtoisie</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Vérification de l&apos;initialisation</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Vérification des éléments</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>Streaming Meter</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>Contrôle Streaming Meter</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>Réinstallation Streaming Meter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Foyer_Paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_Paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer Panéliste</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Le foyer panéliste n&apos;est pas un des foyers panéliste du foyer</errorMessage>
        <filterItems>
            <field>Foyer_paneliste__c.Foyer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Foyer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Actions</relationshipLabel>
    <relationshipName>Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Type_d_intervention.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Installation</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Désinstallation</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Dépannage/Support</label>
    </customValue>
    <customValue>
        <fullName>Intervention</fullName>
        <isActive>false</isActive>
        <label>Intervention</label>
    </customValue>
    <customValue>
        <fullName>Visite de courtoisie</fullName>
        <isActive>false</isActive>
        <label>Visite de courtoisie</label>
    </customValue>
    <masterLabel>Type d&apos;intervention</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP01_WorkOrder.cls
/*
* @date: 08/03/2022
* @ Description Class that create workOrderLineItems on WorkOrder creation
* @TestClass:AP01_WorkOrderTest 
* @Coverage: 100 %
*/
public class AP01_WorkOrder {
    

    
    //method called after creation of Work Order, and will create for each WO corresp WOLI equal to nb TV on WO.
    public static void NewWorkOrderLineItems(List<WorkOrder> ListInter){
        List<WorkOrderLineItem> listActionsToInsert = new List<WorkOrderLineItem>();
        List<Id> interListId = new List<Id>();
        for(WorkOrder inter:ListInter) {
            interListId.add(inter.Id);
        }
        
        List<WorkOrder> ListWorkOrder = new List<WorkOrder>();
        
        ListWorkOrder = [SELECT Id, Type_de_l_intervention__c, Actions__c, Account.Nombre_tv__c, Account.Nombre_pc__c,
                         Account.Nombre_smartphone__c, Account.Nombre_tablette__c, Remarques__c, foyer_paneliste__c, Nombre_d_equipements__c,
                         AccountId, foyer_paneliste__r.referentiel_panel__r.type_de_panel__c FROM WorkOrder WHERE Id IN:interListId];
        decimal nbDevices=0;
        for (WorkOrder wo :ListWorkOrder){
            if(wo.Account.Nombre_tv__c != null) {
                for(integer i =0; i <Integer.ValueOf(wo.Account.Nombre_tv__c); i++ ){
                    if(wo.Type_de_l_intervention__c == Label.WOR_Type_d_intervention_Installation){
                        WorkOrderLineItem WL = new WorkOrderLineItem();
                        WL.Actions__c = Label.WOR_Actions_Nouveau_Foyer;
                        WL.WorkOrderId=WO.Id;
                        WL.Foyer__c=WO.AccountId;
                        WL.foyer_paneliste__c=WO.foyer_paneliste__c;
                        WL.Remarques__c=WO.Remarques__c;
                        listActionsToInsert.add(WL);
                    }
                    
                }
            }
            
               
           	if (wo.Type_de_l_intervention__c == Label.WOR_Type_d_intervention_Desinstallation){
                for (integer i =0; i <wo.Nombre_d_equipements__c; i++ ) {
                    WorkOrderLineItem WL = new WorkOrderLineItem();
                    WL.Actions__c = Label.WOR_Actions_Desinstallation_Definitive;
                    WL.WorkOrderId=WO.Id;
                    WL.Foyer__c=WO.AccountId;
                    WL.foyer_paneliste__c=WO.foyer_paneliste__c;
                    WL.Remarques__c=WO.Remarques__c;
                    listActionsToInsert.add(WL);
                }
            }
            
            
            if(wo.Account.Nombre_pc__c != null){
                nbDevices += wo.Account.Nombre_pc__c;
            }
            if(wo.Account.Nombre_smartphone__c != null){
                nbDevices += wo.Account.Nombre_smartphone__c;
            }
            if(wo.Account.Nombre_tablette__c != null){
                nbDevices += wo.Account.Nombre_tablette__c;
            }
            
            if(wo.Type_de_l_intervention__c == Label.WOR_Type_d_intervention_Installation && wo.foyer_paneliste__r.referentiel_panel__r.type_de_panel__c == Label.RFP_TypePanel_PaME && nbDevices >1){
                WorkOrderLineItem WL = new WorkOrderLineItem();
                WL.WorkOrderId=WO.Id;
                WL.Foyer__c=WO.AccountId;
                WL.foyer_paneliste__c=WO.foyer_paneliste__c;
                if(nbDevices >=2 && nbDevices<=4){
                    WL.Actions__c = Label.WOR_Actions_Parametrage_Meters_2_a_4;
                    listActionsToInsert.add(WL);
                }
                else if(nbDevices>=5 && nbDevices<=8){
                    WL.Actions__c =Label.WOR_Actions_Parametrage_Meters_5_a_8;
                    listActionsToInsert.add(WL);
                }
            }
            
        
        }
        if (listActionsToInsert != null && listActionsToInsert.size()>0 ){
            try{ 
                insert( listActionsToInsert);
            }Catch(exception ex){
                system.debug(ex.getmessage());
            }
            
        }
    }
    
    //method called before inserting work order line items, will determine the duration based on custom setting 
    public static void UpdateDurationWorkOrderLineItems(List<WorkOrderLineItem> ListWorkOrderLineItem){
        Map<String,Duree_de_lintervention__c> mapStringToDuree = new Map<String,Duree_de_lintervention__c>();
        List<Duree_de_lintervention__c> ListDuree= Duree_de_lintervention__c.getall().values();
        
        List<Id> WOIds = new List<Id>();
        Map<String,Map<String, List<WorkOrderLineItem>>> mapWOtoListWOLI = new Map<String,Map<String, List<WorkOrderLineItem>>>();
        
        for (WorkOrderLineItem woli :ListWorkOrderLineItem){
            WOIds.add(woli.WorkOrderId);
            
        }
        List<WorkOrderLineItem> AllWOLI = [SELECT Id, Duration, WorkOrderId, Actions__c, WorkOrder.Type_de_l_intervention__c, WorkOrder.foyer_paneliste__r.referentiel_panel__r.type_de_panel__c FROM WorkOrderLineITem WHERE WorkOrderID IN:WOIds];
        AllWOLI.addAll(ListWorkOrderLineItem);
        for(Duree_de_lintervention__c duree :ListDuree){
            mapStringToDuree.put(duree.Type_d_intervention__c+'-'+duree.Sous_type_d_intervention__c+'-'+duree.Evol__c, duree);
        }
        Map<Id,WorkOrder> MapWorkOrder = new Map<Id,WorkOrder>([SELECT Id,Type_de_l_intervention__c, foyer_paneliste__r.referentiel_panel__r.type_de_panel__c , Nombre_d_equipements__c FROM WorkOrder WHERE Id IN :WOIds ]);
        for(WorkOrderLineItem woli :AllWOLI){
            if(mapWOtoListWOLI.get(woli.WorkOrderId) != null){
                if(mapWOtoListWOLI.get(woli.WorkOrderId).get(MapWorkOrder.get(woli.WorkOrderId).Type_de_l_intervention__c+'-'+woli.Actions__c+'-'+MapWorkOrder.get(woli.WorkOrderId).foyer_paneliste__r.referentiel_panel__r.type_de_panel__c) !=null){
                    mapWOtoListWOLI.get(woli.WorkOrderId).get(MapWorkOrder.get(woli.WorkOrderId).Type_de_l_intervention__c+'-'+woli.Actions__c+'-'+MapWorkOrder.get(woli.WorkOrderId).foyer_paneliste__r.referentiel_panel__r.type_de_panel__c).add(woli);
                }
                else{
                    List<WorkOrderLineItem> listWOLINew = new List<WorkOrderLineItem>();
                    listWOLINew.add(woli);
                    mapWOtoListWOLI.get(woli.WorkOrderId).put(MapWorkOrder.get(woli.WorkOrderId).Type_de_l_intervention__c+'-'+woli.Actions__c+'-'+MapWorkOrder.get(woli.WorkOrderId).foyer_paneliste__r.referentiel_panel__r.type_de_panel__c,listWOLINew );	
                
                }
            }
            else{
                Map<String, List<WorkOrderLineItem>> mapTypeSousType = new Map<String, List<WorkOrderLineItem>>(); 
                List<WorkOrderLineItem> ListWOLI = new List<WorkOrderLineItem>();
                ListWOLI.add(woli);
                mapTypeSousType.put(MapWorkOrder.get(woli.WorkOrderId).Type_de_l_intervention__c+'-'+woli.Actions__c+'-'+MapWorkOrder.get(woli.WorkOrderId).foyer_paneliste__r.referentiel_panel__r.type_de_panel__c, ListWOLI);
                mapWOtoListWOLI.put(woli.WorkOrderId,mapTypeSousType );
            }
            
        }

        for(Map<String, List<WorkOrderLineItem>> MapConcatToListWoli :mapWOtoListWOLI.values()){
            for(String key :MapConcatToListWoli.keySet()){
                if (MapConcatToListWoli.get(key).size()>0){
                    if(MapConcatToListWoli.get(key)[0] != null){   
                        if(mapStringToDuree.get(key) != null && MapConcatToListWoli.get(key)[0].Duration == null && MapConcatToListWoli.get(key)[0].Actions__c == Label.WOR_Actions_Desinstallation_Definitive && MapWorkOrder.get(MapConcatToListWoli.get(key)[0].WorkOrderId).Nombre_d_equipements__c >2 ){
                             MapConcatToListWoli.get(key)[0].Duration = mapStringToDuree.get(key).Duree_3_postes__c;
                    }      
                   	 else if(mapStringToDuree.get(key) != null && MapConcatToListWoli.get(key)[0].Duration == null && MapConcatToListWoli.get(key)[0].Actions__c == Label.WOR_Actions_Desinstallation_Definitive && MapWorkOrder.get(MapConcatToListWoli.get(key)[0].WorkOrderId).Nombre_d_equipements__c <=2 ){
                            
                         MapConcatToListWoli.get(key)[0].Duration = mapStringToDuree.get(key).Duree_initiale__c; 
                    }                           
                        if(mapStringToDuree.get(key) != null && MapConcatToListWoli.get(key)[0].Duration == null && MapConcatToListWoli.get(key)[0].Actions__c != Label.WOR_Actions_Desinstallation_Definitive) { 
                         MapConcatToListWoli.get(key)[0].Duration = mapStringToDuree.get(key).Duree_initiale__c; 
                       }  
                }
                }
                    else{
                        continue;
                    }
                    if(MapConcatToListWoli.get(key).size()>1 && MapConcatToListWoli.get(key)[1] != null && MapConcatToListWoli.get(key)[1].Duration == null){
                        MapConcatToListWoli.get(key)[1].Duration = mapStringToDuree.get(key).Duree_2_postes__c;
                    }
              
                    if(MapConcatToListWoli.get(key).size()>2 && MapConcatToListWoli.get(key)[2] != null && MapConcatToListWoli.get(key)[2].Duration == null){
                        MapConcatToListWoli.get(key)[2].Duration = mapStringToDuree.get(key).Duree_3_postes__c;
                    }
                     
                    if(MapConcatToListWoli.get(key).size()>3 && MapConcatToListWoli.get(key)[3] != null && MapConcatToListWoli.get(key)[3].Duration == null){
                        MapConcatToListWoli.get(key)[3].Duration = mapStringToDuree.get(key).Duree_4_postes__c;
                    }
                    
                }
            }
        }
    }