force-app/main/default/objects/Account/fields/Nombre_TV__c.field-meta.xml
<CustomField>
    <fullName>Nombre_TV__c</fullName>
    <label>Nombre de TV actives</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_de_portable__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_portable__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Numéro de téléphone portable</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Actions__c.field-meta.xml
<CustomField>
    <fullName>Actions__c</fullName>
    <formula>IF( TEXT(Intervention__r.Actions__c) == &apos;1&apos;, $Label.WOR_Actions_Nouveau_Foyer_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;3&apos;, $Label.WOR_Actions_Suppression_D_Un_Poste_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;4&apos;, $Label.WOR_Actions_Changement_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;5&apos;, $Label.WOR_Actions_Controle_De_l_installation_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;6&apos;, $Label.WOR_Actions_Demenagement_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;7&apos;, $Label.WOR_Actions_Reinstallation_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;8&apos;, $Label.WOR_Actions_Desinstallation_Definitive_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;10&apos;, $Label.WOR_Actions_Verification_de_l_initialisation_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;11&apos;, $Label.WOR_Actions_Verification_Des_Elements_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;12&apos;, $Label.WOR_Actions_Controle_De_Connexion_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;13&apos;, $Label.WOR_Actions_Pb_Sonde_Tv_Declaration_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;14&apos;, $Label.WOR_Actions_Routeur_Ne_S_allume_plus_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;16&apos;, $Label.WOR_Actions_Controle_Audience_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;18&apos;, $Label.WOR_Actions_Mise_A_Jour_Etiquette_Equipement_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;19&apos;, $Label.WOR_Actions_Mutation_Audimetre_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;21&apos;, $Label.WOR_Actions_Ajout_De_Poste_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;22&apos;, $Label.WOR_Actions_Visite_De_Courtoisie_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;23&apos;, $Label.WOR_Actions_Passage_Improviste_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;24&apos;, $Label.WOR_Actions_Controle_Qualite_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;25&apos;, $Label.WOR_Actions_Auto_desinstallation_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;25&apos;, $Label.WOR_Actions_Configuration_Routeur_Pame_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;27&apos;, $Label.WOR_Actions_Parametrage_EtiquetteMeters_2_a_4_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;28&apos;, $Label.WOR_Actions_Parametrage_Meters_5_a_8_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;29&apos;, $Label.WOR_Actions_Configuration_Meters_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;31&apos;, $Label.WOR_Actions_Configuration_Routeur_2_et_plus_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;32&apos;, $Label.WOR_Actions_Modification_Abonnement_Etiquette, &apos;&apos;
))))))))))))))))))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actions</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Rendez-vous de service</relationshipLabel>
    <relationshipName>Rendez_vous_de_service</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_flows__c.field-meta.xml
<CustomField>
    <fullName>Bypass_flows__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass flows</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_triggers__c.field-meta.xml
<CustomField>
    <fullName>Bypass_triggers__c</fullName>
    <label>Bypass triggers</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AP01_BandeUsine</fullName>
            </value>
            <value>
                <fullName>AP01_Commande</fullName>
            </value>
            <value>
                <fullName>AP01_Conge</fullName>
            </value>
            <value>
                <fullName>AP01_Control</fullName>
                <isActive>false</isActive>
                <label>AP01_Control</label>
            </value>
            <value>
                <fullName>AP01_Controle</fullName>
            </value>
            <value>
                <fullName>AP01_Convention</fullName>
            </value>
            <value>
                <fullName>AP01_Equipement</fullName>
            </value>
            <value>
                <fullName>AP01_EquipementDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP01_Evenement</fullName>
            </value>
            <value>
                <fullName>AP01_Fidelisation</fullName>
            </value>
            <value>
                <fullName>AP01_Foyer</fullName>
            </value>
            <value>
                <fullName>AP01_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP01_IndividuPaneliste</fullName>
            </value>
            <value>
                <fullName>AP01_LienMeter</fullName>
            </value>
            <value>
                <fullName>AP01_MembreDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP01_Requete</fullName>
            </value>
            <value>
                <fullName>AP01_StockProduit</fullName>
            </value>
            <value>
                <fullName>AP01_SuiviStockSAV</fullName>
            </value>
            <value>
                <fullName>AP01_UpdatescheduledDate</fullName>
            </value>
            <value>
                <fullName>AP01_WorkOrder</fullName>
            </value>
            <value>
                <fullName>AP010_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP011_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP02_BandeUsine</fullName>
            </value>
            <value>
                <fullName>AP02_Commande</fullName>
            </value>
            <value>
                <fullName>AP02_Controle</fullName>
            </value>
            <value>
                <fullName>AP02_Convention</fullName>
            </value>
            <value>
                <fullName>AP02_Equipement</fullName>
            </value>
            <value>
                <fullName>AP02_EquipementDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP02_Foyer</fullName>
            </value>
            <value>
                <fullName>AP02_FoyerPaneliste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_validation_rules__c.field-meta.xml
<CustomField>
    <fullName>Bypass_validation_rules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass validation rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_workflows__c.field-meta.xml
<CustomField>
    <fullName>Bypass_workflows__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass workflows</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Le foyer sélectionné n&apos;est pas celui du foyer panéliste</errorMessage>
        <filterItems>
            <field>Foyer_paneliste__c.Foyer__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Interventions</relationshipLabel>
    <relationshipName>Interventions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Nombre_TV__c.field-meta.xml
<CustomField>
    <fullName>Nombre_TV__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nombre TV active</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Type_de_l_intervention__c.field-meta.xml
<CustomField>
    <fullName>Type_de_l_intervention__c</fullName>
    <label>Type d&apos;intervention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_d_intervention</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Actions</relationshipLabel>
    <relationshipName>Actions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Foyer_Paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_Paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer Panéliste</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Le foyer panéliste n&apos;est pas un des foyers panéliste du foyer</errorMessage>
        <filterItems>
            <field>Foyer_paneliste__c.Foyer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Foyer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Actions</relationshipLabel>
    <relationshipName>Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Type_d_intervention.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Installation</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Désinstallation</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Dépannage/Support</label>
    </customValue>
    <customValue>
        <fullName>Intervention</fullName>
        <isActive>false</isActive>
        <label>Intervention</label>
    </customValue>
    <customValue>
        <fullName>Visite de courtoisie</fullName>
        <isActive>false</isActive>
        <label>Visite de courtoisie</label>
    </customValue>
    <masterLabel>Type d&apos;intervention</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchRDD15_Action_Test.cls
/*
* @Auteur Claire VEHRLE
* @date: 09/03/2022
* @Classe: BarchRDD15_Action
* * History
* <Date of modification>   		<Author>    		<Description of modification>
*/
@isTest
public class BatchRDD15_Action_Test {

    @isTest
    Static void RDD_Action() {
         
         User u = [SELECT id, Bypass_flows__c, Bypass_validation_rules__c FROM User WHERE isActive = true and Profile.name like '%dministra%' limit 1];
         u.Bypass_workflows__c = true;
         u.Bypass_flows__c = true;
         u.Bypass_triggers__c = 'AP01_WorkOrder; AP08_FoyerPaneliste';
         update u;
        
        System.runAs(u){
        
        Id recordTypeIdFoyerPanelisteMMATPaME = Schema.SObjectType.Foyer_Paneliste__c.getRecordTypeInfosByName().get(Label.PAN_recordType_mediamatpame).getRecordTypeId();

        List<Account> foyerList = new List<Account>();
        
        Account foyer2 = Test_Utils.createFoyer();
        foyer2.Name = 'Foyer 2';
        foyer2.Numero_de_portable__c = '0622222222';
        foyer2.Nombre_tv__c = '3';
        foyerList.add(foyer2);
        
        insert foyerList;
        
        List<Foyer_Paneliste__c> foyerPanelisteList = new List<Foyer_Paneliste__c>();
        
        Foyer_Paneliste__c foyerPaneliste2 = new Foyer_Paneliste__c();
        foyerPaneliste2.RecordTypeId = recordTypeIdFoyerPanelisteMMATPaME;
        foyerPaneliste2.Name = 'Foyer Paneliste 2';
        foyerPaneliste2.Foyer__c = foyer2.Id;
        foyerPanelisteList.add(foyerPaneliste2);
        
        insert foyerPanelisteList;
        
        WorkOrder intervention = new WorkOrder();
        intervention.AccountId = foyer2.Id;
        intervention.Type_de_l_intervention__c = '1';
        intervention.Actions__c = '1';
        intervention.Foyer_paneliste__c = foyerPaneliste2.Id;
        
        insert intervention;
        
        WorkOrderLineItem action = new WorkOrderLineItem();
        action.Foyer__c = foyer2.Id;
        action.Actions__c = '1';
        action.WorkOrderId = intervention.Id;
        
        insert action;
        
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(intervention.id));
        BatchRDD15_Action btch = new BatchRDD15_Action();
        database.executeBatch(btch);
        Test.stopTest();
        
        //List<ServiceAppointment> rdvServiceBatch = [SELECT Id, Foyer_Paneliste__r.Id FROM ServiceAppointment WHERE AccountId = :foyer2.Id];
        WorkOrderLineItem actionList = [SELECT Id, Foyer_Paneliste__c FROM WorkOrderLineItem];
        
        System.debug('$$$actionList: ' + actionList);
        
         
            
        }
    }
}