force-app/main/default/objects/Account/fields/Numero_de_portable__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_portable__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Numéro de téléphone portable</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type_de_foyer__c.field-meta.xml
<CustomField>
    <fullName>Type_de_foyer__c</fullName>
    <label>Type de foyer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Médiamat</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Single Source</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>AIP</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Multi panel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Controle.recordType-meta.xml
<RecordType>
    <fullName>Controle</fullName>
    <active>true</active>
    <businessProcess>Contrôle</businessProcess>
    <label>Contrôle</label>
</RecordType>

force-app/main/default/objects/Controle__c/Controle__c.object-meta.xml
<CustomObject>
    <label>Contrôle</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du contrôle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrôles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Controle__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actif</fullName>
                <default>true</default>
                <label>Actif</label>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>Pré-codé</fullName>
            </value>
            <value>
                <fullName>Traité</fullName>
            </value>
            <value>
                <fullName>Abandonné</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Batch001_ControleAbandone_Test.cls
/*
* @author: Joyce Saidy
* @date: 10/09/2020
* @ Description Class that test Batch001_ControleAbandone  
* History
* <Date of modification>   <Author>    <Description of modification>
*/
@isTest
public class Batch001_ControleAbandone_Test {
    public static testMethod void Batch001_ControleAbandoneTest(){
        Id recordTypeIdFoyerPanMMPaME  = Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(Label.PAN_recordType_mediamatpame).getRecordTypeId();
        Id recordTypeIdFoyerPanAIP  = Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(Label.PAN_recordType_AIP).getRecordTypeId();
        
        //Create foyer
        list<Account> listFoyersToInsert = new list<Account>();
        account testAccount = Test_Utils.createFoyer();
        testAccount.Type_de_foyer__c = Label.ACC_Type_de_panel_Mediamat;
        testAccount.Numero_de_portable__c = '0611111121';
        listFoyersToInsert.add(testAccount);
        
        account testAccount2 = Test_Utils.createFoyer();
        testAccount2.Type_de_foyer__c = Label.ACC_Type_de_panel_AIP;
        testAccount2.Numero_de_portable__c = '0611111125';
        listFoyersToInsert.add(testAccount2);
        
        insert listFoyersToInsert; 
        
        Referentiel_Panel__c refPanTest = new Referentiel_Panel__c();
        refPanTest.Type_de_panel__c 	= Label.RFP_Nom_PaME;
        refPanTest.Name					= Label.RFP_Nom_PaME;
        insert refPanTest;
        
        Referentiel_Panel__c refPanTest2 = new Referentiel_Panel__c();
        refPanTest2.Type_de_panel__c 	= Label.RFP_Nom_AIP;
        refPanTest2.Name					= Label.RFP_Nom_AIP;
        insert refPanTest2;
        
        Foyer_paneliste__c foyerPanTest     = new Foyer_paneliste__c();
        foyerPanTest.foyer__c				= testAccount.id;
        foyerPanTest.Referentiel_Panel__c = refPanTest.id;
        foyerPanTest.Name = 'foyerPanTest';
        foyerPanTest.RecordTypeId = recordTypeIdFoyerPanMMPaME;
        insert foyerPanTest;
        
        Foyer_paneliste__c foyerPanTest2     = new Foyer_paneliste__c();
        foyerPanTest2.foyer__c				= testAccount2.id;
        foyerPanTest2.Referentiel_Panel__c = refPanTest2.id;
        foyerPanTest2.Name = 'foyerPanTest2';
        foyerPanTest2.RecordTypeId = recordTypeIdFoyerPanAIP;
        insert foyerPanTest2;
        
        //Create Case
        list<Case> listCaseToInsert = new list<Case>();
        Case testCase = Test_Utils.createCase(testAccount.id);
        testCase.Foyer_paneliste__c = foyerPanTest.Id;
        listCaseToInsert.add(testCase); 
        
        Id recordTypeIdControleAIP =Schema.SObjectType.case.getRecordTypeInfosByName().get(label.CAS_Recordtype_ControleAIP).getRecordTypeId();
        Case testCase2 = Test_Utils.createCase(testAccount2.id);
        testCase2.RecordTypeId=recordTypeIdControleAIP;
        testCase2.Foyer_paneliste__c = foyerPanTest2.Id;
        listCaseToInsert.add(testCase2); 
        insert listCaseToInsert; 
        
        //Create Controle
        list<Controle__c> listControleToInsert = new list<Controle__c>();
        Controle__c testCtrl = Test_Utils.createControle(testAccount.id,null,null,testCase.id,system.today()); 
        testCtrl.Statut__c=Label.CTRL_StatutActif;
        testCtrl.Foyer_Paneliste__c= foyerPanTest.Id;
        listControleToInsert.add(testCtrl);  
        
        Controle__c testCtrl2 = Test_Utils.createControle(testAccount2.id,null,null,testCase2.id,system.today()); 
        testCtrl2.Statut__c=Label.CTRL_StatutActif;
        testCtrl2.Foyer_Paneliste__c= foyerPanTest2.Id;
        listControleToInsert.add(testCtrl2);   
        
        insert listControleToInsert; 
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(testAccount.id)); 
        Batch001_ControleAbandone btch = new Batch001_ControleAbandone();
        database.executeBatch(btch);
        Test.stopTest(); 

		testCase2=[SELECT status from Case where Id=:testCase2.Id];
        System.debug('testCase2');
        System.debug(testCase2);
        
    }
}