force-app/main/default/objects/Account/fields/Numero_de_portable__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_portable__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Numéro de téléphone portable</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Statut_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Statut_du_foyer__c</fullName>
    <label>Statut du foyer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Recruté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Installé</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Equipé</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Integré</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Désinstallé</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Chute définitive</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chute temporaire</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Statut_du_foyer__c/Statut_du_foyer__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Ensemble clé-valeur pour le champ Statut du foyer de l&apos;objet Foyer</description>
    <label>Statut du foyer</label>
</CustomObject>

force-app/main/default/classes/Batch007_InstallationFoyer_Test.cls
/*
* @author: Joyce Saidy
* @date: 5/10/2020
* @ Description Class that test Batch007_InstallationFoyer  
* History
* <Date of modification>   <Author>    <Description of modification>
*/ 
@isTest
public class Batch007_InstallationFoyer_Test {
    public static testMethod void Batch007_InstallationFoyerTest(){
         
        //Create foyer
        list<Account> listFoyersToInsert = new list<Account>();
        account testAccount = Test_Utils.createFoyer();
        testAccount.Numero_de_portable__c = '0611111121';
        listFoyersToInsert.add(testAccount); 
        testAccount.Statut_du_foyer__c=Label.ACC_Statut_du_foyer_Recrute;
        insert listFoyersToInsert;         
        
        //MD
        //Foyer Panéliste
        List<Foyer_paneliste__c> listFoyerPaneliste = new List<Foyer_paneliste__c>();
        Foyer_Paneliste__c foyerPaneliste = Test_Utils.createFoyerPaneliste();
        foyerPaneliste.Foyer__c = testAccount.id;
        foyerPaneliste.Name = 'test foyer panéliste';
        listFoyerPaneliste.add(foyerPaneliste);        
        insert listFoyerPaneliste;
        
        //MD
        //Create Case
        list<Case> listCaseToInsert = new list<Case>();
        Case testCase = Test_Utils.createCase(testAccount.id);
        testCase.Origin = Label.CAS_Origine_NouveauFoyer;
        testCase.Foyer_paneliste__c = foyerPaneliste.Id;
        listCaseToInsert.add(testCase);  
        insert listCaseToInsert;
                
        Test.startTest();
        Batch007_InstallationFoyer btch = new Batch007_InstallationFoyer();
        database.executeBatch(btch);
        Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(testAccount.id)); 
        Test.stopTest();
        
    }
}