force-app/main/default/objects/Account/fields/Numero_de_portable__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_portable__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Numéro de téléphone portable</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Type_de_controle__c</fullName>
    <label>Type de contrôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <label>Présence</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Autres usages</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Connexion</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Participation</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Réception/abonnement</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Non Répondant</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Participation Web</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Foyer vacancier longue durée</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Inconnu</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Foyer vacancier</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Contrôle Beacon</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Installation SetMeter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Controle__c/Controle__c.object-meta.xml
<CustomObject>
    <label>Contrôle</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du contrôle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrôles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Controle__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actif</fullName>
                <default>true</default>
                <label>Actif</label>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>Pré-codé</fullName>
            </value>
            <value>
                <fullName>Traité</fullName>
            </value>
            <value>
                <fullName>Abandonné</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Type_de_controle__c</fullName>
    <label>Type de contrôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <label>Présence</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Autres usages</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Connexion</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Participation</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Réception/abonnement</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Non Répondant</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Participation Web</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Foyer vacancier longue durée</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Foyer vacancier</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Contrôle Beacon</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Installation SetMeter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Etiquette__c/Etiquette__c.object-meta.xml
<CustomObject>
    <label>Étiquette</label>
    <nameField>
        <displayFormat>ETQ - {000000}</displayFormat>
        <label>Numéro de l&apos;étiquette</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Étiquettes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Etiquette__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Etiquette__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Etiquette__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Etiquettes</relationshipLabel>
    <relationshipName>Etiquettes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Etiquette__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La foyer panéliste sélectionné n&apos;appartient pas au foyer choisi</errorMessage>
        <filterItems>
            <field>Foyer_paneliste__c.Foyer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Foyer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Étiquettes</relationshipLabel>
    <relationshipName>Etiquettes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Etiquette__c/fields/Nom_de_l_etiquette__c.field-meta.xml
<CustomField>
    <fullName>Nom_de_l_etiquette__c</fullName>
    <label>Nom de l&apos;étiquette</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abo en cours de changement</fullName>
                <isActive>false</isActive>
                <label>Abo en cours de changement</label>
            </value>
            <value>
                <fullName>Mauvaise réception</fullName>
                <label>AIP Mauvaise réception</label>
            </value>
            <value>
                <fullName>Mouvement atypique</fullName>
                <label>AIP Mouvement atypique</label>
            </value>
            <value>
                <fullName>Peu écoute casque</fullName>
                <label>AIP  Peu écoute casque</label>
            </value>
            <value>
                <fullName>Profession atypique</fullName>
                <label>AIP Profession atypique</label>
            </value>
            <value>
                <fullName>Refus temporaire de participation</fullName>
                <label>AIP Refus temporaire de participation</label>
            </value>
            <value>
                <fullName>Set meter(s) débranché(s)</fullName>
                <label>AIP Set meter(s) débranché(s)</label>
            </value>
            <value>
                <fullName>Attente intervention Ambassadeur pour installation du Meter</fullName>
            </value>
            <value>
                <fullName>Attente matériel MM</fullName>
            </value>
            <value>
                <fullName>Autodésinstallation</fullName>
            </value>
            <value>
                <fullName>Autres usages +</fullName>
            </value>
            <value>
                <fullName>Box monobloc</fullName>
            </value>
            <value>
                <fullName>Chgt FAI/Box</fullName>
            </value>
            <value>
                <fullName>Chgt TV</fullName>
            </value>
            <value>
                <fullName>Ctrl abonnement</fullName>
            </value>
            <value>
                <fullName>Débranchés</fullName>
            </value>
            <value>
                <fullName>Déménagement</fullName>
            </value>
            <value>
                <fullName>Device HS</fullName>
            </value>
            <value>
                <fullName>Device Incompatible</fullName>
            </value>
            <value>
                <fullName>Equipé Non Actif</fullName>
            </value>
            <value>
                <fullName>Foyer PaME à chuter</fullName>
            </value>
            <value>
                <fullName>Foyer témoin</fullName>
            </value>
            <value>
                <fullName>Foyer test</fullName>
            </value>
            <value>
                <fullName>Foyer vacancier</fullName>
            </value>
            <value>
                <fullName>Gros conso TV</fullName>
            </value>
            <value>
                <fullName>Indispo prochains jours</fullName>
            </value>
            <value>
                <fullName>INJ Step1</fullName>
            </value>
            <value>
                <fullName>INJ Step2</fullName>
            </value>
            <value>
                <fullName>INJ Step3</fullName>
            </value>
            <value>
                <fullName>INJ Step4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Etiquette__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actif</fullName>
                <default>true</default>
                <label>Actif</label>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Etiquette__c/fields/Type_de_Panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_Panel__c</fullName>
    <formula>TEXT( Foyer_paneliste__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de Panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Batch013_CreationRequeteAIPNonRep_Test.cls
/*
* @Auteur : Claire VEHRLE
* @date: 02/11/2021
* @Classe: Batch013_CreationRequeteAIPNonRep
* * History
* <Date of modification>   		<Author>    		<Description of modification>
*/
@IsTest
public class Batch013_CreationRequeteAIPNonRep_Test {
    
    @IsTest
    static void testCreationRequeteAIPNonRep() { 
         Id recordTypeIdFoyerPanelisteMMATPaME = Schema.SObjectType.Foyer_Paneliste__c.getRecordTypeInfosByName().get(Label.PAN_recordType_mediamatpame).getRecordTypeId();
        
        Id ControleAIPId = Schema.SObjectType.Controle__c.getRecordTypeInfosByName().get(Label.CTRL_RecordType_ControleAIP).getRecordTypeId();
        
        list<Account> listFoyersToInsert = new list<Account>();
        account foyer1 = Test_Utils.createFoyer();
        foyer1.Numero_de_portable__c = '0611111121';
        listFoyersToInsert.add(foyer1);
        
        account foyer2 = Test_Utils.createFoyer();
        foyer2.Numero_de_portable__c = '0611111121';
        listFoyersToInsert.add(foyer2);
        
        account foyer3 = Test_Utils.createFoyer();
        foyer3.Numero_de_portable__c = '0611111121';
        listFoyersToInsert.add(foyer3); 
        
        account foyer4 = Test_Utils.createFoyer();
        foyer4.Numero_de_portable__c = '0611111121';
        listFoyersToInsert.add(foyer4); 
        
        insert listFoyersToInsert;
        
        List<Referentiel_Panel__c> listReferentielPanelToInsert = new List<Referentiel_Panel__c>();
        Referentiel_Panel__c refPanelPaME = new Referentiel_Panel__c();
        refPanelPaME.Name = Label.RFP_Nom_PaME;
        refPanelPaME.Type_de_panel__c = Label.RFP_Nom_PaME;
        listReferentielPanelToInsert.add(refPanelPaME);
        
        insert listReferentielPanelToInsert;
        
        
        List<Foyer_Paneliste__c> foyerPanelisteList = new List<Foyer_Paneliste__c>();        
        Foyer_Paneliste__c foyerPaneliste1 = new Foyer_Paneliste__c();
        foyerPaneliste1.RecordTypeId = recordTypeIdFoyerPanelisteMMATPaME;
        foyerPaneliste1.Name = 'Foyer Paneliste 1';
        foyerPaneliste1.Foyer__c = foyer2.Id;
        foyerPaneliste1.Referentiel_Panel__c = refPanelPaME.Id;
        foyerPanelisteList.add(foyerPaneliste1);
                
        Foyer_Paneliste__c foyerPaneliste3 = new Foyer_Paneliste__c();
        foyerPaneliste3.RecordTypeId = recordTypeIdFoyerPanelisteMMATPaME;
        foyerPaneliste3.Name = 'Foyer Paneliste 1';
        foyerPaneliste3.Foyer__c = foyer3.Id;
        foyerPaneliste3.Referentiel_Panel__c = refPanelPaME.Id;
        foyerPanelisteList.add(foyerPaneliste3);
        
        insert foyerPanelisteList;
                
        List<Controle__c> contrleToInsert = new list<Controle__c>();
        Controle__c controle1 = Test_Utils.createControle(foyer1.Id, null, null, null, null);  
		controle1.Foyer_paneliste__c = foyerPaneliste1.Id;      
        controle1.RecordTypeId = ControleAIPId;  
        controle1.Type_de_controle__c = Label.CTRL_Type_NonRepondant;
        controle1.Statut__c = Label.CTRL_Statut_Precode;
        contrleToInsert.add(controle1);
        
        Controle__c controle2 = Test_Utils.createControle(foyer2.Id, null, null, null, null);  
        controle2.RecordTypeId = ControleAIPId;  
        controle2.Foyer_paneliste__c = foyerPaneliste1.Id;  
        controle2.Type_de_controle__c = Label.CTRL_Type_NonRepondant;  
        controle2.Statut__c = Label.CTRL_Statut_Precode;
        contrleToInsert.add(controle2);
        
        Controle__c controle3 = Test_Utils.createControle(foyer3.Id, null, null, null, null);  
		controle3.Foyer_paneliste__c = foyerPaneliste3.Id;       
        controle3.RecordTypeId = ControleAIPId;  
        controle3.Type_de_controle__c = Label.CTRL_Type_NonRepondant; 
        controle3.Statut__c = Label.CTRL_Statut_Precode;
        contrleToInsert.add(controle3);
        
        Controle__c controle4 = Test_Utils.createControle(foyer4.Id, null, null, null, null);  
        controle4.RecordTypeId = ControleAIPId;  
        controle4.Foyer_paneliste__c = foyerPaneliste3.Id;
        controle4.Type_de_controle__c = Label.CTRL_Type_NonRepondant; 
        controle4.Statut__c = Label.CTRL_Statut_Actif;
        contrleToInsert.add(controle4);
        
        insert contrleToInsert;
        
        list<Etiquette__c> listEtiquetteToInsert = new list<Etiquette__c>();
        Etiquette__c etq1 = Test_Utils.createEtiquette(foyer1.id, null, null, Date.Today(), Date.Today() + 2);
        etq1.Nom_de_l_etiquette__c = Label.ETI_Nom_de_l_etiquette_Raisons_Personnelles;
        listEtiquetteToInsert.add(etq1);
        
        Etiquette__c etq2 = Test_Utils.createEtiquette(foyer2.id, null, null, Date.Today(), Date.Today() + 2);
        etq2.Nom_de_l_etiquette__c = Label.ETI_Nom_de_l_etiquette_Refus_Temporaire_De_Participation;
        listEtiquetteToInsert.add(etq2);
        
        Etiquette__c etq3 = Test_Utils.createEtiquette(foyer3.id, null, null, Date.Today(), Date.Today() + 2);
        etq3.Nom_de_l_etiquette__c = Label.ETI_Nom_de_l_etiquette_Foyer_temoin;
        listEtiquetteToInsert.add(etq3);
        
        Etiquette__c etq4 = Test_Utils.createEtiquette(foyer3.id, null, null, Date.Today(), Date.Today() + 2);
        etq4.Nom_de_l_etiquette__c = Label.ETI_Nom_de_l_etiquette_Raisons_Personnelles;
        listEtiquetteToInsert.add(etq4);
        
        insert listEtiquetteToInsert;
        
        List<Etiquette__c> etiquetteToUpdate = new List<Etiquette__c>();
        Test.setCreatedDate(etq1.Id, Date.Today() - 6);
        etq1.Date_de_debut__c = Date.Today() - 5;
        etq1.Date_de_fin__c = Date.Today() - 1;
        etiquetteToUpdate.add(etq1);
        
        Test.setCreatedDate(etq2.Id, Date.Today() - 3);
        etq2.Date_de_debut__c = Date.Today() - 2;
        etq2.Date_de_fin__c = Date.Today() + 2;
        etiquetteToUpdate.add(etq2);
        
        Test.setCreatedDate(etq3.Id, Date.Today() - 11);
        etq3.Date_de_debut__c = Date.Today() - 10;
        etq3.Date_de_fin__c = Date.Today() - 3;
        etiquetteToUpdate.add(etq3);
        
        Test.setCreatedDate(etq4.Id, Date.Today() - 11);
        etq4.Date_de_debut__c = Date.Today() - 10;
        etq4.Date_de_fin__c = Date.Today() + 3;
        etiquetteToUpdate.add(etq4);
        
        update etiquetteToUpdate;
        
        Test.startTest();
        Batch013_CreationRequeteAIPNonRep btch = new Batch013_CreationRequeteAIPNonRep();
        database.executeBatch(btch);
        Test.stopTest();
        
        List<Case> requeteList =  [SELECT Id, Account.Id FROM Case];
        List<Controle__c> controleList =  [SELECT Id, Foyer__c, Requete__r.Id FROM Controle__c WHERE Foyer__r.Id = :foyer2.Id];
        
        System.debug('$$$requeteList: ' + requeteList);
        System.debug('$$$controle1: ' + controle1);
        
        //System.assertEquals(2, requeteList.size());
        //System.assertEquals(foyer2.id, requeteList[0].Account.Id);
        
        
    }
}