force-app/main/default/objects/Account/fields/Numero_de_portable__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_portable__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Numéro de téléphone portable</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Actions__c.field-meta.xml
<CustomField>
    <fullName>Actions__c</fullName>
    <formula>IF( TEXT(Intervention__r.Actions__c) == &apos;1&apos;, $Label.WOR_Actions_Nouveau_Foyer_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;3&apos;, $Label.WOR_Actions_Suppression_D_Un_Poste_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;4&apos;, $Label.WOR_Actions_Changement_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;5&apos;, $Label.WOR_Actions_Controle_De_l_installation_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;6&apos;, $Label.WOR_Actions_Demenagement_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;7&apos;, $Label.WOR_Actions_Reinstallation_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;8&apos;, $Label.WOR_Actions_Desinstallation_Definitive_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;10&apos;, $Label.WOR_Actions_Verification_de_l_initialisation_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;11&apos;, $Label.WOR_Actions_Verification_Des_Elements_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;12&apos;, $Label.WOR_Actions_Controle_De_Connexion_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;13&apos;, $Label.WOR_Actions_Pb_Sonde_Tv_Declaration_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;14&apos;, $Label.WOR_Actions_Routeur_Ne_S_allume_plus_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;16&apos;, $Label.WOR_Actions_Controle_Audience_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;18&apos;, $Label.WOR_Actions_Mise_A_Jour_Etiquette_Equipement_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;19&apos;, $Label.WOR_Actions_Mutation_Audimetre_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;21&apos;, $Label.WOR_Actions_Ajout_De_Poste_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;22&apos;, $Label.WOR_Actions_Visite_De_Courtoisie_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;23&apos;, $Label.WOR_Actions_Passage_Improviste_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;24&apos;, $Label.WOR_Actions_Controle_Qualite_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;25&apos;, $Label.WOR_Actions_Auto_desinstallation_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;25&apos;, $Label.WOR_Actions_Configuration_Routeur_Pame_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;27&apos;, $Label.WOR_Actions_Parametrage_EtiquetteMeters_2_a_4_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;28&apos;, $Label.WOR_Actions_Parametrage_Meters_5_a_8_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;29&apos;, $Label.WOR_Actions_Configuration_Meters_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;31&apos;, $Label.WOR_Actions_Configuration_Routeur_2_et_plus_Etiquette,
IF( TEXT(Intervention__r.Actions__c) == &apos;32&apos;, $Label.WOR_Actions_Modification_Abonnement_Etiquette, &apos;&apos;
))))))))))))))))))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actions</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Rendez-vous de service</relationshipLabel>
    <relationshipName>Rendez_vous_de_service</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Actions__c.field-meta.xml
<CustomField>
    <fullName>Actions__c</fullName>
    <label>Actions</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_de_l_intervention__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>21</fullName>
                <label>Ajout de poste</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Auto désinstallation</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Changement (TV, barre de son ect …)</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Configuration Meters (si boite mail ok)</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Configuration routeur (connexion des equipements au routeur Mediametrie )</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>Configuration routeur (connexion des equipements au routeur Mediametrie ) 2 et +</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Configuration Routeur (Pame)</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Contrôle audience</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Contrôle de connexion</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Contrôle de l&apos;installation</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Contrôle qualité</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Déménagement</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Désinstallation définitive</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Mise à jour équipement</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Modification Abonnement</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Mutation Audimètre</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Nouveau foyer</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Paramétrage Meters 2 à 4</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Paramétrage Meters 5 à 8</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Passage Improviste</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Pb Sonde Tv (Déclaration)</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Réinstallation</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Routeur ne s&apos;allume plus</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Suppression d&apos;un poste</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Vérification de l&apos;initialisation</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Vérification des éléments</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>Visite de courtoisie</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>Streaming Meter</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>Contrôle Streaming Meter</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>Réinstallation Streaming Meter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Le foyer sélectionné n&apos;est pas celui du foyer panéliste</errorMessage>
        <filterItems>
            <field>Foyer_paneliste__c.Foyer__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Interventions</relationshipLabel>
    <relationshipName>Interventions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Type_de_l_intervention__c.field-meta.xml
<CustomField>
    <fullName>Type_de_l_intervention__c</fullName>
    <label>Type d&apos;intervention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_d_intervention</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Type_d_intervention.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Installation</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Désinstallation</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Dépannage/Support</label>
    </customValue>
    <customValue>
        <fullName>Intervention</fullName>
        <isActive>false</isActive>
        <label>Intervention</label>
    </customValue>
    <customValue>
        <fullName>Visite de courtoisie</fullName>
        <isActive>false</isActive>
        <label>Visite de courtoisie</label>
    </customValue>
    <masterLabel>Type d&apos;intervention</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchRDD10_RDVService_Test.cls
/*
* @Auteur Claire VEHRLE
* @date: 09/03/2022
* @Classe: BatchRDD10_RDVService
* * History
* <Date of modification>   		<Author>    		<Description of modification>
*/
@isTest
public class BatchRDD10_RDVService_Test {

    @isTest
    Static void RDD_RDVService() {
        
        Id recordTypeIdFoyerPanelisteMMATPaME = Schema.SObjectType.Foyer_Paneliste__c.getRecordTypeInfosByName().get(Label.PAN_recordType_mediamatpame).getRecordTypeId();

        List<Account> foyerList = new List<Account>();
        
        Account foyer2 = Test_Utils.createFoyer();
        foyer2.Name = 'Foyer 2';
        foyer2.Numero_de_portable__c = '0622222222';
        foyerList.add(foyer2);
        
        insert foyerList;
        
        List<Foyer_Paneliste__c> foyerPanelisteList = new List<Foyer_Paneliste__c>();
        
        Foyer_Paneliste__c foyerPaneliste2 = new Foyer_Paneliste__c();
        foyerPaneliste2.RecordTypeId = recordTypeIdFoyerPanelisteMMATPaME;
        foyerPaneliste2.Name = 'Foyer Paneliste 2';
        foyerPaneliste2.Foyer__c = foyer2.Id;
        foyerPanelisteList.add(foyerPaneliste2);
        
        insert foyerPanelisteList;
        
        WorkOrder intervention = new WorkOrder();
        intervention.AccountId = foyer2.Id;
        intervention.Type_de_l_intervention__c = '1';
        intervention.Actions__c = '1';
        intervention.Foyer_paneliste__c = foyerPaneliste2.Id;
        
        insert intervention;
        
        ServiceAppointment rdvService = new ServiceAppointment();
        rdvService.ParentRecordId = intervention.Id;
        
        insert rdvService;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(intervention.id));
        BatchRDD10_RDVService btch = new BatchRDD10_RDVService();
        database.executeBatch(btch);
        Test.stopTest();
        
        //List<ServiceAppointment> rdvServiceBatch = [SELECT Id, Foyer_Paneliste__r.Id FROM ServiceAppointment WHERE AccountId = :foyer2.Id];
        List<ServiceAppointment> rdvServiceBatch = [SELECT Id, Foyer_Paneliste__r.Id FROM ServiceAppointment];
        
        System.debug('$$$rdvServiceBatch: ' + rdvServiceBatch);
        
        System.assertEquals(foyerPaneliste2.Id, rdvServiceBatch[0].Foyer_Paneliste__r.Id);
    }
}