force-app/main/default/objects/Account/fields/Numero_de_portable__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_portable__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Numéro de téléphone portable</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_de_telephone_fixe__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_telephone_fixe__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Numéro de téléphone fixe</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Statut_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Statut_du_foyer__c</fullName>
    <label>Statut du foyer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Recruté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Installé</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Equipé</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Integré</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Désinstallé</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Chute définitive</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chute temporaire</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Type_de_foyer__c.field-meta.xml
<CustomField>
    <fullName>Type_de_foyer__c</fullName>
    <label>Type de foyer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Médiamat</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Single Source</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>AIP</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Multi panel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appel__c/Appel__c.object-meta.xml
<CustomObject>
    <description>Objet pour lancer les appels webservice avaya (preparelistOfCalls)</description>
    <label>Appel</label>
    <nameField>
        <displayFormat>Appel-{0000}</displayFormat>
        <label>Appel Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign/fields/CampagneID_Avaya__c.field-meta.xml
<CustomField>
    <fullName>CampagneID_Avaya__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CampagneID Avaya</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Campaign/fields/Temps_dattente__c.field-meta.xml
<CustomField>
    <fullName>Temps_dattente__c</fullName>
    <defaultValue>30</defaultValue>
    <inlineHelpText>Secondes</inlineHelpText>
    <label>T&apos;emps d&apos;attente</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Etiquette__c/Etiquette__c.object-meta.xml
<CustomObject>
    <label>Étiquette</label>
    <nameField>
        <displayFormat>ETQ - {000000}</displayFormat>
        <label>Numéro de l&apos;étiquette</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Étiquettes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Etiquette__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Etiquettes</relationshipLabel>
    <relationshipName>Etiquettes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Etiquette__c/fields/Nom_de_l_etiquette__c.field-meta.xml
<CustomField>
    <fullName>Nom_de_l_etiquette__c</fullName>
    <label>Nom de l&apos;étiquette</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abo en cours de changement</fullName>
                <isActive>false</isActive>
                <label>Abo en cours de changement</label>
            </value>
            <value>
                <fullName>Mauvaise réception</fullName>
                <label>AIP Mauvaise réception</label>
            </value>
            <value>
                <fullName>Mouvement atypique</fullName>
                <label>AIP Mouvement atypique</label>
            </value>
            <value>
                <fullName>Peu écoute casque</fullName>
                <label>AIP  Peu écoute casque</label>
            </value>
            <value>
                <fullName>Profession atypique</fullName>
                <label>AIP Profession atypique</label>
            </value>
            <value>
                <fullName>Refus temporaire de participation</fullName>
                <label>AIP Refus temporaire de participation</label>
            </value>
            <value>
                <fullName>Set meter(s) débranché(s)</fullName>
                <label>AIP Set meter(s) débranché(s)</label>
            </value>
            <value>
                <fullName>Attente intervention Ambassadeur pour installation du Meter</fullName>
            </value>
            <value>
                <fullName>Attente matériel MM</fullName>
            </value>
            <value>
                <fullName>Autodésinstallation</fullName>
            </value>
            <value>
                <fullName>Autres usages +</fullName>
            </value>
            <value>
                <fullName>Box monobloc</fullName>
            </value>
            <value>
                <fullName>Chgt FAI/Box</fullName>
            </value>
            <value>
                <fullName>Chgt TV</fullName>
            </value>
            <value>
                <fullName>Ctrl abonnement</fullName>
            </value>
            <value>
                <fullName>Débranchés</fullName>
            </value>
            <value>
                <fullName>Déménagement</fullName>
            </value>
            <value>
                <fullName>Device HS</fullName>
            </value>
            <value>
                <fullName>Device Incompatible</fullName>
            </value>
            <value>
                <fullName>Equipé Non Actif</fullName>
            </value>
            <value>
                <fullName>Foyer PaME à chuter</fullName>
            </value>
            <value>
                <fullName>Foyer témoin</fullName>
            </value>
            <value>
                <fullName>Foyer test</fullName>
            </value>
            <value>
                <fullName>Foyer vacancier</fullName>
            </value>
            <value>
                <fullName>Gros conso TV</fullName>
            </value>
            <value>
                <fullName>Indispo prochains jours</fullName>
            </value>
            <value>
                <fullName>INJ Step1</fullName>
            </value>
            <value>
                <fullName>INJ Step2</fullName>
            </value>
            <value>
                <fullName>INJ Step3</fullName>
            </value>
            <value>
                <fullName>INJ Step4</fullName>
            </value>
            <value>
                <fullName>Pilote TvRouteur</fullName>
                <isActive>false</isActive>
                <label>Pilote TvRouteur</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Statut_du_foyer__c/Statut_du_foyer__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Ensemble clé-valeur pour le champ Statut du foyer de l&apos;objet Foyer</description>
    <label>Statut du foyer</label>
</CustomObject>

force-app/main/default/objects/User/fields/Bypass_validation_rules__c.field-meta.xml
<CustomField>
    <fullName>Bypass_validation_rules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass validation rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AP10_CreateAppels_Test.cls
@isTest
public class AP10_CreateAppels_Test {
    
    @isTest
    static void testCreateAppels() {
        // Test data setup
        List<Id> recordIdList = new List<Id>();
        recordIdList.add(createTestRecord('Case'));
        recordIdList.add(createTestRecord('Task'));
        recordIdList.add(createTestRecord('Etiquette__c'));
        recordIdList.add(createTestRecord('Account'));
        
        String campaignId = createTestCampaign();
        
        // Call the method under test
        Set<Appel__c> appels = AP10_CreateAppels.CreateAppels(recordIdList, campaignId);
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('AcceptTryRessource');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        // Associate the callout with a mock response
        Test.setMock(HttpCalloutMock.class, mock);
        // Perform assertions
        System.assertNotEquals(null, appels, 'CreateAppels() returned null');
        System.assertEquals(4, appels.size(), 'Incorrect number of appels created');
    }
    
    static Id createTestRecord(String objectType) {
        
        User adminUser =[SELECT Id,UserRoleId FROM User WHERE Profile.Name='System Administrator'And IsActive=true Limit 1];
        adminUser.Bypass_validation_rules__c=true;
        update adminUser;
        
        SObject obj;
        System.runAs(adminUser){
        
        if (objectType == 'Case') {
            //System.runAs(adminUser){
            obj = new Case(AccountId = createTestAccount());
            } else if (objectType == 'Task') {
            obj = new Task(WhatId = createTestAccount()); // Use WhatId instead of AccountId
        } else if (objectType == 'Etiquette__c') {
            obj = new Etiquette__c(Foyer__c = createTestAccount(),Nom_de_l_etiquette__c=/*'Pilote TvRouteur'*/'Foyer test');
        } else if (objectType == 'Account') {
            obj = new Account(Name = 'Test Account2',Statut_du_foyer__c='0', Type_de_foyer__c='1');
        }
        
        
        insert obj;
        }
        return obj.Id;
    
    }
    
    static Id createTestAccount() {
        Account acc = new Account(Name = 'Test Account',Statut_du_foyer__c='0', Type_de_foyer__c='1',Numero_de_telephone_fixe__c='0123456789',Numero_de_portable__c='0123456789');
        insert acc;
        return acc.Id;
    }
    
    static String createTestCampaign() {
        Campaign campaign = new campaign(Temps_dattente__c = 10,CampagneID_Avaya__c='ID1',Name='Anes Test');
        insert campaign;
        return campaign.Id;
    }
}