force-app/main/default/objects/Account/fields/Numero_de_portable__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_portable__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Numéro de téléphone portable</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Etiquette__c/Etiquette__c.object-meta.xml
<CustomObject>
    <label>Étiquette</label>
    <nameField>
        <displayFormat>ETQ - {000000}</displayFormat>
        <label>Numéro de l&apos;étiquette</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Étiquettes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Etiquette__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Etiquettes</relationshipLabel>
    <relationshipName>Etiquettes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Etiquette__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La foyer panéliste sélectionné n&apos;appartient pas au foyer choisi</errorMessage>
        <filterItems>
            <field>Foyer_paneliste__c.Foyer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Foyer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Étiquettes</relationshipLabel>
    <relationshipName>Etiquettes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Etiquette__c/fields/Nom_de_l_etiquette__c.field-meta.xml
<CustomField>
    <fullName>Nom_de_l_etiquette__c</fullName>
    <label>Nom de l&apos;étiquette</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abo en cours de changement</fullName>
                <isActive>false</isActive>
                <label>Abo en cours de changement</label>
            </value>
            <value>
                <fullName>Mauvaise réception</fullName>
                <label>AIP Mauvaise réception</label>
            </value>
            <value>
                <fullName>Mouvement atypique</fullName>
                <label>AIP Mouvement atypique</label>
            </value>
            <value>
                <fullName>Peu écoute casque</fullName>
                <label>AIP  Peu écoute casque</label>
            </value>
            <value>
                <fullName>Profession atypique</fullName>
                <label>AIP Profession atypique</label>
            </value>
            <value>
                <fullName>Refus temporaire de participation</fullName>
                <label>AIP Refus temporaire de participation</label>
            </value>
            <value>
                <fullName>Set meter(s) débranché(s)</fullName>
                <label>AIP Set meter(s) débranché(s)</label>
            </value>
            <value>
                <fullName>Attente intervention Ambassadeur pour installation du Meter</fullName>
            </value>
            <value>
                <fullName>Attente matériel MM</fullName>
            </value>
            <value>
                <fullName>Autodésinstallation</fullName>
            </value>
            <value>
                <fullName>Autres usages +</fullName>
            </value>
            <value>
                <fullName>Box monobloc</fullName>
            </value>
            <value>
                <fullName>Chgt FAI/Box</fullName>
            </value>
            <value>
                <fullName>Chgt TV</fullName>
            </value>
            <value>
                <fullName>Ctrl abonnement</fullName>
            </value>
            <value>
                <fullName>Débranchés</fullName>
            </value>
            <value>
                <fullName>Déménagement</fullName>
            </value>
            <value>
                <fullName>Device HS</fullName>
            </value>
            <value>
                <fullName>Device Incompatible</fullName>
            </value>
            <value>
                <fullName>Equipé Non Actif</fullName>
            </value>
            <value>
                <fullName>Foyer PaME à chuter</fullName>
            </value>
            <value>
                <fullName>Foyer témoin</fullName>
            </value>
            <value>
                <fullName>Foyer test</fullName>
            </value>
            <value>
                <fullName>Foyer vacancier</fullName>
            </value>
            <value>
                <fullName>Gros conso TV</fullName>
            </value>
            <value>
                <fullName>Indispo prochains jours</fullName>
            </value>
            <value>
                <fullName>INJ Step1</fullName>
            </value>
            <value>
                <fullName>INJ Step2</fullName>
            </value>
            <value>
                <fullName>INJ Step3</fullName>
            </value>
            <value>
                <fullName>INJ Step4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchRDD07_Etiquette_Test.cls
@isTest
public class BatchRDD07_Etiquette_Test {
    
    @isTest
    Static void etiqu(){
         Id recordTypeIdFoyerPanelisteMMATPaME = Schema.SObjectType.Foyer_Paneliste__c.getRecordTypeInfosByName().get(Label.PAN_recordType_mediamatpame).getRecordTypeId();

        List<Account> foyerList = new List<Account>();
        Account foyer1 = Test_Utils.createFoyer();
        foyer1.Name = 'Foyer 1';
        foyer1.Numero_de_portable__c = '0611111121';
        foyerList.add(foyer1);
        
        Account foyer2 = Test_Utils.createFoyer();
        foyer2.Name = 'Foyer 2';
        foyer2.Numero_de_portable__c = '0622222222';
        foyerList.add(foyer2);
        
        insert foyerList;
        
         List<Foyer_Paneliste__c> foyerPanelisteList = new List<Foyer_Paneliste__c>();
        Foyer_Paneliste__c foyerPaneliste1 = new Foyer_Paneliste__c();
        foyerPaneliste1.RecordTypeId = recordTypeIdFoyerPanelisteMMATPaME;
        foyerPaneliste1.Name = 'Foyer Paneliste 1';
        foyerPaneliste1.Foyer__c = foyer1.Id;
        foyerPanelisteList.add(foyerPaneliste1);
        
        Foyer_Paneliste__c foyerPaneliste2 = new Foyer_Paneliste__c();
        foyerPaneliste2.RecordTypeId = recordTypeIdFoyerPanelisteMMATPaME;
        foyerPaneliste2.Name = 'Foyer Paneliste 2';
        foyerPaneliste2.Foyer__c = foyer2.Id;
        foyerPanelisteList.add(foyerPaneliste2);
        
        insert foyerPanelisteList;
        Etiquette__c et = new Etiquette__c();
        et.Foyer__c = foyer2.id;
        et.Nom_de_l_etiquette__c = 'Foyer test';
        insert et;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(et.id));
        BatchRDD07_Etiquette btch = new BatchRDD07_Etiquette();
        database.executeBatch(btch);
        Test.stopTest();
        
        List<Etiquette__c> etiBatch = [SELECT Id, Foyer_Paneliste__c FROM Etiquette__c WHERE foyer__c = :foyer2.Id];
        
        System.assertEquals(foyerPaneliste2.Id, etiBatch[0].Foyer_Paneliste__c);
    }

}