force-app/main/default/objects/Account/fields/Numero_de_portable__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_portable__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Numéro de téléphone portable</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type_de_foyer__c.field-meta.xml
<CustomField>
    <fullName>Type_de_foyer__c</fullName>
    <label>Type de foyer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Médiamat</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Single Source</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>AIP</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Multi panel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Activite_actuelle__c.field-meta.xml
<CustomField>
    <fullName>Activite_actuelle__c</fullName>
    <label>Activité actuelle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
                <label>Au chômage ayant déjà travaillé</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Exerce une activité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>À la rechercher d&apos;un 1er emploi</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Retraite ou pré-retraite</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Congé maternité</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Congé parental</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Maladie longue durée</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Femme ou homme au foyer</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Autre cas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Code_profession__c.field-meta.xml
<CustomField>
    <fullName>Code_profession__c</fullName>
    <label>Code profession</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CON_ExtId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>CON_ExtId_SIPanel__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>CON_ExtId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Lien_de_parente_stat__c.field-meta.xml
<CustomField>
    <fullName>Lien_de_parente_stat__c</fullName>
    <label>Lien de parenté stat</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Couple</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Parent</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Enfant</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Famille</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Isolé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Lien_parente__c.field-meta.xml
<CustomField>
    <fullName>Lien_parente__c</fullName>
    <label>Lien parenté</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Chef de famille</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Conjoint</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Enfant</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Ascendant</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Autre</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Membre</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Invité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Non panéliste</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP00_Objet_Non_transforme_Test.cls
/*
* @date: 06/07/2022
* @ Description Class qui teste AP01_Commande . Associatée au declenchers : REqueteAfterUpdate & REqueteAfterInsert
* @version 1.00   
* pourcentage : 95%
* @Auteur Claire VEHRLE
 History
* <Date of modification> <Author> 	<Description of modification>
*/
@isTest
public class AP00_Objet_Non_transforme_Test {

    @isTest
    static void foyerNonTransformeMMATPaME() {
        Account foyer = new Account();
        foyer.name = 'Foyer';
        foyer.Numero_de_portable__c = '0123456789';
        foyer.Type_de_foyer__c = Label.ACC_Type_de_panel_Mediamat;
        
        insert foyer;
        AP00_Objet_Non_transforme.foyerNonTransformeMMATPaME();
    }
    
    @isTest
    static void foyerNonTransformeAIP() {
        Account foyer = new Account();
        foyer.name = 'Foyer';
        foyer.Numero_de_portable__c = '0123456789';
        foyer.Type_de_foyer__c = Label.ACC_Type_de_panel_AIP;
        
        insert foyer;
        AP00_Objet_Non_transforme.foyerNonTransformeAIP();
    }
    
    @isTest
    static void compoFoyerNonTransformeMMATPaME() {
        Account foyer = new Account();
        foyer.name = 'Foyer';
        foyer.Numero_de_portable__c = '0123456789';
        foyer.Type_de_foyer__c = Label.ACC_Type_de_panel_Mediamat;
        
        insert foyer;
        
        Contact compoFoyer = new Contact();
        compoFoyer.AccountId = foyer.Id;
        compoFoyer.LastName = 'Compo Foyer';
        compoFoyer.Lien_parente__c = Label.CON_LienParente_ChefDeFamille;
        compoFoyer.Activite_actuelle__c = System.Label.CON_ActiviteActuelle_A_la_recherche_premier_emploi;
        compoFoyer.Code_profession__c = 132;
        compoFoyer.Birthdate = Date.today();
        compoFoyer.Type__c = Label.CON_Type_MEMBRE;
        compoFoyer.CON_ExtId_SIPanel__c = '122223456';
        
        insert compoFoyer;   
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(compoFoyer.Id));
        AP00_Objet_Non_transforme.compoFoyerNonTransformeMMATPaME();
        Test.stopTest();
    }
    
    @isTest
    static void compoFoyerNonTransformeAIP() {
        Account foyer = new Account();
        foyer.name = 'Foyer';
        foyer.Numero_de_portable__c = '0123456789';
        foyer.Type_de_foyer__c = Label.ACC_Type_de_panel_AIP;
        
        insert foyer;
        
        Contact compoFoyer = new Contact();
        compoFoyer.AccountId = foyer.Id;
        compoFoyer.LastName = 'Compo Foyer';
        compoFoyer.Lien_de_parente_stat__c = Label.CON_LienParenteStat_Parent;
        compoFoyer.Activite_actuelle__c = System.Label.CON_ActiviteActuelle_A_la_recherche_premier_emploi;
        compoFoyer.Code_profession__c = 132;
        compoFoyer.Birthdate = Date.today();
        compoFoyer.Type__c = Label.CON_Type_MEMBRE;
        compoFoyer.CON_ExtId_SIPanel__c = '122223456';
        
        insert compoFoyer;   
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(compoFoyer.Id));
        AP00_Objet_Non_transforme.compoFoyerNonTransformeAIP();
        Test.stopTest();
    }
}