force-app/main/default/objects/Account/fields/Numero_de_portable__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_portable__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Numéro de téléphone portable</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Activite_actuelle__c.field-meta.xml
<CustomField>
    <fullName>Activite_actuelle__c</fullName>
    <label>Activité actuelle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
                <label>Au chômage ayant déjà travaillé</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Exerce une activité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>À la rechercher d&apos;un 1er emploi</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Retraite ou pré-retraite</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Congé maternité</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Congé parental</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Maladie longue durée</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Femme ou homme au foyer</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Autre cas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CON_ExtId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>CON_ExtId_SIPanel__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>CON_ExtId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/CSP42__c.field-meta.xml
<CustomField>
    <fullName>CSP42__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code profession CSP42</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Lien_parente__c.field-meta.xml
<CustomField>
    <fullName>Lien_parente__c</fullName>
    <label>Lien parenté</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Chef de famille</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Conjoint</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Enfant</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Ascendant</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Autre</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fidelisation__c/Fidelisation__c.object-meta.xml
<CustomObject>
    <label>Fidélisation</label>
    <nameField>
        <displayFormat>FID-{0000}</displayFormat>
        <label>Nom de Fidélisation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fidélisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fidelisation__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Composition du foyer</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Ce membre de foyer ne fait pas partie de ce foyer ou il n&apos;existe pas</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Foyer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fidelisations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fid_lisations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fidelisations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Individu_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Individu_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individu Panéliste</label>
    <referenceTo>Individu_Paneliste__c</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fid_lisations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT(Foyer_paneliste__r.Referentiel_Panel__r.Type_de_panel__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/recordTypes/AIP.recordType-meta.xml
<RecordType>
    <fullName>AIP</fullName>
    <active>true</active>
    <label>AIP</label>
</RecordType>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/CON_EXTId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>CON_EXTId_SIPanel__c</fullName>
    <description>&quot;(UUID) c&apos;est l&apos;id salesforce de l&apos;enregistrement Composition Du Foyer Parent
Ce champ sert a identifier l&apos;enregistrement parent (Composition Du Foyer) de l&apos;Individu Panéliste&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>CON_EXTId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Individus Panélistes</relationshipLabel>
    <relationshipName>Individus_Paneliste</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT( Foyer_paneliste__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_flows__c.field-meta.xml
<CustomField>
    <fullName>Bypass_flows__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass flows</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_triggers__c.field-meta.xml
<CustomField>
    <fullName>Bypass_triggers__c</fullName>
    <label>Bypass triggers</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AP01_BandeUsine</fullName>
            </value>
            <value>
                <fullName>AP01_Commande</fullName>
            </value>
            <value>
                <fullName>AP01_Conge</fullName>
            </value>
            <value>
                <fullName>AP01_Control</fullName>
                <isActive>false</isActive>
                <label>AP01_Control</label>
            </value>
            <value>
                <fullName>AP01_Controle</fullName>
            </value>
            <value>
                <fullName>AP01_Convention</fullName>
            </value>
            <value>
                <fullName>AP01_Equipement</fullName>
            </value>
            <value>
                <fullName>AP01_EquipementDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP01_Evenement</fullName>
            </value>
            <value>
                <fullName>AP01_Fidelisation</fullName>
            </value>
            <value>
                <fullName>AP01_Foyer</fullName>
            </value>
            <value>
                <fullName>AP01_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP01_IndividuPaneliste</fullName>
            </value>
            <value>
                <fullName>AP01_LienMeter</fullName>
            </value>
            <value>
                <fullName>AP01_MembreDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP01_Requete</fullName>
            </value>
            <value>
                <fullName>AP01_StockProduit</fullName>
            </value>
            <value>
                <fullName>AP01_SuiviStockSAV</fullName>
            </value>
            <value>
                <fullName>AP01_UpdatescheduledDate</fullName>
            </value>
            <value>
                <fullName>AP01_WorkOrder</fullName>
            </value>
            <value>
                <fullName>AP010_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP011_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP02_BandeUsine</fullName>
            </value>
            <value>
                <fullName>AP02_Commande</fullName>
            </value>
            <value>
                <fullName>AP02_Controle</fullName>
            </value>
            <value>
                <fullName>AP02_Convention</fullName>
            </value>
            <value>
                <fullName>AP02_Equipement</fullName>
            </value>
            <value>
                <fullName>AP02_EquipementDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP02_Foyer</fullName>
            </value>
            <value>
                <fullName>AP02_FoyerPaneliste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_validation_rules__c.field-meta.xml
<CustomField>
    <fullName>Bypass_validation_rules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass validation rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchRDD016_FidelisationChampOblTest.cls
/*
* @author: Mikael Chaaya
* @date: 31/05/2023
* @TestedClass: BatchRDD016_FidelisationChampObligatoire
* @Coverage: 96%
* Note : This Batch and test Class should be run before setting the Fidelisation__c.Composition_du_foyer__c and Fidelisation__c.Individu_paneliste__c to required fields and should be used only to correct 
*        previously created fidelisations that had Fidelisation__c.Composition_du_foyer__c=null AND/OR Fidelisation__c.Individu_paneliste__c=null
*/
@isTest
public class BatchRDD016_FidelisationChampOblTest {
@isTest
    Static void fidelisation(){

        User u = [SELECT id, Bypass_triggers__c, Bypass_flows__c FROM User WHERE isActive = true and Profile.name like '%dministra%' limit 1];
        u.Bypass_flows__c = true;
        u.Bypass_validation_rules__c=true;
        update u;
        
         System.runAs(u){
            Id recordTypeIdFoyerPanelisteAIP = Schema.SObjectType.Foyer_Paneliste__c.getRecordTypeInfosByName().get(Label.PAN_recordType_AIP).getRecordTypeId();
            Id recordTypeIdFoyerPanelisteMMATPaME = Schema.SObjectType.Foyer_Paneliste__c.getRecordTypeInfosByName().get(Label.PAN_recordType_mediamatpame).getRecordTypeId();
            Id recordTypeIdFidelisationCredit = Schema.SObjectType.Fidelisation__c.getRecordTypeInfosByName().get(Label.FID_Type_d_enregistrement_Credit).getRecordTypeId();


            List<Account> foyerList = new List<Account>();
            Account foyer1 = Test_Utils.createFoyer();
            foyer1.Name = 'Foyer 1';
            foyer1.Numero_de_portable__c = '0611111121';
            foyerList.add(foyer1);

            Account foyer2 = Test_Utils.createFoyer();
            foyer2.Name = 'Foyer AIP';
            foyer2.Numero_de_portable__c = '0611145121';
            foyerList.add(foyer2);
            
            
            List<Referentiel_Panel__c> listReferentielPanelToInsert = new List<Referentiel_Panel__c>();
            Referentiel_Panel__c refPanelPaME = new Referentiel_Panel__c();
            refPanelPaME.Name = Label.RFP_Nom_PaME;
            refPanelPaME.Type_de_panel__c = Label.RFP_TypePanel_PaME;
            listReferentielPanelToInsert.add(refPanelPaME);

            Referentiel_Panel__c refPanAIP = new Referentiel_Panel__c();
            refPanAIP.Name = 'AIP';
            refPanAIP.Type_de_panel__c = Label.RFP_TypePanel_AIP;
            listReferentielPanelToInsert.add(refPanAIP);
            
            insert listReferentielPanelToInsert;
            
            insert foyerList;
            
            List<Foyer_Paneliste__c> foyerPanelisteList = new List<Foyer_Paneliste__c>();        
            Foyer_Paneliste__c foyerPaneliste2 = new Foyer_Paneliste__c();
            foyerPaneliste2.RecordTypeId = recordTypeIdFoyerPanelisteMMATPaME;
            foyerPaneliste2.Name = 'Foyer Paneliste 2';
            foyerPaneliste2.Foyer__c = foyer1.Id;
            foyerPaneliste2.Referentiel_Panel__c = refPanelPaME.Id;
            foyerPanelisteList.add(foyerPaneliste2);

            Foyer_paneliste__c foyerPaneliste1 = Test_Utils.createFoyerPaneliste();
            foyerPaneliste1.RecordTypeId = recordTypeIdFoyerPanelisteAIP;
            foyerPaneliste1.Foyer__c = foyer2.Id;
            foyerPaneliste1.Referentiel_Panel__c = refPanAIP.Id;
            foyerPanelisteList.add(foyerPaneliste1);

            
            insert foyerPanelisteList;
            
            list<Contact> listMembreFoyerToInsert = new list<Contact>();
            Contact Cont = Test_Utils.createMembreFoyer(foyer1.id); 
            Cont.Lien_parente__c = 'Conjoint';
            Cont.Activite_actuelle__c = 'Congé maternité';
            Cont.CSP42__c = '132';
            Cont.CON_ExtId_SIPanel__c = '122223456';
            Cont.AccountId=foyer1.id;
            listMembreFoyerToInsert.add(Cont);

            Contact Cont2 = Test_Utils.createMembreFoyer(foyer2.id); 
            Cont2.Lien_parente__c = 'Conjoint';
            Cont2.Activite_actuelle__c = 'Congé maternité';
            Cont2.CSP42__c = '137';
            Cont2.CON_ExtId_SIPanel__c = '122783456';
            Cont2.AccountId=foyer2.id;
            listMembreFoyerToInsert.add(Cont2);
            
            insert listMembreFoyerToInsert; 
            
            foyer1.Personne_de_reference__c = cont.Id;
            foyer1.contact_principal__c = cont.Id;

            foyer2.Personne_de_reference__c = cont2.Id;
            foyer2.contact_principal__c = cont2.Id;
            update foyer1;
            update foyer2;
            
            List<Individu_paneliste__c> individuPanelisteToInsert = new List<Individu_paneliste__c>();
            Individu_paneliste__c indPan = new Individu_Paneliste__c();
            indPan.Foyer_paneliste__c = foyerPaneliste2.Id;
            indPan.Composition_du_foyer__c = Cont.Id;
            indPan.Lettre__c = 'D';
            indPan.Date_de_chute_de_l_individu__c=null;
            individuPanelisteToInsert.add(indPan);

            Individu_paneliste__c indPan2 = new Individu_Paneliste__c();
            indPan2.Foyer_paneliste__c = foyerPaneliste1.Id;
            indPan2.Composition_du_foyer__c = Cont2.Id;
            indPan2.Lettre__c = 'D';
            indPan2.Date_de_chute_de_l_individu__c=null;
            individuPanelisteToInsert.add(indPan2);
            
            insert individuPanelisteToInsert;
            
            List<Fidelisation__c> FidelisationToInsert = new List<Fidelisation__c>();
            Fidelisation__c fd = new Fidelisation__c();
            fd.Foyer__c = foyer1.id;
            fd.Foyer_Paneliste__c= foyerPaneliste2.id;
            fd.recordTypeId = recordTypeIdFidelisationCredit;
            fd.Composition_du_foyer__c=Cont.Id;
            fd.Individu_paneliste__c=indPan.Id;
            fd.Motif_de_credit__c='1';
            fd.Type_de_mouvement__c = '6';
            FidelisationToInsert.add(fd);
             
            Fidelisation__c fd1 = new Fidelisation__c();
            fd1.Foyer__c = foyer1.id;
             
            fd1.Foyer_Paneliste__c= foyerPaneliste2.id;
             fd1.Individu_paneliste__c=indPan.Id;
            fd1.recordTypeId = recordTypeIdFidelisationCredit;
            fd1.Motif_de_credit__c='1';
            fd1.Type_de_mouvement__c = '6';
            FidelisationToInsert.add(fd1);
             
             Fidelisation__c fd2 = new Fidelisation__c();
            fd2.Foyer__c = foyer1.id;
            fd2.Foyer_Paneliste__c= foyerPaneliste2.id;
            fd2.recordTypeId = recordTypeIdFidelisationCredit;
            fd2.Composition_du_foyer__c=Cont.Id;
            fd2.Motif_de_credit__c='1';
            fd2.Type_de_mouvement__c = '6';
            FidelisationToInsert.add(fd2);
             
            Fidelisation__c fd3 = new Fidelisation__c();
            fd3.Foyer__c = foyer1.id;
            fd3.Foyer_Paneliste__c= foyerPaneliste2.id;
            fd3.recordTypeId = recordTypeIdFidelisationCredit;
            
            fd3.Motif_de_credit__c='1';
            fd3.Type_de_mouvement__c = '6';
            FidelisationToInsert.add(fd3);

            Fidelisation__c fd4 = new Fidelisation__c();
            fd4.Foyer__c = foyer2.id;
            fd4.Foyer_Paneliste__c= foyerPaneliste1.id;
            fd4.recordTypeId = recordTypeIdFidelisationCredit;
            fd4.Motif_de_credit__c='1';
            fd4.Type_de_mouvement__c = '6';
            FidelisationToInsert.add(fd4);
             
            insert FidelisationToInsert;
            
             List<Fidelisation__c> fidBeforeBatchList = [SELECT Id, Foyer_Paneliste__c 
                                                  FROM Fidelisation__c
                                                  WHERE (Composition_du_foyer__c=null
                                                        AND 
                                                        Individu_paneliste__c<>null
                                                        )
                                                    OR(Composition_du_foyer__c<>null
                                                        AND 
                                                        Individu_paneliste__c=null
                                                      )
                                                    OR(Composition_du_foyer__c=null
                                                      AND Individu_paneliste__c=null
                                                       AND Foyer__r.Personne_de_reference__c<> null
                                                      )
                                                 ];
            System.debug(fidBeforeBatchList);
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(cont.id));
            Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(cont2.id));
            BatchRDD016_FidelisationChampObligatoire btch = new BatchRDD016_FidelisationChampObligatoire();
            database.executeBatch(btch);
            Test.stopTest();
            
            List<Fidelisation__c> fidBatchList = [SELECT Id, Foyer_Paneliste__c 
                                                  FROM Fidelisation__c
                                                  WHERE (Composition_du_foyer__c=null
                                                        AND 
                                                        Individu_paneliste__c<>null
                                                        )
                                                    OR(Composition_du_foyer__c<>null
                                                        AND 
                                                        Individu_paneliste__c=null
                                                      )
                                                    OR(Composition_du_foyer__c=null
                                                      AND Individu_paneliste__c=null
                                                       AND Foyer__r.Personne_de_reference__c<> null
                                                      )
                                                 ];
            
            System.assertEquals(0, fidBatchList.size());
         }
    }

}