force-app/main/default/objects/Account/fields/Numero_de_telephone_fixe__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_telephone_fixe__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Numéro de téléphone fixe</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Statut_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Statut_du_foyer__c</fullName>
    <label>Statut du foyer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Recruté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Installé</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Equipé</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Integré</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Désinstallé</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Chute définitive</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chute temporaire</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Type_de_foyer__c.field-meta.xml
<CustomField>
    <fullName>Type_de_foyer__c</fullName>
    <label>Type de foyer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Médiamat</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Single Source</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>AIP</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Multi panel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Controle__c/Controle__c.object-meta.xml
<CustomObject>
    <label>Contrôle</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du contrôle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrôles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Controle__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Rep_ou_non_rep__c.field-meta.xml
<CustomField>
    <fullName>Rep_ou_non_rep__c</fullName>
    <label>Rep ou non rep</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Répondant</fullName>
            </value>
            <value>
                <fullName>Non répondant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Sous_type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Sous_type_de_controle__c</fullName>
    <label>Sous type de contrôle</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_de_controle__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>13</fullName>
                <label>Anomalie des données en base panel</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Anomalie lors du traitement des données d&apos;audience</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Audience individuelle &gt; 9h</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Individu sans activité Web cohérente</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>Individus sans audience depuis 28 jours ou plus</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Foyers sans audience depuis 6 jours ou plus</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Foyer avec audience sans abo</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Foyer avec abo C+ sans audience</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Foyer sans activité routeur</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Foyer sans activité Web cohérente</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Non envoyé au Médiamat</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Rejeté Médiamat</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>TV On &gt; 12h</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Autres usages</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Autre cause technique</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Foyer vacancier longue durée</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Audimètre non connecté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Audience individuelle &gt;7h</label>
            </value>
            <value>
                <fullName>-1</fullName>
                <label>Inconnu</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Foyers sans audience depuis 4 jours</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Foyers sans audience depuis plus de 4 jours</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Individus sans audience depuis 4 jours</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Individus sans audience depuis plus de 4 jours</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Statut audim. sans date</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Foyers sans audience depuis plus de 90 jours</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Foyers sans audience depuis plus de 180 jours</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Absence mouvement</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Absence collecte</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Pager OFF</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Pager éteint trop longtemps</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Type_de_controle__c</fullName>
    <label>Type de contrôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <label>Présence</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Autres usages</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Connexion</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Participation</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Réception/abonnement</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Non Répondant</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Participation Web</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Foyer vacancier longue durée</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Foyer vacancier</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Contrôle Beacon</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Installation SetMeter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Priorites_de_controles__c/Priorites_de_controles__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Priorités de contrôles</label>
</CustomObject>

force-app/main/default/objects/Priorites_de_controles__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Case Origin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Priorites_de_controles__c/fields/Priorite__c.field-meta.xml
<CustomField>
    <fullName>Priorite__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Priorité</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Priorites_de_controles__c/fields/Rep_ou_non_rep__c.field-meta.xml
<CustomField>
    <fullName>Rep_ou_non_rep__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Rep ou non rep</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Priorites_de_controles__c/fields/Sous_type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Sous_type_de_controle__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sous type de contrôle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Priorites_de_controles__c/fields/Type_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Type_de_controle__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type de contrôle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Priorites_de_controles__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type de panel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ControleTriggerHandler_Test.cls
/*
* @author: Elio Bou Habib
* @date: 29/03/2021
* @Description Controle Trigger handler test class
* @Tested Class: ControleTriggerHandler
* @Coverage: 100 %
* History
* <Date of modification>   <Author>    <Description of modification>
*/
@isTest
public class ControleTriggerHandler_Test 
{
    
    /** 
	* @author Elio Bou Habib
	* @date 29/03/2021
	* @description tests the after insert trigger of the controle trigger handler
	*/
    @isTest
    public static void testAfterInsert()
    {
        Priorites_de_controles__c pdc12 = new Priorites_de_controles__c();
        pdc12.Name                      = 'Priorité 12';
        pdc12.Origin__c                 = 'Contrôle';
        pdc12.Type_de_controle__c       = Label.CTRL_Type_Participation;
        pdc12.Sous_type_de_controle__c  = '8';
        pdc12.Type_de_panel__c          = 'MEDIAMAT (MMAT)';
        pdc12.Rep_ou_non_rep__c         = 'Non répondant';
        pdc12.Priorite__c               = '12';
        insert pdc12;
        
        Priorites_de_controles__c pdc22 = new Priorites_de_controles__c();
        pdc22.Name                      = 'Priorité 22';
        pdc22.Origin__c                 = 'Contrôle';
        pdc22.Type_de_controle__c       = Label.CTRL_Type_ParticipationWeb;
        pdc22.Type_de_panel__c          = 'PAME';
        pdc22.Rep_ou_non_rep__c         = 'Répondant';
        pdc22.Priorite__c               = '22';
        insert pdc22;
        
        try
        {
            ControleTriggerHandler.updateTechPriority();
        }
        catch(Exception ex) {}
        
        Account account1                     = Test_Utils.createFoyer();
        account1.Statut_du_foyer__c          = 'Installé';
        account1.Type_de_foyer__c            = Label.ACC_Type_de_panel_Mediamat;
        account1.Numero_de_telephone_fixe__c = '0000000000';
        insert account1;
        
        Id recordTypeIdPanelMediamatPame =Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_mediamatpame).getRecordTypeId();
           
         Referentiel_Panel__c refPan = new Referentiel_Panel__c();
         refPan.Name	= Label.RFP_TypePanel_PaME;
         refPan.Type_de_panel__c =  Label.REF_PANEL_TypePan_PAME;
         insert refPan;
           
         Foyer_paneliste__c foyerPan = new Foyer_paneliste__c(RecordTypeId = recordTypeIdPanelMediamatPame,Name='testAip',Foyer__c=account1.id ,Statut_Foyer_paneliste__c=Label.PAN_Statut_panel, Referentiel_Panel__c = refPan.Id);
         insert foyerPan;
        
        Controle__c controle1              = Test_Utils.createControle(account1.Id, null, null, null, System.today());
        controle1.Type_de_controle__c      = Label.CTRL_Type_Participation;
        controle1.Sous_type_de_controle__c = '8';
        controle1.Rep_ou_non_rep__c        = 'Non répondant';
        controle1.Foyer_Paneliste__c = foyerPan.Id;
        insert controle1;
        system.debug('eee'+controle1.Tech_Priority__c);
        controle1 = refreshControle(controle1.Id);
       
        
        Account account2                     = Test_Utils.createFoyer();
        account2.Statut_du_foyer__c          = 'Installé';
        account2.Type_de_foyer__c            = Label.ACC_Type_de_panel_Pame;
        account2.Numero_de_telephone_fixe__c = '0000000000';
        insert account2;
        
        Controle__c controle2              = Test_Utils.createControle(account1.Id, null, null, null, System.today());
        controle2.Foyer__c                 = account2.Id;
        controle2.Type_de_controle__c      = Label.CTRL_Type_ParticipationWeb;
        controle2.Sous_type_de_controle__c = '8';
        controle2.Rep_ou_non_rep__c        = 'Répondant';
        controle2.Foyer_Paneliste__c = foyerPan.Id;
        insert controle2;
        controle2 = refreshControle(controle2.Id);
        system.debug(controle2.Tech_Priority__c);
       
        
        delete controle2;
        undelete controle2;
    }
    
    /** 
	* @author Elio Bou Habib
	* @date 29/03/2021
	* @description refreshes controles's fields
	*/
    public static Controle__c refreshControle(Id controleId)
    {
        Controle__c controle = [SELECT Id, Foyer__c, Type_de_controle__c, Sous_type_de_controle__c, 
                                Rep_ou_non_rep__c, Tech_Priority__c, Type_de_panel__c, Foyer__r.Type_de_foyer__c
                                FROM Controle__c
                                WHERE Id = :controleId];
        return controle;
    }
}