force-app/main/default/objects/Account/fields/Numero_de_portable__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_portable__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Numéro de téléphone portable</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Personne_de_reference__c.field-meta.xml
<CustomField>
    <fullName>Personne_de_reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personne de référence</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Cet individu n&apos;existe pas ou n&apos;est pas rattaché à ce foyer.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Foyers</relationshipLabel>
    <relationshipName>Foyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Statut_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Statut_du_foyer__c</fullName>
    <label>Statut du foyer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Recruté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Installé</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Equipé</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Integré</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Désinstallé</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Chute définitive</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chute temporaire</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Territoire_de_service__c.field-meta.xml
<CustomField>
    <fullName>Territoire_de_service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territoire de service</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Foyers</relationshipLabel>
    <relationshipName>Foyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type_de_foyer__c.field-meta.xml
<CustomField>
    <fullName>Type_de_foyer__c</fullName>
    <label>Type de foyer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Médiamat</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Single Source</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>AIP</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Multi panel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Code_Postal_Commune__c/Code_Postal_Commune__c.object-meta.xml
<CustomObject>
    <label>Code Postal Commune</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom Commune</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Code Postal Commune</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Code_Postal_Commune__c/fields/Code_postal__c.field-meta.xml
<CustomField>
    <fullName>Code_postal__c</fullName>
    <label>Code postal</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Statut_du_foyer__c/Statut_du_foyer__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Ensemble clé-valeur pour le champ Statut du foyer de l&apos;objet Foyer</description>
    <label>Statut du foyer</label>
</CustomObject>

force-app/main/default/objects/Territoire_de_Service__c/Territoire_de_Service__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Territoire de Service</label>
</CustomObject>

force-app/main/default/objects/Territoire_de_Service__c/fields/Nom_du_territoire__c.field-meta.xml
<CustomField>
    <fullName>Nom_du_territoire__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Nom du territoire</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AP01_Foyer_Test.cls
/*
* @author: Joyce Saidy
* @date: 02/09/2020
* @ Description Class that test AP01_Foyer . Associated Trigger : FoyerAfterInsert ,FoyerBeforeInsert
* History
* <Date of modification>   <Author>    <Description of modification>
*/
@isTest 
public class AP01_Foyer_Test {
    public static testMethod void AP01_FoyerTest(){ 
        
        OperatingHours oh = new OperatingHours();
        oh.Name = 'OperatingHour1';
        insert oh; 
        
        ServiceTerritory ts = new ServiceTerritory();
        ts.name='Est';
        ts.OperatingHoursId=oh.id;
        insert ts;
        ServiceTerritory ts2 = new ServiceTerritory();
        ts2.name='Ouest';
        ts2.OperatingHoursId=oh.id;
        insert ts2;
        //Création custom setting
        Territoire_de_Service__c CustomSetting= new Territoire_de_Service__c();
        CustomSetting.name = '01';
        CustomSetting.Nom_du_territoire__c='Est';
        Territoire_de_Service__c CustomSetting2= new Territoire_de_Service__c();
        CustomSetting2.name = '12';
        CustomSetting2.Nom_du_territoire__c='Ouest';
        insert CustomSetting2;
        
        //Création foyer
        Account acc = new Account();
        acc.name='Dupond';
        acc.ShippingPostalCode='01234';
        acc.Statut_du_foyer__c=Label.ACC_Statut_du_foyer_Recrute;
        acc.Type_de_foyer__c = Label.ACC_Type_de_panel_Mediamat;
        acc.Numero_de_portable__c = '0611111121';

        //creation Code_Postal_Commune__c
        Code_Postal_Commune__c cp=new Code_Postal_Commune__c();
        cp.Name='VELIZY-VILLACOUBLAY';
        cp.Code_postal__c=78140;

        insert cp;

        test.startTest(); 
        insert acc; 
        Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(acc.id)); 
        Account acc1=[Select Id , ShippingPostalCode, ShippingCity,Personne_de_reference__c from Account Where Id=:acc.Id ];

        AP01_Foyer.NouvelleReq(new Account[]{acc1});
       // System.debug(acc1);
        acc1.ShippingPostalCode='78140';
        acc1.ShippingCity='VELIZY-VILLACOUBLAY';
       // System.debug(acc1);
        update acc1;
        test.stopTest();
    }
}