force-app/main/default/objects/Account/fields/Personne_de_reference__c.field-meta.xml
<CustomField>
    <fullName>Personne_de_reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personne de référence</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Cet individu n&apos;existe pas ou n&apos;est pas rattaché à ce foyer.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Foyers</relationshipLabel>
    <relationshipName>Foyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type_de_foyer__c.field-meta.xml
<CustomField>
    <fullName>Type_de_foyer__c</fullName>
    <label>Type de foyer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Médiamat</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Single Source</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>AIP</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Multi panel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Lien_parente__c.field-meta.xml
<CustomField>
    <fullName>Lien_parente__c</fullName>
    <label>Lien parenté</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Chef de famille</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Conjoint</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Enfant</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Ascendant</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Autre</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Personne_de_Reference__c.field-meta.xml
<CustomField>
    <fullName>Personne_de_Reference__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Personne de Référence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchRDD02_Foyer_Test.cls
/*
* @Auteur Elia KARAM
* @date: 02/03/2022
* @Classe: BatchRDD02_Foyer
* * History
* <Date of modification>   		<Author>    		<Description of modification>
*/
@isTest
public class BatchRDD02_Foyer_Test {
    static testMethod void testMethod1() {
        List<Account> lstAccount= new List<Account>();
        
        Account foyer = new Account();
        foyer.Name ='Name1234';
        foyer.ShippingStreet='rue stalingrad';
        lstAccount.add(foyer);
        
        insert lstAccount;
        Account foyer1 = new Account();
        foyer1.Name ='Name12345';
        foyer1.ShippingStreet='rue stalingrad1';
        foyer1.Type_de_foyer__c = Label.ACC_Type_de_panel_AIP;
        lstAccount.add(foyer1);
        
        insert foyer1;
        
        List<Contact> contactToInsert = new List<Contact>();
        Contact compoFoyer = Test_Utils.createMembreFoyer(foyer.id); 
        compoFoyer.Lien_parente__c = 'Conjoint';
        compoFoyer.LastName = 'DUPONTT';
        contactToInsert.add(compoFoyer);
        
        
        Contact compoFoyer1 = Test_Utils.createMembreFoyer(foyer.id); 
        compoFoyer1.Lien_parente__c = 'Conjoint';
        compoFoyer1.LastName = 'DUPONT';
        contactToInsert.add(compoFoyer1);
        
        insert contactToInsert;
        
        foyer.Personne_de_reference__c = compoFoyer.Id;
        
        update foyer;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(compoFoyer.id));
        BatchRDD02_Foyer obj = new BatchRDD02_Foyer();
        DataBase.executeBatch(obj); 
        
        Test.stopTest();
    }
}