force-app/main/default/objects/Account/fields/Personne_de_reference__c.field-meta.xml
<CustomField>
    <fullName>Personne_de_reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personne de référence</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Cet individu n&apos;existe pas ou n&apos;est pas rattaché à ce foyer.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Foyers</relationshipLabel>
    <relationshipName>Foyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Solde_de_points__c.field-meta.xml
<CustomField>
    <fullName>Solde_de_points__c</fullName>
    <formula>Nombre_de_points_cumules__c - Nombre_de_points_debites__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Solde de points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF(
				NOT(ISBLANK(Birthdate)),
				IF(
								DATE(2000, MONTH(Birthdate), DAY(Birthdate)) &lt;= DATE(2000, MONTH(TODAY()), DAY(TODAY())),
        YEAR (Today()) - YEAR ( Birthdate ),
        YEAR (Today()) - YEAR ( Birthdate ) -1
				),
				null
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Âge</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Canal_privilegie__c.field-meta.xml
<CustomField>
    <fullName>Canal_privilegie__c</fullName>
    <label>Canal privilégié</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Fixe du foyer</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Personne_de_Reference__c.field-meta.xml
<CustomField>
    <fullName>Personne_de_Reference__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Personne de Référence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Solde_de_points__c.field-meta.xml
<CustomField>
    <fullName>Solde_de_points__c</fullName>
    <formula>Nombre_de_points_cr_dit_s__c - Nombre_de_points_debites__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Solde de points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Solde_de_points_fid__c.field-meta.xml
<CustomField>
    <fullName>Solde_de_points_fid__c</fullName>
    <formula>Nombre_de_points_credites_fid__c - Nombre_de_points_debites_fid__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Solde de points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Acces_Replanification__c.field-meta.xml
<CustomField>
    <fullName>Acces_Replanification__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Case à cocher si le technicien a le droit de replanifier ses rendez-vous</inlineHelpText>
    <label>Accès Replanification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Autoriser_Intervention__c.field-meta.xml
<CustomField>
    <fullName>Autoriser_Intervention__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Autoriser Intervention</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Numero_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Numero_paneliste__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Numero paneliste</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Provisioning_IAM__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_IAM__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Provisioning IAM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Solde_de_point__c.field-meta.xml
<CustomField>
    <fullName>Solde_de_point__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Solde de point</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Tech_CanalPrivilegie__c.field-meta.xml
<CustomField>
    <fullName>Tech_CanalPrivilegie__c</fullName>
    <formula>TEXT(Contact.Canal_privilegie__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tech_CanalPrivilegie</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/getUserInformations.cls
public with sharing class getUserInformations {
    @AuraEnabled
    public static onLoadWrapper getInformations() {
        onLoadWrapper onLoadWrapper = new onLoadWrapper();
        List<ContactFormulaire.wrapperType> ChannelPrivilegeList = ContactFormulaire.getPicklistValues(Contact.Canal_privilegie__c);
        onLoadWrapper.ChannelPrivilegeList = ChannelPrivilegeList;
        
        User user =  [SELECT Id, Name, Email, PostalCode, Numero_paneliste__c, Solde_de_point__c, CompanyName, Title, MobilePhone, Acces_Replanification__c,
                      Contact.Account.ShippingAddress, Autoriser_Intervention__c, Provisioning_IAM__c, Tech_CanalPrivilegie__c,ContactId,
                      Contact.Birthdate, Contact.Account.Personne_de_reference__r.Name, Contact.Age__c, Contact.Email, Contact.MobilePhone
                      FROM User
                      WHERE Id=:UserInfo.getUserId()];
        
        
        onLoadWrapper.utilisateur = user;
        System.debug('user.Contact.Age__c ' + user.Contact.Age__c);
        if(user.Contact.Age__c < 18){
           onLoadWrapper.personneDeReference = user.Contact.Account.Personne_de_reference__r.Name; 
        }
        List<Individu_Paneliste__c> individuPan = [SELECT Id, Composition_du_foyer__r.Solde_de_points__c, Foyer_paneliste__r.Name, Foyer_paneliste__r.Solde_de_points_fid__c
                                                   FROM Individu_Paneliste__c 
                                                   WHERE Composition_du_foyer__c = :user.ContactId];
        if(individuPan.size() > 0){
            onLoadWrapper.utilisateur.Solde_de_point__c = String.valueOf(individuPan[0].Foyer_paneliste__r.Solde_de_points_fid__c);
            onLoadWrapper.utilisateur.Numero_paneliste__c = individuPan[0].Foyer_paneliste__r.Name;
            
        }
        return onLoadWrapper;
    }
    
    public static Integer FindAge(Date birthDate)
    {
        Integer days = birthDate.daysBetween(Date.Today());
        Integer age = Integer.valueOf(days/365);
        return age;
    }
    
    @AuraEnabled
    public static String updateUserInformations(User userToUpdate) {
        String message;
        User currentUser = [SELECT Id, ContactId
                            FROM User 
                            WHERE Id=:UserInfo.getUserId()];
        
        currentUser.Email = userToUpdate.Email;
        currentUser.MobilePhone = userToUpdate.MobilePhone;
        System.debug('bastien updateUserInformations currentUser : ' + currentUser);
        try {
            update currentUser;
            message = 'User Updated';
            
            if(String.isNotBlank(currentUser.ContactId)){
                Contact contactToUpdate = [SELECT Id, MobilePhone, Email
                                           FROM Contact 
                                           WHERE Id = :currentUser.ContactId ];
                contactToUpdate.Canal_privilegie__c = userToUpdate.Tech_CanalPrivilegie__c;
                contactToUpdate.MobilePhone = userToUpdate.MobilePhone;
                contactToUpdate.Email = userToUpdate.Email;
                try {
                    update contactToUpdate;
                    message += ', Contact Updated';
                            System.debug('bastien updateUserInformations currentUser : ' + currentUser);

                } catch(DmlException e) {
                    System.debug(', The following exception has occurred on Contact Update: ' + e.getMessage());
                    message += ', The following exception has occurred on Contact Update: ' + e.getMessage();
                }
            }
            
        } catch(DmlException e) {
            System.debug('The following exception has occurred on User Update: ' + e.getMessage());
            message = 'The following exception has occurred on User Update: ' + e.getMessage();
        }
        
        System.debug('message ' + message);
        return message;
    }
    
    /*WRAPPERS*/
    public class onLoadWrapper {
        public onLoadWrapper(){
            this.utilisateur = new User();
            this.ChannelPrivilegeList = new List<ContactFormulaire.wrapperType>();
            this.personneDeReference = '';
        }
        @AuraEnabled
        public User utilisateur;
        @AuraEnabled
        public List<ContactFormulaire.wrapperType> ChannelPrivilegeList;
        @AuraEnabled
        public String personneDeReference;
    }
}