force-app/main/default/objects/Account/fields/Solde_de_points__c.field-meta.xml
<CustomField>
    <fullName>Solde_de_points__c</fullName>
    <formula>Nombre_de_points_cumules__c - Nombre_de_points_debites__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Solde de points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Solde_de_points__c.field-meta.xml
<CustomField>
    <fullName>Solde_de_points__c</fullName>
    <formula>Nombre_de_points_cr_dit_s__c - Nombre_de_points_debites__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Solde de points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/PaME.recordType-meta.xml
<RecordType>
    <fullName>PaME</fullName>
    <active>true</active>
    <label>PaME</label>
</RecordType>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer_Paneliste_ExtId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>Foyer_Paneliste_ExtId_SIPanel__c</fullName>
    <description>&quot;(UID) c&apos;est l&apos;id unique generé par SIPANEL du foyer panéliste 
Ce champ sert a faire l&apos;Upsert du foyer panéliste&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Foyer_Paneliste_ExtId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Solde_de_points_fid__c.field-meta.xml
<CustomField>
    <fullName>Solde_de_points_fid__c</fullName>
    <formula>Nombre_de_points_credites_fid__c - Nombre_de_points_debites_fid__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Solde de points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/recordTypes/AIP.recordType-meta.xml
<RecordType>
    <fullName>AIP</fullName>
    <active>true</active>
    <label>AIP</label>
</RecordType>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/WelcomeEmailController.cls
public class WelcomeEmailController 
{
    public String contactId{get;set;}
    
    public UserInfo getUserInfo()
    {
        UserInfo userInfoWrapper = new UserInfo();
        userInfoWrapper.mailText = label.EXP_WelcomeMail;
        String panelType = '';
        System.debug('contactId ' + contactId);
        List<Individu_Paneliste__c> individuPaneliste = [SELECT Id, Composition_du_foyer__c, Composition_du_foyer__r.Name, 
                                                         Composition_du_foyer__r.Solde_de_points__c, Foyer_paneliste__r.Name, Foyer_paneliste__c, Foyer_paneliste__r.Referentiel_Panel__r.Name,
                                                         Foyer_paneliste__r.Foyer_Paneliste_ExtId_SIPanel__c
                                                         //Composition_du_foyer__r.Account.Sous_Statut__c
                                                         FROM Individu_Paneliste__c
                                                         WHERE Composition_du_foyer__c = :contactId];
        System.debug('individuPaneliste ' + individuPaneliste);
        
        List<Foyer_paneliste__c> soldeDePoint = new List<Foyer_paneliste__c>();
        if(individuPaneliste.size() > 0){
            soldeDePoint = [
                SELECT Solde_de_points_fid__c
                FROM Foyer_paneliste__c
                WHERE Id =: individuPaneliste[0].Foyer_paneliste__c
            ];
            
            if(individuPaneliste[0].Foyer_paneliste__r.Referentiel_Panel__r.Name == 'AIP'){
                panelType = '1';
            } else if(individuPaneliste[0].Foyer_paneliste__r.Referentiel_Panel__r.Name == 'MMT'){
                panelType = '2';
            } else if(individuPaneliste[0].Foyer_paneliste__r.Referentiel_Panel__r.Name == 'PaME'){
                panelType = '3';
            }
        }
        
        if(individuPaneliste.size() > 0 && soldeDePoint.size() > 0){
            userInfoWrapper.SoldeDePoints = String.valueOf(soldeDePoint[0].Solde_de_points_fid__c);
            userInfoWrapper.NumeroPanel = individuPaneliste[0].Foyer_paneliste__r.Name;
            userInfoWrapper.linkQuest = label.EXP_WelcomeMailLink + 'ID_PANELISTE=' + individuPaneliste[0].Foyer_paneliste__r.Foyer_Paneliste_ExtId_SIPanel__c + 'tAud&ID_PANEL=' + panelType;
        }
        
        
        
        /*if(individuPaneliste.size() > 0
&& (individuPaneliste[0].Composition_du_foyer__r.Account.Sous_Statut__c == label.ACC_SousStatut_EnCoursDeCreation 
|| individuPaneliste[0].Composition_du_foyer__r.Account.Sous_Statut__c == label.ACC_SousStatut_DefinitionMembre)){
userInfoWrapper.mailText = label.EXP_WelcomeMailV2;
}*/
        
        
        System.debug('userInfoWrapper ' + userInfoWrapper);
        return userInfoWrapper;
    }
    
    public class UserInfo{
        public String NumeroPanel{get;set;}
        public String SoldeDePoints{get;set;}
        public String mailText{get;set;}
        public String linkQuest{get;set;}
    }
}