force-app/main/default/objects/Account/fields/Statut_audimetrique__c.field-meta.xml
<CustomField>
    <fullName>Statut_audimetrique__c</fullName>
    <label>Statut audimétrique</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Présent</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>En vacances</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Absent</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Non répondant</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Statut_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Statut_du_foyer__c</fullName>
    <label>Statut du foyer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Recruté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Installé</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Equipé</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Integré</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Désinstallé</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Chute définitive</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chute temporaire</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Type_de_foyer__c.field-meta.xml
<CustomField>
    <fullName>Type_de_foyer__c</fullName>
    <label>Type de foyer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Médiamat</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Single Source</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>AIP</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Multi panel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Controle__c/Controle__c.object-meta.xml
<CustomObject>
    <label>Contrôle</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du contrôle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrôles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Controle__c/fields/Date_de_controle__c.field-meta.xml
<CustomField>
    <fullName>Date_de_controle__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de contrôle</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actif</fullName>
                <default>true</default>
                <label>Actif</label>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>Pré-codé</fullName>
            </value>
            <value>
                <fullName>Traité</fullName>
            </value>
            <value>
                <fullName>Abandonné</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Statut_du_foyer__c/Statut_du_foyer__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Ensemble clé-valeur pour le champ Statut du foyer de l&apos;objet Foyer</description>
    <label>Statut du foyer</label>
</CustomObject>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public with sharing class TestDataFactory{
    
     public static List<Controle__c> createControles( Integer numCon){
                    
     List<Controle__c> controles= new List<Controle__c>();
     List<Account> foyers= creerFoyers(numCon);
        for(Account a : foyers){
   
           controles.add(new Controle__c(
                                    Name = 'Test Controle',
             						Statut__c='Actif',
                                    Foyer__c =a.Id,
                                    Date_de_controle__c = Date.today()));
                                    
            } 
            	insert controles;
                      
           return controles;
     }
    

         public static List<Account> creerFoyers(Integer nbfoyers){

        List<Account> foyers = new List<Account>();

        for (Integer nbfoyercrees= 0; nbfoyercrees < nbfoyers; nbfoyercrees++) {
            foyers.add(new Account(Name = 'Foyer ' + nbfoyercrees, 	Type_de_foyer__c='Test type'+ nbfoyercrees, Statut_du_foyer__c='test '+ nbfoyercrees,
                                   Statut_audimetrique__c= 'Test statut'+ nbfoyercrees));
        }

        insert foyers;

        return [SELECT Name FROM Account WHERE Name LIKE 'Foyer _'];
          
            
    }
    
    
     }