force-app/main/default/objects/Account/fields/Statut_audimetrique__c.field-meta.xml
<CustomField>
    <fullName>Statut_audimetrique__c</fullName>
    <label>Statut audimétrique</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Présent</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>En vacances</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Absent</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Non répondant</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Audimetre__c.field-meta.xml
<CustomField>
    <fullName>Audimetre__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Audimètre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Date_de_premiere_detection__c.field-meta.xml
<CustomField>
    <fullName>Date_de_premiere_detection__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de première détection</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Équipements de mesure</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/J45__c.field-meta.xml
<CustomField>
    <fullName>J45__c</fullName>
    <label>J45</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Jour_de_traitement__c.field-meta.xml
<CustomField>
    <fullName>Jour_de_traitement__c</fullName>
    <formula>IF(DATEVALUE(CreatedDate) &gt;= DATE(2023,04,27), TODAY() - DATEVALUE(CreatedDate) + 1, TODAY() - DATEVALUE(CreatedDate) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Etape J</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sous_type__c.field-meta.xml
<CustomField>
    <fullName>Sous_type__c</fullName>
    <label>Sous-type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Absence collecte</fullName>
            </value>
            <value>
                <fullName>Absence mouvement</fullName>
            </value>
            <value>
                <fullName>Adaptateur casque</fullName>
            </value>
            <value>
                <fullName>Anomalie affichage</fullName>
            </value>
            <value>
                <fullName>Anomalie autre</fullName>
            </value>
            <value>
                <fullName>Anomalie batterie</fullName>
            </value>
            <value>
                <fullName>Anomalie carte Sim</fullName>
            </value>
            <value>
                <fullName>Anomalie des données en base panel</fullName>
            </value>
            <value>
                <fullName>Anomalie horloge</fullName>
            </value>
            <value>
                <fullName>Anomalie informations</fullName>
            </value>
            <value>
                <fullName>Anomalie lors du traitement des données d&apos;audience</fullName>
            </value>
            <value>
                <fullName>A quitte la mesure</fullName>
            </value>
            <value>
                <fullName>Audience individuelle &gt;7h</fullName>
            </value>
            <value>
                <fullName>Audience individuelle &gt; 7h</fullName>
                <isActive>false</isActive>
                <label>Audience individuelle &gt; 7h</label>
            </value>
            <value>
                <fullName>Audimètre</fullName>
            </value>
            <value>
                <fullName>Audimètre non connecté</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon batterie faible</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon inactif</fullName>
            </value>
            <value>
                <fullName>Au moins 1 beacon jamais détecté</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Autre cause technique</fullName>
            </value>
            <value>
                <fullName>Autre déplacement</fullName>
            </value>
            <value>
                <fullName>Autre déplacement hors zone de mesure</fullName>
            </value>
            <value>
                <fullName>Autres usages</fullName>
            </value>
            <value>
                <fullName>Avis</fullName>
            </value>
            <value>
                <fullName>Beacon</fullName>
            </value>
            <value>
                <fullName>Beacon (logement plus grand)</fullName>
            </value>
            <value>
                <fullName>Beacon(s) Réceptionné(s)</fullName>
            </value>
            <value>
                <fullName>Beacon (tv en plus)</fullName>
            </value>
            <value>
                <fullName>Beacon (vehicule supplémentaire)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Controle__c/Controle__c.object-meta.xml
<CustomObject>
    <label>Contrôle</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du contrôle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrôles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Controle__c/fields/Audimetre__c.field-meta.xml
<CustomField>
    <fullName>Audimetre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audimètre</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Controle__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Contrôles</relationshipLabel>
    <relationshipName>Controles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Statut_Audimetrique__c.field-meta.xml
<CustomField>
    <fullName>Statut_Audimetrique__c</fullName>
    <label>Statut Audimétrique</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Présent</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>En vacances</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Absent</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Non répondant</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Statut_Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Statut_Foyer_paneliste__c</fullName>
    <label>Statut Foyer Panéliste</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Foyer_equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Recruté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Installé</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Equipé</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Intégré</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Désinstallé</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chute temporaire</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Chute définitive</label>
            </value>
            <value>
                <fullName>Chute définitive et désinstallé</fullName>
                <isActive>false</isActive>
                <label>Chute définitive et désinstallé</label>
            </value>
            <value>
                <fullName>Désinstallé actif</fullName>
                <isActive>false</isActive>
                <label>Désinstallé actif</label>
            </value>
            <value>
                <fullName>Recruté en attente d&apos;installation</fullName>
                <isActive>false</isActive>
                <label>Recruté en attente d&apos;installation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/recordTypes/AIP.recordType-meta.xml
<RecordType>
    <fullName>AIP</fullName>
    <active>true</active>
    <label>AIP</label>
</RecordType>

force-app/main/default/objects/User/fields/Bypass_flows__c.field-meta.xml
<CustomField>
    <fullName>Bypass_flows__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass flows</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_triggers__c.field-meta.xml
<CustomField>
    <fullName>Bypass_triggers__c</fullName>
    <label>Bypass triggers</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AP01_BandeUsine</fullName>
            </value>
            <value>
                <fullName>AP01_Commande</fullName>
            </value>
            <value>
                <fullName>AP01_Conge</fullName>
            </value>
            <value>
                <fullName>AP01_Control</fullName>
                <isActive>false</isActive>
                <label>AP01_Control</label>
            </value>
            <value>
                <fullName>AP01_Controle</fullName>
            </value>
            <value>
                <fullName>AP01_Convention</fullName>
            </value>
            <value>
                <fullName>AP01_Equipement</fullName>
            </value>
            <value>
                <fullName>AP01_EquipementDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP01_Evenement</fullName>
            </value>
            <value>
                <fullName>AP01_Fidelisation</fullName>
            </value>
            <value>
                <fullName>AP01_Foyer</fullName>
            </value>
            <value>
                <fullName>AP01_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP01_IndividuPaneliste</fullName>
            </value>
            <value>
                <fullName>AP01_LienMeter</fullName>
            </value>
            <value>
                <fullName>AP01_MembreDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP01_Requete</fullName>
            </value>
            <value>
                <fullName>AP01_StockProduit</fullName>
            </value>
            <value>
                <fullName>AP01_SuiviStockSAV</fullName>
            </value>
            <value>
                <fullName>AP01_UpdatescheduledDate</fullName>
            </value>
            <value>
                <fullName>AP01_WorkOrder</fullName>
            </value>
            <value>
                <fullName>AP010_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP011_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP02_BandeUsine</fullName>
            </value>
            <value>
                <fullName>AP02_Commande</fullName>
            </value>
            <value>
                <fullName>AP02_Controle</fullName>
            </value>
            <value>
                <fullName>AP02_Convention</fullName>
            </value>
            <value>
                <fullName>AP02_Equipement</fullName>
            </value>
            <value>
                <fullName>AP02_EquipementDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP02_Foyer</fullName>
            </value>
            <value>
                <fullName>AP02_FoyerPaneliste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_validation_rules__c.field-meta.xml
<CustomField>
    <fullName>Bypass_validation_rules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass validation rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Batch009_ClotureRequeteAutomatique_Test.cls
/*
* @date: 20/09/2021
* @ Description Class qui teste Batch009_ClotureRequeteAutomatique. avant de lancer le test , modifier la variable Jour_de_traitement__c par J45__c a la ligne 62 du Batch009_ClotureRequeteAutomatique
* @version 1.00   
* pourcentage : 97%
* @Auteur Ayoub Ghammaz EIT
History
* <Date of modification> 		<Author> 			<Description of modification>
* 06/09/2021 				Ayoub Ghammaz 			Cloture de la requete deType d’enregistrement = contrôle AIP
* 29/10/2021 				Claire VEHRLE 			Cloture des controles des requêtes non clôturées en fin de journée
* 12/01/2023				Marliatou D.			Clôturer la requête Welcome Call après la première collecte d'audience du dernier équipement
*/
@isTest
public class Batch009_ClotureRequeteAutomatique_Test {
        
    @isTest static void testDAteSup21(){
        
        User u = [SELECT id, Bypass_flows__c, Bypass_validation_rules__c FROM User WHERE isActive = true and Profile.name like '%dministra%' limit 1];
        u.Bypass_triggers__c = 'AP02_Commande';
        update u;
        
        System.runAs(u){
        Id recordTypeIdRequeteControleAIP =Schema.SObjectType.Case.getRecordTypeInfosByName().get(label.CAS_Recordtype_ControleAIP).getRecordTypeId();
        Id recordTypeIdPanelAIP =Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_AIP).getRecordTypeId();
        //------------------------------- test  cloturer la requete :tt  date debut detection > 21 jours
        //creer foyer
        Account foyer2 = new Account(name='FoyerTest2');
        insert(foyer2);
        //creer foyer paneliste aip
        Foyer_paneliste__c paneliste2 = new Foyer_paneliste__c(name='PanelisteTest2',RecordTypeId=recordTypeIdPanelAIP,Foyer__c=foyer2.id,Statut_Foyer_paneliste__c = Label.PAN_Statut_Panel_Installe);
        insert(paneliste2);
        //insert case welcome call
        Case reqWelcome= new case(RecordTypeId = recordTypeIdRequeteControleAIP,
                                  Origin = Label.CAS_Origine_NouveauFoyer,
                                  AccountId=foyer2.id,
                                  Foyer_paneliste__c = paneliste2.id,
                                  Type = Label.CAS_Type_Recrute,
                                  Sous_type__c = Label.CAS_Sous_type_PackInitial);
        insert reqWelcome;
        //creer equipements
        List<Asset> assetToInsert = new list<Asset>();
        For(Integer index=0 ;index<3;index++){//Date.newInstance(2021, 7, 17)
            assetToInsert.add(new asset(recordtypeid=Schema.SObjectType.Asset.getRecordTypeInfosByName().get(label.ASS_RecordType_DispositifsMesureAudienceAIP).getRecordTypeId(),
                                        Name='test2 equi'+index,audimetre__c='adaa'+index,Foyer_paneliste__c=paneliste2.id,AccountId=foyer2.id,Date_de_premiere_detection__c=Date.newInstance(2021, 7, 17)));
        }
        insert assetToInsert;

        
        String orderId = '04a14d54-f45e-4d41-9b59-a01bed2d9de3';
        List <String> listOrderId = new List <String>();
        listOrderId.add(orderId);
        
        IndividuPanelisteCallout_Mock fakeGetOrder = new IndividuPanelisteCallout_Mock(orderId);
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, fakeGetOrder); 

        // Test.startTest();
        Batch009_ClotureRequeteAutomatique bccfb = new Batch009_ClotureRequeteAutomatique();
        Id batchId = Database.executeBatch(bccfb);
        Test.stopTest();
        // after the testing stops, assert records were updated properly
       // System.assertEquals(Label.CAS_Statut_Cloture, [select id ,Sous_type__c,Status from case where Sous_type__c=:Label.CAS_Sous_type_PackInitial].status);
    }
  } 
    
    @isTest static void testUneDAteInf21(){
        
        User u = [SELECT id, Bypass_flows__c, Bypass_validation_rules__c FROM User WHERE isActive = true and Profile.name like '%dministra%' limit 1];
        u.Bypass_triggers__c = 'AP02_Commande';
        update u;
        
        System.runAs(u){
            Id recordTypeIdRequeteDemandePanelisteAIP =Schema.SObjectType.Case.getRecordTypeInfosByName().get(label.CAS_Recordtype_DemandePanelisteAIP).getRecordTypeId();
            Id recordTypeIdPanelAIP =Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_AIP).getRecordTypeId();
            Id recordTypeIdControleAIP =Schema.SObjectType.case.getRecordTypeInfosByName().get(label.CAS_Recordtype_ControleAIP).getRecordTypeId();
            
            //------------------------------- test  ne pas cloturer la requete :une  date debut detection < 21 jours
            //creer foyer
            Account foyer3 = new Account(name='FoyerTest3');
            insert(foyer3);
            //creer foyer paneliste aip
            Foyer_paneliste__c paneliste3 = new Foyer_paneliste__c(name='PanelisteTest3',RecordTypeId=recordTypeIdPanelAIP,Foyer__c=foyer3.id,Statut_Audimetrique__c = Label.PAN_Statut_Audimetrique_nonRepondant);
            insert(paneliste3);
            //insert case welcome call
            Case reqWelcome= new case(RecordTypeId = recordTypeIdControleAIP,
                                      Origin = Label.CAS_Origine_NouveauFoyer,
                                      AccountId=foyer3.id,
                                      Foyer_paneliste__c = paneliste3.id,
                                      Type = Label.CAS_Type_Recrute,
                                      Sous_type__c = Label.CAS_Sous_type_PackInitial
                                     );
            insert reqWelcome;
            
            //creer equipements
            For(Integer index=0 ;index<3;index++){
                insert(new asset(recordtypeid=Schema.SObjectType.Asset.getRecordTypeInfosByName().get(label.ASS_RecordType_DispositifsMesureAudienceAIP).getRecordTypeId(),
                                 Name='test3 equi'+index,audimetre__c='iuyhhg'+index,Foyer_paneliste__c=paneliste3.id,AccountId=foyer3.id,Date_de_premiere_detection__c=Date.newInstance(2021, 7, 17)));
            }
            insert(new asset(recordtypeid=Schema.SObjectType.Asset.getRecordTypeInfosByName().get(label.ASS_RecordType_DispositifsMesureAudienceAIP).getRecordTypeId(),
                             Name='test2 equi223',Foyer_paneliste__c=paneliste3.id,AccountId=foyer3.id,Date_de_premiere_detection__c=date.today()));
            System.debug('bastien reqWelcome : '+ reqWelcome.CreatedDate);
            System.debug('bastien reqWelcome.id : '+ reqWelcome.id);
            
            
            Test.setCreatedDate(reqWelcome.id, Date.Today() - 45);
            
            List<Case> testCase  = [SELECT Id, CreatedDate, Jour_de_traitement__c FROM Case WHERE Id =:reqWelcome.Id];
            System.debug('bastien testCase : '+ testCase);
            
            
            String orderId = '04a14d54-f45e-4d41-9b59-a01bed2d9de3';
            List <String> listOrderId = new List <String>();
            listOrderId.add(orderId);
            
            IndividuPanelisteCallout_Mock fakeGetOrder = new IndividuPanelisteCallout_Mock(orderId);
            
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, fakeGetOrder); 
            //Test.startTest();
            
            Batch009_ClotureRequeteAutomatique bccfb = new Batch009_ClotureRequeteAutomatique();
            Id batchId = Database.executeBatch(bccfb);
            Test.stopTest();
            // after the testing stops, assert records were updated properly
            //System.assertEquals(Label.CAS_Statut_Cloture, [select id ,Sous_type__c,Status from case where Sous_type__c=:Label.CAS_Sous_type_PackInitial].status);
        }
    } 
    @isTest static void testCaseRemplacementMateriel(){
        User u = [SELECT id, Bypass_flows__c, Bypass_validation_rules__c FROM User WHERE isActive = true and Profile.name like '%dministra%' limit 1];
        u.Bypass_triggers__c = 'AP02_Commande';
        update u;
        
        System.runAs(u){
            
            Id recordTypeIdPanelAIP =Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_AIP).getRecordTypeId();
            
            /*------------------------------- test   cloturer la requete de type remplacement materiel :une  date debut detection >= 7 jours*/
            //creer foyer
            Account foyer3 = new Account(name='FoyerTest3');
            insert(foyer3);
            //creer foyer paneliste aip
            Foyer_paneliste__c paneliste3 = new Foyer_paneliste__c(name='PanelisteTest3',RecordTypeId=recordTypeIdPanelAIP,Foyer__c=foyer3.id,Statut_Foyer_paneliste__c = Label.PAN_Statut_panel);
            insert(paneliste3);
            case req=new case(RecordTypeId =Schema.SObjectType.Case.getRecordTypeInfosByName().get(label.CAS_Recordtype_DemandePanelisteAIP).getRecordTypeId(),
                              Origin = Label.CAS_Origine_NouveauFoyer,
                              AccountId=foyer3.id,
                              Foyer_paneliste__c = paneliste3.id ,
                              Type = Label.CAS_Type_RemplacementMateriel);
            insert req;
            //creer equipement
            insert(new asset(recordtypeid=Schema.SObjectType.Asset.getRecordTypeInfosByName().get(label.ASS_RecordType_DispositifsMesureAudienceAIP).getRecordTypeId(),
                             Name='test3 equi',Foyer_paneliste__c=paneliste3.id,AccountId=foyer3.id,requete__c=req.id,Date_de_premiere_detection__c=Date.newInstance(2022, 7, 17)));
            
            
            
            Test.startTest();
            Batch009_ClotureRequeteAutomatique bccfb = new Batch009_ClotureRequeteAutomatique();
            Id batchId = Database.executeBatch(bccfb);
            Test.stopTest();        
            
        }
    }  
    @isTest static void testCaseRemplacementMaterielInf(){
        User u = [SELECT id, Bypass_flows__c, Bypass_validation_rules__c FROM User WHERE isActive = true and Profile.name like '%dministra%' limit 1];
        u.Bypass_triggers__c = 'AP02_Commande';
        update u;
        
        System.runAs(u){
            Id recordTypeIdPanelAIP =Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_AIP).getRecordTypeId();
            
            /*------------------------------- test   ne pas cloturer la requete de type remplacement materiel :une  date debut detection < 7 jours*/
            //creer foyer
            Account foyer3 = new Account(name='FoyerTest3');
            insert(foyer3);
            //creer foyer paneliste aip
            Foyer_paneliste__c paneliste3 = new Foyer_paneliste__c(name='PanelisteTest3',RecordTypeId=recordTypeIdPanelAIP,Foyer__c=foyer3.id,Statut_Foyer_paneliste__c = Label.PAN_Statut_panel);
            insert(paneliste3);
            case req=new case(RecordTypeId =Schema.SObjectType.Case.getRecordTypeInfosByName().get(label.CAS_Recordtype_DemandePanelisteAIP).getRecordTypeId(),
                              Origin = Label.CAS_Origine_NouveauFoyer,
                              AccountId=foyer3.id,
                              Foyer_paneliste__c = paneliste3.id ,
                              Type = Label.CAS_Type_RemplacementMateriel);
            insert req;
            //creer equipement
            insert(new asset(recordtypeid=Schema.SObjectType.Asset.getRecordTypeInfosByName().get(label.ASS_RecordType_DispositifsMesureAudienceAIP).getRecordTypeId(),
                             Name='test3 equi',Foyer_paneliste__c=paneliste3.id,AccountId=foyer3.id,requete__c=req.id,Date_de_premiere_detection__c=Date.today().addDAys(-2)));
            
            
            
            Test.startTest();
            Batch009_ClotureRequeteAutomatique bccfb = new Batch009_ClotureRequeteAutomatique();
            Id batchId = Database.executeBatch(bccfb);
            Test.stopTest();
            System.assertNotEquals(Label.CAS_Statut_Cloture, [select id ,Sous_type__c,Status from case where type=:Label.CAS_Type_RemplacementMateriel].status);
            
        }
    }  
    @isTest static void testCollecteAudience(){
        User u = [SELECT id, Bypass_flows__c, Bypass_validation_rules__c FROM User WHERE isActive = true and Profile.name like '%dministra%' limit 1];
        u.Bypass_triggers__c = 'AP02_Commande';
        update u;
        
        System.runAs(u){
            Id recordTypeIdRequeteControleAIP =Schema.SObjectType.Case.getRecordTypeInfosByName().get(label.CAS_Recordtype_ControleAIP).getRecordTypeId();
            Id recordTypeIdPanelAIP =Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_AIP).getRecordTypeId();
            //------------------------------- test  cloturer la requete :tt  date debut detection > 21 jours
            //creer foyer
            Account foyer2 = new Account(name='FoyerTest2');
            insert(foyer2);
            //creer foyer paneliste aip
            Foyer_paneliste__c paneliste2 = new Foyer_paneliste__c(name='PanelisteTest2',RecordTypeId=recordTypeIdPanelAIP,Foyer__c=foyer2.id,Statut_Foyer_paneliste__c = Label.PAN_Statut_Panel_Installe);
            insert(paneliste2);
            //insert case welcome call
            Case reqWelcome= new case(RecordTypeId = recordTypeIdRequeteControleAIP,
                                      Origin = Label.CAS_Origine_NouveauFoyer,
                                      AccountId=foyer2.id,
                                      Foyer_paneliste__c = paneliste2.id,
                                      Type = Label.CAS_Type_Recrute,
                                      Sous_type__c = Label.CAS_Sous_type_WelcomeCall,
                                      Nombre_de_tentatives_welcome_call__c = 5
                                     );
            insert reqWelcome;
            //creer equipements
            List<Asset> assetToInsert = new list<Asset>();
            For(Integer index=0 ;index<3;index++){//Date.newInstance(2021, 7, 17)
                assetToInsert.add(new asset(recordtypeid=Schema.SObjectType.Asset.getRecordTypeInfosByName().get(label.ASS_RecordType_DispositifsMesureAudienceAIP).getRecordTypeId(),
                                            Name='test2 equi'+index,audimetre__c='iuyhEEhg'+index,Foyer_paneliste__c=paneliste2.id,AccountId=foyer2.id,Date_de_premiere_detection__c=Date.newInstance(2021, 7, 17),
                                            Date_de_premiere_collecte_d_audience__c=Date.newInstance(2021, 7, 17)));
            }
            insert assetToInsert;
            Test.startTest();
            Batch009_ClotureRequeteAutomatique bccfb = new Batch009_ClotureRequeteAutomatique();
            Id batchId = Database.executeBatch(bccfb);
            Test.stopTest();
            // after the testing stops, assert records were updated properly
            //System.assertEquals(Label.CAS_Statut_Cloture, [select id ,Sous_type__c,Status from case where Sous_type__c=:Label.CAS_Sous_type_WelcomeCall].status);
        }
    } 
    @isTest static void testCollect(){
        User u = [SELECT id, Bypass_flows__c, Bypass_validation_rules__c FROM User WHERE isActive = true and Profile.name like '%dministra%' limit 1];
        u.Bypass_triggers__c = 'AP02_Commande';
        update u;
        
        System.runAs(u){
            Id recordTypeIdRequeteControleAIP =Schema.SObjectType.Case.getRecordTypeInfosByName().get(label.CAS_Recordtype_ControleAIP).getRecordTypeId();
            Id recordTypeIdPanelAIP =Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_AIP).getRecordTypeId();
            //------------------------------- test  cloturer la requete :tt  date debut detection > 21 jours
            //creer foyer
            Account foyer2 = new Account(name='FoyerTest2');
            insert(foyer2);
            //creer foyer paneliste aip
            Foyer_paneliste__c paneliste2 = new Foyer_paneliste__c(name='PanelisteTest2',RecordTypeId=recordTypeIdPanelAIP,Foyer__c=foyer2.id,Statut_Foyer_paneliste__c = Label.PAN_Statut_Panel_Installe);
            insert(paneliste2);
            //insert case welcome call
            Case reqWelcome= new case(RecordTypeId = recordTypeIdRequeteControleAIP,
                                      Origin = Label.CAS_Origine_NouveauFoyer,
                                      AccountId=foyer2.id,
                                      Foyer_paneliste__c = paneliste2.id,
                                      Type = Label.CAS_Type_Anomalie_Materiel,
                                      Nombre_de_tentatives_welcome_call__c = 5
                                     );
            insert reqWelcome;
            //creer equipements
            List<Asset> assetToInsert = new list<Asset>();
            For(Integer index=0 ;index<3;index++){//Date.newInstance(2021, 7, 17)
                assetToInsert.add(new asset(recordtypeid=Schema.SObjectType.Asset.getRecordTypeInfosByName().get(label.ASS_RecordType_DispositifsMesureAudienceAIP).getRecordTypeId(),
                                            Name='test2 equi'+index,audimetre__c='iuyheeeehg'+index,Foyer_paneliste__c=paneliste2.id,AccountId=foyer2.id,Date_de_premiere_detection__c=Date.newInstance(2021, 7, 17),
                                            Date_de_premiere_collecte_d_audience__c=Date.newInstance(2021, 7, 17)));
            }
            insert assetToInsert;
            Test.startTest();
            Batch009_ClotureRequeteAutomatique bccfb = new Batch009_ClotureRequeteAutomatique();
            Id batchId = Database.executeBatch(bccfb);
            Test.stopTest();
        }
    }  
    @isTest static void testStatutAudim(){
        
        Id recordTypeIdRequeteControleAIP =Schema.SObjectType.Case.getRecordTypeInfosByName().get(label.CAS_Recordtype_ControleAIP).getRecordTypeId();
        Id recordTypeIdPanelAIP =Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_AIP).getRecordTypeId();
        
        //creer foyer
        Account foyer2 = new Account(name='FoyerTest2');
        insert(foyer2);
        //creer foyer paneliste aip
        Foyer_paneliste__c paneliste2 = new Foyer_paneliste__c(name='PanelisteTest2',RecordTypeId=recordTypeIdPanelAIP,Foyer__c=foyer2.id,Statut_Foyer_paneliste__c = Label.PAN_Statut_Panel_Installe,
                                                               Statut_Audimetrique__c = Label.PAN_Statut_Audimetrique_Present_Batch009);
        insert(paneliste2);
        //insert case
        Case req= new case(RecordTypeId = recordTypeIdRequeteControleAIP,
                           Origin = Label.CAS_Origine_NouveauFoyer,
                           AccountId=foyer2.id,
                           Foyer_paneliste__c = paneliste2.id,
                           Type = Label.CAS_Type_Non_repondant,
                           Type_de_controle__c = Label.CAS_TypeControle_Non_Repondant);
        insert req;
        
        Controle__c controleTest = Test_Utils.createControle(foyer2.Id, null, null, req.Id, null);
        controleTest.Foyer_Paneliste__c= paneliste2.Id;
        insert controleTest;
        
        Test.startTest();
        Batch009_ClotureRequeteAutomatique bccfb = new Batch009_ClotureRequeteAutomatique();
        Id batchId = Database.executeBatch(bccfb);
        Test.stopTest();
    }
    
    
    
    @isTest
    static void testPassageControleAIPAbandonne() {
        
        Id recordTypeIdControleAIP =Schema.SObjectType.case.getRecordTypeInfosByName().get(label.CAS_Recordtype_ControleAIP).getRecordTypeId();
        Id recordTypeIdPanelAIP =Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_AIP).getRecordTypeId();
        Id recordTypeIdControleControleAIP =Schema.SObjectType.controle__c.getRecordTypeInfosByName().get(label.CAS_Recordtype_ControleAIP).getRecordTypeId();
        
        list<Account> listFoyersToInsert = new list<Account>();
        account foyer = Test_Utils.createFoyer();
        foyer.Numero_de_portable__c = '0611111121';
        listFoyersToInsert.add(foyer); 
        
        insert listFoyersToInsert;
        
        //Foyer Panéliste
        List<Foyer_paneliste__c> listFoyerPaneliste = new List<Foyer_paneliste__c>();
        Foyer_Paneliste__c foyerPaneliste = Test_Utils.createFoyerPaneliste();
        foyerPaneliste.Name = 'Foyer panéliste';
        foyerPaneliste.Foyer__c = foyer.id;
        foyerPaneliste.RecordTypeId = recordTypeIdPanelAIP;
        foyerPaneliste.Statut_Audimetrique__c = Label.PAN_Statut_Audimetrique_Present_Batch009;
        listFoyerPaneliste.add(foyerPaneliste);
        
        insert listFoyerPaneliste;
        
        List<Case> caseToInsert = new list<Case>();
        Case requete1 = Test_Utils.createCase(foyer.Id);
        requete1.RecordTypeId = recordTypeIdControleAIP;
        requete1.Origin = Label.CAS_Origine_Controle;
        requete1.Status = Label.CAS_Statut_Cloture;
        requete1.Foyer_paneliste__c = foyerPaneliste.Id;
        requete1.Type_de_controle__c = Label.CAS_TypeControle_Non_Repondant;
        caseToInsert.add(requete1);
        
        Case requete2 = Test_Utils.createCase(foyer.Id);
        requete2.RecordTypeId = recordTypeIdControleAIP;
        requete2.Origin = Label.CAS_Origine_Controle;
        requete2.Status = Label.CAS_Statut_En_cours;
        requete2.Foyer_paneliste__c = foyerPaneliste.Id;
        caseToInsert.add(requete2);
        
        Case requete3 = Test_Utils.createCase(foyer.Id);
        requete3.RecordTypeId = recordTypeIdControleAIP;
        requete3.Origin = Label.CAS_Origine_Controle;
        requete3.Status = Label.CAS_Statut_Nouveau;
        requete3.Foyer_paneliste__c = foyerPaneliste.Id;
        caseToInsert.add(requete3);
        
        Case requete4 = Test_Utils.createCase(foyer.Id);
        requete4.RecordTypeId = recordTypeIdControleAIP;
        requete4.Origin = Label.CAS_Origine_Controle;
        requete4.Status = Label.CAS_Statut_Hierarchise;
        requete4.Foyer_paneliste__c = foyerPaneliste.Id;
        caseToInsert.add(requete4);
        
        Case requete5 = Test_Utils.createCase(foyer.Id);
        requete5.RecordTypeId = recordTypeIdControleAIP;
        requete5.Origin = Label.CAS_Origine_Controle;
        requete5.Type   = Label.CAS_Type_NonRepondantSetMeter;
        requete5.Foyer_paneliste__c = foyerPaneliste.Id;
        caseToInsert.add(requete5);
        
        Case requete6 = Test_Utils.createCase(foyer.Id);
        requete6.RecordTypeId = recordTypeIdControleAIP;
        //requete6.Origin = Label.CAS_Origine_Controle;
        requete6.Type   =  Label.CAS_Type_Non_repondant;
        requete6.Foyer_paneliste__c = foyerPaneliste.Id;
        caseToInsert.add(requete6);
        
        insert caseToInsert;
        
        List<Asset> equipementDuFoyerList = new List<Asset>();
        Id recordTypeIdEquipementDeMesureAIP = Schema.SObjectType.Asset.getRecordTypeInfosByName().get(Label.ASS_RecordType_DispositifsMesureAudienceAIP).getRecordTypeId();
        Asset asset1 = Test_Utils.createEquipement(foyer.Id);
        asset1.RecordTypeId = recordTypeIdEquipementDeMesureAIP;
        asset1.Foyer_paneliste__c = foyerPaneliste.Id;
        asset1.Type_de_materiel__c = Label.ASS_TypeMateriel_Setmeter;
        asset1.Audimetre__c='lkdzgteii';
        asset1.Name = 'asset1';
        equipementDuFoyerList.add(asset1);        
        
        Asset asset2 = Test_Utils.createEquipement(foyer.Id);
        asset2.RecordTypeId = recordTypeIdEquipementDeMesureAIP;
        asset2.Foyer_paneliste__c = foyerPaneliste.Id;
        asset2.Type_de_materiel__c = Label.ASS_TypeMateriel_Pager;
        asset2.Audimetre__c='lkjogteioi';
        asset2.Name = 'asset2';
        equipementDuFoyerList.add(asset2);
        
        insert equipementDuFoyerList;
        
        System.debug('Asset2' + asset2);
        
        
        List<Controle__c> contrleToInsert = new list<Controle__c>();
        Controle__c controle1 = Test_Utils.createControle(foyer.Id, null, null, requete1.Id, null);
        controle1.Foyer_Paneliste__c= foyerPaneliste.Id;
        controle1.recordTypeId = recordTypeIdControleControleAIP;
        contrleToInsert.add(controle1);
        
        Controle__c controle2 = Test_Utils.createControle(foyer.Id, null, null, requete2.Id, null);
        controle2.Foyer_Paneliste__c= foyerPaneliste.Id;
        controle2.recordTypeId = recordTypeIdControleControleAIP;
        contrleToInsert.add(controle2);
        
        Controle__c controle3 = Test_Utils.createControle(foyer.Id, null, null, requete3.Id, null);
        controle3.Foyer_Paneliste__c= foyerPaneliste.Id;
        controle3.recordTypeId = recordTypeIdControleControleAIP;
        contrleToInsert.add(controle3);
        
        Controle__c controle4 = Test_Utils.createControle(foyer.Id, null, null, requete4.Id, null);
        controle4.Foyer_Paneliste__c = foyerPaneliste.Id;
        controle4.recordTypeId = recordTypeIdControleControleAIP;
        contrleToInsert.add(controle4);
      
        Controle__c controle5 = Test_Utils.createControle(foyer.Id, null, asset1.Id, requete5.Id, null);
        controle5.Foyer_Paneliste__c= foyerPaneliste.Id;
        controle5.recordTypeId = recordTypeIdControleControleAIP;
        contrleToInsert.add(controle5);
        
        Controle__c controle6 = Test_Utils.createControle(foyer.Id, null, asset2.Id, requete6.Id, null);
        controle6.Foyer_Paneliste__c= foyerPaneliste.Id;
        controle6.recordTypeId = recordTypeIdControleControleAIP;
        controle6.statut__c = Label.CTRL_Statut_Actif;
        contrleToInsert.add(controle6);
        
        insert contrleToInsert;
        
        System.debug('controle5  ' + controle5);
        System.debug('controle6  ' + controle6);
        
        Test.startTest();
        Batch009_ClotureRequeteAutomatique bccfb = new Batch009_ClotureRequeteAutomatique();
        Id batchId = Database.executeBatch(bccfb);
        Test.stopTest();
                 
    }
    
    
}