force-app/main/default/objects/Account/fields/TECH_CongePrincipal__c.field-meta.xml
<CustomField>
    <fullName>TECH_CongePrincipal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TECH_CongePrincipal</label>
    <referenceTo>Conge__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Foyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Conge__c/Conge__c.object-meta.xml
<CustomObject>
    <label>Congé</label>
    <nameField>
        <displayFormat>ABS - {0000}</displayFormat>
        <label>Numéro du congé</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Congés</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conge__c/fields/Conge_de_l_individu__c.field-meta.xml
<CustomField>
    <fullName>Conge_de_l_individu__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Congé de l&apos;individu</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Congés</relationshipLabel>
    <relationshipName>Cong_s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Conge__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Conge__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Conge__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Congés</relationshipLabel>
    <relationshipName>Conges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Conge__c/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>Autre</label>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>Médical</label>
            </value>
            <value>
                <fullName>2</fullName>
                <isActive>false</isActive>
                <label>Professionnel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Conge__c/fields/Type_de_conge__c.field-meta.xml
<CustomField>
    <fullName>Type_de_conge__c</fullName>
    <label>Type de congé</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
                <label>En vacances</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Absent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Activite_actuelle__c.field-meta.xml
<CustomField>
    <fullName>Activite_actuelle__c</fullName>
    <label>Activité actuelle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
                <label>Au chômage ayant déjà travaillé</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Exerce une activité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>À la rechercher d&apos;un 1er emploi</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Retraite ou pré-retraite</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Congé maternité</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Congé parental</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Maladie longue durée</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Femme ou homme au foyer</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Autre cas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Code_profession__c.field-meta.xml
<CustomField>
    <fullName>Code_profession__c</fullName>
    <label>Code profession</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CON_ExtId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>CON_ExtId_SIPanel__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>CON_ExtId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Lien_parente__c.field-meta.xml
<CustomField>
    <fullName>Lien_parente__c</fullName>
    <label>Lien parenté</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Chef de famille</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Conjoint</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Enfant</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Ascendant</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Autre</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/TECH_CongePrincipal__c.field-meta.xml
<CustomField>
    <fullName>TECH_CongePrincipal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TECH_CongePrincipal</label>
    <referenceTo>Conge__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Individus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BATCH0014_UpdateConge_Test.cls
@istest
public class BATCH0014_UpdateConge_Test {
    public static testMethod void BATCH0014_UpdateConge_Test() {
        list<Account> listFoyersToInsert = new list<Account>();
        account acc1 = Test_Utils.createFoyer();
        listFoyersToInsert.add(acc1); 
        account acc2 = Test_Utils.createFoyer();
        listFoyersToInsert.add(acc2); 
        account acc3 = Test_Utils.createFoyer();
        listFoyersToInsert.add(acc3); 
        account acc4 = Test_Utils.createFoyer();
        listFoyersToInsert.add(acc4); 
        insert listFoyersToInsert;
        
        list<Contact> listMembreFoyerToInsert = new list<Contact>();
       
        Contact contact1 = Test_Utils.createMembreFoyer(acc1.id); 
        contact1.Lien_parente__c = Label.CON_LienParente_ChefDeFamille;
        contact1.Activite_actuelle__c = System.Label.CON_ActiviteActuelle_A_la_recherche_premier_emploi;
        contact1.Code_profession__c = 132;
        contact1.CON_ExtId_SIPanel__c = '122233458';
        
        Contact contact2 = Test_Utils.createMembreFoyer(acc2.id); 
        contact2.Lien_parente__c = Label.CON_LienParente_ChefDeFamille;
        contact2.Activite_actuelle__c = System.Label.CON_ActiviteActuelle_A_la_recherche_premier_emploi;
        contact2.Code_profession__c = 132;
        contact2.CON_ExtId_SIPanel__c = '124433458';
        
        Contact contact3 = Test_Utils.createMembreFoyer(acc3.id); 
        contact3.Lien_parente__c = Label.CON_LienParente_ChefDeFamille;
        contact3.Activite_actuelle__c = System.Label.CON_ActiviteActuelle_A_la_recherche_premier_emploi;
        contact3.Code_profession__c = 132;
        contact3.CON_ExtId_SIPanel__c = '114433458';
        
        Contact contact4 = Test_Utils.createMembreFoyer(acc4.id); 
        contact4.Lien_parente__c = Label.CON_LienParente_ChefDeFamille;
        contact4.Activite_actuelle__c = System.Label.CON_ActiviteActuelle_A_la_recherche_premier_emploi;
        contact4.Code_profession__c = 132;
        contact4.CON_ExtId_SIPanel__c = '814433458';
        
        listMembreFoyerToInsert.add(contact1);
        listMembreFoyerToInsert.add(contact2);
        listMembreFoyerToInsert.add(contact3);
        listMembreFoyerToInsert.add(contact4);

        insert listMembreFoyerToInsert; 
        
        Conge__c conge1 = new Conge__c();
		conge1.Date_de_debut__c= system.today() - 5;
        conge1.Date_de_fin__c= system.today() ;
        conge1.Conge_de_l_individu__c=contact1.Id;
        conge1.Foyer__c=acc1.Id;
        conge1.Type_de_conge__c= '1';
        conge1.Motif__c='1';
        insert conge1;
        
        
        Conge__c conge2 = new Conge__c();
		conge2.Date_de_debut__c= system.today();
        conge2.Date_de_fin__c= system.today() + 3;
        conge2.Conge_de_l_individu__c= contact2.Id;
        conge2.Foyer__c=acc2.Id;
        conge2.Type_de_conge__c= '1';
        conge2.Motif__c='1';
        insert conge2;
        
        Conge__c conge3 = new Conge__c();
		conge3.Date_de_debut__c= system.today()+4;
        conge3.Date_de_fin__c= system.today() +6;
        //conge3.Conge_de_l_individu__c= contact3.Id;
       
        conge3.Foyer__c=acc3.Id;
        conge3.Type_de_conge__c= '1';
        conge3.Motif__c='1';
        insert conge3;
        
        
        
        Conge__c conge4 = new Conge__c();
		conge4.Date_de_debut__c= system.today()-9;
        conge4.Date_de_fin__c= system.today()+7;
        conge4.Conge_de_l_individu__c= contact4.Id;
        conge4.Foyer__c=acc4.Id;
        conge4.Type_de_conge__c= '1';
        conge4.Motif__c='1';
        insert conge4;
        
        contact2.TECH_CongePrincipal__c=conge3.Id;
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(contact1.CON_ExtId_SIPanel__c));
        BATCH0014_UpdateConge btch = new BATCH0014_UpdateConge();
        database.executeBatch(btch); 
        Test.stopTest();
      
        system.assertEquals( contact2.TECH_CongePrincipal__c,conge3.Id);
    }
}