force-app/main/default/objects/Account/fields/Type_de_foyer__c.field-meta.xml
<CustomField>
    <fullName>Type_de_foyer__c</fullName>
    <label>Type de foyer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Médiamat</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Single Source</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>AIP</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Multi panel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Browser__c.field-meta.xml
<CustomField>
    <fullName>Browser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Browser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CON_ExtId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>CON_ExtId_SIPanel__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>CON_ExtId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_d_entree_individu__c.field-meta.xml
<CustomField>
    <fullName>Date_d_entree_individu__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;entrée individu</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_de_chute_individu__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute_individu__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute individu</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_de_synchronisation_Google__c.field-meta.xml
<CustomField>
    <fullName>Date_de_synchronisation_Google__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de synchronisation Google</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Id_google__c.field-meta.xml
<CustomField>
    <fullName>Id_google__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>ID Google</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Lettre__c.field-meta.xml
<CustomField>
    <fullName>Lettre__c</fullName>
    <label>Lettre</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Lien_meter__c.field-meta.xml
<CustomField>
    <fullName>Lien_meter__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Lien meter</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mobile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Routeur__c.field-meta.xml
<CustomField>
    <fullName>Routeur__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Routeur</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Signature_convention_individuelle_meter__c.field-meta.xml
<CustomField>
    <fullName>Signature_convention_individuelle_meter__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Signature convention individuelle Meter</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Statut_individu__c.field-meta.xml
<CustomField>
    <fullName>Statut_individu__c</fullName>
    <label>Statut de l&apos;individu</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Présent</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Vacancier</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Absent</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Inactif</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Ne fait plus partie du panel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Tv__c.field-meta.xml
<CustomField>
    <fullName>Tv__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tv</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Browser__c.field-meta.xml
<CustomField>
    <fullName>Browser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Browser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/CON_EXTId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>CON_EXTId_SIPanel__c</fullName>
    <description>&quot;(UUID) c&apos;est l&apos;id salesforce de l&apos;enregistrement Composition Du Foyer Parent
Ce champ sert a identifier l&apos;enregistrement parent (Composition Du Foyer) de l&apos;Individu Panéliste&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>CON_EXTId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Date_d_entree_de_l_individu__c.field-meta.xml
<CustomField>
    <fullName>Date_d_entree_de_l_individu__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;entrée de l&apos;individu</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Date_de_chute_de_l_individu__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute_de_l_individu__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute de l&apos;individu</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Date_de_synchronisation_Google__c.field-meta.xml
<CustomField>
    <fullName>Date_de_synchronisation_Google__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de synchronisation Google</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Individus Panélistes</relationshipLabel>
    <relationshipName>Individus_Paneliste</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/ID_Google__c.field-meta.xml
<CustomField>
    <fullName>ID_Google__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ID Google</label>
    <length>233</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Lettre__c.field-meta.xml
<CustomField>
    <fullName>Lettre__c</fullName>
    <label>Lettre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Lien_meter__c.field-meta.xml
<CustomField>
    <fullName>Lien_meter__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Lien meter</label>
    <length>233</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mobile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Routeur__c.field-meta.xml
<CustomField>
    <fullName>Routeur__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Routeur</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Signature_convention_individuelle_Meter__c.field-meta.xml
<CustomField>
    <fullName>Signature_convention_individuelle_Meter__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Signature convention individuelle Meter</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/TV__c.field-meta.xml
<CustomField>
    <fullName>TV__c</fullName>
    <defaultValue>true</defaultValue>
    <label>TV</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT( Foyer_paneliste__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchRDD03_IndividuPaneliste.cls
/*
* @author: Elia KARAM
* @date: 07/03/2022
* @ Description Batch pour la RDD de l'objet Individu Panéliste
* @TestClass: BatchRDD03_IndividuPaneliste_Test
* @Coverage: 93 %
* History
* <Date of modification>   		<Author>   		 <Description of modification>
*/
public class BatchRDD03_IndividuPaneliste implements Database.Batchable<sObject>{
    public Database.Querylocator start(Database.BatchableContext BC){
        
        return Database.getQueryLocator([SELECT id,Account.Type_de_foyer__c,accountid, Statut_individu__c, Date_d_entree_individu__c, 
                                         Date_de_chute_individu__c, Lettre__c, 
                                         Id_google__c, Browser__c, Tv__c,  CON_ExtId_SIPanel__c,
                                         Routeur__c, Mobile__c, Lien_meter__c, Date_de_synchronisation_Google__c, 
                                         Signature_convention_individuelle_meter__c, (SELECT Id FROM Paneliste__r)
                                         FROM Contact WHERE Account.Type_de_foyer__c != :Label.ACC_Type_de_panel_AIP
                                         				AND AccountId != null 
                                         				AND (NOT(FirstName LIKE 'prenom_%'))]);
    } 
    public void execute(Database.BatchableContext info, List<Contact> scope){
        System.debug(info);
        Map<String,String> foyerPaneFoyer = new Map<String,String>();
        Map<String,String> foyerPaneExternalId = new Map<String,String>();
        for(Foyer_paneliste__c fp : [SELECT id , Foyer__c FROM Foyer_paneliste__c 
                                     WHERE referentiel_panel__r.type_de_panel__c = :Label.RFP_TypePanel_PaME
                                     OR referentiel_panel__r.type_de_panel__c = :Label.RFP_TypePanel_MMAT]){
            foyerPaneFoyer.put(fp.Foyer__c,fp.id);
        }
        List<Individu_Paneliste__c> individuP = new List<Individu_Paneliste__c>();
        
        for(Contact compoFoyer : scope){ 
            if (compoFoyer.Paneliste__r.isEmpty() && compoFoyer.Paneliste__r.size() == 0) {
                Individu_Paneliste__c  ip = new Individu_Paneliste__c ();
                ip.Foyer_paneliste__c = foyerPaneFoyer.get(compoFoyer.AccountId); 
                ip.Composition_du_foyer__c = compoFoyer.Id;                
                ip.Date_d_entree_de_l_individu__c = compoFoyer.Date_d_entree_individu__c;
                ip.Date_de_chute_de_l_individu__c = compoFoyer.Date_de_chute_individu__c;
                ip.Lettre__c = compoFoyer.Lettre__c;
                ip.Id_google__c = compoFoyer.Id_google__c; 
                ip.Browser__c = compoFoyer.Browser__c; 
                ip.Tv__c = compoFoyer.Tv__c;
                ip.Routeur__c = compoFoyer.Routeur__c;
                ip.Mobile__c = compoFoyer.Mobile__c;
                ip.Lien_meter__c = compoFoyer.Lien_meter__c; 
                ip.Date_de_synchronisation_Google__c = compoFoyer.Date_de_synchronisation_Google__c; 
                ip.Signature_convention_individuelle_meter__c = compoFoyer.Signature_convention_individuelle_meter__c;
                ip.CON_EXTId_SIPanel__c = compoFoyer.CON_EXTId_SIPanel__c;
                individuP.add(ip);
            }
            
            
        }
        if(individuP.size() > 0 && individuP != null){
            try{ 
                database.insert(individuP, false);
            }Catch(exception ex){
                system.debug('Update Foyer Exception Error:' + ex.getmessage());
            }
        }
        
    }     
    public void finish(Database.BatchableContext info){    
        
    }
}