force-app/main/default/objects/Account/fields/Type_de_foyer__c.field-meta.xml
<CustomField>
    <fullName>Type_de_foyer__c</fullName>
    <label>Type de foyer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Médiamat</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Single Source</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>AIP</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Multi panel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Membre</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Invité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Non panéliste</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/PaME.recordType-meta.xml
<RecordType>
    <fullName>PaME</fullName>
    <active>true</active>
    <label>PaME</label>
</RecordType>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Membre_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Membre_du_foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membre du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/recordTypes/AIP.recordType-meta.xml
<RecordType>
    <fullName>AIP</fullName>
    <active>true</active>
    <label>AIP</label>
</RecordType>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invité</fullName>
            </value>
            <value>
                <fullName>Membre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP00_Objet_Non_transforme.cls
/*
* @author: Claire VEHRLE
* @date: 25/04/2022
* @ Description Trouver les objets qui n'ont pa sréussi à être transformé
* @TestClass:
* @Coverage:
* History
* <Date of modification>   		<Author>   		 <Description of modification>
*/
public class AP00_Objet_Non_transforme {

    public static void foyerNonTransformeMMATPaME() {
        List<Account> allFoyer = [SELECT Id, name, (SELECT Id FROM Panelistes__r) FROM Account
                                 WHERE Type_de_foyer__c = :Label.ACC_Type_de_panel_Pame 
                                                 OR Type_de_foyer__c = :Label.ACC_Type_de_panel_Mediamat];
        List<Account> foyerNonTransformeList = new List<Account>();
        
        for(Account foyer : allFoyer){
            System.debug('NON foyer.Panelistes__r: ' +foyer.Panelistes__r);
            if(foyer.Panelistes__r.isEmpty() && foyer.Panelistes__r.size() == 0) {
                foyerNonTransformeList.add(foyer);
            }
        }
        
        System.debug('NON_TRANSFORME: Taille list Foyer MMAT PaME: ' + foyerNonTransformeList.size());
        for(Account foyerNontransforme :foyerNonTransformeList) {
            System.debug('NON_TRANSFORME: Foyer MMAT PaME: ' + foyerNontransforme);
        }
        
    }
    
    public static void foyerNonTransformeAIP() {
        List<Account> allFoyer = [SELECT Id, name, (SELECT Id FROM Panelistes__r) FROM Account WHERE Type_de_foyer__c = '4'];
        List<Account> foyerNonTransformeList = new List<Account>();
        
        for(Account foyer : allFoyer){ 
            if(foyer.Panelistes__r.isEmpty() && foyer.Panelistes__r.size() == 0) {
                foyerNonTransformeList.add(foyer);
            }
        }
        
        System.debug('NON_TRANSFORME: Taille list Foyer AIP: ' + foyerNonTransformeList.size());
        for(Account foyerNontransforme :foyerNonTransformeList) {
            System.debug('NON_TRANSFORME: Foyer AIP: ' + foyerNontransforme);
        }
        
    }
    
    public static void compoFoyerNonTransformeMMATPaME() {
        List<Contact> allCompositionFoyer = [SELECT id, name, account.Type_de_foyer__c, (SELECT Id FROM Paneliste__r)
                                         	FROM Contact 
                                             WHERE (Account.Type_de_foyer__c = :Label.ACC_Type_de_panel_Pame 
                                                 OR Account.Type_de_foyer__c = :Label.ACC_Type_de_panel_Mediamat) 
                                             	AND AccountID != null AND (NOT(FirstName LIKE 'prenom_%'))];
        
        List<Contact> compoFoyerNonTransformeList = new List<Contact>();
        
        for(Contact compoFoyer : allCompositionFoyer){ 
            if(compoFoyer.Paneliste__r.isEmpty() && compoFoyer.Paneliste__r.size() == 0) {
                compoFoyerNonTransformeList.add(compoFoyer);
            }
        }
        
        System.debug('NON_TRANSFORME: Taille list Composition Foyer MMAT PaME: ' + compoFoyerNonTransformeList.size());
        for(Contact compoFoyer :compoFoyerNonTransformeList) {
            System.debug('NON_TRANSFORME: Composition Foyer MMAT PaME: ' + compoFoyer);
        }
        
    }
    
    public static void compoFoyerNonTransformeAIP() {
        List<Contact> allCompositionFoyer = [SELECT id, name, account.Type_de_foyer__c, (SELECT Id FROM Paneliste__r)
                                         FROM Contact WHERE Account.Type_de_foyer__c = :Label.ACC_Type_de_panel_AIP AND Type__c != '2'];
        
        List<Contact> compoFoyerNonTransformeList = new List<Contact>();
        
        for(Contact compoFoyer : allCompositionFoyer){ 
            if(compoFoyer.Paneliste__r.isEmpty() && compoFoyer.Paneliste__r.size() == 0) {
                compoFoyerNonTransformeList.add(compoFoyer);
            }
        }
        
        System.debug('NON_TRANSFORME: Taille list Composition Foyer AIP: ' + compoFoyerNonTransformeList.size());
        for(Contact compoFoyer :compoFoyerNonTransformeList) {
            System.debug('NON_TRANSFORME: Composition Foyer AIP: ' + compoFoyer);
        }
        
    }
}