force-app/main/default/objects/Equipements_du_foyer__c/Equipements_du_foyer__c.object-meta.xml
<CustomObject>
    <label>Equipement du foyer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;équipement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipements du foyer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Equipements du foyer</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Modele_de_console_de_jeux__c.field-meta.xml
<CustomField>
    <fullName>Modele_de_console_de_jeux__c</fullName>
    <label>Modèle de console de jeux</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>35</fullName>
                <label>MICROSOFT - XBOX One</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>SONY - PLAYSTATION 4</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>MICROSOFT - XBOX 360</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>SONY - PLAYSTATION 3</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>NINTENDO - Wii U</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>NINTENDO - Wii</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>MICROSOFT - XBOX</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>AUTRES MODELES</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Poste_TV__c.field-meta.xml
<CustomField>
    <fullName>Poste_TV__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Poste TV</label>
    <referenceTo>Equipements_du_foyer__c</referenceTo>
    <relationshipLabel>Périphériques</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>7</fullName>
                <label>Ordinateur fixe</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Ordinateur portable</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Tablette</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Mobile</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Poste TV</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Lecteur DVD</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Console de jeux</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Magnétoscope</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Décodeur</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Divers</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Box</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Caster</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Objet Connecté</label>
            </value>
            <value>
                <fullName>17</fullName>
                <isActive>false</isActive>
                <label>Autre équipement</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP03_EquipementDuFoyer_Test.cls
/*
* @Auteur : Bastien PINARD
* @date: 30/08/2022
* @ Description : 

* @Class: AP03_EquipementDuFoyer
* @Coverage: 100%
History
* <Date of modification> 		<Author> 			<Description of modification>
*/
@isTest
public with sharing class AP03_EquipementDuFoyer_Test {
    @isTest
    public static void deletePeripherique(){
        Id devPeriRecordTypeId =Schema.SObjectType.Equipements_du_foyer__c.getRecordTypeInfosByName().get('Périphériques').getRecordTypeId();
        Id devPosteTVRecordTypeId =Schema.SObjectType.Equipements_du_foyer__c.getRecordTypeInfosByName().get('Poste TV').getRecordTypeId();
        
        Account acc = new Account();
        acc.Name = 'toto';
        insert acc;
        
        Equipements_du_foyer__c eq1 = new Equipements_du_foyer__c();
        eq1.Foyer__c = acc.Id;
        eq1.Name = 'azer';
        eq1.RecordTypeId = devPosteTVRecordTypeId;
        insert eq1;
        
        Equipements_du_foyer__c eq2 = new Equipements_du_foyer__c();
        eq2.Foyer__c = acc.Id;
        eq2.Name = 'azer';
        eq2.Type__c='5';
        eq2.Poste_TV__c=eq1.Id;
        eq2.RecordTypeId = devPeriRecordTypeId;
        eq2.Modele_de_console_de_jeux__c='28';
        insert eq2;
        
        delete eq1;
        
        
        List<Equipements_du_foyer__c> testEquipementFoyer = [SELECT Id , Name FROM Equipements_du_foyer__c WHERE Name = 'Console Poste 0 SONY - PLAYSTATION 3'];
        System.assertEquals(0, testEquipementFoyer.size()); 
    }
}