force-app/main/default/objects/Equipements_du_foyer__c/Equipements_du_foyer__c.object-meta.xml
<CustomObject>
    <label>Equipement du foyer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;équipement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipements du foyer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Equipements du foyer</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Marque_d_ordinateur__c.field-meta.xml
<CustomField>
    <fullName>Marque_d_ordinateur__c</fullName>
    <label>Marque d&apos;ordinateur</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Apple</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Autre marque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Marque_de_telephone__c.field-meta.xml
<CustomField>
    <fullName>Marque_de_telephone__c</fullName>
    <label>Marque de téléphone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>38</fullName>
                <label>Acer</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Alcatel</label>
            </value>
            <value>
                <fullName>37</fullName>
                <label>Android Edition / S by SFR</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>Apple</label>
            </value>
            <value>
                <fullName>54</fullName>
                <label>Archos</label>
            </value>
            <value>
                <fullName>58</fullName>
                <label>Asus</label>
            </value>
            <value>
                <fullName>71</fullName>
                <label>Autre marque</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Benq-Siemens</label>
            </value>
            <value>
                <fullName>68</fullName>
                <label>Blackview</label>
            </value>
            <value>
                <fullName>52</fullName>
                <label>Bouygues Telecom</label>
            </value>
            <value>
                <fullName>55</fullName>
                <label>Carrefour</label>
            </value>
            <value>
                <fullName>45</fullName>
                <label>Dell</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>Doogee</label>
            </value>
            <value>
                <fullName>42</fullName>
                <label>Doro</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>Echo</label>
            </value>
            <value>
                <fullName>46</fullName>
                <label>Eten</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>GHT</label>
            </value>
            <value>
                <fullName>53</fullName>
                <label>Google</label>
            </value>
            <value>
                <fullName>64</fullName>
                <label>Honor</label>
            </value>
            <value>
                <fullName>47</fullName>
                <label>HP</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>HTC</label>
            </value>
            <value>
                <fullName>36</fullName>
                <label>Huawei</label>
            </value>
            <value>
                <fullName>63</fullName>
                <label>Lenovo</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>LG</label>
            </value>
            <value>
                <fullName>62</fullName>
                <label>Logicom</label>
            </value>
            <value>
                <fullName>59</fullName>
                <label>Meizu</label>
            </value>
            <value>
                <fullName>48</fullName>
                <label>Mitac</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Motorola</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>NEC</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Nokia</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Samsung</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>T-Mobile</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Marque_du_magnetoscope__c.field-meta.xml
<CustomField>
    <fullName>Marque_du_magnetoscope__c</fullName>
    <label>Marque du magnétoscope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1114</fullName>
                <label>?</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>A.R. SYSTEMS</label>
            </value>
            <value>
                <fullName>1212</fullName>
                <label>ACER</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>AGASHI</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>AGEF</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>AIKO</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>AIWA</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>AKAI</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>AKIBA</label>
            </value>
            <value>
                <fullName>1201</fullName>
                <label>AKITA</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>ALBA</label>
            </value>
            <value>
                <fullName>956</fullName>
                <label>ALTUS</label>
            </value>
            <value>
                <fullName>1197</fullName>
                <label>AMOI</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>AMPLIVISION</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>AMSTRAD</label>
            </value>
            <value>
                <fullName>951</fullName>
                <label>ANEX</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>ANITECH</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>ARDEM</label>
            </value>
            <value>
                <fullName>36</fullName>
                <label>ASUKA</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>AUDIOSONIC</label>
            </value>
            <value>
                <fullName>911</fullName>
                <label>AUTRE MARQUE</label>
            </value>
            <value>
                <fullName>1211</fullName>
                <label>AYA</label>
            </value>
            <value>
                <fullName>46</fullName>
                <label>BANG &amp; OLUFSEN</label>
            </value>
            <value>
                <fullName>1190</fullName>
                <label>BARCO</label>
            </value>
            <value>
                <fullName>48</fullName>
                <label>BASIC LINE</label>
            </value>
            <value>
                <fullName>1130</fullName>
                <label>BAZIN</label>
            </value>
            <value>
                <fullName>53</fullName>
                <label>BEKO</label>
            </value>
            <value>
                <fullName>55</fullName>
                <label>BEST</label>
            </value>
            <value>
                <fullName>1177</fullName>
                <label>BISONIC</label>
            </value>
            <value>
                <fullName>58</fullName>
                <label>BLACK STAR</label>
            </value>
            <value>
                <fullName>558</fullName>
                <label>LG</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Modele_de_console_de_jeux__c.field-meta.xml
<CustomField>
    <fullName>Modele_de_console_de_jeux__c</fullName>
    <label>Modèle de console de jeux</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>35</fullName>
                <label>MICROSOFT - XBOX One</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>SONY - PLAYSTATION 4</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>MICROSOFT - XBOX 360</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>SONY - PLAYSTATION 3</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>NINTENDO - Wii U</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>NINTENDO - Wii</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>MICROSOFT - XBOX</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>AUTRES MODELES</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Poste_TV__c.field-meta.xml
<CustomField>
    <fullName>Poste_TV__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Poste TV</label>
    <referenceTo>Equipements_du_foyer__c</referenceTo>
    <relationshipLabel>Périphériques</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>7</fullName>
                <label>Ordinateur fixe</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Ordinateur portable</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Tablette</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Mobile</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Poste TV</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Lecteur DVD</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Console de jeux</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Magnétoscope</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Décodeur</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Divers</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Box</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Caster</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Objet Connecté</label>
            </value>
            <value>
                <fullName>17</fullName>
                <isActive>false</isActive>
                <label>Autre équipement</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/recordTypes/Devices.recordType-meta.xml
<RecordType>
    <fullName>Devices</fullName>
    <active>true</active>
    <label>Devices</label>
</RecordType>

force-app/main/default/classes/AP02_EquipementDuFoyer_Test.cls
/*
* @Auteur : Bastien PINARD
* @date: 26/08/2022
* @ Description : 
- A l'ajout d'un equipement lié à un poste Tv on calcule le nom de cette equipement en fonction du nom du poste tv

-à la suppression d'un poste tv on recalcule le nom de de tous les equipements liés aux postes tv encore existant pour le foyer donné


* @Class: AP02_EquipementDuFoyer
* @Coverage: 92%
History
* <Date of modification> 			<Author> 			<Description of modification>
* 		22/03/23					Marliat D.		     Nommage des accessoires 
* 		21/09/2023				Claire VEHRLE				TMASF-528
* @Coverage: 98%
*/
@isTest
public with sharing class AP02_EquipementDuFoyer_Test {
    
    @isTest
    public static void insertPeripherique(){
                
        Id devPeriRecordTypeId =Schema.SObjectType.Equipements_du_foyer__c.getRecordTypeInfosByName().get(Label.EQPF_RecordType_Peripheriques).getRecordTypeId();
        Id devPosteTVRecordTypeId =Schema.SObjectType.Equipements_du_foyer__c.getRecordTypeInfosByName().get(Label.EQPF_RecordType_PosteTV).getRecordTypeId();
        
        Account acc = new Account();
        acc.Name = 'toto';
        insert acc;
        
        Equipements_du_foyer__c eq1 = new Equipements_du_foyer__c();
        eq1.Foyer__c = acc.Id;
        eq1.Name = 'azer';
        eq1.RecordTypeId = devPosteTVRecordTypeId;
        insert eq1;
        
        Equipements_du_foyer__c eq2 = new Equipements_du_foyer__c();
        eq2.Foyer__c = acc.Id;
        eq2.Name = 'azer';
        eq2.Type__c = Label.EQF_Type_Console_De_Jeux;
        eq2.Poste_TV__c=eq1.Id;
        eq2.RecordTypeId = devPeriRecordTypeId;
        eq2.Modele_de_console_de_jeux__c='28';
        insert eq2;
        
        Equipements_du_foyer__c eq3 = new Equipements_du_foyer__c();
        eq3.Foyer__c = acc.Id;
        eq3.Name = 'azer';
        eq3.Type__c = Label.EQF_Type_Magnetoscope;
        eq3.Poste_TV__c=eq1.Id;
        eq3.RecordTypeId = devPeriRecordTypeId;
        eq3.Marque_du_magnetoscope__c='558'; 
        insert eq3;
        
        //MD
        Equipements_du_foyer__c eq4 = new Equipements_du_foyer__c();
        eq4.Foyer__c = acc.Id;
        eq4.Name = 'Divers';
        eq4.Type__c = Label.EQF_Type_Divers;
        eq4.Poste_TV__c=eq1.Id;
        eq4.RecordTypeId = devPeriRecordTypeId;
        insert eq4;
                   
        //MD
        Equipements_du_foyer__c eq6 = new Equipements_du_foyer__c();
        eq6.Foyer__c = acc.Id;
        eq6.Name = 'DVD';
        eq6.Type__c = Label.EQF_Type_Lecteur_DVD;
        eq6.Poste_TV__c=eq1.Id;
        eq6.RecordTypeId = devPeriRecordTypeId;
        insert eq6;            
        
        Equipements_du_foyer__c eq7 = new Equipements_du_foyer__c();
        eq7.Foyer__c = acc.Id;
        eq7.Name = 'Test';
        eq7.Type__c = Label.EQF_Type_Caster;
        eq7.Poste_TV__c=eq1.Id;
        eq7.RecordTypeId = devPeriRecordTypeId;
        insert eq7;    
        
        List<Equipements_du_foyer__c> testEquipementFoyer = [SELECT Id , Name FROM Equipements_du_foyer__c WHERE Name = 'Console Poste 0 SONY - PLAYSTATION 3'];
        System.assertEquals(1, testEquipementFoyer.size()); 

  } 
    @isTest
    public static void insertDevice(){
        Id devDeviRecordTypeId =Schema.SObjectType.Equipements_du_foyer__c.getRecordTypeInfosByName().get('Devices').getRecordTypeId();
        Id devPosteTVRecordTypeId =Schema.SObjectType.Equipements_du_foyer__c.getRecordTypeInfosByName().get('Poste TV').getRecordTypeId();
        
        Account acc = new Account();
        acc.Name = 'toto';
        insert acc;
        
        Equipements_du_foyer__c eq2 = new Equipements_du_foyer__c();
        eq2.Foyer__c = acc.Id;
        eq2.Name = 'azer';
        eq2.Type__c = Label.EQF_Type_Smartphone;
        eq2.RecordTypeId = devDeviRecordTypeId;
        eq2.Marque_de_telephone__c ='15'; //MD
        insert eq2;
        
        Equipements_du_foyer__c eq3 = new Equipements_du_foyer__c();
        eq3.Foyer__c = acc.Id;
        eq3.Name = 'azer';
        eq3.Type__c =Label.EQF_Type_OrdinateurPortable;
        eq3.RecordTypeId = devDeviRecordTypeId;
        eq3.Marque_d_ordinateur__c ='1'; //MD
        insert eq3;
        
        //MD
        Equipements_du_foyer__c eq4 = new Equipements_du_foyer__c();
        eq4.Foyer__c = acc.Id;
        eq4.Name = 'Ord fixe';
        eq4.Type__c= Label.EQF_Type_OrdinateurFixe;
        eq4.RecordTypeId = devDeviRecordTypeId;
        eq4.Marque_d_ordinateur__c ='1'; 
        insert eq4;
        
        //MD
        Equipements_du_foyer__c eq5 = new Equipements_du_foyer__c();
        eq5.Foyer__c = acc.Id;
        eq5.Name = 'Tab';
        eq5.Type__c = Label.EQF_Type_Tablette;
        eq5.Marque_Tablette__c = '1';
        eq5.RecordTypeId = devDeviRecordTypeId;
        insert eq5;        
        
        List<Equipements_du_foyer__c> testEquipementFoyer = [SELECT Id , Name FROM Equipements_du_foyer__c WHERE Name = 'Mobile Samsung'];
        System.assertEquals(1, testEquipementFoyer.size()); 
    }
    
    @isTest
    public static void deleteUpdatePeripheriqueName(){
        Id devPeriRecordTypeId =Schema.SObjectType.Equipements_du_foyer__c.getRecordTypeInfosByName().get('Périphériques').getRecordTypeId();
        Id devPosteTVRecordTypeId =Schema.SObjectType.Equipements_du_foyer__c.getRecordTypeInfosByName().get('Poste TV').getRecordTypeId();
        
        Account acc = new Account();
        acc.Name = 'toto';
        insert acc;
        
        Equipements_du_foyer__c eq1 = new Equipements_du_foyer__c();
        eq1.Foyer__c = acc.Id;
        eq1.Name = 'azer';
        eq1.RecordTypeId = devPosteTVRecordTypeId;
        insert eq1;
        
        Equipements_du_foyer__c eq2 = new Equipements_du_foyer__c();
        eq2.Foyer__c = acc.Id;
        eq2.Name = 'azer';
        eq2.Type__c = Label.EQF_Type_Console_De_Jeux;
        eq2.Poste_TV__c=eq1.Id;
        eq2.RecordTypeId = devPeriRecordTypeId;
        eq2.Modele_de_console_de_jeux__c='28';
        insert eq2;
               
        Equipements_du_foyer__c eq3 = new Equipements_du_foyer__c();
        eq3.Foyer__c = acc.Id;
        eq3.Name = 'azer';
        eq3.RecordTypeId = devPosteTVRecordTypeId;
        insert eq3;
        
        Equipements_du_foyer__c eq4 = new Equipements_du_foyer__c();
        eq4.Foyer__c = acc.Id;
        eq4.Name = 'azer';
        eq4.Type__c = Label.EQF_Type_Console_De_Jeux;
        eq4.Poste_TV__c=eq3.Id;
        eq4.RecordTypeId = devPeriRecordTypeId;
        eq4.Modele_de_console_de_jeux__c='35';
        insert eq4;

        delete eq1;
        
        List<Equipements_du_foyer__c> testEquipementFoyer = [SELECT Id , Name FROM Equipements_du_foyer__c WHERE Name = 'Console Poste 0 MICROSOFT - XBOX One'];
        System.assertEquals(1, testEquipementFoyer.size()); 
    }
    
    @isTest
    public static void UpdateNameTest(){
 Id devPeriRecordTypeId =Schema.SObjectType.Equipements_du_foyer__c.getRecordTypeInfosByName().get(Label.EQPF_RecordType_Peripheriques).getRecordTypeId();
  Id devPosteTVRecordTypeId =Schema.SObjectType.Equipements_du_foyer__c.getRecordTypeInfosByName().get(Label.EQPF_RecordType_PosteTV).getRecordTypeId();
               
        Account acc = new Account();
        acc.Name = 'toto';
        insert acc;
        
        Equipements_du_foyer__c eq1 = new Equipements_du_foyer__c();
        eq1.Foyer__c = acc.Id;
        eq1.Name = 'azera';
        eq1.Fournisseur__c='3';
        eq1.RecordTypeId = devPosteTVRecordTypeId;
        insert eq1;
        
        eq1.Fournisseur__c='4';
        update eq1;
        
    }
}