force-app/main/default/objects/Equipements_du_foyer__c/Equipements_du_foyer__c.object-meta.xml
<CustomObject>
    <label>Equipement du foyer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;équipement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipements du foyer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Poste_TV__c.field-meta.xml
<CustomField>
    <fullName>Poste_TV__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Poste TV</label>
    <referenceTo>Equipements_du_foyer__c</referenceTo>
    <relationshipLabel>Périphériques</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AP03_EquipementDuFoyer.cls
/*
* @Auteur : Bastien Pinard
* @date: 30/08/2022
* @ Description :
* @TestClass: AP03_EquipementDuFoyer_Test
* @Coverage: 100%
History
* <Date of modification> 		<Author> 			<Description of modification>
*/

public with sharing class AP03_EquipementDuFoyer {
    public static void DeleteEquipements(List<Equipements_du_foyer__c> listEquipementFoyer){
        System.debug('bastien listEquipementFoyer : '+listEquipementFoyer);
        Id peripheriqueRecordTypeId =Schema.SObjectType.Equipements_du_foyer__c.getRecordTypeInfosByName().get('Périphériques').getRecordTypeId();
        Id devRecordTypeId =Schema.SObjectType.Equipements_du_foyer__c.getRecordTypeInfosByName().get('Poste TV').getRecordTypeId();
        Set<Id> equipementsId = new Set<Id>();
        for(Equipements_du_foyer__c eq : listEquipementFoyer){
            if(eq.RecordTypeId==devRecordTypeId){
                equipementsId.add(eq.Id);
            }
        }

        if(equipementsId.size()>0){
            List<Equipements_du_foyer__c> listPeripheriquesToDelete = [
                SELECT Id
                FROM Equipements_du_foyer__c
                WHERE Poste_TV__c IN :equipementsId
                AND RecordTypeId =:peripheriqueRecordTypeId
            ];

            if(listPeripheriquesToDelete.size()>0){
                delete listPeripheriquesToDelete;
            }
        }
    }
}