force-app/main/default/objects/Equipements_du_foyer__c/Equipements_du_foyer__c.object-meta.xml
<CustomObject>
    <label>Equipement du foyer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;équipement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipements du foyer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Equipements du foyer</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Equipements du foyer</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer_Paneliste_ExtId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>Foyer_Paneliste_ExtId_SIPanel__c</fullName>
    <description>&quot;(UID) c&apos;est l&apos;id unique generé par SIPANEL du foyer panéliste 
Ce champ sert a faire l&apos;Upsert du foyer panéliste&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Foyer_Paneliste_ExtId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Statut_Device_Equipement_Mesure__c/Statut_Device_Equipement_Mesure__c.object-meta.xml
<CustomObject>
    <label>Device rattaché à l&apos;équipement de mesure</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Numéro de Statut Device Equipement de Me</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Device rattaché à l&apos;équipement de mesure</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Statut_Device_Equipement_Mesure__c/fields/Equipement_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Equipement_du_foyer__c</fullName>
    <label>Équipement du foyer</label>
    <referenceTo>Equipements_du_foyer__c</referenceTo>
    <relationshipName>Statuts_Device_Equipement_de_Mesure</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AP01_Statut_Device.cls
/*
* @date: 09/08/2023
* @ Description : Appel flux mulesoft. Création/Modification Statut Device 
* @version 1.00   
* @Auteur Claire VEHRLE
* @TestClass: AP01_Statut_Device_Test
* @Coverage: --%
History
* <Date of modification> <Author> 	<Description of modification>
*/
public class AP01_Statut_Device {
    
    public static void creationStatutDeviceNielsen(Set<Id> eqtFoyerIdList) {
        List<String> foyerPanelisteIdToSend = new List<String>();
        List<foyer_paneliste__c> foyerPanList = new List<Foyer_Paneliste__c>();
        List<Equipements_du_foyer__c> foyerList = new List<Equipements_du_foyer__c>();
        Set<Id> foyerIdSet = new Set<Id>();
        

        foyerList= [SELECT Id, foyer__c FROM Equipements_du_foyer__c WHERE id IN :eqtFoyerIdList];
        for(Equipements_du_foyer__c eqtFoyer:foyerList) {
            foyerIdSet.add(eqtFoyer.foyer__c);
        }
        
        foyerPanList= [SELECT Id, Foyer_Paneliste_ExtId_SIPanel__c FROM Foyer_Paneliste__c WHERE referentiel_panel__r.type_de_panel__c = :Label.RFP_TypePanel_Mesure_Plateforme AND foyer__c IN :foyerIdSet];
        for(Foyer_Paneliste__c foyerPan:foyerPanList) {
            foyerPanelisteIdToSend.add(foyerPan.Foyer_Paneliste_ExtId_SIPanel__c);
        }
        callMulesoft(foyerPanelisteIdToSend);
    }
    
    public static void updateStatutDeviceNielsen(List<Statut_Device_Equipement_Mesure__c> StatutDeviceList, Map<Id,Statut_Device_Equipement_Mesure__c> mapOldStatutDeviceList) {
        Set<Id> eqtFoyerId = new Set<Id>();
        List<Schema.FieldSetMember> fields = Schema.SObjectType.Statut_Device_Equipement_Mesure__c.fieldSets.Champ_envoyes_Nielsen.getFields();
        
        for(Statut_Device_Equipement_Mesure__c statutDevice : StatutDeviceList){
            for(Schema.FieldSetMember statutDeviceField : fields) {
                //Vérifier si l'un des champs à envoyer à Mulesoft a été mis à jour
                if(statutDevice.get(statutDeviceField.getFieldPath()) != mapOldStatutDeviceList.get(statutDevice.Id).get(statutDeviceField.getFieldPath())) {
                    eqtFoyerId.add(statutDevice.Equipement_du_foyer__c); // to be modified accordingly
                }
            }
        }
        
        if(eqtFoyerId.size() > 0 && eqtFoyerId!= null){
            creationStatutDeviceNielsen(eqtFoyerId);
        }
           
    }
    
    @future(callout=true)
    public static void callMulesoft(List<String> foyerPanelisteIdToSend) {
        
        
        for(String idValue :foyerPanelisteIdToSend){
            String endpoint = 'callout:Mulesoft_experience_API/' +'api/'+label.Mulesoft_Xapp_MM_Sync_Nielsen+'/v1/'+label.Mulesoft_expAPI_houseHolds + '/' + idValue; 
            String method = 'POST';
            
            Http http = new Http();
            HttpRequest req = new HttpRequest();
            req.setHeader('x-client-id', label.Mulesoft_expAPI_clientId);
            req.setHeader('x-client-secret', label.Mulesoft_expAPI_clientSecret);
            req.setHeader('Accept', 'application/json');
            req.setHeader('Content-Type', 'application/json');
            req.setEndpoint(endpoint);
            req.setMethod(method);
            JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
            gen.writeStringField('description', 'test');
            gen.writeEndObject();
            req.setBody(gen.getAsString());
            
            req.setEndpoint(endpoint);
            req.setMethod(method);
            
            HTTPResponse res = http.send(req);
            System.debug('***Http response: ' + res.getBody());
        }
    }

}