force-app/main/default/objects/Equipements_du_foyer__c/Equipements_du_foyer__c.object-meta.xml
<CustomObject>
    <label>Equipement du foyer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;équipement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipements du foyer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Equipements du foyer</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Equipements du foyer</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer_Paneliste_ExtId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>Foyer_Paneliste_ExtId_SIPanel__c</fullName>
    <description>&quot;(UID) c&apos;est l&apos;id unique generé par SIPANEL du foyer panéliste 
Ce champ sert a faire l&apos;Upsert du foyer panéliste&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Foyer_Paneliste_ExtId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP04_EquipementDuFoyer.cls
/*
* @date: 10/08/2023
* @ Description : Appel flux mulesoft. Modification/Suppression Equipement du foyer
* @version 1.00   
* @Auteur Claire VEHRLE
* @TestClass: AP04_EquipementDuFoyer_Test
* @Coverage: --%
History
* <Date of modification> <Author> 	<Description of modification>
*/
public class AP04_EquipementDuFoyer {
    
    public static void updateEquipementFoyer(List<Equipements_du_foyer__c> eqtFoyerList, Map<Id,Equipements_du_foyer__c> mapOldeqtFoyerList) {
        Set<Id> foyerIdList = new Set<Id>();
        List<String> foyerPanelisteIdToSend = new List<String>();
        List<foyer_paneliste__c> foyerPanList = new List<Foyer_Paneliste__c>();
        List<Schema.FieldSetMember> fields = Schema.SObjectType.Equipements_du_foyer__c.fieldSets.Champs_envoyes_Nielsen.getFields();
        
        for(Equipements_du_foyer__c eqtFoyer : eqtFoyerList){
            for(Schema.FieldSetMember eqtFoyerField : fields) {
                //Vérifier si l'un des champs à envoyer à Mulesoft a été mis à jour
                if(eqtFoyer.get(eqtFoyerField.getFieldPath()) != mapOldeqtFoyerList.get(eqtFoyer.Id).get(eqtFoyerField.getFieldPath())) {
                    foyerIdList.add(eqtFoyer.Id); // to be modified accordingly
                }
            }
        }
        
        foyerPanList= [SELECT Id, Foyer_Paneliste_ExtId_SIPanel__c FROM Foyer_Paneliste__c WHERE referentiel_panel__r.type_de_panel__c = :Label.RFP_TypePanel_Mesure_Plateforme AND foyer__c IN :foyerIdList];
        for(Foyer_Paneliste__c foyerPan:foyerPanList) {
            foyerPanelisteIdToSend.add(foyerPan.Foyer_Paneliste_ExtId_SIPanel__c);
        }
        
        if(foyerIdList.size() > 0 && foyerIdList!= null){
            callMulesoft(foyerPanelisteIdToSend);
        }
           
    }
    
    public static void suppressionEqtFoyer(Set<Id> foyerIdList) {
        List<foyer_paneliste__c> foyerPanList = new List<Foyer_Paneliste__c>();
        List<String> foyerPanelisteIdToSend = new List<String>();
        
        foyerPanList= [SELECT Id FROM Foyer_Paneliste__c WHERE referentiel_panel__r.type_de_panel__c = :Label.RFP_TypePanel_Mesure_Plateforme AND foyer__c IN :foyerIdList];
        for(Foyer_Paneliste__c foyerPan:foyerPanList) {
            foyerPanelisteIdToSend.add(foyerPan.Id);
        }
        
        if(foyerIdList.size() > 0 && foyerIdList!= null){
            callMulesoft(foyerPanelisteIdToSend);
        }
    }
    
    @future(callout=true)
    public static void callMulesoft(List<String> foyerPanelisteIdToSend) {
        
        
        for(String idValue :foyerPanelisteIdToSend){
            String endpoint = 'callout:Mulesoft_experience_API/' +'api/'+label.Mulesoft_Xapp_MM_Sync_Nielsen+'/v1/'+label.Mulesoft_expAPI_houseHolds + '/' + idValue; 
            String method = 'POST';
            
            Http http = new Http();
            HttpRequest req = new HttpRequest();
            req.setHeader('x-client-id', label.Mulesoft_expAPI_clientId);
            req.setHeader('x-client-secret', label.Mulesoft_expAPI_clientSecret);
            req.setHeader('Accept', 'application/json');
            req.setHeader('Content-Type', 'application/json');
            req.setEndpoint(endpoint);
            req.setMethod(method);
            JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
            gen.writeStringField('description', 'test');
            gen.writeEndObject();
            req.setBody(gen.getAsString());
            
            req.setEndpoint(endpoint);
            req.setMethod(method);
            
            HTTPResponse res = http.send(req);
            System.debug('***Http response: ' + res.getBody());
        }
    }
}