force-app/main/default/objects/Appel__c/Appel__c.object-meta.xml
<CustomObject>
    <description>Objet pour lancer les appels webservice avaya (preparelistOfCalls)</description>
    <label>Appel</label>
    <nameField>
        <displayFormat>Appel-{0000}</displayFormat>
        <label>Appel Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appel__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appels</relationshipLabel>
    <relationshipName>Appels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appel__c/fields/Campagne_Id_Avaya__c.field-meta.xml
<CustomField>
    <fullName>Campagne_Id_Avaya__c</fullName>
    <formula>Campaign__r.CampagneID_Avaya__c</formula>
    <label>Campagne Id Avaya</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appel__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Appels</relationshipLabel>
    <relationshipName>Appels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Sended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appel__c/fields/Telephone1__c.field-meta.xml
<CustomField>
    <fullName>Telephone1__c</fullName>
    <formula>IF(Account__r.Contact_principal__r.MobilePhone !=null,&apos;+33&apos;+TRIM(right(Account__r.Contact_principal__r.MobilePhone , (LEN( Account__r.Contact_principal__r.MobilePhone) - 1))),null)</formula>
    <inlineHelpText>Numéro du contact principal du foyer</inlineHelpText>
    <label>Téléphone1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appel__c/fields/Telephone2__c.field-meta.xml
<CustomField>
    <fullName>Telephone2__c</fullName>
    <formula>IF(Account__r.Numero_de_telephone_fixe__c !=null,&apos;+33&apos;+TRIM(right(Account__r.Numero_de_telephone_fixe__c , (LEN( Account__r.Numero_de_telephone_fixe__c) - 1))),null)</formula>
    <inlineHelpText>Numéro de fix du foyer</inlineHelpText>
    <label>Téléphone2</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Temps_dattente__c.field-meta.xml
<CustomField>
    <fullName>Temps_dattente__c</fullName>
    <defaultValue>30</defaultValue>
    <inlineHelpText>Secondes</inlineHelpText>
    <label>T&apos;emps d&apos;attente</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Batch022_CreateAvayaCalls.cls
/**
 * @description       : 
 * @author            : Anes BOUZOUINA
 * @group             : 
 * @last modified on  : 11-22-2022
 * @last modified by  : Anes BOUZOUINA
**/
global class Batch022_CreateAvayaCalls implements Database.Batchable<sObject>, Database.AllowsCallouts{ 
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        system.debug('start');
        String query='select  Campagne_Id_Avaya__c, Telephone1__c, Telephone2__c,account__c,Campaign__r.Temps_dattente__c from appel__c WHERE Createddate= today and status__c=\'Created\'';
       
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Appel__c> scope){
        system.debug(' execute');
        system.debug(' scope '+ scope);
        //limiter le scope a 100
        // le statu est active pour creer des nouvels appels
        AP09_WebService_Avaya.PrepareListOfCalls(scope,'ACTIVE');

        for(appel__c appItr : scope){
            appItr.status__c='Sended';
        }
        update scope;
       
    }
    
    global void finish(Database.BatchableContext BC){
        
    }


}