force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_de_produit__c/Stock_de_produit__c.object-meta.xml
<CustomObject>
    <label>Stock de produit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks de produits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_de_produit__c/fields/Produit__c.field-meta.xml
<CustomField>
    <fullName>Produit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks de produits</relationshipLabel>
    <relationshipName>Stocks_de_produits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_de_produit__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gestion des Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Stocks de produits</relationshipLabel>
    <relationshipName>Stocks_de_produits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_de_produit__c/fields/Valeur_du_stock__c.field-meta.xml
<CustomField>
    <fullName>Valeur_du_stock__c</fullName>
    <label>Valeur du stock</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AP03_StockProduit.cls
/*
* @author: Claire VEHRLE
* @date: 06/07/2023 
* @ Description: Classe appelé par le Trigger SuiviStockSAVAfterInsert
* @TestClass: AP03_StockProduit_Test
* @Coverage: --%
* History
* <Date of modification>   		<Author>   		 <Description of modification>
*
* */
public class AP03_StockProduit {

    public static Map<Stock_de_Produit__c, Id> insertOrUpdate(List<Stock_de_Produit__c> stockProduitList) {
        List<Stock_de_Produit__c> enregistrementExistant = new List<Stock_de_Produit__c>();
        List<Stock_de_Produit__c> stockDeProduitToUpdate = new List<Stock_de_Produit__c>();
        Map<Stock_de_Produit__c, Id> StockProduitId = new Map<Stock_de_Produit__c, Id>();
        
        enregistrementExistant = [SELECT Id, name, Produit__c, Stock__c, Quantite__c, Valeur_du_stock__c  FROM Stock_de_Produit__c];
        
        for(Stock_de_Produit__c stprdt:stockProduitList) {
            for(Stock_de_Produit__c stprdtExistant:enregistrementExistant) {
                if((stprdt.Produit__c == stprdtExistant.Produit__c) && (stprdt.Stock__c == stprdtExistant.Stock__c)) {
                    stprdtExistant.Quantite__c = stprdt.Quantite__c;
                    stprdtExistant.Valeur_du_stock__c = stprdt.Valeur_du_stock__c;
                    stockDeProduitToUpdate.add(stprdtExistant);
                    StockProduitId.put(stprdt, stprdtExistant.Id);
                }
            }
        }
        
        return StockProduitId;
    }
}