force-app/main/default/objects/Contact/fields/Activite_actuelle__c.field-meta.xml
<CustomField>
    <fullName>Activite_actuelle__c</fullName>
    <label>Activité actuelle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
                <label>Au chômage ayant déjà travaillé</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Exerce une activité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>À la rechercher d&apos;un 1er emploi</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Retraite ou pré-retraite</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Congé maternité</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Congé parental</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Maladie longue durée</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Femme ou homme au foyer</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Autre cas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Autre_activite__c.field-meta.xml
<CustomField>
    <fullName>Autre_activite__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Autre activité</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Ouvrier non qualifié</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Ouvrier qualifié</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Employé</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Technicien</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Agent de maîtrise</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Cadre</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>NSP/Refus</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CSP42__c.field-meta.xml
<CustomField>
    <fullName>CSP42__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code profession CSP42</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CSP4__c.field-meta.xml
<CustomField>
    <fullName>CSP4__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code profession CSP4</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_de_suppression__c.field-meta.xml
<CustomField>
    <fullName>Date_de_suppression__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de suppression</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequence_de_connexion_mobile__c.field-meta.xml
<CustomField>
    <fullName>Frequence_de_connexion_mobile__c</fullName>
    <label>Fréquence de connexion mobile</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequence_d_utilisation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequence_de_connexion_ordinateur__c.field-meta.xml
<CustomField>
    <fullName>Frequence_de_connexion_ordinateur__c</fullName>
    <label>Fréquence de connexion ordinateur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequence_d_utilisation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequence_de_connexion_tablette__c.field-meta.xml
<CustomField>
    <fullName>Frequence_de_connexion_tablette__c</fullName>
    <label>Fréquence de connexion tablette</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequence_d_utilisation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Lien_de_parente_stat__c.field-meta.xml
<CustomField>
    <fullName>Lien_de_parente_stat__c</fullName>
    <label>Lien de parenté stat</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Couple</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Parent</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Enfant</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Famille</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Isolé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Lien_parente__c.field-meta.xml
<CustomField>
    <fullName>Lien_parente__c</fullName>
    <label>Lien parenté</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Chef de famille</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Conjoint</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Enfant</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Ascendant</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Autre</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Nombre_d_heures_travaillees__c.field-meta.xml
<CustomField>
    <fullName>Nombre_d_heures_travaillees__c</fullName>
    <label>Nombre d&apos;heures travaillées</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Nombre_de_jour_de_presence_par_mois__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_jour_de_presence_par_mois__c</fullName>
    <label>Nombre de jour de présence par mois</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Presence_permanente__c.field-meta.xml
<CustomField>
    <fullName>Presence_permanente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Présence permanente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Profession__c.field-meta.xml
<CustomField>
    <fullName>Profession__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Profession</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Secteur_d_activite__c.field-meta.xml
<CustomField>
    <fullName>Secteur_d_activite__c</fullName>
    <label>Secteur d&apos;activité</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Etat ou collectivité locale</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Entreprise privée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Sexe__c.field-meta.xml
<CustomField>
    <fullName>Sexe__c</fullName>
    <label>Sexe</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>M</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>F</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Temps_plein__c.field-meta.xml
<CustomField>
    <fullName>Temps_plein__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Temps plein</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Membre</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Invité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Non panéliste</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Type_d_emploi__c.field-meta.xml
<CustomField>
    <fullName>Type_d_emploi__c</fullName>
    <label>Type d&apos;emploi</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Salarié</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>À son compte</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Profession__c.field-meta.xml
<CustomField>
    <fullName>Profession__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Profession</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/recordTypes/AIP.recordType-meta.xml
<RecordType>
    <fullName>AIP</fullName>
    <active>true</active>
    <label>AIP</label>
</RecordType>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Frequence_de_connexion_mobile__c.field-meta.xml
<CustomField>
    <fullName>Frequence_de_connexion_mobile__c</fullName>
    <label>Fréquence de connexion mobile</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tous les jours</fullName>
            </value>
            <value>
                <fullName>Presque tous les jours</fullName>
            </value>
            <value>
                <fullName>1 à 2 fois par semaine</fullName>
            </value>
            <value>
                <fullName>1 à 3 fois par mois</fullName>
            </value>
            <value>
                <fullName>Moins souvent</fullName>
            </value>
            <value>
                <fullName>Jamais</fullName>
            </value>
            <value>
                <fullName>NSP/Refus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Frequence_de_connexion_ordinateur__c.field-meta.xml
<CustomField>
    <fullName>Frequence_de_connexion_ordinateur__c</fullName>
    <label>Fréquence de connexion ordinateur</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tous les jours</fullName>
            </value>
            <value>
                <fullName>Presque tous les jours</fullName>
            </value>
            <value>
                <fullName>1 à 2 fois par semaine</fullName>
            </value>
            <value>
                <fullName>1 à 3 fois par mois</fullName>
            </value>
            <value>
                <fullName>Moins souvent</fullName>
            </value>
            <value>
                <fullName>Jamais</fullName>
            </value>
            <value>
                <fullName>NSP/Refus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Frequence_de_connexion_tablette__c.field-meta.xml
<CustomField>
    <fullName>Frequence_de_connexion_tablette__c</fullName>
    <label>Fréquence de connexion tablette</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tous les jours</fullName>
            </value>
            <value>
                <fullName>Presque tous les jours</fullName>
            </value>
            <value>
                <fullName>1 à 2 fois par semaine</fullName>
            </value>
            <value>
                <fullName>1 à 3 fois par mois</fullName>
            </value>
            <value>
                <fullName>Moins souvent</fullName>
            </value>
            <value>
                <fullName>Jamais</fullName>
            </value>
            <value>
                <fullName>NSP/Refus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Nombre_de_jour_de_presence_par_mois__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_jour_de_presence_par_mois__c</fullName>
    <label>Nombre de jour de présence par mois</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invité</fullName>
            </value>
            <value>
                <fullName>Membre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Frequence_d_utilisation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tous les jours</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Presque tous les jours</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>1 à 2 fois par semaine</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>1 à 3 fois par mois</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Moins souvent</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Jamais</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>NSP/Refus</label>
    </customValue>
    <masterLabel>Fréquence d&apos;utilisation</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP01_MembreDuFoyer.cls
/*
* @author: Khaled Hammoudeh
* @date: 22/01/2021
* @ Description: cette classe met à jour le membre du foyer dans Si-Panel lorsque ce membre du foyer (unitaire) est mis à jour dans Salesforce
* @TestClass: AP01_MembreDuFoyer_Test
* @Coverage: 100%
* History
* <Date of modification>   <Author>    <Description of modification>
*  11.03.2021				  MZ		Modified getContactFromSipanelFuture and getContactFromSipanel to wait for the HTTP response
*										and return the error details to the flow
* Jerome HE 27/04/22 Envoi des individus vers SiPanel + envoie du contact et des individus panéliste si les foyer pan du contact sont AIP
* 20/05/2022			Ayoub GHAMMAZ	Modification du endpoint
* 15/12/2022			Marliatou DIALLO  Envoi des contacts pour MAJ des statuts dans SIPanel après chute 
*/
public class AP01_MembreDuFoyer {
    /*
* @author: Maribelle ZARAZIR
* @ Description: Méthode qui vérifie toutes les conditions avant d'envoyer les contacts vers SI Panel (dans les 2 cas : création et mise à jour)
*/
    // A décommenter lorsque la liason avec SIPanel sera ok
    public static void checkSendContactToSIPanel(List<Contact> listContact, Map<Id,Contact> mapOldContacts) {
        Set<String> setExtIds = new Set<String>();
        List<Schema.FieldSetMember> fields = Schema.SObjectType.Contact.fieldSets.Champs_envoyes_vers_SIPanel.getFields();
        List<Id> compoFoyerId = new List<Id>();
        for(Contact compoFoyer: listContact) {
            compoFoyerId.add(compoFoyer.Id);
        }
            //Ajouter les champs de l'ensemble de champ
        List<Contact> listCompoFoyer = [SELECT Id, Name, LastName, FirstName, Lien_de_parente_stat__c, Lien_parente__c, Birthdate, Sexe__c, Email, MobilePhone, 
                                        Presence_permanente__c, Nombre_de_jour_de_presence_par_mois__c, Frequence_de_connexion_mobile__c, Date_de_suppression__c,
                                        Frequence_de_connexion_ordinateur__c, Frequence_de_connexion_tablette__c, Type__c, Activite_actuelle__c,
                                        Profession__c, Type_d_emploi__c, Classification__c, Autre_activite__c, Secteur_d_activite__c, Temps_plein__c,
                                        Nombre_d_heures_travaillees__c,CSP42__c,CSP4__c	, Nombre_de_salaries__c, Domaine_d_activite__c, Code_profession__c, Date_d_anonymisation__c,
                                        Age_de_fin_d_etude__c, Niveau_d_etude_en_cours__c, Dernier_diplome_obtenu__c, AccountId, A_anonymiser__c, RecordTypeId
                                        FROM Contact
                                        WHERE Id in : compoFoyerId];
        for(Contact compoFoyer : listCompoFoyer){
            for(Schema.FieldSetMember compoFoyerField : fields) {
                //Vérifier si l'un des champs à envoyer à Mulesoft a été mis à jour
                if(compoFoyer.get(compoFoyerField.getFieldPath()) != mapOldContacts.get(compoFoyer.Id).get(compoFoyerField.getFieldPath())) {
                    setExtIds.add(compoFoyer.Id); // to be modified accordingly
                }
            }
        }
        System.debug('***setExtIds: '  + setExtIds);
        if(setExtIds.size() > 0 && setExtIds!= null){
            sendUpdatedContactToSiPanel(setExtIds);
        }
    }
    
    public static void contactAIPToInsert(List<Contact> compoFoyerPanelAIPList) {
        List<String> foyerPanelisteUId = new List<String>();
        List<String> compoFoyerId = new List<String>();
        List<String> compoFoyerAccountId = new List<String>();
        List<Foyer_paneliste__c> foyerPanelisteAIP = new List<Foyer_paneliste__c>();
        Id recordTypeIdFoyerPanelisteAIP =Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_AIP).getRecordTypeId();
        
        for(Contact compoFoyer: compoFoyerPanelAIPList) {
            compoFoyerAccountId.add(compoFoyer.AccountId);
        }
        
        foyerPanelisteAIP = [SELECT Id, Foyer_Paneliste_ExtId_SIPanel__c, Foyer__c FROM Foyer_paneliste__c 
                             WHERE Foyer__c IN :compoFoyerAccountId
                             AND recordTypeId  = :recordTypeIdFoyerPanelisteAIP];
        for(Foyer_Paneliste__c foyerPan: foyerPanelisteAIP) {
            for (Contact compoFoyer:compoFoyerPanelAIPList) {
                if(foyerPan.Foyer__c == compoFoyer.AccountId) {
                    foyerPanelisteUId.add(foyerPan.Foyer_Paneliste_ExtId_SIPanel__c);
                    compoFoyerId.add(compoFoyer.Id);
                }
            }
        }
        
        sendContactAIPToInsertToSiPanel(foyerPanelisteUId, compoFoyerId);
    }
    
    //Method used to send contact information to SIPanel when a contact is updated
    @future (callout=true)
    public static void sendUpdatedContactToSiPanel(Set<string> listContactIds) {
        //String baseEndpoint = 'callout:Mulesoft_experience_API/' + label.Mulesoft_expAPI_contactPath + '/' 
        //   + label.Mulesoft_expAPI_putContact + '/';
        String method = 'PUT';
        String endpoint;
        Http http = new Http();
        
        List<Contact> listContactsToUpdate = [SELECT Id
                                              FROM Contact
                                              WHERE Id IN :listContactIds];
        
        for(Contact thisContact : listContactsToUpdate) {
            endpoint =  'callout:Mulesoft_experience_API/' +'api/'+ Label.Mulesoft_Xapp_MM_Sync_Sipanel+'/v1/'+ label.Mulesoft_expAPI_indivduPanPath + '/' 
                + thisContact.Id
                + '?flow=' + label.Mulesoft_flow_parameter_sf_to_sipanel;
            
            HttpRequest req = creatHttpRequest(method, endpoint);
            HTTPResponse res = http.send(req);
            
            //Added by MZ for showing the errors on the record - 16/03/2021 - Start
            /*thisContact.Date_du_dernier_appel__c = System.now();
            
            if(res.getStatus() == 'OK') {
                //No errors returned from the system
                thisContact.Appel_OK_KO__c = 'OK';
                thisContact.Message_en_cas_d_erreur__c = '';
                //if date de chute is no longer empty >> continue with the needed flows
                if(thisContact.Date_de_chute_individu__c != null && !thisContact.TECH_IndividuChute__c) {
                    thisContact.TECH_IndividuChute__c = True; //check this field in order to launch the flows related to "Chute d'un individu"
                    
                    system.debug('MZ :: Debug in MBF ap01');
                    system.debug('MZ :: Debug >> thisContact.TECH_IndividuChute__c ' + thisContact.TECH_IndividuChute__c);
                }
            } else {
                //Store the error returned on the record
                if(res.getBody() != null && res.getBody() != '') {
                    Map<String, Object> mapResponse = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
                    Map<String, Object> mapError = (Map<String, Object>) mapResponse.get('error');
                    thisContact.Appel_OK_KO__c = 'KO';
                    thisContact.Message_en_cas_d_erreur__c = 'ERROR CODE : ' + res.getStatusCode();
                    thisContact.Message_en_cas_d_erreur__c += '\nERROR REFERENCE : '
                        + (mapError.containsKey('errorReference')? (String) mapError.get('errorReference') : 'undefined');
                    thisContact.Message_en_cas_d_erreur__c += '\nERROR DESCRIPTION : '
                        + (mapError.containsKey('errorDescription')? (String) mapError.get('errorDescription') : 'undefined');
                }
                
                //if date de chute is no not empty and the tech field is not checked => there was an error synchronizing the change with SI Panel
                //and date de chute should be emptied
                if(thisContact.Date_de_chute_individu__c != null && !thisContact.TECH_IndividuChute__c) {
                    thisContact.Date_de_chute_individu__c = null;
                }
            }*/
        }
        
        /*try {
            update listContactsToUpdate;
        } catch (Exception e) {
            System.debug('exception caught while updating the contacts : ' + e);
        }*/
        //Added by MZ - 16/03/2021 - End
    }
    
    //Method used to send contact information to SIPanel when a contact AIP is insert
    @future (callout=true)
    public static void sendContactAIPToInsertToSiPanel(List<String> foyerPanelisteUId, List<String> compoFoyerId) {
        String method = 'POST';
        String endpoint;
        Http http = new Http();
        
        for(Integer i = 0; i < compoFoyerId.size(); i++) {
            endpoint =  'callout:Mulesoft_experience_API/' +'api/'+ Label.Mulesoft_Xapp_MM_Sync_Sipanel+'/v1/'+ label.Mulesoft_expAPI_indivduPanPath + '/' 
                + compoFoyerId[i]
                + '?flow=' + label.Mulesoft_flow_parameter_sf_to_sipanel 
                + '&uid=' + foyerPanelisteUId[i];
            
            HttpRequest req = creatHttpRequest(method, endpoint);
            HTTPResponse res = http.send(req);
            System.debug(res.getBody());
        }
    }
    
       
    /*@InvocableMethod
    public static List<CalloutResponse> getContactFromSipanel(list<String> listContactExternalIds) {
        
        HTTPResponse resp = getContactFromSipanelFuture(listContactExternalIds);
        
        //If the response contains an error, cast it into a map
        Map<String, Object> mapResponse = new Map<String, Object>();
        Map<String, Object> mapError = new Map<String, Object>();
        if(resp.getStatus() != 'OK') {
            mapResponse = (Map<String, Object>) JSON.deserializeUntyped(resp.getBody());
            mapError = (Map<String, Object>) mapResponse.get('error');
        }
        
        //Build the response that will be sent back to the flow
        List<CalloutResponse> listReturnValue = new List<CalloutResponse>();
        CalloutResponse returnValue = new CalloutResponse();
        returnValue.responseStatus = resp.getStatus();
        returnValue.responseStatusCode = resp.getStatusCode();
        returnValue.responseErrorReference = ( (resp.getStatus() != 'OK') && (mapError.containsKey('errorReference')) ) ? (String) mapError.get('errorReference') : 'undefined';
        //returnValue.responseErrorDescription = ( (resp.getStatus() != 'OK') && (mapError.containsKey('errorDescription')) ) ? (String) mapError.get('errorDescription') : 'undefined';
        //system.debug(returnValue);
        listReturnValue.add(returnValue);
        
        return listReturnValue;
    }*/
    
    /*public static HTTPResponse getContactFromSipanelFuture(list<String> listContactExternalIds)
    {
        string endpoint = 'callout:Mulesoft_experience_API/' + label.Mulesoft_expAPI_contactPath + '/' 
            + label.Mulesoft_expAPI_getContact + '/' + listContactExternalIds[0];
        string method = 'GET';
        HttpRequest req = creatHttpRequest(method, endpoint);
        
        Http http = new Http();
        HTTPResponse res = http.send(req);
        System.debug(res.getBody());
        
        return res;
    }*/
    

    // Added by Marliatou DIALLO - 15/12/2022
    // Start
    @InvocableMethod
    public static List<CalloutResponse> updateContactToSipanel(list<String> listContactIds) {
        String method;
        HTTPResponse resp = sendContactToSipanel(listContactIds);
        
        List<CalloutResponse> listReturnValue = new List<CalloutResponse>();
        CalloutResponse returnValue = new CalloutResponse();
        returnValue.responseStatus = resp.getStatus();
        returnValue.responseStatusCode = resp.getStatusCode();
        system.debug(returnValue);
        listReturnValue.add(returnValue);
        
        return listReturnValue;
    }  
    
    
    public static HTTPResponse sendContactToSipanel(list<String> listContactIdsToSIP) {
        String method;
        String endpoint;
        List<Contact> listContactsToUpdate = new List<Contact>();
        List<Individu_Paneliste__c> listIndPan = new List<Individu_Paneliste__c>();
        List<Foyer_paneliste__c> listfoyerPaneliste = new List <Foyer_paneliste__c>();
        
       
        listContactsToUpdate = [SELECT Id, Name, AccountId, RecordTypeId
                                              FROM Contact
                                              WHERE Id IN :listContactIdsToSIP]; 
              
       listIndPan = [SELECT Id, Name, Foyer_Paneliste__c 
                         					    FROM Individu_Paneliste__c 
                                                WHERE Composition_du_foyer__c =:listContactsToUpdate[0].Id];
       
      
      if(!listIndPan.isEmpty())
        {
  	  		listfoyerPaneliste = [SELECT Id, Name, Foyer_Paneliste_ExtId_SIPanel__c, Foyer__c 
                           FROM Foyer_paneliste__c 
                           WHERE Id =: ListIndPan[0].Foyer_Paneliste__c  
                           AND Foyer__c =: listContactsToUpdate[0].AccountId LIMIT 1];
        }
        else{
            listfoyerPaneliste = [SELECT Id, Name, Foyer_Paneliste_ExtId_SIPanel__c, Foyer__c 
                                    FROM Foyer_paneliste__c 
                                    WHERE Foyer__c =: listContactsToUpdate[0].AccountId LIMIT 1];

        }
             
        If(listfoyerPaneliste.size() > 0){
                     method ='PUT';
                	 endpoint =  'callout:Mulesoft_experience_API/' +'api/'+ Label.Mulesoft_Xapp_MM_Sync_Sipanel+'/v1/'+ label.Mulesoft_expAPI_indivduPanPath + '/' 
               		 +  listContactsToUpdate[0].Id
               		 + '?flow=' + label.Mulesoft_flow_parameter_sf_to_sipanel 
                	 + '&uid=' + listfoyerPaneliste[0].Foyer_Paneliste_ExtId_SIPanel__c;                                     
        }
        
        Http http = new Http();
        HttpRequest req = creatHttpRequest(method, endpoint);
        HTTPResponse res = http.send(req);
        System.debug(res.getBody());   
                        
        return res;    
      
    }
  // End  
 
    
     public static HttpRequest creatHttpRequest(string method, string endpoint)
    {
        HttpRequest reqToReturn = new HttpRequest();
        reqToReturn.setHeader('x-client-id', label.Mulesoft_expAPI_clientId);
        reqToReturn.setHeader('x-client-secret', label.Mulesoft_expAPI_clientSecret);
        reqToReturn.setHeader('Accept', 'application/json');
        reqToReturn.setHeader('Content-Type', 'application/json');
        reqToReturn.setEndpoint(endpoint);
        reqToReturn.setMethod(method);
        if(method=='PUT' || method=='POST'){
            JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
            gen.writeStringField('description', 'test');
            gen.writeEndObject();
            reqToReturn.setBody(gen.getAsString());
        }
        
        return reqToReturn;
    }
    
    
    //Wrapper used to return the HTTP response to the visual flow
    public class CalloutResponse {
        @InvocableVariable
        public String responseStatus;
        
        @InvocableVariable
        public Integer responseStatusCode;
        
        @InvocableVariable
        public String responseErrorReference;
        
        @InvocableVariable
        public String responseErrorDescription;
    }
}