force-app/main/default/objects/Contact/fields/Activite_actuelle__c.field-meta.xml
<CustomField>
    <fullName>Activite_actuelle__c</fullName>
    <label>Activité actuelle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
                <label>Au chômage ayant déjà travaillé</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Exerce une activité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>À la rechercher d&apos;un 1er emploi</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Retraite ou pré-retraite</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Congé maternité</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Congé parental</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Maladie longue durée</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Femme ou homme au foyer</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Autre cas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Code_profession__c.field-meta.xml
<CustomField>
    <fullName>Code_profession__c</fullName>
    <label>Code profession</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CON_ExtId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>CON_ExtId_SIPanel__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>CON_ExtId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Id_google__c.field-meta.xml
<CustomField>
    <fullName>Id_google__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>ID Google</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Lettre__c.field-meta.xml
<CustomField>
    <fullName>Lettre__c</fullName>
    <label>Lettre</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Lien_parente__c.field-meta.xml
<CustomField>
    <fullName>Lien_parente__c</fullName>
    <label>Lien parenté</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Chef de famille</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Conjoint</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Enfant</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Ascendant</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Autre</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/CON_EXTId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>CON_EXTId_SIPanel__c</fullName>
    <description>&quot;(UUID) c&apos;est l&apos;id salesforce de l&apos;enregistrement Composition Du Foyer Parent
Ce champ sert a identifier l&apos;enregistrement parent (Composition Du Foyer) de l&apos;Individu Panéliste&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>CON_EXTId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Date_de_chute_de_l_individu__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute_de_l_individu__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute de l&apos;individu</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Individus Panélistes</relationshipLabel>
    <relationshipName>Individus_Paneliste</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/ID_Google__c.field-meta.xml
<CustomField>
    <fullName>ID_Google__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ID Google</label>
    <length>233</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Lettre__c.field-meta.xml
<CustomField>
    <fullName>Lettre__c</fullName>
    <label>Lettre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT( Foyer_paneliste__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_flows__c.field-meta.xml
<CustomField>
    <fullName>Bypass_flows__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass flows</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_triggers__c.field-meta.xml
<CustomField>
    <fullName>Bypass_triggers__c</fullName>
    <label>Bypass triggers</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AP01_BandeUsine</fullName>
            </value>
            <value>
                <fullName>AP01_Commande</fullName>
            </value>
            <value>
                <fullName>AP01_Conge</fullName>
            </value>
            <value>
                <fullName>AP01_Control</fullName>
                <isActive>false</isActive>
                <label>AP01_Control</label>
            </value>
            <value>
                <fullName>AP01_Controle</fullName>
            </value>
            <value>
                <fullName>AP01_Convention</fullName>
            </value>
            <value>
                <fullName>AP01_Equipement</fullName>
            </value>
            <value>
                <fullName>AP01_EquipementDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP01_Evenement</fullName>
            </value>
            <value>
                <fullName>AP01_Fidelisation</fullName>
            </value>
            <value>
                <fullName>AP01_Foyer</fullName>
            </value>
            <value>
                <fullName>AP01_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP01_IndividuPaneliste</fullName>
            </value>
            <value>
                <fullName>AP01_LienMeter</fullName>
            </value>
            <value>
                <fullName>AP01_MembreDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP01_Requete</fullName>
            </value>
            <value>
                <fullName>AP01_StockProduit</fullName>
            </value>
            <value>
                <fullName>AP01_SuiviStockSAV</fullName>
            </value>
            <value>
                <fullName>AP01_UpdatescheduledDate</fullName>
            </value>
            <value>
                <fullName>AP01_WorkOrder</fullName>
            </value>
            <value>
                <fullName>AP010_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP011_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP02_BandeUsine</fullName>
            </value>
            <value>
                <fullName>AP02_Commande</fullName>
            </value>
            <value>
                <fullName>AP02_Controle</fullName>
            </value>
            <value>
                <fullName>AP02_Convention</fullName>
            </value>
            <value>
                <fullName>AP02_Equipement</fullName>
            </value>
            <value>
                <fullName>AP02_EquipementDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP02_Foyer</fullName>
            </value>
            <value>
                <fullName>AP02_FoyerPaneliste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP01_IndividuPaneliste_Test.cls
/*
* @author: Jérôme HE
* @date: 25/02/2022
* @Classe: AP01_IndividuPaneliste
* * History
* <Date of modification>   		<Author>    		<Description of modification>
*/
@isTest
public class AP01_IndividuPaneliste_Test {
    @testSetup
    static void setup(){
        
    }
    public static testMethod void AP01_IndPanTest(){
        User u = [SELECT id, Bypass_triggers__c FROM User WHERE isActive = true and Profile.name like '%dministra%' limit 1];
        u.Bypass_triggers__c = 'AP01_MembreDuFoyer;AP02_Foyer;AP08_FoyerPaneliste;AP03_Individu_paneliste';
        u.Bypass_flows__c = true;
        update u;
        
        //System.runAs(u){

            List <String> ExternalIds = new List <String>();
            Id recordTypeIdFoyerPanMMPaME  = Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(Label.PAN_recordType_mediamatpame).getRecordTypeId();
            Id recordTypeIdFoyerPanMMAIP  = Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(Label.PAN_recordType_AIP).getRecordTypeId();
        
            list<Account> listFoyersToInsert = new list<Account>();
            account acc = Test_Utils.createFoyer();
            listFoyersToInsert.add(acc); 
            insert listFoyersToInsert;
            
            Referentiel_Panel__c refPanTest = new Referentiel_Panel__c();
            refPanTest.Type_de_panel__c = Label.RFP_TypePanel_PaME;
            refPanTest.Name = Label.RFP_Nom_PaME;
            insert refPanTest;
            
            Foyer_paneliste__c foyerPanTest = new Foyer_paneliste__c(Name ='foyerPanTest');
            foyerPanTest.Referentiel_Panel__c = refPanTest.id;
            foyerPanTest.foyer__c = acc.id;
            foyerPanTest.RecordTypeId = recordTypeIdFoyerPanMMPaME;
            insert foyerPanTest;
            
            list<Contact> listMembreFoyerToInsert = new list<Contact>();
            Contact Cont = Test_Utils.createMembreFoyer(acc.id); 
            Cont.Lien_parente__c = Label.CON_LienParente_ChefDeFamille;
            Cont.Activite_actuelle__c = System.Label.CON_ActiviteActuelle_A_la_recherche_premier_emploi;
            Cont.Code_profession__c = 132;
            listMembreFoyerToInsert.add(Cont);       
            insert listMembreFoyerToInsert;        
            
            
            Individu_Paneliste__c indPantest = new Individu_Paneliste__c();
            indPanTest.name = 'indPanTest';
            indPanTest.Lettre__c = 'B';
            indPanTest.Foyer_paneliste__c = foyerPanTest.id;
            indPanTest.Composition_du_foyer__c = cont.id;
            indPanTest.Date_de_chute_de_l_individu__c = null;
        	indPanTest.ID_Google__c = '12345';
            insert indPanTest;
            
            IndividuPanelisteCallout_Mock indPanMock = new IndividuPanelisteCallout_Mock(indPanTest.id);
            indPanTest.Date_de_chute_de_l_individu__c = date.today();
            Test.startTest();
            Update indPanTest;
            Test.setMock(HttpCalloutMock.class, indPanMock);
            //Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(Cont.CON_ExtId_SIPanel__c)); 
            Test.stopTest();
            
        //}
    }
}