force-app/main/default/objects/Contact/fields/Activite_actuelle__c.field-meta.xml
<CustomField>
    <fullName>Activite_actuelle__c</fullName>
    <label>Activité actuelle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
                <label>Au chômage ayant déjà travaillé</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Exerce une activité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>À la rechercher d&apos;un 1er emploi</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Retraite ou pré-retraite</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Congé maternité</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Congé parental</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Maladie longue durée</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Femme ou homme au foyer</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Autre cas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Code_profession__c.field-meta.xml
<CustomField>
    <fullName>Code_profession__c</fullName>
    <label>Code profession</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CON_ExtId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>CON_ExtId_SIPanel__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>CON_ExtId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/CSP42__c.field-meta.xml
<CustomField>
    <fullName>CSP42__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code profession CSP42</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CSP4__c.field-meta.xml
<CustomField>
    <fullName>CSP4__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code profession CSP4</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_d_entree_individu__c.field-meta.xml
<CustomField>
    <fullName>Date_d_entree_individu__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date d&apos;entrée individu</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Lettre__c.field-meta.xml
<CustomField>
    <fullName>Lettre__c</fullName>
    <label>Lettre</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Lien_de_parente_stat__c.field-meta.xml
<CustomField>
    <fullName>Lien_de_parente_stat__c</fullName>
    <label>Lien de parenté stat</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Couple</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Parent</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Enfant</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Famille</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Isolé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Lien_parente__c.field-meta.xml
<CustomField>
    <fullName>Lien_parente__c</fullName>
    <label>Lien parenté</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Chef de famille</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Conjoint</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Enfant</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Ascendant</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Autre</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Nombre_d_heures_travaillees__c.field-meta.xml
<CustomField>
    <fullName>Nombre_d_heures_travaillees__c</fullName>
    <label>Nombre d&apos;heures travaillées</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tech_lettre_MAJ__c.field-meta.xml
<CustomField>
    <fullName>Tech_lettre_MAJ__c</fullName>
    <defaultValue>1</defaultValue>
    <description>champ tech mis à jour par le flux individupan_updatecontact_techfield permettant de savoir quand l&apos;enfant ind pan a été mis à jour dans le traitement de classe AP02_MembreDuFoyer</description>
    <label>Tech_lettre_MAJ</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Membre</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Invité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Non panéliste</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/CON_EXTId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>CON_EXTId_SIPanel__c</fullName>
    <description>&quot;(UUID) c&apos;est l&apos;id salesforce de l&apos;enregistrement Composition Du Foyer Parent
Ce champ sert a identifier l&apos;enregistrement parent (Composition Du Foyer) de l&apos;Individu Panéliste&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>CON_EXTId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Lettre__c.field-meta.xml
<CustomField>
    <fullName>Lettre__c</fullName>
    <label>Lettre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invité</fullName>
            </value>
            <value>
                <fullName>Membre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT( Foyer_paneliste__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_flows__c.field-meta.xml
<CustomField>
    <fullName>Bypass_flows__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass flows</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_triggers__c.field-meta.xml
<CustomField>
    <fullName>Bypass_triggers__c</fullName>
    <label>Bypass triggers</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AP01_BandeUsine</fullName>
            </value>
            <value>
                <fullName>AP01_Commande</fullName>
            </value>
            <value>
                <fullName>AP01_Conge</fullName>
            </value>
            <value>
                <fullName>AP01_Control</fullName>
                <isActive>false</isActive>
                <label>AP01_Control</label>
            </value>
            <value>
                <fullName>AP01_Controle</fullName>
            </value>
            <value>
                <fullName>AP01_Convention</fullName>
            </value>
            <value>
                <fullName>AP01_Equipement</fullName>
            </value>
            <value>
                <fullName>AP01_EquipementDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP01_Evenement</fullName>
            </value>
            <value>
                <fullName>AP01_Fidelisation</fullName>
            </value>
            <value>
                <fullName>AP01_Foyer</fullName>
            </value>
            <value>
                <fullName>AP01_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP01_IndividuPaneliste</fullName>
            </value>
            <value>
                <fullName>AP01_LienMeter</fullName>
            </value>
            <value>
                <fullName>AP01_MembreDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP01_Requete</fullName>
            </value>
            <value>
                <fullName>AP01_StockProduit</fullName>
            </value>
            <value>
                <fullName>AP01_SuiviStockSAV</fullName>
            </value>
            <value>
                <fullName>AP01_UpdatescheduledDate</fullName>
            </value>
            <value>
                <fullName>AP01_WorkOrder</fullName>
            </value>
            <value>
                <fullName>AP010_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP011_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP02_BandeUsine</fullName>
            </value>
            <value>
                <fullName>AP02_Commande</fullName>
            </value>
            <value>
                <fullName>AP02_Controle</fullName>
            </value>
            <value>
                <fullName>AP02_Convention</fullName>
            </value>
            <value>
                <fullName>AP02_Equipement</fullName>
            </value>
            <value>
                <fullName>AP02_EquipementDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP02_Foyer</fullName>
            </value>
            <value>
                <fullName>AP02_FoyerPaneliste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP02_MembreDuFoyer_Test.cls
/*
* @date: 01/04/2022
* @ Description : test class qui test AP02_MembreDuFoyer qui appele API mulesoft Google 
                  pour envoi du contact à l'update 
* @ Condition : - suite changement du nom prénom
*               - suite changement de l'adresse mail
*               - suite changement de la date de naissance
*               - lorsque le champ Lettre__c de l'un des individu panéliste 
                  appartenant à la composition du foyer (contact) mis à jour est mis à jour

* @Auteur : Téoman Sertçelik
* @Coverage: 96 %
History
* <Date of modification> 		<Author> 			<Description of modification>
*/
@isTest
public with sharing class AP02_MembreDuFoyer_Test {

    @isTest
    public static void AP02_SendContactUpdated () {
        
        User u = [SELECT id, Bypass_triggers__c FROM User WHERE isActive = true and Profile.name like '%dministra%' limit 1];
        u.Bypass_triggers__c = 'AP01_MembreDuFoyer;AP02_Foyer; AP01_IndividuPaneliste;AP01_IndividuPaneliste;AP08_FoyerPaneliste;AP03_Individu_paneliste';
        u.Bypass_flows__c = true;
        update u;
        
        System.runAs(u){
            List<Account> listAccountToInsert = new List<Account>();
            List<Contact> listMembreFoyerToInsert = new List<Contact>();
            List<Individu_Paneliste__c> listIndToInsert = new List<Individu_Paneliste__c>();
            List<Foyer_paneliste__c> listFoyerPanToInsert = new List<Foyer_paneliste__c>();
            Id recordTypeIdFoyerPanelisteMMAT = Schema.SObjectType.Foyer_Paneliste__c.getRecordTypeInfosByName().get(Label.PAN_recordType_mediamatpame).getRecordTypeId();
            List<Referentiel_Panel__c> listRefPanToInsert = new List<Referentiel_Panel__c>();
    
            Account acc1 = new Account();
            acc1.Name = 'Foyer1';
            acc1.ShippingPostalCode = '98222';
            acc1.ShippingState = 'France';
            acc1.ShippingCountry = 'PHUKET';
            acc1.ShippingStreet = 'toto';
            acc1.ShippingCity = 'paname';
            listAccountToInsert.add(acc1);
            insert listAccountToInsert;
        
            Contact cont1 = new Contact();
            cont1.FirstName = 'firstNameAno';
            cont1.LastName = 'lastNameAno';
            cont1.Type__c = Label.CON_Type_MEMBRE;
            cont1.Birthdate = date.newInstance(1993, 02, 25);
            cont1.Nombre_d_heures_travaillees__c=3;
            cont1.Date_d_entree_individu__c = Date.today();
            cont1.AccountId = acc1.Id;
            cont1.Lien_parente__c = '1';
            cont1.Tech_lettre_MAJ__c = 1;
            cont1.CSP42__c = 'test';
            cont1.CSP4__c = 'testt';
            cont1.MobilePhone='1234567891';
            cont1.Lien_de_parente_stat__c = '1';
            cont1.CON_ExtId_SIPanel__c = '122223456';
            cont1.Lien_parente__c = Label.CON_LienParente_ChefDeFamille;
            cont1.Activite_actuelle__c = System.Label.CON_ActiviteActuelle_A_la_recherche_premier_emploi;
            cont1.Code_profession__c = 132;
            listMembreFoyerToInsert.add(cont1);
            insert listMembreFoyerToInsert;
           
            Referentiel_Panel__c refPan = new Referentiel_Panel__c();
            refPan.Name	= Label.RFP_TypePanel_PaME;
            refPan.Type_de_panel__c =  Label.REF_PANEL_TypePan_PAME;
            listRefPanToInsert.add(refPan);
            insert refPan;
            
    
            Foyer_paneliste__c fpMMAT1 = new Foyer_paneliste__c();
            fpMMAT1.RecordTypeId = recordTypeIdFoyerPanelisteMMAT;
            fpMMAT1.Name = 'FoyerPan1';
            fpMMAT1.Foyer__c = acc1.Id;
            fpMMAT1.Membre_du_foyer__c = cont1.Id;
            fpMMAT1.Referentiel_Panel__c = refPan.Id;
            fpMMAT1.Statut_Foyer_paneliste__c = Label.PAN_Statut_Panel_Integre;
            fpMMAT1.Date_de_creation__c = date.newInstance(2005, 02, 25);
            listFoyerPanToInsert.add(fpMMAT1);
            insert listFoyerPanToInsert;
    
    
            Individu_Paneliste__c ind1 = new Individu_Paneliste__c();
            ind1.Composition_du_foyer__c = cont1.Id;
            ind1.Foyer_paneliste__c = fpMMAT1.Id;
            ind1.Lettre__c = 'F';
            listIndToInsert.add(ind1);
            insert listIndToInsert;
    
            MembreFoyerCallout_Mock fakeSendCont = new MembreFoyerCallout_Mock(cont1.Id);
            Test.startTest();
            cont1.FirstName = 'updated';            
            update cont1;
            Test.setMock(HttpCalloutMock.class, fakeSendCont);
            Test.stopTest();
        }
    }
}