force-app/main/default/objects/Contact/fields/Activite_actuelle__c.field-meta.xml
<CustomField>
    <fullName>Activite_actuelle__c</fullName>
    <label>Activité actuelle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
                <label>Au chômage ayant déjà travaillé</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Exerce une activité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>À la rechercher d&apos;un 1er emploi</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Retraite ou pré-retraite</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Congé maternité</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Congé parental</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Maladie longue durée</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Femme ou homme au foyer</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Autre cas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CSP42__c.field-meta.xml
<CustomField>
    <fullName>CSP42__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code profession CSP42</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CSP4__c.field-meta.xml
<CustomField>
    <fullName>CSP4__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code profession CSP4</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Lettre__c.field-meta.xml
<CustomField>
    <fullName>Lettre__c</fullName>
    <label>Lettre</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Lien_parente__c.field-meta.xml
<CustomField>
    <fullName>Lien_parente__c</fullName>
    <label>Lien parenté</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Chef de famille</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Conjoint</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Enfant</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Ascendant</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Autre</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer_Paneliste_ExtId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>Foyer_Paneliste_ExtId_SIPanel__c</fullName>
    <description>&quot;(UID) c&apos;est l&apos;id unique generé par SIPANEL du foyer panéliste 
Ce champ sert a faire l&apos;Upsert du foyer panéliste&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Foyer_Paneliste_ExtId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Membre_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Membre_du_foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membre du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Statut_Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Statut_Foyer_paneliste__c</fullName>
    <label>Statut Foyer Panéliste</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Foyer_equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Recruté</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Installé</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Equipé</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Intégré</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Désinstallé</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Chute temporaire</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Chute définitive</label>
            </value>
            <value>
                <fullName>Chute définitive et désinstallé</fullName>
                <isActive>false</isActive>
                <label>Chute définitive et désinstallé</label>
            </value>
            <value>
                <fullName>Désinstallé actif</fullName>
                <isActive>false</isActive>
                <label>Désinstallé actif</label>
            </value>
            <value>
                <fullName>Recruté en attente d&apos;installation</fullName>
                <isActive>false</isActive>
                <label>Recruté en attente d&apos;installation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Date_de_chute_de_l_individu__c.field-meta.xml
<CustomField>
    <fullName>Date_de_chute_de_l_individu__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de chute de l&apos;individu</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Individus Panélistes</relationshipLabel>
    <relationshipName>Individus_Paneliste</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Lettre__c.field-meta.xml
<CustomField>
    <fullName>Lettre__c</fullName>
    <label>Lettre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT( Foyer_paneliste__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_triggers__c.field-meta.xml
<CustomField>
    <fullName>Bypass_triggers__c</fullName>
    <label>Bypass triggers</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AP01_BandeUsine</fullName>
            </value>
            <value>
                <fullName>AP01_Commande</fullName>
            </value>
            <value>
                <fullName>AP01_Conge</fullName>
            </value>
            <value>
                <fullName>AP01_Control</fullName>
                <isActive>false</isActive>
                <label>AP01_Control</label>
            </value>
            <value>
                <fullName>AP01_Controle</fullName>
            </value>
            <value>
                <fullName>AP01_Convention</fullName>
            </value>
            <value>
                <fullName>AP01_Equipement</fullName>
            </value>
            <value>
                <fullName>AP01_EquipementDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP01_Evenement</fullName>
            </value>
            <value>
                <fullName>AP01_Fidelisation</fullName>
            </value>
            <value>
                <fullName>AP01_Foyer</fullName>
            </value>
            <value>
                <fullName>AP01_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP01_IndividuPaneliste</fullName>
            </value>
            <value>
                <fullName>AP01_LienMeter</fullName>
            </value>
            <value>
                <fullName>AP01_MembreDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP01_Requete</fullName>
            </value>
            <value>
                <fullName>AP01_StockProduit</fullName>
            </value>
            <value>
                <fullName>AP01_SuiviStockSAV</fullName>
            </value>
            <value>
                <fullName>AP01_UpdatescheduledDate</fullName>
            </value>
            <value>
                <fullName>AP01_WorkOrder</fullName>
            </value>
            <value>
                <fullName>AP010_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP011_FoyerPaneliste</fullName>
            </value>
            <value>
                <fullName>AP02_BandeUsine</fullName>
            </value>
            <value>
                <fullName>AP02_Commande</fullName>
            </value>
            <value>
                <fullName>AP02_Controle</fullName>
            </value>
            <value>
                <fullName>AP02_Convention</fullName>
            </value>
            <value>
                <fullName>AP02_Equipement</fullName>
            </value>
            <value>
                <fullName>AP02_EquipementDuFoyer</fullName>
            </value>
            <value>
                <fullName>AP02_Foyer</fullName>
            </value>
            <value>
                <fullName>AP02_FoyerPaneliste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP01_MembreDuFoyer_Test.cls
/*
* @author: Khaled Hammoudeh
* @date: 28/1/2020
* @ Description Class that test AP01_MembreDuFoyer . Associated Trigger : membreDuFoyerAfterInsert
* History
* <Date of modification>   <Author> 
Jerome HE 29/04/22 
Marliatou 15/12/22
<Description of modification>
*/
@istest
public class AP01_MembreDuFoyer_Test {
    public static testMethod void AP01_MembreDuFoyerTest(){
        User u = [SELECT id, Bypass_triggers__c FROM User WHERE isActive = true and Profile.name like '%dministra%' limit 1];
        Id recordTypeIdFoyerPanelisteAIP =Schema.SObjectType.Foyer_paneliste__c.getRecordTypeInfosByName().get(label.PAN_recordType_AIP).getRecordTypeId();
        
        System.runAs(u){
            list<Account> listFoyersToInsert = new list<Account>();
            account acc = Test_Utils.createFoyer();
            listFoyersToInsert.add(acc); 
            insert listFoyersToInsert;
            
            Referentiel_Panel__c refPanAIP = new Referentiel_Panel__c();
            refPanAIP.Type_de_panel__c = Label.RFP_Nom_AIP;
            refPanAIP.Name	= Label.RFP_TypePanel_AIP;
            insert refPanAIP;
            
            List<Foyer_Paneliste__c> foyerPanelisteToInsert = new List<Foyer_Paneliste__c>();
            Foyer_Paneliste__c foyerPan = new Foyer_Paneliste__c();
            foyerPan.Referentiel_Panel__c = refPanAIP.Id;
            foyerPan.Statut_Foyer_paneliste__c = Label.PAN_Statut_Panel_Installe;
            foyerPan.RecordTypeId = recordTypeIdFoyerPanelisteAIP;
            foyerPan.name = 'TestAP01_Contact';
            foyerPan.Foyer__c = acc.Id;
            foyerPan.Foyer_Paneliste_ExtId_SIPanel__c = 'AZE34';
            foyerPanelisteToInsert.add(foyerPan);
            Insert foyerPanelisteToInsert;
            
            list<Contact> listMembreFoyerToInsert = new list<Contact>();
            Contact Cont = Test_Utils.createMembreFoyer(acc.id); 
            Cont.Lien_parente__c = Label.CON_LienParente_ChefDeFamille;
            Cont.Activite_actuelle__c = System.Label.CON_ActiviteActuelle_A_la_recherche_premier_emploi;
            Cont.CSP42__c = '132';
            COnt.CSP4__c='1';
            listMembreFoyerToInsert.add(Cont); 
                     
            Test.startTest();
            insert listMembreFoyerToInsert;  
            Cont.MobilePhone = '0123456789';
            update Cont;
            Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(Cont.Id));
            Test.stopTest();
        }
    }
    
   public static testMethod void AP01_CompoFoyerTest(){
       
           list <String> listContactIds = new List <String>();
           list<Account> listFoyer = new list<Account>();
           list<Contact> listContactToInsert = new list<Contact>(); 
           list<Foyer_Paneliste__c> listfoyerPan = new List<Foyer_Paneliste__c>();
           Id recordTypeIdPAME =Schema.SObjectType.Contact.getRecordTypeInfosByName().get(label.CON_RecordType_PaME).getRecordTypeId();
       
            account acc = Test_Utils.createFoyer();
            listFoyer.add(acc); 
            insert listFoyer;
                
            Contact contact = Test_Utils.createMembreFoyer(acc.id); 
            contact.Lien_parente__c = Label.CON_LienParente_ChefDeFamille;
            contact.RecordTypeId = recordTypeIdPAME;
       		contact.CSP4__c='2';
            contact.Activite_actuelle__c = System.Label.CON_ActiviteActuelle_A_la_recherche_premier_emploi;
            listContactToInsert.add(contact);
            insert listContactToInsert;
       
            listContactIds.add(contact.Id);
       
           Individu_Paneliste__c indPantest = new Individu_Paneliste__c();
            indPanTest.name = 'indPanTest';
            indPanTest.Lettre__c = 'A';
            indPanTest.Composition_du_foyer__c = contact.id;
            indPanTest.Date_de_chute_de_l_individu__c = null;
            insert indPanTest;
            
            Foyer_Paneliste__c foyerP = Test_Utils.createFoyerPaneliste();  
			foyerP.Foyer__c = acc.Id;
            foyerP.Foyer_Paneliste_ExtId_SIPanel__c = 'AZB34';
            foyerP.Membre_du_foyer__c = contact.Id;
            listfoyerPan.add(foyerP);
            Insert listfoyerPan;
       
             indPanTest.Foyer_paneliste__c = foyerP.id;
             update indPanTest;
            
         
           Test.startTest(); 
            Test.setMock(HttpCalloutMock.class, new MembreFoyerCallout_Mock(contact.Id));
            List<AP01_MembreDuFoyer.CalloutResponse> resp = AP01_MembreDuFoyer.updateContactToSipanel(listContactIds);
           Test.stopTest();
             
          
         
     }
}