force-app/main/default/objects/Contact/fields/Contact_principal__c.field-meta.xml
<CustomField>
    <fullName>Contact_principal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contact Principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/Fidelisation__c.object-meta.xml
<CustomObject>
    <label>Fidélisation</label>
    <nameField>
        <displayFormat>FID-{0000}</displayFormat>
        <label>Nom de Fidélisation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fidélisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fidelisation__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Composition du foyer</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Ce membre de foyer ne fait pas partie de ce foyer ou il n&apos;existe pas</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Foyer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fidelisations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Date_de_traitement__c.field-meta.xml
<CustomField>
    <fullName>Date_de_traitement__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de traitement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fidelisations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Individu_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Individu_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individu Panéliste</label>
    <referenceTo>Individu_Paneliste__c</referenceTo>
    <relationshipLabel>Fidélisations</relationshipLabel>
    <relationshipName>Fid_lisations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fidelisation__c/fields/Points_debites__c.field-meta.xml
<CustomField>
    <fullName>Points_debites__c</fullName>
    <label>Points Débités</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer Panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Commandes</relationshipLabel>
    <relationshipName>Commandes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/getDerniereCommande.cls
public with sharing class getDerniereCommande {
    @AuraEnabled
    public static wrapperType getInfo(Integer pageNumber, Integer recordsPerPage) {
        Integer requestOffset = 0;
        pageNumber = pageNumber -1;
        if(pageNumber == 0) {
            requestOffset = 0;
        } else {
            requestOffset = recordsPerPage * pageNumber;
        }
Id userId = UserInfo.getUserId();
System.debug('bastien userId : '+ userId);

Id contactId = [Select id,contactId, Contact.Contact_principal__c  from user where id = :userId].get(0).contactId;
System.debug('bastien contactId : '+ contactId);

Id foyerId = [select id,Foyer_paneliste__r.Id from Individu_Paneliste__c where Composition_du_foyer__c = :contactId].size()>0 ?[select id,Foyer_paneliste__r.Id from Individu_Paneliste__c where Composition_du_foyer__c = :contactId].get(0).Foyer_paneliste__r.Id : null;
System.debug('bastien foyerId : '+ foyerId);


// //get all membre foyer
List<Individu_Paneliste__c> listIdUsers = [select Composition_du_foyer__c from Individu_Paneliste__c where Foyer_paneliste__c =:foyerId];
System.debug('bastien listIdUsers : '+ listIdUsers);

// Set<Id> resultIds = (new Map<Id,SObject>(listIdUsers)).keySet();
// System.debug('bastien resultIds : '+ resultIds);

Map<Id, Individu_Paneliste__c> mapIndividu = new Map<Id, Individu_Paneliste__c>();
for (Individu_Paneliste__c i : listIdUsers) {
    mapIndividu.put(i.Composition_du_foyer__c, i);
}
System.debug('bastien mapIndividu : '+ mapIndividu);

Set<Id> resultIds =mapIndividu.keySet();
System.debug('bastien resultIds : '+ resultIds);

wrapperType wr = new wrapperType();
// List<Contact> listDerniereCommande = [SELECT Id, (SELECT Id, Name , CreatedDate, Date_de_traitement__c, Points_debites__c FROM Fidelisations__r WHERE RecordType.Name='Débit' ORDER BY CreatedDate desc LIMIT 1) FROM Contact WHERE Id IN :resultIds ORDER BY Name ASC NULLS LAST LIMIT :recordsPerPage OFFSET :requestOffset];
List<Contact> listDerniereCommande = [SELECT Id, (SELECT Id, Name , CreatedDate, Date_de_traitement__c, Points_debites__c FROM Fidelisations__r  WHERE RecordType.Name='Débit' ORDER BY CreatedDate desc LIMIT 1) FROM Contact  WHERE id IN (SELECT Composition_du_foyer__c  FROM Fidelisation__c WHERE Name!=null AND RecordType.Name='Débit') AND Id IN :resultIds ORDER BY Name ASC NULLS LAST LIMIT :recordsPerPage OFFSET :requestOffset];
System.debug('bastien listDerniereCommande : '+ listDerniereCommande);


Integer totalCommande = [SELECT COUNT() FROM Contact  WHERE id IN (SELECT Composition_du_foyer__c  FROM Fidelisation__c WHERE Name!=null AND RecordType.Name='Débit') AND Id IN :resultIds ];
wr.totalCommande=totalCommande;
System.debug('bastien totalCommande : '+ totalCommande);

List<Fidelisation__c> listFid = new List<Fidelisation__c>(); 
for(Contact e : listDerniereCommande){
    if(e.Fidelisations__r!=null && e.Fidelisations__r.size() > 0){
        listFid.add(e.Fidelisations__r);
    }
}

wr.listCommande=listFid;
        return wr;
    }

    public class wrapperType {
        @AuraEnabled
        public List<Fidelisation__c> listCommande;
        @AuraEnabled
        public Integer totalCommande;
        }
}