force-app/main/default/objects/Contact/fields/Lien_parente__c.field-meta.xml
<CustomField>
    <fullName>Lien_parente__c</fullName>
    <label>Lien parenté</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Chef de famille</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Conjoint</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Enfant</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Ascendant</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Autre</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Membre</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Invité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Non panéliste</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipement_du_foyer_de_l_individu__c/Equipement_du_foyer_de_l_individu__c.object-meta.xml
<CustomObject>
    <label>Équipement du foyer de l&apos;individu</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de É</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Équipements du foyer des individus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipement_du_foyer_de_l_individu__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Équipements du foyer des individus</relationshipLabel>
    <relationshipName>Equipements_du_foyer_des_individus</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Equipement_du_foyer_de_l_individu__c/fields/Equipement_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Equipement_du_foyer__c</fullName>
    <label>Équipement du foyer</label>
    <referenceTo>Equipements_du_foyer__c</referenceTo>
    <relationshipLabel>Équipements du foyer des individus</relationshipLabel>
    <relationshipName>Equipements_du_foyer_des_individus</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Equipement_du_foyer_de_l_individu__c/fields/Utilisation_de_l_equipement__c.field-meta.xml
<CustomField>
    <fullName>Utilisation_de_l_equipement__c</fullName>
    <label>Utilisation de l&apos;équipement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non</fullName>
                <default>true</default>
                <label>Non</label>
            </value>
            <value>
                <fullName>Oui</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/Equipements_du_foyer__c.object-meta.xml
<CustomObject>
    <label>Equipement du foyer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;équipement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipements du foyer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Foyer__c.field-meta.xml
<CustomField>
    <fullName>Foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Equipements du foyer</relationshipLabel>
    <relationshipName>Equipements_du_foyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipements_du_foyer__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>7</fullName>
                <label>Ordinateur fixe</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Ordinateur portable</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Tablette</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Mobile</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Poste TV</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Lecteur DVD</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Console de jeux</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Magnétoscope</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Décodeur</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Divers</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Box</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Caster</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Objet Connecté</label>
            </value>
            <value>
                <fullName>17</fullName>
                <isActive>false</isActive>
                <label>Autre équipement</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP01_Equipement_Du_Foyer_Individu_Test.cls
/*
* @date: 28/09/2023
* @ Description Class qui teste AP01_Equipement_Du_Foyer_De_l_Individu
* @version 1.00   
* pourcentage : %
* @Auteur Claire VEHRLE
History
* <Date of modification> <Author> 	<Description of modification>
*/
@isTest
public class AP01_Equipement_Du_Foyer_Individu_Test {

    @isTest
    static void Get_Equipement_Du_Foyer_Individu() {
        Id recordTypeIdeqtFoyerPoste = Schema.SObjectType.Equipements_du_foyer__c.getRecordTypeInfosByName().get(Label.EQPF_RecordType_PosteTV).getRecordTypeId();
        Id recordTypeIdeqtFoyerDevice = Schema.SObjectType.Equipements_du_foyer__c.getRecordTypeInfosByName().get(Label.EQF_RecodType_Device).getRecordTypeId();
        
        List<Account> foyerToInsert = new List<Account>();
        Account foyer1 = new Account();
        foyer1.Name = 'Foyer1';
        foyerToInsert.add(foyer1);
        insert foyerToInsert;
        
        List<Contact> contactToInsert = new List<Contact>();
        Contact compoFoyer = new Contact();
        compoFoyer.accountId = foyer1.Id;
        compoFoyer.FirstName = 'Prénom';
        compoFoyer.LastName = 'Nom';
        compoFoyer.Birthdate = Date.Today();
        compoFoyer.Lien_parente__c = Label.CON_LienParente_ChefDeFamille;
        compoFoyer.Type__c = Label.CON_Type_MEMBRE;
        contactToInsert.add(compoFoyer);
        
        insert contactToInsert;
        
        List<Equipements_du_foyer__c> eqtFoyerToInsert = new List<Equipements_du_foyer__c>();
        Equipements_du_foyer__c eqtFoyer1 = new Equipements_du_foyer__c();
        eqtFoyer1.recordTypeId = recordTypeIdeqtFoyerPoste;
        eqtFoyer1.foyer__c = foyer1.Id;
        eqtFoyerToInsert.add(eqtFoyer1);
        
        Equipements_du_foyer__c eqtFoyer2 = new Equipements_du_foyer__c();
        eqtFoyer2.recordTypeId = recordTypeIdeqtFoyerDevice;
        eqtFoyer2.foyer__c = foyer1.Id;
        eqtFoyer2.Type__c = Label.EQF_Type_Smartphone;
        eqtFoyerToInsert.add(eqtFoyer2);
        
        insert eqtFoyerToInsert;
        
        Equipement_du_foyer_de_l_individu__c eqtInd = new Equipement_du_foyer_de_l_individu__c();
        eqtInd.Utilisation_de_l_equipement__c = 'Oui';
        eqtInd.Composition_du_foyer__c = compofoyer.Id;
        eqtInd.Equipement_du_foyer__c = eqtFoyer2.Id;
        
        insert eqtInd;
        
        MembreFoyerCallout_Mock fakeSendcompoFoyer = new MembreFoyerCallout_Mock(compoFoyer.Id);
        
        Test.startTest();
        AP01_Equipement_Du_Foyer_De_l_Individu.getEquipementFoyerIndividu(eqtFoyer2.Id);
        Test.stopTest();
    }
    
    @isTest
    static void Update_Equipement_Du_Foyer_Individu() {
        Id recordTypeIdeqtFoyerPoste = Schema.SObjectType.Equipements_du_foyer__c.getRecordTypeInfosByName().get(Label.EQPF_RecordType_PosteTV).getRecordTypeId();
        Id recordTypeIdeqtFoyerDevice = Schema.SObjectType.Equipements_du_foyer__c.getRecordTypeInfosByName().get(Label.EQF_RecodType_Device).getRecordTypeId();
        
        List<Account> foyerToInsert = new List<Account>();
        Account foyer1 = new Account();
        foyer1.Name = 'Foyer1';
        foyerToInsert.add(foyer1);
        insert foyerToInsert;
        
        List<Contact> contactToInsert = new List<Contact>();
        Contact compoFoyer = new Contact();
        compoFoyer.accountId = foyer1.Id;
        compoFoyer.FirstName = 'Prénom';
        compoFoyer.LastName = 'Nom';
        compoFoyer.Birthdate = Date.Today();
        compoFoyer.Lien_parente__c = Label.CON_LienParente_ChefDeFamille;
        compoFoyer.Type__c = Label.CON_Type_MEMBRE;
        contactToInsert.add(compoFoyer);
        
        insert contactToInsert;
        
        List<Equipements_du_foyer__c> eqtFoyerToInsert = new List<Equipements_du_foyer__c>();
        Equipements_du_foyer__c eqtFoyer1 = new Equipements_du_foyer__c();
        eqtFoyer1.recordTypeId = recordTypeIdeqtFoyerPoste;
        eqtFoyer1.foyer__c = foyer1.Id;
        eqtFoyerToInsert.add(eqtFoyer1);
        
        Equipements_du_foyer__c eqtFoyer2 = new Equipements_du_foyer__c();
        eqtFoyer2.recordTypeId = recordTypeIdeqtFoyerDevice;
        eqtFoyer2.foyer__c = foyer1.Id;
        eqtFoyer2.Type__c = Label.EQF_Type_Smartphone;
        eqtFoyerToInsert.add(eqtFoyer2);
        
        insert eqtFoyerToInsert;
        
        Equipement_du_foyer_de_l_individu__c eqtInd = new Equipement_du_foyer_de_l_individu__c();
        eqtInd.Utilisation_de_l_equipement__c = 'Oui';
        eqtInd.Composition_du_foyer__c = compofoyer.Id;
        eqtInd.Equipement_du_foyer__c = eqtFoyer2.Id;
        
        insert eqtInd;
        
        
        Test.startTest();
        List<Equipement_du_foyer_de_l_individu__c> eqtIndToUpdate = new List<Equipement_du_foyer_de_l_individu__c>();
        eqtInd.Utilisation_de_l_equipement__c = 'Non';
        eqtIndToUpdate.add(eqtInd);
        AP01_Equipement_Du_Foyer_De_l_Individu.updateEquipementFoyerIndividu(eqtIndToUpdate);
        Test.stopTest();
    }
    
}