force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Membre</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Invité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Non panéliste</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/PaME.recordType-meta.xml
<RecordType>
    <fullName>PaME</fullName>
    <active>true</active>
    <label>PaME</label>
</RecordType>

force-app/main/default/objects/Convention__c/Convention__c.object-meta.xml
<CustomObject>
    <label>Convention</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de Convention</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conventions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Convention__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Conventions</relationshipLabel>
    <relationshipName>Conventions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convention__c/fields/CON_ExtId_Google__c.field-meta.xml
<CustomField>
    <fullName>CON_ExtId_Google__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>CON ExtId Google</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Convention__c/fields/Date_de_signature_de_la_convention__c.field-meta.xml
<CustomField>
    <fullName>Date_de_signature_de_la_convention__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de signature de la convention</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Convention__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Conventions</relationshipLabel>
    <relationshipName>Conventions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convention__c/fields/Individu_Paneliste__c.field-meta.xml
<CustomField>
    <fullName>Individu_Paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individu Panéliste</label>
    <referenceTo>Individu_Paneliste__c</referenceTo>
    <relationshipLabel>Conventions</relationshipLabel>
    <relationshipName>Conventions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convention__c/fields/Referentiel_convention__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_convention__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel convention</label>
    <referenceTo>Referentiel_convention__c</referenceTo>
    <relationshipLabel>Conventions</relationshipLabel>
    <relationshipName>Conventions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convention__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT( Referentiel_convention__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Date_de_signature_de_la_convention__c.field-meta.xml
<CustomField>
    <fullName>Date_de_signature_de_la_convention__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date de signature de la convention</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Foyer_Paneliste_ExtId_SIPanel__c.field-meta.xml
<CustomField>
    <fullName>Foyer_Paneliste_ExtId_SIPanel__c</fullName>
    <description>&quot;(UID) c&apos;est l&apos;id unique generé par SIPANEL du foyer panéliste 
Ce champ sert a faire l&apos;Upsert du foyer panéliste&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Foyer_Paneliste_ExtId_SIPanel</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invité</fullName>
            </value>
            <value>
                <fullName>Membre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT( Foyer_paneliste__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer Panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Commandes</relationshipLabel>
    <relationshipName>Commandes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referentiel_convention__c/Referentiel_convention__c.object-meta.xml
<CustomObject>
    <label>Référentiel convention</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du modèle de convention</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel convention</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_convention__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Référentiel convention</relationshipLabel>
    <relationshipName>Referentiel_convention</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referentiel_convention__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <description>Si la date de fin est supérieure à la date d’aujourd’hui, le statut passe à « inactif »</description>
    <formula>IF( AND(Date_de_debut__c &lt;= TODAY(), OR(TODAY() &lt;= Date_de_fin__c,  ISNULL(Date_de_fin__c) )), &apos;Actif&apos;, &apos;Inactif&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Statut</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referentiel_convention__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Version</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP01_Convention.cls
/*
* @date: 24/03/2022
* @ Description : appeler API mulesoft pour envoi de la convention à l'insert et l'update 
* @ Condition : - individu fait partie de la compo foyer où il est membre
*               - le foyer panéliste auquel l'individu appartient et le référentiel panel du foyer pan est de type pame
*               - que la (dernière) convention est rattachée à la dernière version de référentiel convention 
                  et que celle ci est signé et actif
* @Auteur : Téoman Sertçelik
* @TestClass: AP01_Convention_Test
* @Coverage: 98 %
History
* <Date of modification> 		<Author> 			<Description of modification>
20/04/2022                      Téoman Sertçelik    Modified endpoint +
* 25/05/2022					Ayoub GHAMMAZ	Modification du endpoint
*/

public class AP01_Convention  {
   
    public static void sendConvention(List<Convention__c> listConvention , Map<Id,Convention__c> mapOldConvention){
    
        Set<String> setCnvIds = new Set<String>();
        Boolean isInsert = mapOldConvention == null;
        //List<String> listExtIdsUpdatedConventions = new List<String>();
        List<String> listIdsCreatedConventions = new List<String>();
        Convention__c newConv;
        //Convention__c oldConv;
        

        for(Convention__c cnv : listConvention) {
            setCnvIds.add(cnv.Id);
        }

        Map<Id, Convention__c> mapNewConvention = new Map<Id, Convention__c> 
        ([SELECT Id, CON_ExtId_Google__c, Individu_Paneliste__c, Individu_Paneliste__r.Composition_du_foyer__c, Individu_Paneliste__r.Composition_du_foyer__r.Type__c,
                 Foyer_paneliste__c, Foyer_paneliste__r.Referentiel_Panel__r.Type_de_panel__c, Foyer_paneliste__r.Foyer_Paneliste_ExtId_SIPanel__c,
                 Referentiel_convention__c, Referentiel_convention__r.Version__c, Referentiel_convention__r.Statut__c, Referentiel_convention__r.CreatedDate, Referentiel_convention__r.Name,
                 Composition_du_foyer__r.Type__c, Composition_du_foyer__c,
                 Date_de_signature_de_la_convention__c
          FROM Convention__c
          WHERE Id IN : setCnvIds]
        );

        Map<String, List<Referentiel_convention__c>> mapRefPanelIdToRefConvention = new Map<String, List<Referentiel_convention__c>>();

        List<Referentiel_convention__c> listReferentielConv = [SELECT Id, Statut__c, Version__c, Referentiel_Panel__c, CreatedDate,
                                                                    (SELECT Id, Date_de_signature_de_la_convention__c, Referentiel_convention__c
                                                                     FROM Conventions__r
                                                                     WHERE Id IN : mapNewConvention.keyset() )
                                                               FROM Referentiel_convention__c
                                                               WHERE Version__c != null 
                                                               AND Statut__c = 'Actif'
                                                               ORDER BY CreatedDate DESC
                                                               LIMIT 1];

        Set<String> setRefConvIds = new Set<String>();
        for(Referentiel_convention__c refCnv : listReferentielConv) {
            setRefConvIds.add(refCnv.Id);
            if(!mapRefPanelIdToRefConvention.containsKey(refCnv.Referentiel_Panel__c)) {
                mapRefPanelIdToRefConvention.put(refCnv.Referentiel_Panel__c, new List<Referentiel_convention__c>());

            }
            mapRefPanelIdToRefConvention.get(refCnv.Referentiel_Panel__c).add(refCnv);
        }
        
        for(Convention__c cnv : mapNewConvention.values()) {  
            if(isInsert) {
                newConv = mapNewConvention.get(cnv.Id);
                if(setRefConvIds.contains(newConv.Referentiel_convention__c)) {
                    if(newConv.Foyer_paneliste__r.Referentiel_Panel__r.Type_de_panel__c == Label.REF_PANEL_TypePan_PAME	&& newConv.Individu_Paneliste__r.Composition_du_foyer__r.Type__c == Label.CON_Type_MEMBRE &&  newConv.Date_de_signature_de_la_convention__c != null ){
                        listIdsCreatedConventions.add(cnv.Id);
                    } 
                }
                
            }
        }
        System.debug('***listIdsCreatedConventions: ' + listIdsCreatedConventions);
        if(listIdsCreatedConventions.size()>0  && listIdsCreatedConventions !=  null) {
            System.debug('***Envoi convention: ');
            sendConventionToGoogle(listIdsCreatedConventions);
            }   
    }

    @future(callout=true)
    public static void sendConventionToGoogle(List<String> listConventionToUpdate) {
        System.debug('$$$ AP01_Convention.sendConventionToGoogle ');
        String method = 'POST';
        String endpoint;
        Http http = new Http();

        List<Convention__c> listConventionToUpdateOrCreate = [SELECT Id, 
                                                                        Composition_du_foyer__c,
                                                                        Foyer_paneliste__r.Foyer_Paneliste_ExtId_SIPanel__c
                                                                 FROM Convention__c
                                                                 WHERE Id =: listConventionToUpdate ];
        
        for(Convention__c conv : listConventionToUpdateOrCreate) {      
            //modification AYoub GHMMAZ du 25/05/2022 : debut
            //modification EGZARA du 01/12/2022 
            //x-mm-sync-google-pfi/v1/agreements?flow=sf-to-google&agreementId
            endpoint = 'callout:Mulesoft_experience_API/' +'api/'+label.Mulesoft_Xapp_MM_Sync_Google+'/v1/'+ label.Mulesoft_expAPI_agreementsPath  
                        + '?flow=' + label.Mulesoft_flow_parameter_sf_to_google+'&uid='+conv.Foyer_paneliste__r.Foyer_Paneliste_ExtId_SIPanel__c + '&uuid=' + conv.Composition_du_foyer__c;
            // old   + '?flow=' + label.Mulesoft_flow_parameter_sf_to_google+'&'+conv.Id;
            HttpRequest req = createHttpRequest(method, endpoint);
            HTTPResponse res = http.send(req);
            System.debug('$$$ AP01_Convention.sendConventionToGoogle: endpoint:'+endpoint);
            System.debug('$$$ AP01_Convention.sendConventionToGoogle: response:'+res.getBody());
        }
       /*  try {
            update listConventionToUpdateOrCreate;
        } catch (Exception e) {
            System.debug('exception caught while updating the conventions : ' + e);
        } */
    }
    
    public static HttpRequest createHttpRequest(string method, string endpoint) {
        HttpRequest reqToReturn = new HttpRequest();
        reqToReturn.setHeader('x-client-id', label.Mulesoft_expAPI_clientId);
        reqToReturn.setHeader('x-client-secret', label.Mulesoft_expAPI_clientSecret);
        reqToReturn.setHeader('Accept', 'application/json');
        reqToReturn.setHeader('Content-Type', 'application/json');
        reqToReturn.setEndpoint(endpoint);
        reqToReturn.setMethod(method);
        if(method=='PUT' || method=='POST'){
            JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
            gen.writeStringField('description', 'test');
            gen.writeEndObject();
            reqToReturn.setBody(gen.getAsString());
        }
        
        return reqToReturn;
    }
}