force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Membre</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Invité</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Non panéliste</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/Foyer_paneliste__c.object-meta.xml
<CustomObject>
    <label>Foyer panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numéro du Foyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foyers panélistes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Foyer_paneliste__c/fields/Referentiel_Panel__c.field-meta.xml
<CustomField>
    <fullName>Referentiel_Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel Panel</label>
    <referenceTo>Referentiel_Panel__c</referenceTo>
    <relationshipLabel>Foyers panélistes (Référentiel Panel)</relationshipLabel>
    <relationshipName>Foyers_pan_listes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Foyer_paneliste__c/recordTypes/AIP.recordType-meta.xml
<RecordType>
    <fullName>AIP</fullName>
    <active>true</active>
    <label>AIP</label>
</RecordType>

force-app/main/default/objects/Individu_Paneliste__c/Individu_Paneliste__c.object-meta.xml
<CustomObject>
    <label>Individu Panéliste</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de l&apos;individu panéliste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individus Panélistes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individu_Paneliste__c/fields/Composition_du_foyer__c.field-meta.xml
<CustomField>
    <fullName>Composition_du_foyer__c</fullName>
    <label>Composition du foyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Paneliste</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Foyer_paneliste__c.field-meta.xml
<CustomField>
    <fullName>Foyer_paneliste__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foyer panéliste</label>
    <referenceTo>Foyer_paneliste__c</referenceTo>
    <relationshipLabel>Individus Panélistes Non</relationshipLabel>
    <relationshipName>Panelistes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invité</fullName>
            </value>
            <value>
                <fullName>Membre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individu_Paneliste__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <formula>TEXT( Foyer_paneliste__r.Referentiel_Panel__r.Type_de_panel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de panel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referentiel_Panel__c/Referentiel_Panel__c.object-meta.xml
<CustomObject>
    <description>Objet pour le référentiel et catalogue de panels de MediaMetrie qui pourraient être associés aux foyer et aux individus.</description>
    <label>Référentiel Panel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom du référentiel panel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiel Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referentiel_Panel__c/fields/Type_de_panel__c.field-meta.xml
<CustomField>
    <fullName>Type_de_panel__c</fullName>
    <label>Type de panel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>PAME</fullName>
                <label>PaME</label>
            </value>
            <value>
                <fullName>AIP</fullName>
            </value>
            <value>
                <fullName>WebAll</fullName>
            </value>
            <value>
                <fullName>Mesure Plateforme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Solde_de_point__c.field-meta.xml
<CustomField>
    <fullName>Solde_de_point__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Solde de point</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Tech_CanalPrivilegie__c.field-meta.xml
<CustomField>
    <fullName>Tech_CanalPrivilegie__c</fullName>
    <formula>TEXT(Contact.Canal_privilegie__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tech_CanalPrivilegie</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/getUserInformations_Test.cls
@isTest
public class getUserInformations_Test {
    
    @isTest 
    static void testGetInformations() {
        setupTestData();
        User testUser = [SELECT Id,Tech_CanalPrivilegie__c FROM User WHERE Email = 'AnesUser@testorg.com'];
        
        // Run test
        System.runAs(testUser) {
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
            
            getUserInformations.onLoadWrapper result = getUserInformations.getInformations();
            Test.stopTest();
            // add assertions to validate the result
            System.assertNotEquals(null, result);
            System.assertNotEquals(null, result.utilisateur);
            System.assertNotEquals(null, result.ChannelPrivilegeList);
        }
    }
    
    @isTest 
    static void testUpdateUserInformations() {
        setupTestData();
        User testUser = [SELECT Id, Email, MobilePhone,Tech_CanalPrivilegie__c FROM User WHERE Email = 'AnesUser@testorg.com'];
        
        // Run test
        System.runAs(testUser) {
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
            String result = getUserInformations.updateUserInformations(testUser);
            Test.stopTest();
            // add assertions to validate the result
            System.debug('bastien result : ' + result);
            System.assertEquals('User Updated, Contact Updated', result);
        }
    }
    @isTest 
    static void testUpdateUserInformationsWithException() {
        setupTestData();
        User testUser = [SELECT Id, Email, MobilePhone,ProfileId,ContactId FROM User WHERE Email = 'AnesUser@testorg.com'];
        
        Account testAccount2 = new Account(Name = 'Test Account 2');
        insert testAccount2;
        
        Contact testContact2 = new Contact(LastName = 'Test', AccountId = testAccount2.Id,Type__c= '1',Birthdate=system.today().addYears(-43));
        insert testContact2;
        // Create a new user with the same email as testUser
        User testUser2 = new User(Alias = 'BzAnes', Email = 'AnesUser2@testorg.com', 
                                  EmailEncodingKey = 'UTF-8', LastName = 'Bz test2', LanguageLocaleKey = 'en_US', 
                                  LocaleSidKey = 'en_US', ProfileId = testUser.ProfileId, TimeZoneSidKey = 'America/Los_Angeles', UserName = 'BzAnesUser@testorg.com',
                                  ContactId = testContact2.Id, Solde_de_point__c = '200');
        insert testUser2;
        
        // Set testUser's email to a new email
        testUser.Email = 'newAnesUser@testorg.com';
        
        // Run test
        System.runAs(testUser) {
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
            
            String result = getUserInformations.updateUserInformations(testUser2);
            Test.stopTest();
            
            // add assertions to validate the result
            System.assertEquals('User Updated, Contact Updated', result);
        }
    }
    
    // Set up test data
    static void setupTestData() {
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        
        Contact testContact = new Contact(LastName = 'Test',FirstName='Nade', AccountId = testAccount.Id, Birthdate = Date.newInstance(2000, 1, 1),type__c='1');
        insert testContact;
        
        Referentiel_Panel__c referentiel = new Referentiel_Panel__c(Type_de_panel__c = 'AIP');
        insert referentiel;
        // Retrieve a portal profile
        Profile p = [SELECT Id FROM Profile WHERE UserType = 'CspLitePortal' LIMIT 1];
        UserLicense ul = [SELECT Id FROM UserLicense WHERE Name = 'Customer Community' LIMIT 1];
        
        User testUser = new User(Alias = 'AnesBz', Email = 'AnesUser@testorg.com', 
                                 EmailEncodingKey = 'UTF-8', LastName = 'Anes test', LanguageLocaleKey = 'en_US', 
                                 LocaleSidKey = 'en_US', ProfileId = p.Id, TimeZoneSidKey = 'America/Los_Angeles', UserName = 'AnesUser@testorg.com',
                                 ContactId = testContact.Id, Solde_de_point__c = '100');
        insert testUser;
        
        Foyer_paneliste__c testFoyer = new Foyer_paneliste__c(Name = 'Test Foyer',Referentiel_Panel__c = referentiel.Id);
        insert testFoyer;
        
        Individu_Paneliste__c testIndividu = new Individu_Paneliste__c(Name = 'Test Individu', Foyer_paneliste__c = testFoyer.Id, Composition_du_foyer__c = testContact.Id);
        insert testIndividu;
    }
}