force-app/main/default/objects/ServiceAppointment/fields/Departement__c.field-meta.xml
<CustomField>
    <fullName>Departement__c</fullName>
    <formula>Account.Departement__c</formula>
    <label>Département</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Trafic_Additionnel__c.field-meta.xml
<CustomField>
    <fullName>Trafic_Additionnel__c</fullName>
    <label>Trafic Additionnel (En min)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trafic_Added__c/Trafic_Added__c.object-meta.xml
<CustomObject>
    <description>the additional traffic estimate</description>
    <label>Trafic Ajouté</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>Nom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trafic Ajouté</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trafic_Added__c/fields/Added_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Added_Percentage__c</fullName>
    <label>Pourcentage Ajouté</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Trafic_Added__c/fields/Arriving_Department__c.field-meta.xml
<CustomField>
    <fullName>Arriving_Department__c</fullName>
    <label>Département d&apos;Arrivée</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>31</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trafic_Added__c/fields/Arriving_Time__c.field-meta.xml
<CustomField>
    <fullName>Arriving_Time__c</fullName>
    <label>Créneau Horaire</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Entre 9 et 10 H</fullName>
            </value>
            <value>
                <fullName>Entre 10 et 11 H</fullName>
            </value>
            <value>
                <fullName>Entre 15 et 16 H</fullName>
            </value>
            <value>
                <fullName>Entre 16 et 17 H</fullName>
            </value>
            <value>
                <fullName>Entre 17 et 18 H</fullName>
            </value>
            <value>
                <fullName>Entre 18 et 19 H</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trafic_Added__c/fields/TECH_DEPARTMENT_ARRIVINGTIME__c.field-meta.xml
<CustomField>
    <fullName>TECH_DEPARTMENT_ARRIVINGTIME__c</fullName>
    <formula>TEXT(Arriving_Department__c)  +  TEXT(Arriving_Time__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_DEPARTMENT_ARRIVINGTIME</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AP02_UpdateTraficOnServiceAppointment.cls
public class AP02_UpdateTraficOnServiceAppointment {
    
    public static void updateSchedDate (list<ServiceAppointment> listeSa, Map<Id,ServiceAppointment> oldSAs){
        
        set<Id> serviceAppointmentIds = new Set<Id>();
        set<String> traficAddedToQuery = new Set<String>();
        Integer i;
        String arrivingTime;
        
        system.debug('listeSa' + listeSa);
        system.debug('listeSa' + listeSa[0].SchedStartTime);
        
        for (ServiceAppointment sa : listeSa){
            if(sa.SchedStartTime!=null ){
                system.debug('sa.SchedStartTime' + sa.SchedStartTime);
                system.debug('sa.Status first' + sa.Status);
                serviceAppointmentIds.add(sa.Id);
                i = sa.SchedStartTime.hour()+1 ; 
                arrivingTime = 'Entre ' + sa.SchedStartTime.hour() + ' et ' + i + ' H';
                traficAddedToQuery.add(sa.Departement__c + arrivingTime);                
            }
              
        }
        if(traficAddedToQuery!=null && traficAddedToQuery.size()>0 ){
            system.debug('traficAddedToQuery : ' + traficAddedToQuery);
            
            // map of Service App and its assigned resource
            Map<Id, List<AssignedResource>> mapSAAssignedResource = new Map<Id, List<AssignedResource>>();            
            for(AssignedResource ar : [SELECT id, ServiceAppointmentId, EstimatedTravelTime, ServiceAppointment.SchedStartTime, 
                                       ServiceAppointment.SchedEndTime, ServiceAppointment.Departement__c 
                                       FROM AssignedResource 
                                       WHERE ServiceAppointmentId in : serviceAppointmentIds]) {
                                           if(mapSAAssignedResource.containsKey(ar.ServiceAppointmentId)) {
                                               List<AssignedResource> aResource = mapSAAssignedResource.get(ar.ServiceAppointmentId);
                                               aResource.add(ar);
                                               mapSAAssignedResource.put(ar.ServiceAppointmentId, aResource);
                                           } else {
                                               mapSAAssignedResource.put(ar.ServiceAppointmentId, new List<AssignedResource> { ar });
                                           }
                                       }
            
            system.debug('mapSAAssignedResource : ' + mapSAAssignedResource);
            
            if(mapSAAssignedResource.size()>0  ){
                // map : key concatination variable , value : trafic added
                Map<String, Trafic_Added__c> mapKeyTrafic = new Map<String, Trafic_Added__c> ();
                for(Trafic_Added__c tr : [SELECT id,Added_Percentage__c, Arriving_Department__c, Arriving_Time__c,TECH_DEPARTMENT_ARRIVINGTIME__c
                                          FROM Trafic_Added__c 
                                          WHERE TECH_DEPARTMENT_ARRIVINGTIME__c in: traficAddedToQuery ]){
                                              //clé unique donc pas d'écrasement
                                              mapKeyTrafic.put(tr.TECH_DEPARTMENT_ARRIVINGTIME__c, tr);       
                                          }
                
                system.debug('mapKeyTrafic : '+mapKeyTrafic);
                
                for (ServiceAppointment sa : listeSa ){
                    
                    system.debug('sa.id ' + sa.id);
                    system.debug('mapSAAssignedResource '+ mapSAAssignedResource);
                    system.debug('mapSAAssignedResource.get(sa.Id) ' + mapSAAssignedResource.get(sa.Id));
                    
                    List<AssignedResource> listAR = mapSAAssignedResource.get(sa.Id);
                    system.debug('sa.SchedStartTime : '+sa.SchedStartTime);
                     

                    if(sa.SchedStartTime!=null ){
                         system.debug('sa.Status' + sa.Status);

                        i = sa.SchedStartTime.hour()+1 ; 
                        arrivingTime = 'Entre ' + sa.SchedStartTime.hour() + ' et ' + i + ' H';
                        Trafic_Added__c trafic = mapKeyTrafic.get(sa.Departement__c + arrivingTime);
                        if(trafic !=null){
                            //un service appointment a un toujours un seul assigned resource 
                            for ( AssignedResource resource : listAR){
                                if(resource.EstimatedTravelTime !=null){
                                Decimal addedTime = resource.EstimatedTravelTime *  (trafic.Added_Percentage__c)  /100;
                                system.debug('EstimatedTravelTime : '+resource.EstimatedTravelTime);
                                system.debug('Added_Percentage__c : '+trafic.Added_Percentage__c);
                                system.debug('addedTime : '+addedTime);
                                
                                sa.Trafic_Additionnel__c = addedTime ;
                                system.debug('sched start time before update : ' + resource.ServiceAppointment.SchedStartTime);
                                
                                resource.ServiceAppointment.SchedStartTime = resource.ServiceAppointment.SchedStartTime.addMinutes(Integer.valueof(addedTime));
                                	system.debug('new start time : ' + resource.ServiceAppointment.SchedStartTime);
                                resource.ServiceAppointment.SchedEndTime = resource.ServiceAppointment.SchedEndTime.addMinutes(Integer.valueof(addedTime));
                                   system.debug('sched start time after update : ' +sa.SchedStartTime);   
                                if(resource.EstimatedTravelTime!=0){
                                    AP02_ServiceAppointment_RecursiveHandler.schedStartDateUpdated = true;
                               	
                                }
                                }
                            }                     
                        }else {
                            sa.Trafic_Additionnel__c = 0 ;
                        } 
                    }
                }  
            }
        }
    }   
}